### ISSUE TITLE
Forge's OBJ loader always throws an exception for models using it

### ISSUE THREAD

**Issue by SuperMartijn642** [MinecraftForge/MinecraftForge#10064]
**Minecraft Version:** 1.21.1

**Forge Version:** 52.0.3

**Logs:** https://gist.github.com/SuperMartijn642/9d573901abc24d2b05eebb148bac3248 (Since model loading only shows exception message, I used debugger to print the stack trace)
```
[16Aug2024 15:41:48.406] [Worker-Main-3/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to bake model: 'minecraft:redstone_block#inventory': java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 32
java.lang.ArrayIndexOutOfBoundsException: Index 32 out of bounds for length 32
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.pipeline.QuadBakingVertexConsumer.addVertex(QuadBakingVertexConsumer.java:60)
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.obj.ObjModel.makeQuad(ObjModel.java:424)
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.obj.ObjModel$ModelMesh.addQuads(ObjModel.java:633)
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.obj.ObjModel$ModelObject.addQuads(ObjModel.java:530)
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.obj.ObjModel$ModelGroup.addQuads(ObjModel.java:569)
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.obj.ObjModel.lambda$addQuads$2(ObjModel.java:340)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.obj.ObjModel.addQuads(ObjModel.java:340)
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.geometry.SimpleUnbakedGeometry.bake(SimpleUnbakedGeometry.java:36)
	at TRANSFORMER/forge@52.0.3/net.minecraftforge.client.model.geometry.UnbakedGeometryHelper.bake(UnbakedGeometryHelper.java:105)
```

**Steps to Reproduce:**
 1. Launch Minecraft and enable the following resource pack which replaces the redstone block model with an OBJ model: 
[obj-model-example.zip](https://github.com/user-attachments/files/16636933/obj-model-example.zip)
2. Load a world and place a redstone block
3. Observe that the redstone block has a missing model
   <img src="https://github.com/user-attachments/assets/9ba51b2e-b4ae-4224-84b3-a2e656a6afcf" width="500" />

**Description of issue:**
Forge's `ObjModel#makeQuad` method relies on an implementation of `VertexConsumer` in `QuadBakingVertexConsumer`. 
From Minecraft 1.20.6 to 1.21, the `VertexConsumer` interface was changed to no longer explicitly end vertices, i.e. `VertexConsumer#endVertex` was removed.
During the Forge update to 1.21, a call to `QuadBakingVertexConsumer#endVertex` was added at the start of `QuadBakingVertexConsumer#addVertex`.
https://github.com/MinecraftForge/MinecraftForge/blob/f106ff0c21f268ae9e5edb6db57b7e51d3df91eb/src/main/java/net/minecraftforge/client/model/pipeline/QuadBakingVertexConsumer.java#L55-L60
In `QuadBakingVertexConsumer#endVertex`, the first if-statement which checks whether 4 vertices have been submitted was changed to also increase the current vertex index.
https://github.com/MinecraftForge/MinecraftForge/blob/f106ff0c21f268ae9e5edb6db57b7e51d3df91eb/src/main/java/net/minecraftforge/client/model/pipeline/QuadBakingVertexConsumer.java#L127-L135

The problem here is that when `QuadBakingVertexConsumer#addVertex` is called for the first vertex, the vertex index already gets increased to 1 whilst it should be 0. This results in the fourth vertex writing to vertex index 4 rather than 3 and since `QuadBakingVertexConsumer#endVertex` assigns an array with space for only 4 vertices, this causes an exception.

As Forge's OBJ loader is the only place using `QuadBakingVertexConsumer`, it is the only part affected by this issue.

**Comment by SuperMartijn642** [comment]
The issue described was fixed in #10065.
