### ISSUE TITLE
[1.21.1] java.lang.NoSuchMethodError: 'double net.minecraft.world.entity.Entity.m_20185_()

### ISSUE THREAD

**Issue by jarryDk** [MinecraftForge/MinecraftForge#10079]
I am creating a server mod and subscribe to the `EntityJoinLevelEvent` but is uable to use some methods on the Entity object.

I get an `java.lang.NoSuchMethodError: 'double net.minecraft.world.entity.Entity.m_20185_()'` when calling `getX()` on let's say on a Chicken -> `net.minecraft.world.entity.animal.Chicken` 

I am using `net.minecraftforge:forge:1.21.1-52.0.9`

````
public class EntityEventSubscriber {
    @SubscribeEvent
    public void onEntityJoinLevelEvent(EntityJoinLevelEvent event) {
        EntityEventRecord entityEventRecord = new EntityEventRecord(event); // Line 32
        // Do some stuff ...
    }
}
````

````
@JsonPropertyOrder(alphabetic = true)
public class EntityEventRecord extends Location {

    Entity entity;
    EntityEvent event;

    public EntityEventRecord(EntityEvent event){
        super(event); // Line 20
        this.event = event;
        this.entity = event.getEntity();
    }
````

````
abstract class Location {

    double x;
    double y;
    double z;

    public Location(EntityEvent event) {
        Entity entity = event.getEntity();
        this.x = entity.getX(); // Line 14
        this.y = entity.getY();
        this.z = entity.getZ();
    }
}
````

[20:18:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forge_server, nogui]
[20:18:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: JVM identified as Eclipse Adoptium OpenJDK 64-Bit Server VM 21.0.1+12-LTS
[20:18:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.2.1 starting: java version 21.0.1 by Eclipse Adoptium; OS Linux arch amd64 version 6.10.6-200.fc40.x86_64
[20:18:08] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forge_server
[20:18:08] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=jar:file:///opt/minecraft/forge/.minecraft_1.21.1-52.0.9/libraries/org/spongepowered/mixin/0.8.7/mixin-0.8.7.jar!/ Service=ModLauncher Env=SERVER
[20:18:08] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[20:18:09] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forge_server' with arguments [nogui]
[20:18:22] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: 'double net.minecraft.world.entity.Entity.m_20185_()'
	Index: 5
	Listeners:
		0: HIGHEST
		1: ASM: net.minecraftforge.common.ForgeInternalHandler@6ae12fe3 builtinMobSpawnBlocker(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
		2: HIGH
		3: ASM: net.minecraftforge.common.ForgeInternalHandler@6ae12fe3 onEntityJoinWorld(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
		4: NORMAL
		5: ASM: dk.jarry.kafkamod.control.EntityEventSubscriber@21be5bfe onEntityJoinLevelEvent(Lnet/minecraftforge/event/entity/EntityJoinLevelEvent;)V
java.lang.NoSuchMethodError: 'double net.minecraft.world.entity.Entity.m_20185_()'
	at TRANSFORMER/kafkamod@1.0.5/dk.jarry.kafkamod.entity.Location.<init>(Location.java:14)
	at TRANSFORMER/kafkamod@1.0.5/dk.jarry.kafkamod.entity.EntityEventRecord.<init>(EntityEventRecord.java:20)
	at TRANSFORMER/kafkamod@1.0.5/dk.jarry.kafkamod.control.EntityEventSubscriber.onEntityJoinLevelEvent(EntityEventSubscriber.java:32)
	at TRANSFORMER/kafkamod@1.0.5/dk.jarry.kafkamod.control.__EntityEventSubscriber_onEntityJoinLevelEvent_EntityJoinLevelEvent.invoke(.dynamic)
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:48)
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:304)
	at SECURE-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:290)
	at TRANSFORMER/forge@52.0.9/net.minecraftforge.event.ForgeEventFactory.post(ForgeEventFactory.java:228)
	at TRANSFORMER/forge@52.0.9/net.minecraftforge.event.ForgeEventFactory.onEntityJoinLevel(ForgeEventFactory.java:995)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntity(PersistentEntitySectionManager.java:79)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$processPendingLoads$11(PersistentEntitySectionManager.java:246)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:5073)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:5081)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.processPendingLoads(PersistentEntitySectionManager.java:246)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.PersistentEntitySectionManager.tick(PersistentEntitySectionManager.java:252)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:420)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1021)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:315)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:911)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701)
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by LexManos** [comment]
I use official names during runtime now so you have to disable reobf as the mdk explains. Also this isn't tech support use the discord for that.
