### ISSUE TITLE
DataGenerator is somehow broken on 1.21.4

### ISSUE THREAD

**Issue by rikka0w0** [MinecraftForge/MinecraftForge#10203]
**Minecraft Version:** 1.21.4

**Forge Version:** 54.0.6

**Steps to Reproduce:**
 1. Clone this repo: https://github.com/rikka0w0/MobZReborn
 2. Run the data generator: `cd MobZReborn/forge && ./gradlew runData`

**Description of issue:**
The vanilla codec `ClientItem.CODEC` cannot be found when running this line:
https://github.com/rikka0w0/MobZReborn/blob/3db9b8b1488edad6e0e5cee05800e7a84574c4b5/src/main/java/net/mobz/data/ModelDataProvider.java#L189

The same DataGenerator class works on the other mod loaders, so I believe this is a Forge-specific issue.

<details>
  <summary>Console log</summary>

```
[02:44:17] [main/INFO] [ne.mi.da.lo.DatagenModLoader/]: Initializing Data Gatherer for mods [mobz]
[02:44:17] [main/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/C:/Users/user/eclipse-workspace/MobZReborn/forge/build/fg_cache/net/minecraftforge/forge/1.21.4-54.0.6_mapped_official_1.21.4/forge-1.21.4-54.0.6_mapped_official_1.21.4.jar%230!/assets/.mcassetsroot' uses unexpected schema
[02:44:17] [main/WARN] [minecraft/VanillaPackResourcesBuilder]: Assets URL 'union:/C:/Users/user/eclipse-workspace/MobZReborn/forge/build/fg_cache/net/minecraftforge/forge/1.21.4-54.0.6_mapped_official_1.21.4/forge-1.21.4-54.0.6_mapped_official_1.21.4.jar%230!/data/.mcassetsroot' uses unexpected schema
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Starting provider: Registries
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Registries finished after 186 ms
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Starting provider: Tags for minecraft:worldgen/biome mod id mobz
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Tags for minecraft:worldgen/biome mod id mobz finished after 3 ms
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Starting provider: Tags for minecraft:block mod id vanilla
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Tags for minecraft:block mod id vanilla finished after 0 ms
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Starting provider: Tags for minecraft:item mod id vanilla
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Tags for minecraft:item mod id vanilla finished after 1 ms
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Starting provider: Tags for minecraft:entity_type mod id vanilla
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Tags for minecraft:entity_type mod id vanilla finished after 1 ms
[02:44:18] [main/INFO] [minecraft/DataGenerator]: Starting provider: Item models for mobz
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at net.minecraftforge.bootstrap.Bootstrap.bootstrapMain(Bootstrap.java:133)
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:53)
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:19)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.4-54.0.6/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:86)
        at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.21.4-54.0.6/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:69)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:77)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:97)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:116)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:75)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
        at net.minecraftforge.bootstrap@2.1.6/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:188)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 4 more
Caused by: java.lang.IllegalStateException: Element with unknown id: RecordCodec[UnitDecoder[net.minecraft.client.renderer.item.BlockModelWrapper$Unbaked$$Lambda/0x0000021281e49238@2a4d39fa] * Field[model: String[comapFlatMapped]] * OptionalFieldCodec[tints: ListCodec[KeyDispatchCodec[String[comapFlatMapped][flatXmapped] java.util.function.Function$$Lambda/0x000002128117daa0@7e15cac4 java.util.function.Function$$Lambda/0x000002128117daa0@3d150d83]]][xmapped]]
        at SECURE-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287)
        at SECURE-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.data.DataProvider.lambda$saveAll$2(DataProvider.java:49)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.data.DataProvider.lambda$saveAll$3(DataProvider.java:56)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1858)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.data.DataProvider.saveAll(DataProvider.java:59)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.data.DataProvider.saveAll(DataProvider.java:49)
        at TRANSFORMER/mobz@4.5.0/net.mobz.data.ModelDataProvider.run(ModelDataProvider.java:189)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.data.HashCache.generateUpdate(HashCache.java:96)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.data.DataGenerator.lambda$run$0(DataGenerator.java:44)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.data.DataGenerator.run(DataGenerator.java:37)
        at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.data.event.GatherDataEvent$DataGeneratorConfig.lambda$runAll$2(GatherDataEvent.java:111)
        at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.2.2/cpw.mods.modlauncher.api.LamdbaExceptionUtils.lambda$rethrowConsumer$0(LamdbaExceptionUtils.java:21)
        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:833)
        at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.data.event.GatherDataEvent$DataGeneratorConfig.runAll(GatherDataEvent.java:107)
        at TRANSFORMER/net.minecraftforge.forge@54.0.6/net.minecraftforge.data.loading.DatagenModLoader.run(DatagenModLoader.java:120)
        at TRANSFORMER/minecraft@1.21.4/net.minecraft.data.Main.main(Main.java:89)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 14 more

> Task :runData FAILED

FAILURE: Build failed with an exception.
```
</details>

**Comment by LexManos** [comment]
You're gunna have to make a much smaller reproduction case
However the issue seems to be that you have not registered your properties by the time the ClientItem codec is resolved for the first time.
And it's eagerly cached.
Probably related to https://github.com/MinecraftForge/MinecraftForge/issues/10200

**Comment by LexManos** [comment]
Okay looking into it, the issue is that Mojang split the data gen into two entry points in 1.21.4. I saw it during the update and wondered why they did it. Both entry points have the hooks needed to load your mod and run data gen.
The main difference is that the client side calls ClientBootstrap which loads up all those codecs.
So for now you have two options. Make the run config for the client side data gen yourself. Or just call ClientBootstrap yourself before your data gens. Don't worry about calling it, as it has guards against it being called multiple times. So you should be fine.

**Comment by rikka0w0** [comment]
> So for now you have two options. Make the run config for the client side data gen yourself. Or just call ClientBootstrap yourself before your data gens. Don't worry about calling it, as it has guards against it being called multiple times. So you should be fine.

Thanks for pointing out the solutions. Calling ClientBootstrap manually fixes the problem:
```java
public static void onDataGeneratorInvoked(final GatherDataEvent event) {
    if (event.includeClient())
        net.minecraft.client.ClientBootstrap.bootstrap();
    ....
}
```

However, I'm interested in knowing how to use the first approach. From the class hierarchy I can see that the "userdev" LaunchHandlers dont have a ClientData, unlike the `ForgeDevLaunchHandler`:
![image](https://github.com/user-attachments/assets/9f6bb3a9-31b9-4bae-b563-489a4db0183e)

It looks like I cannot invoke the client data gen entry point by only changing `build.gradle` like this:
`args '--launchTarget', 'forge_userdev_client_data'`

**Comment by LexManos** [comment]
You may be interested in https://github.com/MinecraftForge/MinecraftForge/pull/10206 as it exposes those new entry points as well as a generic way to use any entry point in the future.
