### ISSUE TITLE
Vec3 pool size error

### ISSUE THREAD

**Issue by VoiceOfZen** [MinecraftForge/MinecraftForge#10204]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/9/24 6:51 AM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 0
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:62)
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:39)
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:119)
	at bspkrs.bspkrscore.fml.bspkrsCoreMod.init(bspkrsCoreMod.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:699)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:62)
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:39)
	at bspkrs.util.ModVersionChecker.<init>(ModVersionChecker.java:119)
	at bspkrs.bspkrscore.fml.bspkrsCoreMod.init(bspkrsCoreMod.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:699)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:249)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(SourceFile:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
	Minecraft Version: 1.6.4
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_11, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 119980472 bytes (114 MB) / 406323200 bytes (387 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Suspicious classes: FML and Forge are installed
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v8.11 FML v6.4.49.965 Minecraft Forge 9.11.1.965 26 mods loaded, 26 mods active
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{6.4.49.965} [Forge Mod Loader] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{9.11.1.965} [Minecraft Forge] (minecraftforge-9.11.1.965.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BabyAnimalsModelSwapper{1.6.4} [BabyAnimalsModelSwapper] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CodeChickenCore{0.9.0.7} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	NotEnoughItems{1.6.1.5} [Not Enough Items] (NotEnoughItems 1.6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	shadersmod{2.0.1 beta 18} [GLSL Shaders Mod] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	battlegear2{1.0.4.6} [Mine & Blade Battlegear 2 - Bullseye] ([1.6.4] Mine & Blade Battlegear 2 - Bullseye - 1.0.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
	bspkrsCore{v5.3(1.6.4)} [bspkrsCore] ([1.6.4]bspkrsCorev5.3.zip) Unloaded->Constructed->Pre-initialized->Errored
	extendedWorkbench{1.1.10.3} [Extended Workbench] (Extended-Workbench-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ExtrabiomesXL{3.14.2} [ExtrabiomesXL] (ExtrabiomesXL-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Haunted{1.0.0} [HAUNTED] (Haunted 1.0.2 For 1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	inventorytweaks{1.56} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	millenaire{5.1.11} [Millénaire] (millenaire-jar-5.1.11) Unloaded->Constructed->Pre-initialized->Initialized
	Natura{2.1.12} [Natura] (Natura-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Natura|ForgeMuliPart{0.1} [Natura Compat: FMP] (Natura-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Natura|CompatMineFactoryReloaded{0.1} [Natura Compat: MFR] (Natura-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Natura|NotEnoughItems{0.1} [Natura Compat: NEI] (Natura-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	secretroomsmod{4.6.2} [The SecretRoomsMod] (Secret-Rooms-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	SS2{2 (build 2)} [Soul Shards 2] (Soul-Shards-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Thaumcraft{4.0.4c} [Thaumcraft] (Thaumcraft-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
	ThaumicTinkerer{2.0} [Thaumic Tinkerer] (ThaumicTinkerer 2.0-24.jar) Unloaded->Constructed->Pre-initialized->Initialized
	tuxweapons{0.6} [TuxWeapons] (TuxWeapons-Mod-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	TwilightForest{1.20.1} [The Twilight Forest] (twilightforest-1.20.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
	wonderfulwands{1.1.0} [Cyano's Wonderful Wands] (Wonderful-Wands-Mod-1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
	Launched Version: 1.6.4-Forge9.11.1.965
	LWJGL: 2.9.0
	OpenGL: AMD Radeon(TM) Graphics GL version 4.6.0 Compatibility Profile Context 23.19.10.231127, ATI Technologies Inc.
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Pack: Default
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by VoiceOfZen** [comment]
trying to open 1.6.4 modpack that worked but is not working now. partually.
