### ISSUE TITLE
NullPointerException: Zip file rt.jar failed to read properly

### ISSUE THREAD

**Issue by kevingoos** [MinecraftForge/MinecraftForge#1234]
I am using idea with java SDK 1.7.0_60

This is my error, when I run the client I get the error but the client runs. The server on the other hand will not startup because of the error.

[Client thread/WARN] [FML]: Zip file rt.jar failed to read properly, it will be ignored
java.lang.NullPointerException
    at cpw.mods.fml.common.discovery.asm.ASMModParser.isBaseMod(ASMModParser.java:130) ~[ASMModParser.class:?]
    at cpw.mods.fml.common.ModContainerFactory.build(ModContainerFactory.java:34) ~[ModContainerFactory.class:?]
    at cpw.mods.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:83) [JarDiscoverer.class:?]
    at cpw.mods.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
    at cpw.mods.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
    at cpw.mods.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:123) [ModDiscoverer.class:?]
    at cpw.mods.fml.common.Loader.identifyMods(Loader.java:347) [Loader.class:?]
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:468) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.startGame(Minecraft.java:532) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:941) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:164) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
    at GradleStart.bounce(GradleStart.java:108) [start/:?]
    at GradleStart.startClient(GradleStart.java:101) [start/:?]
    at GradleStart.main(GradleStart.java:56) [start/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134) [idea_rt.jar:?]
[01:40:31] [Client thread/ERROR] [FML]: FML has detected a mod that is using a package name based on 'net.minecraft.src' : net.minecraft.src.FMLRenderAccessLibrary. This is generally a severe programming error.  There should be no mod code in the minecraft namespace. MOVE YOUR MOD! If you're in eclipse, select your source code and 'refactor' it into a new package. Go on. DO IT NOW!

**Comment by r1sk01** [comment]
this is still an issue, it happens on Eclipse too

**Comment by LexManos** [comment]
Do not necro 9 year old closed issues. Use the forums or discord for basic tech support.
