### ISSUE TITLE
[1.8] Cancelling ClientChatRecievedEvent causes exception

### ISSUE THREAD

**Issue by mmdanggg2** [MinecraftForge/MinecraftForge#1644]
Not too serious as it gets caught and does actually cancel the chat message but causes a lot of console spam.

```
Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.7.0_71]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.7.0_71]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:677) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1012) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:345) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:117) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:78) [start/:?]
	at GradleStart.main(GradleStart.java:45) [start/:?]
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213) ~[guava-17.0.jar:?]
	at com.google.common.collect.Lists.newArrayList(Lists.java:127) ~[guava-17.0.jar:?]
	at net.minecraft.client.gui.GuiUtilRenderComponents.func_178908_a(GuiUtilRenderComponents.java:28) ~[GuiUtilRenderComponents.class:?]
	at net.minecraft.client.gui.GuiNewChat.setChatLine(GuiNewChat.java:149) ~[GuiNewChat.class:?]
	at net.minecraft.client.gui.GuiNewChat.printChatMessageWithOptionalDeletion(GuiNewChat.java:137) ~[GuiNewChat.class:?]
	at net.minecraft.client.gui.GuiNewChat.printChatMessage(GuiNewChat.java:132) ~[GuiNewChat.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleChat(NetHandlerPlayClient.java:766) ~[NetHandlerPlayClient.class:?]
	at net.minecraft.network.play.server.S02PacketChat.processPacket(S02PacketChat.java:45) ~[S02PacketChat.class:?]
	at net.minecraft.network.play.server.S02PacketChat.processPacket(S02PacketChat.java:67) ~[S02PacketChat.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:18) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.7.0_71]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.7.0_71]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:676) ~[FMLCommonHandler.class:?]
	... 11 more
```

**Comment by mmdanggg2** [comment]
Fixed by 4380ca026ead1bd516579bb528ed5b2219f7f5f8
