### ISSUE TITLE
[1.7.10] internal server error on chat message

### ISSUE THREAD

**Issue by Victorious3** [MinecraftForge/MinecraftForge#1712]
Completely crashes the client in SP, creates an internal server error on MP & disconnects.
For any semi-valid URL that gets terminated with a "]".
Occurs because it tries to create a URI without catching any exceptions that might occur `if (URI.create(url).getScheme() == null)`

Forge: 10.13.2.1291

````
java.lang.IllegalArgumentException: Illegal character in path at index 7: abc.def]
	at java.net.URI.create(Unknown Source) ~[?:1.8.0_31]
	at net.minecraftforge.common.ForgeHooks.newChatWithLinks(ForgeHooks.java:419) ~[ForgeHooks.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:768) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.processPacket(C01PacketChatMessage.java:47) ~[C01PacketChatMessage.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.processPacket(C01PacketChatMessage.java:68) ~[C01PacketChatMessage.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241) ~[NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:349) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752) [MinecraftServer$2.class:?]
Caused by: java.net.URISyntaxException: Illegal character in path at index 7: abc.def]
	at java.net.URI$Parser.fail(Unknown Source) ~[?:1.8.0_31]
	at java.net.URI$Parser.checkChars(Unknown Source) ~[?:1.8.0_31]
	at java.net.URI$Parser.parseHierarchical(Unknown Source) ~[?:1.8.0_31]
	at java.net.URI$Parser.parse(Unknown Source) ~[?:1.8.0_31]
	at java.net.URI.<init>(Unknown Source) ~[?:1.8.0_31]
	... 12 more
````

**Comment by Baughn** [comment]
Sorry, this is still a problem; you just need a 'properly formatted' message. Here, have another crash log:

[16:04:32] [Server thread/WARN]: Failed to handle packet for /89.233.74.86:52861
java.lang.IllegalArgumentException: Expected scheme-specific part at index 12: max.voltage:
        at java.net.URI.create(URI.java:852) ~[?:1.8.0-ea]
        at net.minecraftforge.common.ForgeHooks.newChatWithLinks(ForgeHooks.java:417) ~[ForgeHooks.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:722) ~[nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) ~[ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) ~[ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 12: max.voltage:
        at java.net.URI$Parser.fail(URI.java:2848) ~[?:1.8.0-ea]
        at java.net.URI$Parser.failExpecting(URI.java:2854) ~[?:1.8.0-ea]
        at java.net.URI$Parser.parse(URI.java:3057) ~[?:1.8.0-ea]
        at java.net.URI.<init>(URI.java:588) ~[?:1.8.0-ea]
        at java.net.URI.create(URI.java:850) ~[?:1.8.0-ea]
        ... 11 more
[16:04:32] [Server thread/INFO]: MrCrackx02 lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[16:04:32] [Server thread/INFO]: MrCrackx02 left the game
