### ISSUE TITLE
[Client thread/ERROR] [FML]: Unable to determine registrant mod for TextureAtlasSprite{name='minecraft:white', frameCount=0, rotated=false, x=0, y=0, height=0, width=0, u0=0.0, u1=0.0, v0=0.0, v1=0.0}. This is a critical error and should be impossible

### ISSUE THREAD

**Issue by CAD97** [MinecraftForge/MinecraftForge#1715]
From a fresh profile of Forge 1.8-11.14.1.1319

I noticed this error while coding a mod and downloaded a clean install to see if it was a problem in Forge or something I did. The below log is what I got on a fresh install of 1319. As the error says `This is a critical error and should be impossible` I thought I should report it.

I opened up an empty flatworld to trigger a debug crash, in case that is useful.

Log:
```
[17:49:48] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:49:49] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:49:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:49:49] [main/INFO] [FML]: Forge Mod Loader version 8.0.32.1319 for Minecraft 1.8 loading
[17:49:49] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 8.1:amd64:6.3, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[17:49:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:49:49] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:49:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:49:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:49:49] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:49:50] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:49:50] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:49:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:49:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:49:50] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:49:50] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:49:50] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:49:51] [Client thread/INFO]: Setting user: CAD97
[17:49:53] [Client thread/INFO]: LWJGL Version: 2.9.1
[17:49:53] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[17:49:53] [Client thread/INFO] [FML]: MinecraftForge v11.14.1.1319 Initialized
[17:49:54] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[17:49:54] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[17:49:54] [Client thread/INFO] [FML]: Searching C:\Users\Christopher\AppData\Roaming\.minecraft\profiles\Forge\mods for mods
[17:49:55] [Client thread/INFO] [FML]: Forge Mod Loader has identified 3 mods to load
[17:49:56] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[17:49:56] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[17:49:56] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[17:49:56] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[17:49:56] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[17:49:56] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:49:56] [Client thread/INFO] [FML]: Applying holder lookups
[17:49:56] [Client thread/INFO] [FML]: Holder lookups applied
[17:49:57] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:49:57] [Thread-7/INFO]: Initializing LWJGL OpenAL
[17:49:57] [Thread-7/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:49:57] [Thread-7/INFO]: OpenAL initialized.
[17:49:57] [Client thread/ERROR] [FML]: Unable to determine registrant mod for TextureAtlasSprite{name='minecraft:white', frameCount=0, rotated=false, x=0, y=0, height=0, width=0, u0=0.0, u1=0.0, v0=0.0, v1=0.0}. This is a critical error and should be impossible
java.lang.Throwable
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:55) [EventBus.class:?]
	at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:80) [ModelLoader.class:?]
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:28) [cxk.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SourceFile:99) [cvt.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[17:49:57] [Sound Library Loader/INFO]: Sound engine started
[17:49:58] [Client thread/INFO]: Created: 512x512 textures-atlas
[17:49:59] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 3 mods
[17:49:59] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[17:49:59] [Client thread/INFO]: SoundSystem shutting down...
[17:49:59] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[17:49:59] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:49:59] [Thread-9/INFO]: Initializing LWJGL OpenAL
[17:49:59] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:49:59] [Thread-9/INFO]: OpenAL initialized.
[17:50:00] [Sound Library Loader/INFO]: Sound engine started
[17:50:00] [Client thread/INFO]: Created: 512x512 textures-atlas
[17:50:19] [Server thread/INFO]: Starting integrated minecraft server version 1.8
[17:50:19] [Server thread/INFO]: Generating keypair
[17:50:19] [Server thread/INFO]: Converting map!
[17:50:19] [Server thread/INFO]: Scanning folders...
[17:50:19] [Server thread/INFO]: Total conversion count is 0
[17:50:19] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[17:50:19] [Server thread/INFO] [FML]: Applying holder lookups
[17:50:19] [Server thread/INFO] [FML]: Holder lookups applied
[17:50:19] [Server thread/INFO] [FML]: Loading dimension 0 (test) (net.minecraft.server.integrated.IntegratedServer@6f536c52)
[17:50:20] [Server thread/INFO] [FML]: Loading dimension 1 (test) (net.minecraft.server.integrated.IntegratedServer@6f536c52)
[17:50:20] [Server thread/INFO] [FML]: Loading dimension -1 (test) (net.minecraft.server.integrated.IntegratedServer@6f536c52)
[17:50:20] [Server thread/INFO]: Preparing start region for level 0
[17:50:21] [Server thread/INFO]: Changing view distance to 12, from 10
[17:50:21] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 1
[17:50:21] [Netty Server IO #1/INFO] [FML]: Client protocol version 1
[17:50:21] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 3 mods : FML@8.0.32.1319,Forge@11.14.1.1319,mcp@9.05
[17:50:21] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[17:50:21] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[17:50:21] [Server thread/INFO]: CAD97[local:E:49f5a73d] logged in with entity id 23 at (-1331.5, 4.0, 4161.5)
[17:50:21] [Server thread/INFO]: CAD97 joined the game
[17:50:41] [Server thread/INFO]: Stopping server
[17:50:41] [Server thread/INFO]: Saving players
[17:50:41] [Server thread/INFO]: Saving worlds
[17:50:41] [Server thread/INFO]: Saving chunks for level 'test'/Overworld
[17:50:42] [Server thread/INFO]: Saving chunks for level 'test'/Nether
[17:50:42] [Server thread/INFO]: Saving chunks for level 'test'/The End
[17:50:42] [Server thread/INFO] [FML]: Unloading dimension 0
[17:50:42] [Server thread/INFO] [FML]: Unloading dimension -1
[17:50:42] [Server thread/INFO] [FML]: Unloading dimension 1
[17:50:42] [Server thread/INFO] [FML]: Applying holder lookups
[17:50:42] [Server thread/INFO] [FML]: Holder lookups applied
[17:50:43] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Manually triggered debug crash
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1790) ~[bsu.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1021) ~[bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: java.lang.Throwable
	... 10 more
[17:50:43] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:492]: ---- Minecraft Crash Report ----
// Oops.

Time: 2/17/15 5:50 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1790)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1021)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:350)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CAD97'/23, l='MpServer', x=-1331.50, y=4.00, z=4161.50]]
	Chunk stats: MultiplayerChunkCache: 612, 612
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -1323.00,4.00,4169.00 - World: (-1323,4,4169), Chunk: (at 5,0,9 in -83,260; contains blocks -1328,0,4160 to -1313,255,4175), Region: (-3,8; contains chunks -96,256 to -65,287, blocks -1536,0,4096 to -1025,255,4607)
	Level time: 399 game time, 399 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 12 total; [EntitySlime['Slime'/114882, l='MpServer', x=-1388.63, y=4.00, z=4106.94], EntitySlime['Slime'/31269, l='MpServer', x=-1401.84, y=4.00, z=4187.40], EntityPlayerSP['CAD97'/23, l='MpServer', x=-1331.50, y=4.00, z=4161.50], EntitySlime['Slime'/4248, l='MpServer', x=-1376.68, y=4.91, z=4186.46], EntitySlime['Slime'/49272, l='MpServer', x=-1304.75, y=4.67, z=4212.02], EntitySlime['Slime'/61049, l='MpServer', x=-1312.03, y=4.02, z=4199.88], EntitySlime['Slime'/81064, l='MpServer', x=-1301.33, y=4.15, z=4198.42], EntitySlime['Slime'/85688, l='MpServer', x=-1374.66, y=4.02, z=4186.34], EntitySlime['Slime'/44362, l='MpServer', x=-1306.69, y=4.02, z=4207.91], EntitySlime['Slime'/64987, l='MpServer', x=-1295.51, y=4.93, z=4183.02], EntitySlime['Slime'/99882, l='MpServer', x=-1388.78, y=4.00, z=4104.34], EntitySlime['Slime'/128650, l='MpServer', x=-1298.50, y=4.75, z=4182.09]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:350)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2488)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 272677352 bytes (260 MB) / 1252360192 bytes (1194 MB) up to 4187619328 bytes (3993 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.32.1319 Minecraft Forge 11.14.1.1319 3 mods loaded, 3 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{8.0.32.1319} [Forge Mod Loader] (forge-1.8-11.14.1.1319.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{11.14.1.1319} [Minecraft Forge] (forge-1.8-11.14.1.1319.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Loaded coremods (and transformers): 
	Launched Version: 1.8-Forge11.14.1.1319
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 860M/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.52, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
[17:50:43] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:492]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Christopher\AppData\Roaming\.minecraft\profiles\Forge\crash-reports\crash-2015-02-17_17.50.43-client.txt
```

Debug Crash Report:
```
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 2/17/15 5:50 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1790)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1021)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:350)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['CAD97'/23, l='MpServer', x=-1331.50, y=4.00, z=4161.50]]
	Chunk stats: MultiplayerChunkCache: 612, 612
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: -1323.00,4.00,4169.00 - World: (-1323,4,4169), Chunk: (at 5,0,9 in -83,260; contains blocks -1328,0,4160 to -1313,255,4175), Region: (-3,8; contains chunks -96,256 to -65,287, blocks -1536,0,4096 to -1025,255,4607)
	Level time: 399 game time, 399 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 12 total; [EntitySlime['Slime'/114882, l='MpServer', x=-1388.63, y=4.00, z=4106.94], EntitySlime['Slime'/31269, l='MpServer', x=-1401.84, y=4.00, z=4187.40], EntityPlayerSP['CAD97'/23, l='MpServer', x=-1331.50, y=4.00, z=4161.50], EntitySlime['Slime'/4248, l='MpServer', x=-1376.68, y=4.91, z=4186.46], EntitySlime['Slime'/49272, l='MpServer', x=-1304.75, y=4.67, z=4212.02], EntitySlime['Slime'/61049, l='MpServer', x=-1312.03, y=4.02, z=4199.88], EntitySlime['Slime'/81064, l='MpServer', x=-1301.33, y=4.15, z=4198.42], EntitySlime['Slime'/85688, l='MpServer', x=-1374.66, y=4.02, z=4186.34], EntitySlime['Slime'/44362, l='MpServer', x=-1306.69, y=4.02, z=4207.91], EntitySlime['Slime'/64987, l='MpServer', x=-1295.51, y=4.93, z=4183.02], EntitySlime['Slime'/99882, l='MpServer', x=-1388.78, y=4.00, z=4104.34], EntitySlime['Slime'/128650, l='MpServer', x=-1298.50, y=4.75, z=4182.09]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:350)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2488)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 272677352 bytes (260 MB) / 1252360192 bytes (1194 MB) up to 4187619328 bytes (3993 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.32.1319 Minecraft Forge 11.14.1.1319 3 mods loaded, 3 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{8.0.32.1319} [Forge Mod Loader] (forge-1.8-11.14.1.1319.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{11.14.1.1319} [Minecraft Forge] (forge-1.8-11.14.1.1319.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Loaded coremods (and transformers): 
	Launched Version: 1.8-Forge11.14.1.1319
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 860M/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.52, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
```

**Comment by diesieben07** [comment]
Already fixed, the build just failed. It will be fixed in a downloadable version soon.

**Comment by LexManos** [comment]
Fixed in build 1320.

**Comment by rebeccastanke** [comment]
I'm getting the error in forge 13.20.1.2513
