### ISSUE TITLE
The new BigWarning for invalid fluids is not always shown

### ISSUE THREAD

**Issue by mezz** [MinecraftForge/MinecraftForge#1794]
When calling these methods with an invalid fluidID:
https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/fluids/FluidStack.java#L54-L66
```java
    // To be removed in 1.8
    @Deprecated
    public FluidStack(int fluidID, int amount)
    {
    	this(FluidRegistry.getFluid(fluidID), amount);
    }
```

This error is not reached:
https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/fluids/FluidStack.java#L32
```java
    public FluidStack(Fluid fluid, int amount)
    {
        if (!FluidRegistry.isFluidRegistered(fluid))
        {
            FMLLog.bigWarning("Failed attempt to create a FluidStack for an unregistered Fluid %s (type %s)", fluid.getName(), fluid.getClass().getName());
            throw new IllegalArgumentException("Cannot create a fluidstack from an unregistered fluid");
        }
    	this.fluid = fluid;
        this.amount = amount;
    }
```

Because this throws an NPE:
https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/fluids/FluidRegistry.java#L98
```java
    public static boolean isFluidRegistered(Fluid fluid)
    {
        return fluids.containsKey(fluid.getName());
    }
```

Stack trace of the issue:
```
Caused by: java.lang.NullPointerException
	at net.minecraftforge.fluids.FluidRegistry.isFluidRegistered(FluidRegistry.java:98) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:30) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:58) ~[FluidStack.class:?]
	at buildcraft.transport.network.PacketFluidUpdate.readData(PacketFluidUpdate.java:87) ~[PacketFluidUpdate.class:?]
	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:47) ~[BuildCraftChannelHandler.class:?]
	at buildcraft.core.network.BuildCraftChannelHandler.decodeInto(BuildCraftChannelHandler.java:22) ~[BuildCraftChannelHandler.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	... 20 more
```

**Comment by cpw** [comment]
Closing, this is fixed and no longer happens..

**Comment by immibis** [comment]
Why is the bigWarning necessary if it already throws an exception?
