### ISSUE TITLE
Cannot create fluid stack from null fluid crash

### ISSUE THREAD

**Issue by cocopuffs99** [MinecraftForge/MinecraftForge#1810]
Getting this CTD when trying to empty Tinkers smeltery fluid metal into casting basin:

Rendering screen
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
	at tconstruct.smeltery.gui.SmelteryGui.func_146979_b(SmelteryGui.java:151)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
	at tconstruct.smeltery.gui.SmelteryGui.func_73863_a(SmelteryGui.java:64)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full log: http://pastebin.com/3MuAh56b

**Comment by LexManos** [comment]
tconstruct issue, not ours, they shouldn't be making a null stack.

**Comment by cocopuffs99** [comment]
@LexManos  I see - I'll send this over to the TConstruct team.  Thanks!

**Comment by Maegro** [comment]
@LexManos This is a very late response but I have the same problem. I do not have T Construct installed, and yet it is still being made a null stack.

**Comment by LexManos** [comment]
Do not use this for basic tech support. And if you TRULY had the same problem, then the answer would be the same. So no reason to post.

**Comment by Maegro** [comment]
@LexManos However, if the answer was the same, then my game would be fixed now. There is a another reason that my game is crashing with this problem, because I do not have Tconstruct. And I'll gladly screen shot it for you, but it's ignorant suggesting that I might not "Truly" have the same problem.

**Comment by KingLemming** [comment]
You absolutely do not have the same problem. Your crashlog will not be identical, precisely because you do not have tconstruct.

What you DO have is a stupid mod. It's not specific to any given mod - just look through your crashlog and you can find the correct offender in your case.

**Comment by LexManos** [comment]
"I have the same problem", "I don't have Tconstruct"
On a issue that is specifically caused by TCon, with TCon in the stack trace. Making it literally impossible to have the same issue without TCon {or something using its name} installed.
Use the forums and trust me when I tell you something.
