### ISSUE TITLE
Okay I am super confused ... Is this a mod or forge issue??

### ISSUE THREAD

**Issue by DPxKnightxZero** [MinecraftForge/MinecraftForge#1820]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/22/15 7:46 AM
Description: Initializing game

java.lang.RuntimeException: java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-7,5,] already has the context current
	at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:380)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:344)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalStateException: From thread Thread[Client thread,5,main]: Thread[Thread-7,5,] already has the context current
	at org.lwjgl.opengl.ContextGL.checkAccess(ContextGL.java:184)
	at org.lwjgl.opengl.ContextGL.makeCurrent(ContextGL.java:189)
	at org.lwjgl.opengl.DrawableGL.makeCurrent(DrawableGL.java:110)
	at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:372)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.client.SplashProgress.finish(SplashProgress.java:380)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:344)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 492031880 bytes (469 MB) / 1187368960 bytes (1132 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

**Comment by portablejim** [comment]
It has to do with MinecraftForge/FML#644

Post the full crash report (the ENTIRE file) to https://gist.github.com/ (it works like pastebin) and post the url to the bottom of MinecraftForge/FML#644 saying you crashed.

**Comment by Lunatrius** [comment]
Also include whether or not you have Optifine/Fastcraft installed.

**Comment by DPxKnightxZero** [comment]
I had both installed.

**Comment by DPxKnightxZero** [comment]
Okay its caused by Optifine.

**Comment by cpw** [comment]
Please do **NOT** leave these types of report here. They belong where @Lunatrius indicates..
