### ISSUE TITLE
World crash on start

### ISSUE THREAD

**Issue by cocopuffs99** [MinecraftForge/MinecraftForge#1852]
Not sure if this is a forge error but might be.  What do you think?

---- Minecraft Crash Report ----
// There are four lights!

Time: 5/4/15 5:01 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
at java.util.TreeMap.cmp(TreeMap.java:1913)
at java.util.TreeMap.containsKey(TreeMap.java:1707)
at net.minecraftforge.common.config.ConfigCategory.containsKey(ConfigCategory.java:231)
at net.minecraftforge.common.config.Configuration.get(Configuration.java:697)
at net.minecraftforge.common.config.Configuration.get(Configuration.java:569)
at net.minecraftforge.common.config.Configuration.get(Configuration.java:555)
at pl.asie.tweaks.creative.TabManager.arrangeItems(TabManager.java:184)
at pl.asie.tweaks.creative.CreativeTabManager.run(CreativeTabManager.java:36)
at pl.asie.tweaks.AsieTweaks.postInit(AsieTweaks.java:168)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:717)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:304)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:

full log: http://pastebin.com/E2dUi0UB

**Comment by LexManos** [comment]
There is something wrong with AsieTweaks's config. Try deleting it, or removing the mod.

**Comment by cocopuffs99** [comment]
@LexManos Thanks for the heads up.  I'll try deleting it and if that doesn't work I'll notify them.
