### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by lightning02** [MinecraftForge/MinecraftForge#1879]
http://pastebin.com/xgZGzTN7

[03:46:37] [main/INFO]: Setting user: _Red_Lightning_
[03:46:39] [Client thread/INFO]: LWJGL Version: 2.9.1
[03:46:53] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Immibis's Microblocks, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Pistronics 2, FMLFileResourcePack:Furnace 3D, FMLFileResourcePack:Doggy Talents, FMLFileResourcePack:Hearts, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:StatusEffectHUD, FMLFileResourcePack:Treecapitator, FMLFileResourcePack:Additional Pipes, FMLFileResourcePack:Advanced Repulsion Systems, FMLFileResourcePack:Advanced Machines, FMLFileResourcePack:Advanced Solar Panels, FMLFileResourcePack:AgriCraft, FMLFileResourcePack:Alchemical Bling, FMLFileResourcePack:Another One Bites The Dust, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:Archimedes' Ships, FMLFileResourcePack:asielib, FMLFileResourcePack:BD Lib, FMLFileResourcePack:Better HUD, FMLFileResourcePack:Better Foliage, FMLFileResourcePack:Better Records, FMLFileResourcePack:Better Sand, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Biomes O'Plenty Edition, FMLFileResourcePack:BiblioWoods Forestry Edition, FMLFileResourcePack:BiblioWoods Natura Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Botany, FMLFileResourcePack:Binnie Core, FMLFileResourcePack:Extra Bees, FMLFileResourcePack:Extra Trees, FMLFileResourcePack:Genetics, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Botania, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BuildCraft Compat, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:Catwalks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Compact Machines, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Cookie Core, FMLFileResourcePack:Build Mod, FMLFileResourcePack:CoroPets, FMLFileResourcePack:CoroAI, FMLFileResourcePack:Extended Renderer, FMLFileResourcePack:Extended Mod Config, FMLFileResourcePack:Cosmetic Wings, FMLFileResourcePack:CraftHeraldry, FMLFileResourcePack:Decocraft, FMLFileResourcePack:debug, FMLFileResourcePack:Dense Ores, FMLFileResourcePack:Dimensional Anchors, FMLFileResourcePack:DragonAPI, FMLFileResourcePack:DrZhark's Mo'Creatures Mod, FMLFileResourcePack:Dual Hotbar, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:Enchvil Mod, FMLFileResourcePack:Ender Compass, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:Extra Carts, FMLFileResourcePack:ExtraCells, FMLFileResourcePack:ExtraTiC, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:Factorization Miscellaneous Nonsense, FMLFileResourcePack:Factorization Notification System, FMLFileResourcePack:Factorization, FMLFileResourcePack:Fairy Lights, FMLFileResourcePack:FastCraft, FMLFileResourcePack:Flan's Mod, FMLFileResourcePack:Forbidden Magic, FMLFileResourcePack:Forestry for Minecraft, FMLFileResourcePack:FortuneOres, FMLFileResourcePack:Fossils and Archeology Revival, FMLFileResourcePack:FoxLib, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Garden Containers, FMLFileResourcePack:Garden Core, FMLFileResourcePack:Garden Stuff, FMLFileResourcePack:Garden Trees, FMLFileResourcePack:GenDustry, FMLFileResourcePack:Graviation Suite, FMLFileResourcePack:GraviGun, FMLFileResourcePack:Growthcraft Apples, FMLFileResourcePack:Growthcraft Bamboo, FMLFileResourcePack:Growthcraft Bees, FMLFileResourcePack:Growthcraft Cellar, FMLFileResourcePack:Growthcraft, FMLFileResourcePack:Growthcraft Fishtrap, FMLFileResourcePack:Growthcraft Grapes, FMLFileResourcePack:Growthcraft Hops, FMLFileResourcePack:Growthcraft Rice, FMLFileResourcePack:Hats, FMLFileResourcePack:HatStand, FMLFileResourcePack:Nuclear Control 2, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:JABBA, FMLFileResourcePack:Luppii's Ladders, FMLFileResourcePack:Lamps and Traffic lights, FMLFileResourcePack:kris91268's Light Bridges and Doors, FMLFileResourcePack:Liquid XP, FMLFileResourcePack:Logistics Pipes, FMLFileResourcePack:Lycanites Mobs, FMLFileResourcePack:Lycanites Freshwater Mobs, FMLFileResourcePack:Lycanites Demon Mobs, FMLFileResourcePack:Lycanites Desert Mobs, FMLFileResourcePack:Lycanites Mountain Mobs, FMLFileResourcePack:Lycanites Jungle Mobs, FMLFileResourcePack:Lycanites Swamp Mobs, FMLFileResourcePack:Lycanites Shadow Mobs, FMLFileResourcePack:Lycanites Inferno Mobs, FMLFileResourcePack:Lycanites Saltwater Mobs, FMLFileResourcePack:Lycanites Forest Mobs, FMLFileResourcePack:Lycanites Plains Mobs, FMLFileResourcePack:Lycanites Arctic Mobs, FMLFileResourcePack:Magic Bees, FMLFileResourcePack:MalisisCore, FMLFileResourcePack:Malisis' Doors, FMLFileResourcePack:Mantle, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:MillÃ©naire, FMLFileResourcePack:Minechem, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:Mythril mod, FMLFileResourcePack:MobAmputation, FMLFileResourcePack:MachineMuse's Modular Powersuits, FMLFileResourcePack:Modular Powersuit Addons, FMLFileResourcePack:More Enchantments, FMLFileResourcePack:AencEx, FMLFileResourcePack:§9MrCrayfish's Furniture Mod, FMLFileResourcePack:MusicCraft, FMLFileResourcePack:Natura, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Applied Energistics 2, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:Nether Ores, FMLFileResourcePack:NotEnoughCodecs, FMLFileResourcePack:Numina, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenMods, FMLFileResourcePack:Open Modular Turrets, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:Placeable Items Mod, FMLFileResourcePack:planetguyLib, FMLFileResourcePack:PneumaticCraft, FMLFileResourcePack:PortalGun, FMLFileResourcePack:Power Converters, FMLFileResourcePack:Practicalities, FMLFileResourcePack:Pressure Pipes, FMLFileResourcePack:ProjectRed, FMLFileResourcePack:ProjectRed-Compatibility, FMLFileResourcePack:ProjectRed-Integration, FMLFileResourcePack:ProjectRed-Transmission, FMLFileResourcePack:ProjectRed-Illumination, FMLFileResourcePack:ProjectRed-Expansion, FMLFileResourcePack:ProjectRed-Transportation, FMLFileResourcePack:ProjectRed-Exploration, FMLFileResourcePack:Psychedelicraft, FMLFileResourcePack:QuarryPlus, FMLFileResourcePack:RadixCore, FMLFileResourcePack:Railcraft, FMLFileResourcePack:ReactorCraft, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Remain In Motion, FMLFileResourcePack:RikMuld's Core, FMLFileResourcePack:Rival Rebels, FMLFileResourcePack:RoadWorks, FMLFileResourcePack:Roguelike Dungeons, FMLFileResourcePack:Rollercoaster Mod, FMLFileResourcePack:RotaryCraft, FMLFileResourcePack:The SecretRoomsMod, FMLFileResourcePack:Greg's SG Craft, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:TheRealMcrafter's Siren Mod (Version 3.0.0), FMLFileResourcePack:Soul Shards Reborn, FMLFileResourcePack:Statues, FMLFileResourcePack:Steve's Carts 2, FMLFileResourcePack:Steve's Factory Manager, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Technomancy, FMLFileResourcePack:Thaumcarpentry, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thaumic Tinkerer, FMLFileResourcePack:The Camping Mod 2, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:TiC Tooltips, FMLFileResourcePack:Tinkers' Mechworks, FMLFileResourcePack:Trade Booth Mod, FMLFileResourcePack:Tinkers' Steelworks, FMLFileResourcePack:ttCore, FMLFileResourcePack:Tubestuff, FMLFileResourcePack:Thaumic Warden, FMLFileResourcePack:The Twilight Forest, FMLFileResourcePack:Universal Coins, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:WAILA Plugins, FMLFileResourcePack:weather2, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:Ye Gamol Chattels, FMLFileResourcePack:Ztones, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:libsandstone, FMLFileResourcePack:MrTJPCore, msi_conversion.zip, Pixel Reality Atmosphere.zip
[03:46:53] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:53] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:53] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:53] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:53] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:53] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:54] [Client thread/WARN]: File minecraft:sounds/matmos_interactions/jumpina.ogg does not exist, cannot add it to event minecraft:matmos_interactions.jumpina
[03:46:54] [Client thread/WARN]: File minecraft:sounds/matmos_msi/cave/woodb.ogg does not exist, cannot add it to event minecraft:matmos_msi.cave.woodb
[03:46:54] [Client thread/WARN]: File minecraft:sounds/matmos_msi/cave/woodc.ogg does not exist, cannot add it to event minecraft:matmos_msi.cave.woodc
[03:46:54] [Client thread/WARN]: Invalid sounds.json
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
	at net.minecraft.client.audio.SoundHandler.func_110549_a(SourceFile:78) [btp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SourceFile:99) [brg.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:486) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	... 12 more
[03:46:54] [Sound Library Loader/INFO]: Sound engine started
[03:46:57] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[03:46:57] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[03:46:57] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Immibis's Microblocks, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:Pistronics 2, FMLFileResourcePack:Furnace 3D, FMLFileResourcePack:Doggy Talents, FMLFileResourcePack:Hearts, FMLFileResourcePack:Damage Indicators, FMLFileResourcePack:StatusEffectHUD, FMLFileResourcePack:Treecapitator, FMLFileResourcePack:Additional Pipes, FMLFileResourcePack:Advanced Repulsion Systems, FMLFileResourcePack:Advanced Machines, FMLFileResourcePack:Advanced Solar Panels, FMLFileResourcePack:AgriCraft, FMLFileResourcePack:Alchemical Bling, FMLFileResourcePack:Another One Bites The Dust, FMLFileResourcePack:Applied Energistics 2, FMLFileResourcePack:Archimedes' Ships, FMLFileResourcePack:asielib, FMLFileResourcePack:BD Lib, FMLFileResourcePack:Better HUD, FMLFileResourcePack:Better Foliage, FMLFileResourcePack:Better Records, FMLFileResourcePack:Better Sand, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:BiblioWoods Biomes O'Plenty Edition, FMLFileResourcePack:BiblioWoods Forestry Edition, FMLFileResourcePack:BiblioWoods Natura Edition, FMLFileResourcePack:Big Reactors, FMLFileResourcePack:Botany, FMLFileResourcePack:Binnie Core, FMLFileResourcePack:Extra Bees, FMLFileResourcePack:Extra Trees, FMLFileResourcePack:Genetics, FMLFileResourcePack:Biomes O' Plenty, FMLFileResourcePack:Botania, FMLFileResourcePack:BC Silicon, FMLFileResourcePack:BuildCraft, FMLFileResourcePack:BC Transport, FMLFileResourcePack:BC Builders, FMLFileResourcePack:BC Energy, FMLFileResourcePack:BC Factory, FMLFileResourcePack:BuildCraft Compat, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:Catwalks, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:Chisel 2, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Compact Machines, FMLFileResourcePack:ComputerCraft, FMLFileResourcePack:Cookie Core, FMLFileResourcePack:Build Mod, FMLFileResourcePack:CoroPets, FMLFileResourcePack:CoroAI, FMLFileResourcePack:Extended Renderer, FMLFileResourcePack:Extended Mod Config, FMLFileResourcePack:Cosmetic Wings, FMLFileResourcePack:CraftHeraldry, FMLFileResourcePack:Decocraft, FMLFileResourcePack:debug, FMLFileResourcePack:Dense Ores, FMLFileResourcePack:Dimensional Anchors, FMLFileResourcePack:DragonAPI, FMLFileResourcePack:DrZhark's Mo'Creatures Mod, FMLFileResourcePack:Dual Hotbar, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:Enchvil Mod, FMLFileResourcePack:Ender Compass, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:Extra Carts, FMLFileResourcePack:ExtraCells, FMLFileResourcePack:ExtraTiC, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:Factorization Miscellaneous Nonsense, FMLFileResourcePack:Factorization Notification System, FMLFileResourcePack:Factorization, FMLFileResourcePack:Fairy Lights, FMLFileResourcePack:FastCraft, FMLFileResourcePack:Flan's Mod, FMLFileResourcePack:Forbidden Magic, FMLFileResourcePack:Forestry for Minecraft, FMLFileResourcePack:FortuneOres, FMLFileResourcePack:Fossils and Archeology Revival, FMLFileResourcePack:FoxLib, FMLFileResourcePack:Galacticraft Planets, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Garden Containers, FMLFileResourcePack:Garden Core, FMLFileResourcePack:Garden Stuff, FMLFileResourcePack:Garden Trees, FMLFileResourcePack:GenDustry, FMLFileResourcePack:Graviation Suite, FMLFileResourcePack:GraviGun, FMLFileResourcePack:Growthcraft Apples, FMLFileResourcePack:Growthcraft Bamboo, FMLFileResourcePack:Growthcraft Bees, FMLFileResourcePack:Growthcraft Cellar, FMLFileResourcePack:Growthcraft, FMLFileResourcePack:Growthcraft Fishtrap, FMLFileResourcePack:Growthcraft Grapes, FMLFileResourcePack:Growthcraft Hops, FMLFileResourcePack:Growthcraft Rice, FMLFileResourcePack:Hats, FMLFileResourcePack:HatStand, FMLFileResourcePack:Nuclear Control 2, FMLFileResourcePack:iChunUtil, FMLFileResourcePack:Immibis Core, FMLFileResourcePack:IndustrialCraft 2, FMLFileResourcePack:Inventory Tweaks, FMLFileResourcePack:Iron Chest, FMLFileResourcePack:JABBA, FMLFileResourcePack:Luppii's Ladders, FMLFileResourcePack:Lamps and Traffic lights, FMLFileResourcePack:kris91268's Light Bridges and Doors, FMLFileResourcePack:Liquid XP, FMLFileResourcePack:Logistics Pipes, FMLFileResourcePack:Lycanites Mobs, FMLFileResourcePack:Lycanites Freshwater Mobs, FMLFileResourcePack:Lycanites Demon Mobs, FMLFileResourcePack:Lycanites Desert Mobs, FMLFileResourcePack:Lycanites Mountain Mobs, FMLFileResourcePack:Lycanites Jungle Mobs, FMLFileResourcePack:Lycanites Swamp Mobs, FMLFileResourcePack:Lycanites Shadow Mobs, FMLFileResourcePack:Lycanites Inferno Mobs, FMLFileResourcePack:Lycanites Saltwater Mobs, FMLFileResourcePack:Lycanites Forest Mobs, FMLFileResourcePack:Lycanites Plains Mobs, FMLFileResourcePack:Lycanites Arctic Mobs, FMLFileResourcePack:Magic Bees, FMLFileResourcePack:MalisisCore, FMLFileResourcePack:Malisis' Doors, FMLFileResourcePack:Mantle, FMLFileResourcePack:Mekanism, FMLFileResourcePack:MekanismGenerators, FMLFileResourcePack:MekanismTools, FMLFileResourcePack:MillÃ©naire, FMLFileResourcePack:Minechem, FMLFileResourcePack:MineFactory Reloaded, FMLFileResourcePack:MFR Compat: Applied Energistics, FMLFileResourcePack:MFR Compat: Atum, FMLFileResourcePack:MFR Compat: BackTools, FMLFileResourcePack:MFR Compat: BuildCraft, FMLFileResourcePack:MFR Compat: Chococraft, FMLFileResourcePack:MFR Compat: ExtraBiomes, FMLFileResourcePack:MFR Compat: Forestry, FMLFileResourcePack:MFR Compat: ForgeMicroblock, FMLFileResourcePack:MFR Compat: IC2, FMLFileResourcePack:MFR Compat: Mystcraft, FMLFileResourcePack:MFR Compat ProjectRed, FMLFileResourcePack:MFR Compat: Railcraft, FMLFileResourcePack:MFR Compat: Sufficient Biomes, FMLFileResourcePack:MFR Compat: Thaumcraft, FMLFileResourcePack:MFR Compat: Thermal Expansion, FMLFileResourcePack:MFR Compat: Tinkers' Construct, FMLFileResourcePack:MFR Compat: TwilightForest, FMLFileResourcePack:MFR Compat: Vanilla, FMLFileResourcePack:Mythril mod, FMLFileResourcePack:MobAmputation, FMLFileResourcePack:MachineMuse's Modular Powersuits, FMLFileResourcePack:Modular Powersuit Addons, FMLFileResourcePack:More Enchantments, FMLFileResourcePack:AencEx, FMLFileResourcePack:§9MrCrayfish's Furniture Mod, FMLFileResourcePack:MusicCraft, FMLFileResourcePack:Natura, FMLFileResourcePack:NEI Addons, FMLFileResourcePack:NEI Addons: Applied Energistics 2, FMLFileResourcePack:NEI Addons: Botany, FMLFileResourcePack:NEI Addons: Forestry, FMLFileResourcePack:NEI Addons: Crafting Tables, FMLFileResourcePack:NEI Addons: Ex Nihilo, FMLFileResourcePack:NEI Integration, FMLFileResourcePack:Nether Ores, FMLFileResourcePack:NotEnoughCodecs, FMLFileResourcePack:Numina, FMLFileResourcePack:OpenBlocks, FMLFileResourcePack:OpenMods, FMLFileResourcePack:Open Modular Turrets, FMLFileResourcePack:OpenPeripheralIntegration, FMLFileResourcePack:OpenPeripheralCore, FMLFileResourcePack:OpenPeripheralAddons, FMLFileResourcePack:Pam's HarvestCraft, FMLFileResourcePack:Placeable Items Mod, FMLFileResourcePack:planetguyLib, FMLFileResourcePack:PneumaticCraft, FMLFileResourcePack:PortalGun, FMLFileResourcePack:Power Converters, FMLFileResourcePack:Practicalities, FMLFileResourcePack:Pressure Pipes, FMLFileResourcePack:ProjectRed, FMLFileResourcePack:ProjectRed-Compatibility, FMLFileResourcePack:ProjectRed-Integration, FMLFileResourcePack:ProjectRed-Transmission, FMLFileResourcePack:ProjectRed-Illumination, FMLFileResourcePack:ProjectRed-Expansion, FMLFileResourcePack:ProjectRed-Transportation, FMLFileResourcePack:ProjectRed-Exploration, FMLFileResourcePack:Psychedelicraft, FMLFileResourcePack:QuarryPlus, FMLFileResourcePack:RadixCore, FMLFileResourcePack:Railcraft, FMLFileResourcePack:ReactorCraft, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:Remain In Motion, FMLFileResourcePack:RikMuld's Core, FMLFileResourcePack:Rival Rebels, FMLFileResourcePack:RoadWorks, FMLFileResourcePack:Roguelike Dungeons, FMLFileResourcePack:Rollercoaster Mod, FMLFileResourcePack:RotaryCraft, FMLFileResourcePack:The SecretRoomsMod, FMLFileResourcePack:Greg's SG Craft, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:TheRealMcrafter's Siren Mod (Version 3.0.0), FMLFileResourcePack:Soul Shards Reborn, FMLFileResourcePack:Statues, FMLFileResourcePack:Steve's Carts 2, FMLFileResourcePack:Steve's Factory Manager, FMLFileResourcePack:Tinkers' Construct, FMLFileResourcePack:Technomancy, FMLFileResourcePack:Thaumcarpentry, FMLFileResourcePack:Thaumcraft, FMLFileResourcePack:Thaumic Tinkerer, FMLFileResourcePack:The Camping Mod 2, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:TiC Tooltips, FMLFileResourcePack:Tinkers' Mechworks, FMLFileResourcePack:Trade Booth Mod, FMLFileResourcePack:Tinkers' Steelworks, FMLFileResourcePack:ttCore, FMLFileResourcePack:Tubestuff, FMLFileResourcePack:Thaumic Warden, FMLFileResourcePack:The Twilight Forest, FMLFileResourcePack:Universal Coins, FMLFileResourcePack:Waila, FMLFileResourcePack:Waila Harvestability, FMLFileResourcePack:WAILA Plugins, FMLFileResourcePack:weather2, FMLFileResourcePack:WR-CBE Core, FMLFileResourcePack:WR-CBE Addons, FMLFileResourcePack:WR-CBE Logic, FMLFileResourcePack:Ye Gamol Chattels, FMLFileResourcePack:Ztones, FMLFileResourcePack:bspkrsCore, FMLFileResourcePack:Baubles, FMLFileResourcePack:Forge Microblocks, FMLFileResourcePack:Forge Multipart, FMLFileResourcePack:Minecraft Multipart Plugin, FMLFileResourcePack:libsandstone, FMLFileResourcePack:MrTJPCore, LiteLoader, VoxelMenu, MAtmos, VoxelMap, VoxelLib, Lighting Fix, VoxelMenu Music, msi_conversion.zip, Pixel Reality Atmosphere.zip
[03:46:57] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:57] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:57] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:57] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:57] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:57] [Client thread/WARN]: ResourcePack: ignored non-lowercase namespace: %s in %s
[03:46:58] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[03:46:58] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[03:46:59] [Client thread/WARN]: File minecraft:sounds/matmos_interactions/jumpina.ogg does not exist, cannot add it to event minecraft:matmos_interactions.jumpina
[03:46:59] [Client thread/WARN]: File minecraft:sounds/matmos_msi/cave/woodb.ogg does not exist, cannot add it to event minecraft:matmos_msi.cave.woodb
[03:46:59] [Client thread/WARN]: File minecraft:sounds/matmos_msi/cave/woodc.ogg does not exist, cannot add it to event minecraft:matmos_msi.cave.woodc
[03:46:59] [Client thread/WARN]: Invalid sounds.json
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2
	at com.google.gson.Gson.fromJson(Gson.java:818) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
	at net.minecraft.client.audio.SoundHandler.func_110549_a(SourceFile:78) [btp.class:?]
	at com.mumfrey.liteloader.client.SoundHandlerReloadInhibitor.unInhibit(SoundHandlerReloadInhibitor.java:107) [SoundHandlerReloadInhibitor.class:1.7.10_04]
	at com.mumfrey.liteloader.client.LiteLoaderCoreProviderClient.onStartupComplete(LiteLoaderCoreProviderClient.java:72) [LiteLoaderCoreProviderClient.class:1.7.10_04]
	at com.mumfrey.liteloader.core.event.HandlerList$CoreProvider0.onStartupComplete(HandlerList$CoreProvider0.java:100) [?:1.7.10_04]
	at com.mumfrey.liteloader.core.LiteLoader.onStartupComplete(LiteLoader.java:909) [LiteLoader.class:1.7.10_04]
	at com.mumfrey.liteloader.core.Events.onStartupComplete(Events.java:95) [Events.class:1.7.10_04]
	at com.mumfrey.liteloader.client.ClientEvents.onStartupComplete(ClientEvents.java:260) [ClientEvents.class:1.7.10_04]
	at com.mumfrey.liteloader.client.CallbackProxyClient.onStartupComplete(CallbackProxyClient.java:48) [CallbackProxyClient.class:1.7.10_04]
	at com.mumfrey.liteloader.core.event.EventProxy.$event00000(EventProxy.java:211) [EventProxy.class:1.7.10_04]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:573) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 4 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
	... 19 more
[03:47:00] [Sound Library Loader/INFO]: Sound engine started

http://imgur.com/7nAacOF

i've already tried to delete .json file but nothing..

**Comment by Bogdan-G** [comment]
Change version mods for example CoFH. Delete CoFHLib.

**Comment by lightning02** [comment]
I tried to delete and replace the CoFHcore but i don't have idea what you mean for CoFHlib.
I tried the same thing with forge (modpack.jar)
My version of forge is 10.13.1.191,10.14 i guess.
Forge mod loader is for sure version 7.10.114.1388
Anyway you can find all this information in the image that i posted above and in the logs.

**Comment by lightning02** [comment]
Oh god.. the CoFHlib! I ceched around and i figured out thai i was exactly missing that library for CoFHcore!
Actually it works, thank you very much!
Anyway this was weird because it didn't give problems until now.
