### ISSUE TITLE
java.lang.NullPointerException: Colliding entity with block

### ISSUE THREAD

**Issue by Nightreaver** [MinecraftForge/MinecraftForge#1888]
So, because this is modded MC i hope im right, as it doesnt seem to have any mod as cause of this issue - hopefully - dont be angry if I'm wrong

With Forge 10.13.3.1408, MC 1.7.10

Looks like so

java.lang.NullPointerException: Colliding entity with block
        at net.minecraft.block.BlockPortal.func_149670_a(SourceFile:30)
        at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
        at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1490)
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1814)
        at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
        at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
        at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
        ...

Got couple of these, it looks like its always when spawning Zombie Pigman

full crashlog in here -> http://pastebin.com/8dngfqe7

Cheers

**Comment by LexManos** [comment]
Forums
