### ISSUE TITLE
[10.13.3.1428] HashMap

### ISSUE THREAD

**Issue by NitroxydeX** [MinecraftForge/MinecraftForge#1925]
I don't know if this is a forge related problem but what I know is that this not happen in Forge 10.13.3.1408.

```
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:269)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:648)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by diesieben07** [comment]
When does this happen? Always? Only sometimes? Under what circumstances?

**Comment by LexManos** [comment]
This is a mod or the like adding something to the world outside of the world thread.
Remove all mods and see if it happens.
Also move this to the forums.
