### ISSUE TITLE
Forge bug: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by DrakoAlcarus** [MinecraftForge/MinecraftForge#1955]
Apparently this is an old issue, but the old fixes aren't working. I tried downgrading to Java 7, but the game would simply freeze up during the "finishing up" stage (6 of 7). I tried testing mods and removing them. I used the method with the newly installed mods, with no avail. I even tried the LegacyJavaFix mod.

[Basic info]
- Version 1.7.10 with current recommended version of Forge
- Java 1.8.0_45

[The highlighted info]

Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:46)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_404_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

If you need more info, I'd be happy to give more. But I'm looking for a fast permanant fix as soon as possible.

Thanks.

**Comment by simon816** [comment]
Issue with MrTJPCore, update it
https://github.com/MrTJP/MrTJPCore/issues/9

**Comment by DrakoAlcarus** [comment]
Ah, danke. It was in this line:

at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:46)

But I didn't think it was part of the issue. Shaders also suddenly work.
