### ISSUE TITLE
Space in folder path causes NPE

### ISSUE THREAD

**Issue by Kubuxu** [MinecraftForge/MinecraftForge#2001]
NPE is thrown at: [CoreModManager.java:254](https://github.com/MinecraftForge/MinecraftForge/blob/ee414b2037d88a3941ae6c46f4b69222400b8a03/fml/src/main/java/cpw/mods/fml/relauncher/CoreModManager.java#L254).
I have space in my user name.

**Comment by LexManos** [comment]
Logs

**Comment by Kubuxu** [comment]
It won't reveal more than I've said already:
```
[15:10:55] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[15:10:55] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[15:10:55] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[15:10:55] [main/INFO] [FML]: Forge Mod Loader version 7.99.16.1448 for Minecraft 1.7.10 loading
[15:10:55] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_40, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre1.8.0_40
[15:10:55] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Programs\Starcha for Forge Mod Loader
java.lang.NullPointerException
	at com.google.common.collect.ObjectArrays.concat(ObjectArrays.java:73) ~[guava-17.0.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:254) ~[forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:214) ~[forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
	at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
	at cpw.mods.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:126) [forge-1.7.10-10.13.4.1448-1.7.10.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

**Comment by Lunatrius** [comment]
Do you have a `mods/1.7.10` directory? The only thing that can be null is `coreModList`. If you create the folder manually the stack trace will most likely point at line 251 instead.

**Comment by Kubuxu** [comment]
@Lunatrius I have it. Look at he 6th line of logs it should have been `C:\Programs\Starcha sers\starchasers\minecraft\instances\starchasersmodpack\`
