### ISSUE TITLE
Game Crashes Every Time a Ghast Shoots a Fireball

### ISSUE THREAD

**Issue by Delocuro** [MinecraftForge/MinecraftForge#2028]
What the title says. Literally every time any Ghast shoots a fireball, the game instantly crashes. The following crash log resulted from testing this with no mods except Forge itself installed.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/17/15 1:45 AM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at net.minecraft.client.renderer.entity.RenderFireball.func_76986_a(SourceFile:36)
	at net.minecraft.client.renderer.entity.RenderFireball.func_76986_a(SourceFile:13)
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:370)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:327)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:294)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:631)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1297)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1035)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderFireball.func_76986_a(SourceFile:36)
	at net.minecraft.client.renderer.entity.RenderFireball.func_76986_a(SourceFile:13)

-- Entity being rendered --
Details:
	Entity Type: Fireball (net.minecraft.entity.projectile.EntityLargeFireball)
	Entity ID: 5726
	Entity Name: Fireball
	Entity's Exact location: -207.88, 68.38, 145.47
	Entity's Block location: -208.00,68.00,145.00 - World: (-208,68,145), Chunk: (at 0,4,1 in -13,9; contains blocks -208,0,144 to -193,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Rider: ~~ERROR~~ NullPointerException: null
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.RenderFireball@17d6e44
	Location: -14.94,4.38,6.75 - World: (-15,4,6), Chunk: (at 1,0,6 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -56.133816
	Delta: 0.4867973
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:370)
	at net.minecraft.client.renderer.entity.RenderManager.func_147936_a(RenderManager.java:327)
	at net.minecraft.client.renderer.entity.RenderManager.func_147937_a(RenderManager.java:294)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:631)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1297)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1210)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Delocuro'/291, l='MpServer', x=-192.95, y=64.00, z=138.72]]
	Chunk stats: MultiplayerChunkCache: 540, 540
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -180.00,64.00,140.00 - World: (-180,64,140), Chunk: (at 12,4,12 in -12,8; contains blocks -192,0,128 to -177,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 543 game time, 543 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 118 total; [EntityCow['Cow'/85, l='MpServer', x=-267.50, y=66.00, z=100.50], EntityCow['Cow'/86, l='MpServer', x=-269.50, y=67.00, z=100.50], EntityCow['Cow'/87, l='MpServer', x=-271.50, y=72.00, z=98.50], EntityCow['Cow'/88, l='MpServer', x=-268.50, y=67.00, z=98.50], EntityItem['item.tile.gravel'/2136, l='MpServer', x=-227.97, y=30.00, z=196.19], EntityRabbit['Rabbit'/89, l='MpServer', x=-264.19, y=66.00, z=121.69], EntityRabbit['Rabbit'/90, l='MpServer', x=-265.09, y=66.00, z=120.91], EntityRabbit['Rabbit'/91, l='MpServer', x=-263.31, y=66.00, z=121.34], EntitySheep['Sheep'/92, l='MpServer', x=-270.50, y=74.00, z=132.50], EntitySheep['Sheep'/93, l='MpServer', x=-271.06, y=73.00, z=125.06], EntityRabbit['Rabbit'/96, l='MpServer', x=-267.50, y=71.00, z=204.50], EntityRabbit['Rabbit'/98, l='MpServer', x=-267.22, y=64.00, z=203.78], EntityMinecartChest['container.minecart'/111, l='MpServer', x=-232.50, y=31.06, z=189.50], EntityRabbit['Rabbit'/112, l='MpServer', x=-236.31, y=84.00, z=210.97], EntityRabbit['Rabbit'/113, l='MpServer', x=-238.66, y=93.00, z=202.34], EntityRabbit['Rabbit'/114, l='MpServer', x=-248.34, y=87.00, z=208.38], EntitySheep['Sheep'/115, l='MpServer', x=-246.47, y=89.00, z=200.44], EntitySheep['Sheep'/116, l='MpServer', x=-248.47, y=85.00, z=194.81], EntitySheep['Sheep'/117, l='MpServer', x=-240.41, y=87.00, z=204.41], EntitySheep['Sheep'/118, l='MpServer', x=-248.78, y=87.00, z=209.44], EntityRabbit['Rabbit'/122, l='MpServer', x=-217.50, y=90.00, z=192.50], EntityRabbit['Rabbit'/123, l='MpServer', x=-219.66, y=83.00, z=189.34], EntityRabbit['Rabbit'/124, l='MpServer', x=-222.66, y=83.00, z=192.34], EntityItem['item.tile.torch'/128, l='MpServer', x=-214.19, y=33.00, z=165.81], EntityMinecartChest['container.minecart'/129, l='MpServer', x=-204.50, y=34.06, z=189.50], EntityItem['item.tile.flower2.poppy'/2191, l='MpServer', x=-180.97, y=64.00, z=78.84], EntityItem['item.tile.torch'/146, l='MpServer', x=-195.84, y=34.00, z=184.13], EntityMinecartChest['container.minecart'/147, l='MpServer', x=-191.50, y=33.06, z=209.50], EntityCow['Cow'/151, l='MpServer', x=-175.50, y=63.00, z=66.50], EntityCow['Cow'/152, l='MpServer', x=-177.50, y=63.00, z=65.50], EntityItem['item.tile.torch'/153, l='MpServer', x=-169.78, y=34.00, z=188.34], EntityMinecartChest['container.minecart'/154, l='MpServer', x=-171.13, y=34.00, z=189.50], EntityItem['item.tile.rail'/155, l='MpServer', x=-170.75, y=34.00, z=189.88], EntityMinecartChest['container.minecart'/156, l='MpServer', x=-172.50, y=27.06, z=204.50], EntityMinecartChest['container.minecart'/157, l='MpServer', x=-182.50, y=33.06, z=213.50], EntityItem['item.tile.rail'/167, l='MpServer', x=-160.25, y=34.00, z=187.25], EntityItem['item.tile.rail'/168, l='MpServer', x=-155.78, y=34.00, z=187.13], EntityItem['item.tile.rail'/170, l='MpServer', x=-153.38, y=34.00, z=188.25], EntityItem['item.tile.rail'/172, l='MpServer', x=-163.88, y=34.00, z=187.13], EntityMinecartChest['container.minecart'/174, l='MpServer', x=-166.50, y=35.06, z=214.50], EntityItem['item.tile.torch'/193, l='MpServer', x=-130.53, y=32.00, z=188.31], EntitySheep['Sheep'/198, l='MpServer', x=-118.50, y=71.00, z=200.50], EntitySheep['Sheep'/199, l='MpServer', x=-120.31, y=71.00, z=201.16], EntitySheep['Sheep'/200, l='MpServer', x=-116.50, y=72.00, z=204.50], EntitySheep['Sheep'/201, l='MpServer', x=-119.50, y=72.00, z=207.50], EntityEnderman['Enderman'/307, l='MpServer', x=-212.50, y=33.00, z=178.50], EntityBat['Bat'/330, l='MpServer', x=-236.51, y=57.74, z=164.41], EntityBat['Bat'/335, l='MpServer', x=-167.58, y=17.06, z=126.51], EntityBat['Bat'/338, l='MpServer', x=-199.48, y=41.27, z=208.73], EntityPlayerSP['Delocuro'/291, l='MpServer', x=-192.95, y=64.00, z=138.72], EntityCreeper['Creeper'/356, l='MpServer', x=-229.16, y=47.00, z=185.50], EntityCreeper['Creeper'/357, l='MpServer', x=-221.50, y=46.00, z=190.50], EntityCreeper['Creeper'/358, l='MpServer', x=-225.50, y=46.00, z=194.50], EntityCreeper['Creeper'/366, l='MpServer', x=-161.50, y=15.00, z=127.50], EntityEnderman['Enderman'/407, l='MpServer', x=-174.47, y=16.00, z=121.91], EntityEnderman['Enderman'/408, l='MpServer', x=-169.75, y=15.00, z=132.13], EntitySkeleton['Skeleton'/409, l='MpServer', x=-169.72, y=15.00, z=130.28], EntityBat['Bat'/486, l='MpServer', x=-117.05, y=21.18, z=141.38], EntityBat['Bat'/495, l='MpServer', x=-150.68, y=29.11, z=127.45], EntityBat['Bat'/497, l='MpServer', x=-149.78, y=29.02, z=125.59], EntityBat['Bat'/498, l='MpServer', x=-130.32, y=37.01, z=126.93], EntityBat['Bat'/500, l='MpServer', x=-145.47, y=21.10, z=102.25], EntitySkeleton['Skeleton'/619, l='MpServer', x=-135.50, y=17.00, z=145.50], EntitySkeleton['Skeleton'/623, l='MpServer', x=-130.84, y=17.00, z=144.69], EntitySkeleton['Skeleton'/624, l='MpServer', x=-127.78, y=16.00, z=139.66], EntitySkeleton['Skeleton'/625, l='MpServer', x=-135.50, y=17.00, z=148.50], EntityCreeper['Creeper'/626, l='MpServer', x=-172.31, y=13.00, z=132.69], EntityZombie['Zombie'/708, l='MpServer', x=-121.50, y=17.00, z=148.50], EntitySkeleton['Skeleton'/946, l='MpServer', x=-221.50, y=32.00, z=124.50], EntitySkeleton['Skeleton'/967, l='MpServer', x=-185.50, y=27.00, z=214.50], EntitySkeleton['Skeleton'/968, l='MpServer', x=-184.72, y=27.00, z=200.75], EntitySkeleton['Skeleton'/987, l='MpServer', x=-164.53, y=44.00, z=189.88], EntityCreeper['Creeper'/988, l='MpServer', x=-174.50, y=43.00, z=202.50], EntityCreeper['Creeper'/989, l='MpServer', x=-175.50, y=17.00, z=166.81], EntityCreeper['Creeper'/990, l='MpServer', x=-175.50, y=17.00, z=167.69], EntityCreeper['Creeper'/991, l='MpServer', x=-174.50, y=17.00, z=163.50], EntityCreeper['Creeper'/992, l='MpServer', x=-172.50, y=17.00, z=168.50], EntityCreeper['Creeper'/993, l='MpServer', x=-204.97, y=45.00, z=138.47], EntityCreeper['Creeper'/994, l='MpServer', x=-225.09, y=45.00, z=131.63], EntitySkeleton['Skeleton'/995, l='MpServer', x=-211.98, y=45.00, z=136.57], EntitySkeleton['Skeleton'/996, l='MpServer', x=-209.50, y=45.00, z=136.50], EntitySkeleton['Skeleton'/1013, l='MpServer', x=-264.50, y=12.00, z=79.50], EntityCreeper['Creeper'/1056, l='MpServer', x=-239.50, y=56.00, z=162.50], EntityCreeper['Creeper'/1057, l='MpServer', x=-241.50, y=56.00, z=162.50], EntityCreeper['Creeper'/1080, l='MpServer', x=-223.44, y=43.00, z=211.94], EntityCreeper['Creeper'/1081, l='MpServer', x=-219.50, y=40.00, z=210.50], EntityCreeper['Creeper'/1082, l='MpServer', x=-220.50, y=40.00, z=211.50], EntitySkeleton['Skeleton'/1083, l='MpServer', x=-215.50, y=40.00, z=208.50], EntityZombie['Zombie'/1242, l='MpServer', x=-164.22, y=13.00, z=133.47], EntityZombie['Zombie'/1243, l='MpServer', x=-187.50, y=13.00, z=125.13], EntityZombie['Zombie'/1244, l='MpServer', x=-173.50, y=15.00, z=137.50], EntityCreeper['Creeper'/1245, l='MpServer', x=-168.31, y=15.00, z=130.75], EntityCreeper['Creeper'/1268, l='MpServer', x=-136.00, y=32.00, z=108.38], EntityItem['item.tile.gravel'/5381, l='MpServer', x=-227.13, y=30.00, z=196.00], EntityGhast['Ghast'/5482, l='MpServer', x=-178.48, y=79.57, z=135.09], EntityGhast['Ghast'/5488, l='MpServer', x=-212.68, y=77.94, z=96.27], EntityItem['item.item.string'/5494, l='MpServer', x=-243.78, y=56.00, z=161.03], EntityGhast['Ghast'/5498, l='MpServer', x=-213.80, y=95.96, z=129.21], EntityGhast['Ghast'/5502, l='MpServer', x=-196.47, y=89.33, z=132.31], EntityGhast['Ghast'/5509, l='MpServer', x=-185.52, y=82.08, z=138.37], EntityGhast['Ghast'/5541, l='MpServer', x=-194.29, y=74.91, z=141.26], EntityItem['item.item.seeds'/5579, l='MpServer', x=-149.78, y=65.00, z=150.06], EntityGhast['Ghast'/5581, l='MpServer', x=-211.38, y=65.84, z=147.17], EntityGhast['Ghast'/5585, l='MpServer', x=-193.15, y=81.35, z=162.52], EntityGhast['Ghast'/5588, l='MpServer', x=-204.14, y=72.52, z=140.28], EntityGhast['Ghast'/5596, l='MpServer', x=-187.06, y=94.20, z=127.88], EntityGhast['Ghast'/5604, l='MpServer', x=-193.10, y=73.69, z=128.03], EntityGhast['Ghast'/5614, l='MpServer', x=-199.39, y=67.21, z=133.25], EntityGhast['Ghast'/5624, l='MpServer', x=-207.47, y=77.59, z=127.90], EntityGhast['Ghast'/5637, l='MpServer', x=-198.40, y=71.41, z=134.10], EntityGhast['Ghast'/5640, l='MpServer', x=-197.84, y=78.44, z=136.05], EntityGhast['Ghast'/5643, l='MpServer', x=-191.83, y=77.24, z=132.70], EntityGhast['Ghast'/5652, l='MpServer', x=-199.59, y=71.09, z=119.01], EntityGhast['Ghast'/5667, l='MpServer', x=-181.97, y=67.10, z=135.63], EntityLargeFireball['Fireball'/5705, l='MpServer', x=-192.70, y=73.91, z=133.17], EntityLargeFireball['Fireball'/5706, l='MpServer', x=-194.57, y=68.82, z=136.24], EntityLargeFireball['Fireball'/5707, l='MpServer', x=-187.76, y=68.66, z=137.23], EntityLargeFireball['Fireball'/5726, l='MpServer', x=-207.88, y=68.38, z=145.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:351)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2502)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:367)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 218563720 bytes (208 MB) / 529694720 bytes (505 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1483 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1483.jar) 
	UCHIJAAAA	Forge{11.14.3.1483} [Minecraft Forge] (forge-1.8-11.14.3.1483.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.4.0' Renderer: 'GeForce GT 720/PCIe/SSE2'
	Launched Version: 1.8-Forge11.14.3.1483
	LWJGL: 2.9.1
	OpenGL: GeForce GT 720/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Delocuro** [comment]
Nevermind, updating forge fixed it even though a fix didn't appear to be listed in the changelogs. I'll re-open it if it starts happening again, since it hadnt been happening in previous versions.
