### ISSUE TITLE
Forge breaks many textures on Mac OSX 10.10.4

### ISSUE THREAD

**Issue by smesper** [MinecraftForge/MinecraftForge#2077]
Hi, 

I installed the latest version of your client side mod on 3 different Mac OSX Yosemite devices and on all 3 of them many of the textures in Minecraft are not working. 

I did a clean install of Minecraft with no other mods in the mod folder installed on all 3 devices and I still have the problem. I had Java 6 at first and then switched to Java 8 and both don't work on all 3 devices. 

Here is the profile on Minecraft:
![screen shot 2015-08-12 at 5 50 20 pm](https://cloud.githubusercontent.com/assets/1314285/9240401/be76d74c-411a-11e5-954b-b8272b3c0d6b.png)

I ran it in Singleplayer with Creative Mode and Cheats on and see this:
![screen shot 2015-08-12 at 5 52 24 pm](https://cloud.githubusercontent.com/assets/1314285/9240428/0ab83bfa-411b-11e5-9d9d-921ab5d2c74e.png)
And this:
![screen shot 2015-08-12 at 5 52 31 pm](https://cloud.githubusercontent.com/assets/1314285/9240433/17a891f2-411b-11e5-869b-eb6e52ae13fe.png)

Here are the logs in Game Output:
```
[17:51:35] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:51:35] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:51:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:51:35] [main/INFO] [FML]: Forge Mod Loader version 8.99.205.1502 for Minecraft 1.8 loading
[17:51:35] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.6.0_65, running on Mac OS X:x86_64:10.10.4, installed at /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
[17:51:35] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:51:35] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:51:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:51:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:51:35] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:51:36] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[17:51:36] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[17:51:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:51:36] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:51:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:51:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:51:37] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:51:38] [Client thread/INFO]: Setting user: sguthals
[17:51:40] [Client thread/INFO]: LWJGL Version: 2.9.2
[17:51:40] [Client thread/INFO] [FML]: Could not load splash.properties, will create a default one
[17:51:40] [Client thread/INFO] [STDOUT]: [net.minecraftforge.fml.client.SplashProgress:start:235]: ---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/12/15 5:51 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Mac OS X (x86_64) version 10.10.4
	Java Version: 1.6.0_65, Apple Inc.
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
	Memory: 90435896 bytes (86 MB) / 240369664 bytes (229 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.4.2 310.41.35f01' Renderer: 'NVIDIA GeForce GT 750M OpenGL Engine'
[17:51:40] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[17:51:40] [Client thread/INFO] [FML]: MinecraftForge v11.14.3.1502 Initialized
[17:51:40] [Client thread/INFO] [FML]: Replaced 204 ore recipies
[17:51:40] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[17:51:40] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[17:51:40] [Client thread/INFO] [FML]: Searching /Users/sarahguthals/Library/Application Support/minecraft/mods for mods
[17:51:41] [Client thread/INFO] [FML]: Forge Mod Loader has identified 3 mods to load
[17:51:41] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[17:51:41] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[17:51:42] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[17:51:42] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[17:51:42] [Client thread/INFO] [FML]: Found 384 ObjectHolder annotations
[17:51:42] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[17:51:42] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[17:51:42] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[17:51:42] [Client thread/INFO] [FML]: Applying holder lookups
[17:51:42] [Client thread/INFO] [FML]: Holder lookups applied
[17:51:42] [Client thread/INFO] [FML]: Injecting itemstacks
[17:51:42] [Client thread/INFO] [FML]: Itemstack injection complete
[17:51:42] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:51:42] [Thread-14/INFO]: Initializing LWJGL OpenAL
[17:51:42] [Thread-14/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:51:42] [Thread-14/INFO]: OpenAL initialized.
[17:51:43] [Sound Library Loader/INFO]: Sound engine started
[17:51:43] [Client thread/INFO] [FML]: Max texture size: 16384
[17:51:43] [Client thread/INFO]: Created: 16x16 textures-atlas
[17:51:44] [Client thread/INFO] [FML]: Injecting itemstacks
[17:51:44] [Client thread/INFO] [FML]: Itemstack injection complete
[17:51:44] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 3 mods
[17:51:44] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[17:51:44] [Client thread/INFO]: SoundSystem shutting down...
[17:51:45] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[17:51:45] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:51:45] [Thread-17/INFO]: Initializing LWJGL OpenAL
[17:51:45] [Thread-17/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:51:45] [Thread-17/INFO]: OpenAL initialized.
[17:51:45] [Client thread/INFO] [FML]: Max texture size: 16384
[17:51:45] [Sound Library Loader/INFO]: Sound engine started
[17:51:46] [Client thread/INFO]: Created: 512x512 textures-atlas
[17:52:11] [Server thread/INFO]: Starting integrated minecraft server version 1.8
[17:52:11] [Server thread/INFO]: Generating keypair
[17:52:11] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[17:52:11] [Server thread/INFO] [FML]: Applying holder lookups
[17:52:11] [Server thread/INFO] [FML]: Holder lookups applied
[17:52:11] [Server thread/INFO] [FML]: Loading dimension 0 (New World) (net.minecraft.server.integrated.IntegratedServer@744500b2)
[17:52:11] [Server thread/INFO] [FML]: Loading dimension 1 (New World) (net.minecraft.server.integrated.IntegratedServer@744500b2)
[17:52:11] [Server thread/INFO] [FML]: Loading dimension -1 (New World) (net.minecraft.server.integrated.IntegratedServer@744500b2)
[17:52:11] [Server thread/INFO]: Preparing start region for level 0
[17:52:12] [Server thread/INFO]: Changing view distance to 12, from 10
[17:52:13] [Netty Local Client IO #0/INFO] [FML]: Server protocol version 2
[17:52:13] [Netty Server IO #1/INFO] [FML]: Client protocol version 2
[17:52:13] [Netty Server IO #1/INFO] [FML]: Client attempting to join with 3 mods : mcp@9.05,FML@8.0.99.99,Forge@11.14.3.1502
[17:52:13] [Netty Local Client IO #0/INFO] [FML]: [Netty Local Client IO #0] Client side modded connection established
[17:52:13] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[17:52:13] [Server thread/INFO]: sguthals[local:E:6910068d] logged in with entity id 1471 at (146.5, 64.0, 246.5)
[17:52:13] [Server thread/INFO]: sguthals joined the game
[17:52:14] [pool-2-thread-1/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@3ccc420f[id=ac551fcd-c257-4e11-a8b0-32e0f4d6ced0,name=sguthals,properties={textures=[com.mojang.authlib.properties.Property@3d87f139]},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:175) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:59) [YggdrasilMinecraftSessionService$1.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:56) [YggdrasilMinecraftSessionService$1.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [guava-17.0.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:165) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.client.resources.SkinManager$3.run(SourceFile:105) [cvz.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439) [?:1.6.0_65]
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [?:1.6.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:138) [?:1.6.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895) [?:1.6.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918) [?:1.6.0_65]
	at java.lang.Thread.run(Thread.java:695) [?:1.6.0_65]
[17:52:25] [Server thread/INFO]: Saving and pausing game...
[17:52:25] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[17:52:25] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[17:52:25] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[17:52:33] [Server thread/INFO]: Saving and pausing game...
[17:52:33] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[17:52:33] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[17:52:33] [Server thread/INFO]: Saving chunks for level 'New World'/The End
```

**Comment by chibill** [comment]
Just so you know try disabling the splash screen. This is a common driver problem on Macs....

**Comment by smesper** [comment]
Got it. Thanks!
