### ISSUE TITLE
Closing Minecraft throwing an error

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#2122]
2558-09-28 20:04:52,373 ERROR Attempted to append to non-started appender ServerGuiConsole
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: org.apache.logging.log4j.core.appender.AppenderLoggingException: Attempted to append to non-started appender ServerGuiConsole
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1011)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.stopServer(Unknown Source)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.stopServer(Unknown Source)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.stopIntegratedServer(Unknown Source)
[20:04:52] [Client Shutdown Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main$2.run(Unknown Source)

I'm using Forge 1516 on Eclipse.

Step to reproduce
1. Entering any map.
2. Save or exit your game.
3. And you see an error

**Comment by SteveKunG** [comment]
Oh. Nevermind, it not happened.
