### ISSUE TITLE
[1.8.9] ItemStack.splitStack needs to preserve capability NBT like ItemStack.copy

### ISSUE THREAD

**Issue by asiekierka** [MinecraftForge/MinecraftForge#2388]
Otherwise, inserting into a slot via mouse click will reset ItemStack capability NBT data.

**Comment by asiekierka** [comment]
This log might come in handy as proof that splitStack is called during a slot click operation:

[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: java.lang.Throwable
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at pl.asie.charset.audio.tape.ItemTape.initCapabilities(ItemTape.java:89)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.item.ItemStack.setItem(ItemStack.java:1017)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.item.ItemStack.<init>(ItemStack.java:93)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.item.ItemStack.<init>(ItemStack.java:85)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.item.ItemStack.splitStack(ItemStack.java:123)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.inventory.Container.slotClick(Container.java:312)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.network.NetHandlerPlayServer.processClickWindow(NetHandlerPlayServer.java:1039)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.network.play.client.C0EPacketClickWindow.processPacket(C0EPacketClickWindow.java:46)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.network.play.client.C0EPacketClickWindow.processPacket(C0EPacketClickWindow.java:11)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.util.Util.runTask(Util.java:22)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:736)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:681)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:159)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:548)
[18:04:01] [Server thread/INFO]: [pl.asie.charset.audio.tape.ItemTape:initCapabilities:89]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by LexManos** [comment]
Pr, Pr You know better and Pr. There are probably quite a few edge cases where ItemStacks will have issues because of how mutable they are. Stop reporting them one by one and actually put some effort in to finding and fixing them.

**Comment by asiekierka** [comment]
I would if I could get the Forge development environment to work on IDEA,
or if I had time to spend getting Eclipse to work on my Linux setup. I'm
probably going to ask amadornes or cpw how they got it to work later.

2016-01-18 20:50 GMT+01:00 LexManos <notifications@github.com>:

**Comment by asiekierka** [comment]
Also, closing a bug means nobody else will PR, either. Keeping it open means people know.

**Comment by amadornes** [comment]
@asiekierka I cloned it, ran 'gradlew setupForge' and opened the '.ipr' file in the 'projects' folder. It's not that hard ;)

**Comment by asiekierka** [comment]
That gives me a broken setup. That is, net.minecraftforge is not present in
the Forge project.
 I've been trying to fix it since Sunday.

2016-01-19 14:56 GMT+01:00 amadornes <notifications@github.com>:

**Comment by LexManos** [comment]
At thsi time idea is hit and miss due to idea not liking seperate content roots and not supporting mutliple in the gradle plugin. {Theirs not ours}
There are some ways to fix it manually by editing the iml file that is created to manually specify the two content roots. But for now until Abrar can fix it or gradle fixes it our only OFFICIAL support is eclipse. 
Its a simple fix manually kinda complicated pragmatically after the fact.

**Comment by AEnterprise** [comment]
@asiekierka if eclipse doesn't work you can use a text editor instead for simple things, it won't give any error checking or code completion but gradle has tasks to run MC so you could use that route although it is very far from ideal
