### ISSUE TITLE
CrashReportCategory$4 missing?

### ISSUE THREAD

**Issue by sfPlayer1** [MinecraftForge/MinecraftForge#2421]
This happens on the ForgeCraft 1 server frequently, the crash reporter crash hides the real issue.

CrashReportCategory$4 is not even mentioned in the srg file.

```
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:696) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/crash/CrashReportCategory$4
        at net.minecraft.crash.CrashReportCategory.func_175750_a(CrashReportCategory.java:242) ~[c.class:?]
        at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:616) ~[le.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:219) ~[le.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690) ~[MinecraftServer.class:?]
        ... 4 more
```

**Comment by AEnterprise** [comment]
does the server heapens to have mine and blade installed? that does stuff to the crash reporter that can make the crashreporter crash while generating the crashreport, removing that could allow the real crash to be logged to the crashreport

**Comment by LexManos** [comment]
Post the full log we have it spit out all the classes we pre-load for CrashReports IIRC.

**Comment by sfPlayer1** [comment]
Unfortunately I don't have the log anymore. Presumably Thaumcraft causes the exception initially, but I have no idea on how to reproduce it and currently I can't even enter its dimension as TC crashes elsewhere...

Regarding preloading:

- It doesn't log anymore (commented out)
- Exceptions including ClassNotFound get silently ignored, even if the logging was still in
- CrashReportCategory$4 and others aren't included in the preload list

**Comment by AEnterprise** [comment]
yeah a full log is needed in this case as some mod is messing with the crashreporter in such a way that it crahses itself

**Comment by diesieben07** [comment]
Lex, you mentioned in https://github.com/MinecraftForge/MinecraftForge/pull/2127 that there was going to be a marker class in 1.8.8. Did anything ever come from that? (Also, I still argue that that PR is not useless, but... oh well).

**Comment by LexManos** [comment]
No that didnt make it into the 1.8.9 branch, presumably as it was pushed to their master branch and not the 1.8 branch.
For now, gather up a list of Vanilla classes that are used in Crash Reports and we can update the hack.
