### ISSUE TITLE
[1.9] Building from sources

### ISSUE THREAD

**Issue by FRedEnergy** [MinecraftForge/MinecraftForge#2541]
Tried to build 1.9 branch from sources and after successfull compilation I got all needed jars (univesal, userdev and installer). But there is an error while trying to actually run game
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.9-12.16.0.1-1.9-universal.jar:?]
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.9-12.16.0.1-1.9-universal.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.state.BlockStateContainer$StateImplementation.<init>(Lnet/minecraft/block/Block;Lcom/google/common/collect/ImmutableMap;Lnet/minecraft/block/state/BlockStateContainer$1;)V
        at net.minecraft.block.state.BlockStateContainer.<init>(SourceFile:74) ~[ard.class:?]
        at net.minecraft.block.Block.func_180661_e(Block.java:834) ~[ajt.class:?]
        at net.minecraft.block.Block.<init>(Block.java:208) ~[ajt.class:?]
        at net.minecraft.block.Block.<init>(Block.java:217) ~[ajt.class:?]
        at net.minecraft.block.BlockAir.<init>(SourceFile:14) ~[ajj.class:?]
        at net.minecraft.block.Block.func_149671_p(Block.java:2030) ~[ajt.class:?]
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:535) ~[kn.class:?]
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1401) ~[MinecraftServer.class:?]
        ... 12 more
```
Tasks used to build it: `setupForge genPatches build`

And yeah I fully understand that unreleased version do not meant to be used by anyone but I am only trying to launch it.

**Comment by heldplayer** [comment]
> And yeah I fully understand that unreleased version do not meant to be used by anyone but ...

This is the exact reason you shouldn't be using it. They're still working on getting it functional.

Once it actually works, builds will start appearing. For now, just be patient.

**Comment by cpw** [comment]
Well done, your issue just wasted our time. Thanks!
