### ISSUE TITLE
[1.9] Failed to start

### ISSUE THREAD

**Issue by Cat7373** [MinecraftForge/MinecraftForge#2566]
Description: Initializing game
    
    java.lang.NoClassDefFoundError: gnu/trove/map/hash/TByteObjectHashMap
    	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.<init>(FMLIndexedMessageToMessageCodec.java:23)
    	at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.<init>(FMLRuntimeCodec.java:15)
    	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:164)
    	at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:82)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
    	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
    	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    	at net.minecraft.client.main.Main.main(SourceFile:124)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    Caused by: java.lang.ClassNotFoundException: gnu.trove.map.hash.TByteObjectHashMap
    	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    	at java.lang.ClassLoader.loadClass(Unknown Source)
    	at java.lang.ClassLoader.loadClass(Unknown Source)
    	... 36 more
    Caused by: java.lang.NullPointerException
    	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    	... 38 more
    
    
    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------
    
    -- Head --
    Stacktrace:
    	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.<init>(FMLIndexedMessageToMessageCodec.java:23)
    	at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.<init>(FMLRuntimeCodec.java:15)
    	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:164)
    	at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:82)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
    	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:210)
    	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
    
    -- Initialization --
    Details:
    Stacktrace:
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    	at net.minecraft.client.main.Main.main(SourceFile:124)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    	at java.lang.reflect.Method.invoke(Unknown Source)
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    
    -- System Details --
    Details:
    	Minecraft Version: 1.9
    	Operating System: Windows 10 (amd64) version 10.0
    	Java Version: 1.8.0_74, Oracle Corporation
    	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    	Memory: 100661232 bytes (95 MB) / 264241152 bytes (252 MB) up to 2147483648 bytes (2048 MB)
    	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
    	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    	FML: MCP 9.23 Powered by Forge 12.16.0.1766 3 mods loaded, 3 mods active
    	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    	U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1766-1.9.jar) 
    	U	Forge{12.16.0.1766} [Minecraft Forge] (forge-1.9-12.16.0.1766-1.9.jar)

**Comment by liach** [comment]
Why does forge use trove4j? Isn't it removed in minecraft 1.8.8 already?

**Comment by diesieben07** [comment]
No, trove still exists and is used even by vanilla itself in 1.9 as well.

**Comment by matthewprenger** [comment]
Actually Mojang stopped using trove in vanilla, but forge does indeed re-add it.

**Comment by liach** [comment]
Wait why there's a `java.lang.NullPointerException` at the bottom?

**Comment by Cat7373** [comment]
@liach no

**Comment by Cat7373** [comment]
1.9 - 12.16.0.1776 problem remains

**Comment by Cat7373** [comment]
1.9 - 12.16.0.1809 problem remains

**Comment by Cat7373** [comment]
Time: 16-3-25 下午1:15
    Description: Initializing game

    java.lang.NoClassDefFoundError: gnu/trove/map/hash/TByteObjectHashMap
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.<init>(FMLIndexedMessageToMessageCodec.java:23)
        at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.<init>(FMLRuntimeCodec.java:15)
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:164)
        at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:221)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:128)
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:205)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:112)
    Caused by: java.lang.ClassNotFoundException: gnu.trove.map.hash.TByteObjectHashMap
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 41 more
    Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
        ... 43 more


    A detailed walkthrough of the error, its code path and all known details is as follows:
    ---------------------------------------------------------------------------------------

    -- Head --
    Stacktrace:
        at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.<init>(FMLIndexedMessageToMessageCodec.java:23)
        at net.minecraftforge.fml.common.network.internal.FMLRuntimeCodec.<init>(FMLRuntimeCodec.java:15)
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.registerChannel(FMLNetworkHandler.java:164)
        at net.minecraftforge.fml.common.FMLContainer.modConstruction(FMLContainer.java:81)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:221)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:128)
        at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:512)
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:205)
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:434)

    -- Initialization --
    Details:
    Stacktrace:
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:112)

    -- System Details --
    Details:
        Minecraft Version: 1.9
        Operating System: Windows 10 (amd64) version 10.0
        Java Version: 1.8.0_74, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 103806960 bytes (98 MB) / 265289728 bytes (253 MB) up to 2147483648 bytes (2048 MB)
        JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP 9.23 Powered by Forge 12.16.0.1809 3 mods loaded, 3 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
        U	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.0.1809-1.9.jar) 
        U	Forge{12.16.0.1809} [Minecraft Forge] (forge-1.9-12.16.0.1809-1.9.jar)

**Comment by Cat7373** [comment]
@RainWarrior @LexManos

**Comment by matthewprenger** [comment]
> at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:112)

Try using the Mojang launcher.

**Comment by RedL0tus** [comment]
He (She) uses the "Hello Minecraft! Launcher" ([HMCL](https://github.com/huanghongxun/HMCL), because he (she) doesn't bought a Minecraft. 

I've tried with 12.16.0.1809 & the Mojong Launcher, it works. ([Screenshot](http://img.vim-cn.com/eb/bb0fa91123e81b7a446557dd269c6e5242251f.png))

PS. He (She) sent a issue to the HMCL just 30 minutes ago.
PPS. I think this issue can be closed. It's the HMCL's fault. XD

**Comment by Cat7373** [comment]
I'm still not sure if launcher problem, I just tried BMCL also failed to start

**Comment by Cat7373** [comment]
I have a friend use HMCL launched successfully.
I think the problem is not a launched.

**Comment by RedL0tus** [comment]
@Cat7373 
I've also tried HMCL to launch the game and it works.
So it may be your fault. XD

**Comment by liach** [comment]
then its hellominecraft bug, close this please.

**Comment by LexManos** [comment]
We do not support cracked launchers buy the damn game.
