### ISSUE TITLE
[1.9] Array out of bound exception from ItemAxe class

### ISSUE THREAD

**Issue by aod6060** [MinecraftForge/MinecraftForge#2637]
For some reason I'm getting an "array out of bounds exception" from the ItemAxe class. Here is the stack trace for the error.
java.lang.ArrayIndexOutOfBoundsException: 5
	at net.minecraft.item.ItemAxe.<init>(SourceFile:32) ~[forgeBin-1.9-12.16.0.1801-1.9.jar:?]
	at com.derf.ei.items.EIItemAxe.<init>(EIItemAxe.java:8) ~[bin/:?]
	at com.derf.ei.items.EIItems.create(EIItems.java:134) ~[bin/:?]
	at com.derf.ei.EICommonProxy.preInit(EICommonProxy.java:19) ~[bin/:?]
	at com.derf.ei.EIClientProxy.preInit(EIClientProxy.java:15) ~[bin/:?]
	at com.derf.ei.EILoader.preInit(EILoader.java:25) ~[bin/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forgeBin-1.9-12.16.0.1801-1.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:221) ~[forgeBin-1.9-12.16.0.1801-1.9.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:199) ~[forgeBin-1.9-12.16.0.1801-1.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:128) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:241) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:434) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:346) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
If you need me to post were it relevant in my code I don't mind posting it.

**Comment by williewillus** [comment]
Mod problems go on forums or IRC, unless you can show this is related to the vanilla/forge code

**Comment by aod6060** [comment]
I see. Well when I run the minecraft client all of the tools are working (sword, spade, pickaxe, how). However, when I uncomment the code to load my custom axe it gives me an array out of bound exception in the ItemAxe class at line 32.

**Comment by aod6060** [comment]
Oh yeah one more thing here is my custom axe class.
package com.derf.ei.items;

```
import net.minecraft.item.ItemAxe;
public class EIItemAxe extends ItemAxe {

	protected EIItemAxe(String name, ToolMaterial material) {
		super(material);
		// TODO Auto-generated constructor stub
		this.setUnlocalizedName(name);
	}

}
```
How did I get an "Array out of Bounds" exception, when I not doing anything with arrays? To be honest I have no clue how I'm getting such an error from a minuscule temporary class.

**Comment by 61352151511** [comment]
ItemAxe has an array and part of its code uses .ordinal() this is what causes the error. You can't extend ItemAxe anymore that I know of
