### ISSUE TITLE
Use of GameRegistry.ObjectHolder causes Items to not register properly

### ISSUE THREAD

**Issue by pahimar** [MinecraftForge/MinecraftForge#2640]
When using GameRegistry.ObjectHolder in my ModItems class items do not get registered to my mod properly. When the annotation is present, Item.setRegistryName returns null for the active mod container, and as such the item is registered under the "minecraft" domain. When the annotation is removed items are correctly registered

Forge: 12.16.0.1802 (also tested with 1776 and 1800)

Relevant Files: 
-ModItems
-- https://github.com/pahimar/Equivalent-Exchange-3/blob/17d86f9fd7635367318b589117557b20a33d0a6d/src/main/java/com/pahimar/ee3/init/ModItems.java#L10
-Base Item Class (contains the call to register the item)
-- https://github.com/pahimar/Equivalent-Exchange-3/blob/17d86f9fd7635367318b589117557b20a33d0a6d/src/main/java/com/pahimar/ee3/item/base/ItemEE.java

Relevant log excerpts for when annotation is used
`[10:30:16] [Client thread/WARN]: ****************************************
[10:30:16] [Client thread/WARN]: * Dangerous alternative prefix ee3 for name philosophers_stone, invalid registry invocation/invalid name?
[10:30:16] [Client thread/WARN]: *  at net.minecraftforge.fml.common.registry.GameData.addPrefix(GameData.java:166)
[10:30:16] [Client thread/WARN]: *  at net.minecraftforge.fml.common.registry.GameData.registerItem(GameData.java:127)
[10:30:16] [Client thread/WARN]: *  at net.minecraftforge.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:153)
[10:30:16] [Client thread/WARN]: *  at net.minecraftforge.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:138)
[10:30:16] [Client thread/WARN]: *  at com.pahimar.ee3.init.ModItems.register(ModItems.java:16)
[10:30:16] [Client thread/WARN]: *  at com.pahimar.ee3.proxy.CommonProxy.preInit(CommonProxy.java:22)...
[10:30:16] [Client thread/WARN]: ****************************************`

`[10:30:24] [Client thread/ERROR]: Exception loading model for variant minecraft:philosophers_stone#normal for item "minecraft:philosophers_stone"
java.lang.Exception: Could not load item model either from the normal location minecraft:item/philosophers_stone or from the blockstate
	at net.minecraftforge.client.model.ModelLoader.loadItemModels(ModelLoader.java:309) ~[ModelLoader.class:?]`

**Comment by PrinceOfAmber** [comment]
I have the same issue with 12.16.0.1826

If i use the deprecated GameRegistry.registerBlock(block,ItemBlock.class,name); , it works fine.

But if i use the 'new' method


		block.setRegistryName(Const.MODRES , name);
		GameRegistry.register(block);

Then it says


[16:59:41] [Client thread/WARN] [FML]: * Dangerous alternative prefix cyclicmagic: for name block_fragile, invalid registry invocation/invalid name?
[16:59:41] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:63)
[16:59:41] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.IForgeRegistryEntry$Impl.setRegistryName(IForgeRegistryEntry.java:72)
[16:59:41] [Client thread/WARN] [FML]: *  at com.lothrazar.cyclicmagic.registry.BlockRegistry.registerBlock(BlockRegistry.java:24)
[16:59:41] [Client thread/WARN] [FML]: *  at com.lothrazar.cyclicmagic.registry.BlockRegistry.register(BlockRegistry.java:40)
[16:59:41] [Client thread/WARN] [FML]: *  at com.lothrazar.cyclicmagic.ModMain.onInit(ModMain.java:70)
[16:59:41] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...

**Comment by TehNut** [comment]
Don't set the domain. Just `block.setRegistryName(name)`

**Comment by pahimar** [comment]
@TehNut's comment should be removed as it's referencing a comment from another person who deleted their comment

**Comment by TehNut** [comment]
Done. Didn't notice it was deleted.

**Comment by Actuarius** [comment]
@williewillus added labels [Bug]
