### ISSUE TITLE
InvocationTargetException for Forge 1820 for 1.9

### ISSUE THREAD

**Issue by krimin-killr21** [MinecraftForge/MinecraftForge#2683]
I and another dev both had identical errors at startup in the dev environment. Did not occur as late as 1816. Here's the trace:

2016-04-02 00:47:06,664 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-04-02 00:47:06,665 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[00:47:06] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:47:06] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[00:47:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[00:47:06] [main/INFO] [FML]: Forge Mod Loader version 12.16.0.1820 for Minecraft 1.9 loading
[00:47:06] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[00:47:06] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:47:06] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:47:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:47:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:47:06] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:47:07] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[00:47:07] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[00:47:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:47:07] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[00:47:08] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:47:08] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[00:47:08] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
2016-04-02 00:47:08,418 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-04-02 00:47:08,428 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-04-02 00:47:08,430 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[00:47:08] [main/INFO] [STDOUT]: [net.minecraft.client.main.Main:main:56]: Completely ignored arguments: [--nativeLauncherVersion, 301]
[00:47:08] [Client thread/INFO]: Setting user: uxsvent
[00:47:08] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
   at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
   at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
   at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[nf.class:?]
   at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:501) ~[kn.class:?]
   at net.minecraft.client.Minecraft.<init>(Minecraft.java:337) ~[bcf.class:?]
   at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
   ... 6 more
Caused by: java.lang.NegativeArraySizeException: nbits < 0: -2147483648
   at java.util.BitSet.<init>(BitSet.java:159) ~[?:1.8.0_25]
   at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.<init>(FMLControlledNamespacedRegistry.java:77) ~[FMLControlledNamespacedRegistry.class:?]
   at net.minecraftforge.fml.common.registry.PersistentRegistryManager$PersistentRegistry.createRegistry(PersistentRegistryManager.java:85) ~[PersistentRegistryManager$PersistentRegistry.class:?]
   at net.minecraftforge.fml.common.registry.PersistentRegistryManager$PersistentRegistry.access$000(PersistentRegistryManager.java:45) ~[PersistentRegistryManager$PersistentRegistry.class:?]
   at net.minecraftforge.fml.common.registry.PersistentRegistryManager.createRegistry(PersistentRegistryManager.java:139) ~[PersistentRegistryManager.class:?]
   at net.minecraftforge.fml.common.registry.GameData.<init>(GameData.java:64) ~[GameData.class:?]
   at net.minecraftforge.fml.common.registry.GameData.<clinit>(GameData.java:56) ~[GameData.class:?]
   at net.minecraft.util.SoundEvent.<clinit>(SoundEvent.java:9) ~[nf.class:?]
   at net.minecraft.init.Bootstrap.func_151354_b(SourceFile:501) ~[kn.class:?]
   at net.minecraft.client.Minecraft.<init>(Minecraft.java:337) ~[bcf.class:?]
   at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
   ... 6 more
Exception in thread "Client thread" [00:47:08] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[00:47:08] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
[00:47:08] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[00:47:08] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.Runtime.exit(Runtime.java:107)
[00:47:08] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at java.lang.System.exit(System.java:968)
[00:47:08] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[00:47:08] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jacky8399** [comment]
I have the same problem too. I think it's because they used the max int for max_sound_id
`private static final int MAX_SOUND_ID = Integer.MAX_VALUE; // Varint (SPacketSoundEffect)`
And then used it as a parameter
`iSoundEventRegistry = PersistentRegistryManager.createRegistry(PersistentRegistryManager.SOUNDEVENTS, SoundEvent.class, null, MIN_SOUND_ID, MAX_SOUND_ID, false, null, null, null);`
which the method used to create a BitSet
`this.availabilityMap = new BitSet(maxIdValue + 1);`
thus causing this problem
Caused by: java.lang.NegativeArraySizeException: nbits < 0: -2147483648

**Comment by cpw** [comment]
Interesting... Doesn't happen for me...
