### ISSUE TITLE
Crash when using forge version 10.13.4.1614

### ISSUE THREAD

**Issue by sokratis12GR** [MinecraftForge/MinecraftForge#2698]
About the Error:
When I try to launch this version of the forge the game just don't open and just shows the error bellow, I have used an older version and worked fine
Forge's Version Causing the Error: 
10.13.4.1614
Minecraft Version:
1.7.10
Crash Report:
[22:16:03] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[22:16:03] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: cpw.mods.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.forName(Class.java:344) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
How to Reproduse:
Download the 10.13.4.1614 version of forge. Install it, then run it once without any mods installed. and this is what happens

**Comment by williewillus** [comment]
1. what launcher and how are you installing it?
2. 1.7 isn't supported and this should go on forums either way

**Comment by canitzp** [comment]
You installed a Mod for 1.8 or 1.9 Version of MC

**Comment by sokratis12GR** [comment]
normal installing. I install it through the Installer.
I have not installed any mods

**Comment by canitzp** [comment]
Delete the libraries folder in you .minecraft folder and download/install MC and Forge again

**Comment by williewillus** [comment]
Go on the forums for this

**Comment by Actuarius** [comment]
@williewillus closed this issue
