### ISSUE TITLE
[1.9] IllegalAccessError when using InitMapGenEvent (works for mc 1.8.9 but not in mc 1.9)

### ISSUE THREAD

**Issue by JennyLeeP** [MinecraftForge/MinecraftForge#2781]
I am getting this error while trying to initialize my caveGen. This is  mc 1.9 using forge version "1.9-12.16.0.1865-1.9"
It is entirely possible I need to handle the event differently in this version of forge.

************************
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraftforge.event.terraingen.InitMapGenEvent.type from class com.cyborgJenn.cyborgUtils.CyborgUtils
	at com.cyborgJenn.cyborgUtils.CyborgUtils.generatorControl(CyborgUtils.java:155)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_CyborgUtils_generatorControl_InitMapGenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.terraingen.TerrainGen.getModdedMapGen(TerrainGen.java:28)
	at net.minecraft.world.gen.ChunkProviderOverworld.<init>(ChunkProviderOverworld.java:63)
	at net.minecraft.world.WorldType.getChunkGenerator(WorldType.java:178)
	at net.minecraft.world.WorldProvider.createChunkGenerator(WorldProvider.java:75)
	at net.minecraft.world.WorldServer.createChunkProvider(WorldServer.java:883)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:117)
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:85)
	at net.minecraft.server.integrated.IntegratedServer.startServer(IntegratedServer.java:123)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:492)
	at java.lang.Thread.run(Unknown Source)
************************
line 155 = switch(event.type){
below is the code I am using.

```java
@SubscribeEvent(priority = EventPriority.NORMAL)
	public void getWorldEvent(WorldEvent event){
		dimension = event.world.provider.getDimensionId();
	}

	/*
	 * Gets the MinecraftForge MapGen event type
	 */
	@SubscribeEvent(priority = EventPriority.NORMAL)
	public void generatorControl(InitMapGenEvent event)
	{
		if (dimension == 0){
			switch(event.type){

			case CAVE:
				event.newGen = caveGen;
				logger.info("Cave Gen Event Fired");
				break;
			case CUSTOM:
				break;
			case MINESHAFT:
				break;
			case NETHER_BRIDGE:
				break;
			case NETHER_CAVE:
				break;
			case RAVINE:// TODO larger Ravines
				break;
			case SCATTERED_FEATURE:
				break;
			case STRONGHOLD:
				break;
			case VILLAGE:
				break;
			case OCEAN_MONUMENT:
				break;
			default:
				break;
			}
		}
	}
```

**Comment by shadowfacts** [comment]
On 1.9 `InitMapGenEvent#type` is [private](https://github.com/MinecraftForge/MinecraftForge/blob/1.9/src/main/java/net/minecraftforge/event/terraingen/InitMapGenEvent.java#L12). Use the `getType` method instead.

**Comment by liach** [comment]
Update forge in your dev env.

**Comment by JennyLeeP** [comment]
Clearly it acts as if it private and your linked source for 1.9 shows that and shows the getType() method.

Interesting that eclipse is showing me this.
weird indeed. Thanks for the Help.
forgeSrc-1.9-12.16.0.1865-1.9.jar
```java
public class InitMapGenEvent extends Event
{
    /** Use CUSTOM to filter custom event types
     */
    public static enum EventType { CAVE, MINESHAFT, NETHER_BRIDGE, NETHER_CAVE, RAVINE, SCATTERED_FEATURE, STRONGHOLD, VILLAGE, OCEAN_MONUMENT, CUSTOM }

    public final EventType type;
    public final MapGenBase originalGen;
    public MapGenBase newGen;

    InitMapGenEvent(EventType type, MapGenBase original)
    {
        this.type = type;
        this.originalGen = original;
        this.newGen = original;
    }
}
```

**Comment by shadowfacts** [comment]
You need to update Forge in your `build.gradle` file and re-run `gradlew setupDecompWorkspace` and `gradlew eclipse`.

**Comment by JennyLeeP** [comment]
already did that, I will reload my 1.9 env from scratch and see if that fixes it.
Thanks

**Comment by JennyLeeP** [comment]
I am going with eclipse , possibly operator error(not going to admit that one so I feel better about myself), lol.

Anyways Thanks - Closing this issue.
