### ISSUE TITLE
[1.8.9/1.9] Window messed up in development environment

### ISSUE THREAD

**Issue by JBYoshi** [MinecraftForge/MinecraftForge#2782]
1. When the window first comes up, it's at the minimum possible size:
![mcbug-1](https://cloud.githubusercontent.com/assets/12983479/14799400/e6166b9e-0b01-11e6-8c59-8e85d77cee02.png)
2. Once enlarged, the main menu only shows the panorama background:
![mcbug-2](https://cloud.githubusercontent.com/assets/12983479/14799411/f462f122-0b01-11e6-924c-af7caa53bc9e.png)

Log from 1.9 (before I hit "close", it seems to include most relevant system information):
```
[16:08:48] [main/INFO]: Extra: []
[16:08:48] [main/INFO]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/Jonathan/.gradle/caches/minecraft/assets, --assetIndex, 1.9, --accessToken{REDACTED}, --version, 1.9, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[16:08:48] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:08:48] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:08:48] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[16:08:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:08:48] [main/INFO]: Forge Mod Loader version 12.16.0.1865 for Minecraft 1.9 loading
[16:08:48] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_77, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jdk8\jre
[16:08:48] [main/INFO]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[16:08:48] [main/INFO]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[16:08:48] [main/INFO]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[16:08:48] [main/INFO]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[16:08:48] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:08:48] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:08:48] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[16:08:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:08:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:08:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:08:49] [main/ERROR]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[16:08:51] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[16:08:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:08:51] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:08:52] [main/INFO]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[16:08:52] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:08:52] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:08:52] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:08:56] [Client thread/INFO]: Setting user: Player845
[16:09:01] [Client thread/INFO]: LWJGL Version: 2.9.1
[16:09:02] [Client thread/INFO]: [net.minecraftforge.fml.client.SplashProgress:start:200]: ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/25/16 4:09 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 169155912 bytes (161 MB) / 475529216 bytes (453 MB) up to 1404043264 bytes (1339 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3345' Renderer: 'Intel(R) HD Graphics 4000'
[16:09:02] [Client thread/INFO]: MinecraftForge v12.16.0.1865 Initialized
[16:09:02] [Client thread/INFO]: Replaced 207 ore recipes
[16:09:03] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[16:09:03] [Client thread/INFO]: Searching C:\Users\Jonathan\Documents\Java\FpsFix\run\mods for mods
[16:09:06] [Client thread/INFO]: Forge Mod Loader has identified 3 mods to load
[16:09:06] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[16:09:06] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[16:09:07] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[16:09:07] [Client thread/INFO]: Processing ObjectHolder annotations
[16:09:07] [Client thread/INFO]: Found 418 ObjectHolder annotations
[16:09:07] [Client thread/INFO]: Identifying ItemStackHolder annotations
[16:09:07] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[16:09:07] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[16:09:07] [Client thread/INFO]: Applying holder lookups
[16:09:07] [Forge Version Check/INFO]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[16:09:07] [Client thread/INFO]: Holder lookups applied
[16:09:07] [Client thread/INFO]: Injecting itemstacks
[16:09:07] [Client thread/INFO]: Itemstack injection complete
[16:09:07] [Forge Version Check/INFO]: [Forge] Found status: BETA Target: null
[16:09:10] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:09:10] [Thread-8/INFO]: Initializing LWJGL OpenAL
[16:09:10] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:09:10] [Thread-8/INFO]: OpenAL initialized.
[16:09:10] [Sound Library Loader/INFO]: Sound engine started
[16:09:16] [Client thread/INFO]: Max texture size: 8192
[16:09:16] [Client thread/INFO]: Created: 16x16 textures-atlas
[16:09:19] [Client thread/INFO]: Injecting itemstacks
[16:09:19] [Client thread/INFO]: Itemstack injection complete
[16:09:19] [Client thread/INFO]: Forge Mod Loader has successfully loaded 3 mods
[16:09:19] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[16:09:22] [Client thread/INFO]: SoundSystem shutting down...
[16:09:22] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[16:09:22] [Sound Library Loader/INFO]: Starting up SoundSystem...
[16:09:22] [Thread-10/INFO]: Initializing LWJGL OpenAL
[16:09:22] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[16:09:22] [Thread-10/INFO]: OpenAL initialized.
[16:09:23] [Sound Library Loader/INFO]: Sound engine started
[16:09:27] [Client thread/INFO]: Max texture size: 8192
[16:09:28] [Client thread/INFO]: Created: 1024x512 textures-atlas
[16:09:31] [Client thread/INFO]: Stopping!
[16:09:31] [Client thread/INFO]: SoundSystem shutting down...
[16:09:31] [Realms Notification Availability checker #1/INFO]: Could not authorize you against Realms server: Invalid session id
[16:09:31] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
```

From 1.8.9:
```
[17:28:56] [main/INFO]: Extra: []
[17:28:56] [main/INFO]: Running with arguments: [--userProperties, {}, --assetsDir, C:/Users/Jonathan/.gradle/caches/minecraft/assets, --assetIndex, 1.8, --accessToken{REDACTED}, --version, 1.8.9, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[17:28:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:28:56] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[17:28:56] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[17:28:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[17:28:56] [main/INFO]: Forge Mod Loader version 11.15.1.1855 for Minecraft 1.8.9 loading
[17:28:56] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_77, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jdk8\jre
[17:28:56] [main/INFO]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[17:28:56] [main/INFO]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[17:28:56] [main/INFO]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[17:28:56] [main/INFO]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[17:28:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:28:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:28:56] [main/INFO]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[17:28:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:28:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:28:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:28:57] [main/ERROR]: The binary patch set is missing. Either you are in a development environment, or things are not going to work!
[17:28:59] [main/ERROR]: FML appears to be missing any signature data. This is not a good thing
[17:28:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[17:28:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[17:29:00] [main/INFO]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[17:29:00] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:29:00] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[17:29:00] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[17:29:03] [Client thread/INFO]: Setting user: Player683
[17:29:09] [Client thread/INFO]: LWJGL Version: 2.9.1
[17:29:13] [Client thread/WARN]: =============================================================
[17:29:13] [Client thread/WARN]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[17:29:13] [Client thread/WARN]: Offendor: com/sun/jna/Native.main([Ljava/lang/String;)V
[17:29:13] [Client thread/WARN]: Use FMLCommonHandler.exitJava instead
[17:29:13] [Client thread/WARN]: =============================================================
[17:29:15] [Client thread/INFO]: [net.minecraftforge.fml.client.SplashProgress:start:246]: ---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 4/25/16 5:29 PM
Description: Loading screen debug info

This is just a prompt for computer specs to be printed. THIS IS NOT A ERROR


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 156426976 bytes (149 MB) / 411041792 bytes (392 MB) up to 1404043264 bytes (1339 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.3345' Renderer: 'Intel(R) HD Graphics 4000'
[17:29:15] [Client thread/INFO]: MinecraftForge v11.15.1.1855 Initialized
[17:29:15] [Client thread/INFO]: Replaced 229 ore recipies
[17:29:17] [Client thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[17:29:17] [Client thread/INFO]: Searching C:\Users\Jonathan\Documents\Java\FpsFix\run\mods for mods
[17:29:23] [Client thread/INFO]: Forge Mod Loader has identified 3 mods to load
[17:29:24] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at CLIENT
[17:29:24] [Client thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge] at SERVER
[17:29:24] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge
[17:29:24] [Client thread/INFO]: Processing ObjectHolder annotations
[17:29:25] [Client thread/INFO]: Found 384 ObjectHolder annotations
[17:29:25] [Client thread/INFO]: Identifying ItemStackHolder annotations
[17:29:25] [Client thread/INFO]: Found 0 ItemStackHolder annotations
[17:29:25] [Client thread/INFO]: Configured a dormant chunk cache size of 0
[17:29:25] [Client thread/INFO]: Applying holder lookups
[17:29:25] [Forge Version Check/INFO]: [Forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[17:29:25] [Client thread/INFO]: Holder lookups applied
[17:29:25] [Client thread/INFO]: Injecting itemstacks
[17:29:25] [Client thread/INFO]: Itemstack injection complete
[17:29:25] [Forge Version Check/INFO]: [Forge] Found status: AHEAD Target: null
[17:29:25] [Sound Library Loader/INFO]: Starting up SoundSystem...
[17:29:25] [Thread-9/INFO]: Initializing LWJGL OpenAL
[17:29:25] [Thread-9/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[17:29:26] [Thread-9/INFO]: OpenAL initialized.
[17:29:26] [Sound Library Loader/INFO]: Sound engine started
[17:29:34] [Client thread/INFO]: Max texture size: 8192
[17:29:34] [Client thread/INFO]: Created: 16x16 textures-atlas
(I just hit "terminate" at this point.)
```
Although I am working on a core mod, I've disabled the bytecode modifications to debug this. Fresh decompile of build 1865.

**Comment by williewillus** [comment]
If something shows up weird you should probably include a screenshot

**Comment by JBYoshi** [comment]
Whoops, completely forgot. Updated the description.

**Comment by JBYoshi** [comment]
After clicking where the "single player" button would be, another error pops up:
```
Exception in thread "Thread-11" java.lang.NullPointerException
    at paulscode.sound.codecs.CodecJOrbis.readBytes(CodecJOrbis.java:584)
    at paulscode.sound.codecs.CodecJOrbis.read(CodecJOrbis.java:354)
    at paulscode.sound.Source.stream(Source.java:953)
    at paulscode.sound.StreamThread.run(StreamThread.java:129)
```

**Comment by simon816** [comment]
Could be an incomplete workspace environment maybe?
What about `gradlew clean cleanEclipse setupDecompWorkspace eclipse` (s/eclipse/idea/ for Intellij)

**Comment by JBYoshi** [comment]
@simon816 Unfortunately, that didn't work. It also happens when I do `gradlew runClient`, so it's probably not related to my IDE.

**Comment by JBYoshi** [comment]
Just tried copying the native libraries from 1.8.9 (which works) into the 1.9 native directory. Didn't change anything, so it's not a problem with the native libraries.

**Comment by JBYoshi** [comment]
Tried something else that most people would call "crazy" - replacing the 1.9 Forge JAR file with a 1.8 version. It started up, but it didn't fix the problem; it must not be the JAR itself.

**Comment by diesieben07** [comment]
Read the EAQ on the forums.

**Comment by JBYoshi** [comment]
@diesieben07 I took a look at it. `forge.forceNoStencil` doesn't change anything.

**Comment by JBYoshi** [comment]
Well, it's worse than I thought. Even a Forge 1.8.9 development workspace has the bug.

**Comment by cpw** [comment]
This is a driver issue in all likelihood. Does a regular install of Minecraft have the problem? Do you have funky dual graphics? The dev env is running on your Intel gfx card.

It's not a forge problem. The Minecraft forge forums have lots of people experienced in walking others through issues with graphics drivers.

**Comment by JBYoshi** [comment]
Just figured out the issue. A certain dependency was overwriting the LWJGL version, and that version doesn't work with my system. I added an exclude to its transitive dependencies, and everything's working now.

**Comment by WorldSEnder** [comment]
Just noting that I have the same issue without overwriting any dependencies. But in the classpath I see that jwgjl-natives for linux and osx are present. Is that normal?

**Comment by WorldSEnder** [comment]
I solved the problem by manually attaching the natives that Minecraft uses, adding
```
configurations {
    forgeGradleMcNatives.exclude group:'org.lwjgl.lwjgl', module: 'lwjgl-platform'
    forgeGradleMcDepsClient.exclude group:'org.lwjgl.lwjgl', module: 'lwjgl-platform'
    forgeGradleMcDeps.exclude group:'org.lwjgl.lwjgl', module: 'lwjgl-platform'
}
```
to the buildscript and attaching jar from `.minecraft\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.4-nightly-20150209`
