### ISSUE TITLE
[1.9] Shield Crash - NullPointerException: Ticking player

### ISSUE THREAD

**Issue by Joxxs** [MinecraftForge/MinecraftForge#2786]
I experienced this issue and looked into it bit more.
This is the exact error log I experience as well

http://www.minecraftforge.net/forum/index.php?topic=38193.0

I first experienced this crash using the new 1.9 shield while blocking a skeleton arrow and shield broke. Reproduced with nothing but newest forge for 1.9

Trying to hunt it down it looks like it is because a lack of null check of itemstack in EntityLivingBase patch for the hook onItemUseTick submitted by cpw

Caused by: java.lang.NullPointerException
at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2447) ~[sa.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1881) ~[sa.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:226) ~[zj.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:301) ~[lr.class:?]

java.lang.NullPointerException: Ticking player
at net.minecraft.entity.EntityLivingBase.updateActiveHand(EntityLivingBase.java:2694)
at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2079)
at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:252)
at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:339)

**Comment by TomNaughton** [comment]
I fixed it by creating a new world.
