### ISSUE TITLE
"Display not created"

### ISSUE THREAD

**Issue by xJon** [MinecraftForge/MinecraftForge#2999]
Any idea why this error happening for some users?
Gameplay-wise, some items are not showing up (more information [here](https://github.com/xJon/The-1.7.10-Pack/issues/1163)).
```
[B#347] 2016/06/11 16:45:50 [INFO]  Exception in thread "Server thread" [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.IllegalStateException: Display not created
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.lwjgl.opengl.Display.processMessages(Display.java:598)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.client.FMLClientHandler.processWindowMessages(FMLClientHandler.java:1012)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.processWindowMessages(FMLCommonHandler.java:601)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.ProgressManager.push(ProgressManager.java:37)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:186)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.fireRemapEvent(Loader.java:984)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.registry.GameData.revertToFrozen(GameData.java:740)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.serverStopped(Loader.java:849)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.handleServerStopped(FMLCommonHandler.java:483)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:489)
[B#347] 2016/06/11 16:45:50 [INFO]  [16:45:50] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
Thanks for any information.

**Comment by LexManos** [comment]
Do not use github issues for basic debugging. Use the forums and only if this is tracked down to actually being Forge {Which I highly doubt this is} then bring it up.

**Comment by xJon** [comment]
:+1:
