### ISSUE TITLE
[1.10] Custom Resource Pack crash the game

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#3024]
Using Forge Build 1986 for testing

`[13:45:17] [Client thread/INFO]: Caught error stitching, removing all assigned resourcepacks
net.minecraft.util.ReportedException: Generating mipmaps for frame
	at net.minecraft.client.renderer.texture.TextureMap.generateMipmaps(TextureMap.java:300) ~[TextureMap.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.loadTextureAtlas(TextureMap.java:197) ~[TextureMap.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.loadSprites(TextureMap.java:93) ~[TextureMap.class:?]
	at net.minecraftforge.client.model.ModelLoader.setupModelRegistry(ModelLoader.java:155) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.onResourceManagerReload(ModelManager.java:28) ~[ModelManager.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.notifyReloadListeners(SimpleReloadableResourceManager.java:132) ~[SimpleReloadableResourceManager.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.reloadResources(SimpleReloadableResourceManager.java:113) ~[SimpleReloadableResourceManager.class:?]
	at net.minecraft.client.Minecraft.refreshResources(Minecraft.java:799) [Minecraft.class:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.actionPerformed(GuiScreenResourcePacks.java:153) [GuiScreenResourcePacks.class:?]
	at net.minecraft.client.gui.GuiScreen.mouseClicked(GuiScreen.java:500) [GuiScreen.class:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.mouseClicked(GuiScreenResourcePacks.java:166) [GuiScreenResourcePacks.class:?]
	at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:615) [GuiScreen.class:?]
	at net.minecraft.client.gui.GuiScreenResourcePacks.handleMouseInput(GuiScreenResourcePacks.java:86) [GuiScreenResourcePacks.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:581) [GuiScreen.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1797) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:406) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at net.minecraft.client.renderer.texture.TextureUtil.generateMipmapData(TextureUtil.java:77) ~[TextureUtil.class:?]
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.generateMipmaps(TextureAtlasSprite.java:339) ~[TextureAtlasSprite.class:?]
	at net.minecraft.client.renderer.texture.TextureMap.generateMipmaps(TextureMap.java:271) ~[TextureMap.class:?]
	... 29 more`

Resource Pack : https://drive.google.com/file/d/0B_PWTTYduPpfdmIxbEZIUFc1YzA/view

**Comment by KnightMiner** [comment]
Are you using any mods, or just Forge by itself? Extra Utilities 2 was having issues with resource packs for awhile.

If not, can you post the actual crash log on a site such as pastebin and link it here? What you have is the client log.

**Comment by SteveKunG** [comment]
Crash Log : http://pastebin.com/hkUKKEqc
Full FML Log : http://pastebin.com/FJv66aHH

**Comment by LexManos** [comment]
http://puu.sh/pFjIJ/e30796f755.png Not reproduceable.
