### ISSUE TITLE
[1.10] Unwanted obfuscation of parent class.

### ISSUE THREAD

**Issue by bschoenmaeckers** [MinecraftForge/MinecraftForge#3247]
Forge obfuscates variable names of a parent class when this isn't wanted. This leads to situations where you cant use Minecraft classes in for example a array config entry.

Example: 

``` java
public class TestArrayEntry extends GuiEditArrayEntries.BaseEntry {

    public TestArrayEntry(GuiEditArray owningScreen, GuiEditArrayEntries owningEntryList, IConfigElement configElement, Object value) {
        super(owningScreen, owningEntryList, configElement);
    }

    @Override
    public void drawEntry(int slotIndex, int x, int y, int listWidth, int slotHeight, int mouseX, int mouseY, boolean isSelected) {
        super.drawEntry(slotIndex, x, y, listWidth, slotHeight, mouseX, mouseY, isSelected);

        //Accessing minecraft code:
        Minecraft.getMinecraft();
    }
}
```

This crashes minecraft when you open an edit array gui in the settings menu from a mod (for example FML).

```
java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.GuiSlot.field_148161_k from class net.minecraftforge.fml.client.config.GuiEditArrayEntries$BaseEntry
    at net.minecraftforge.fml.client.config.GuiEditArrayEntries$BaseEntry.func_180790_a(GuiEditArrayEntries.java:581)
    at net.minecraftforge.fml.client.config.GuiEditArrayEntries$BooleanEntry.func_180790_a(GuiEditArrayEntries.java:491)
    at net.minecraft.client.gui.GuiListExtended.func_180791_a(SourceFile:25)
    at net.minecraft.client.gui.GuiSlot.func_148120_b(GuiSlot.java:420)
    at net.minecraft.client.gui.GuiSlot.func_148128_a(GuiSlot.java:194)
    at net.minecraftforge.fml.client.config.GuiEditArray.func_73863_a(GuiEditArray.java:192)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

```

This does not happen in a develop environment, only in a deopfuscated client.
I made a test mod to the this bug, you can find it [here](https://github.com/superbas11/ForgeTestCase).

**Comment by bschoenmaeckers** [comment]
I think this is related to issue #3043.

**Comment by LexManos** [comment]
Interesting, not sure how this is happening as it SHOULD be pointing twards the correct field, but this is a https://github.com/md-5/SpecialSource issue as that's what we are using to obfuscate.
No idea why your subclass triggers the issue...
