### ISSUE TITLE
[1.8.9 & 1.10.2] Logging in twice and duplicating items

### ISSUE THREAD

**Issue by inklit** [MinecraftForge/MinecraftForge#3278]
**Explanation of the problem:**
If you connect at the exact same time on two clients, you are able to login twice on the same account. This causes all sorts of issues regarding movement, inventories, and other weird shenanigans.
The primary concern here is item duplication, you are able to login on two accounts and drop both inventories to duplicate items.

**Procedure for testing:**
1. Start a 1.8.9 Forge 1902 or 1.10.2 Forge 2094 server.
2. Set the server to offline mode (only for testing, since sessions don't really work well with two clients, it also works in online mode with hackery)
3. Open two Minecraft clients
4. Line up both clients similar to this with your test server selected: http://i.imgur.com/6n5uEUS.png
5. Very quickly click `Join Server` on both clients.
6. If done fast enough, both of your clients will join the server at the same time without being kicked. It will look something like this: http://i.imgur.com/2rvs3hX.png

**Additional Information:**
I tested with no mods installed, just Forge 1902 on 1.8.9. It also works on Forge 2094 on 1.10.2
The issue does not affect Vanilla minecraft.

In the console, it will look something like this:
http://i.imgur.com/23EsTlL.png

During testing, I managed to get it to throw an error if the timing is not perfect and it fails:

```
[21:26:24] [Server thread/INFO]: BTC joined the game
> Sep 29, 2016 9:26:27 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by net.minecraft.network.NetHandlerPlayServer$1.operationComplete()
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@386b2f6f(uncancellable)
        at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:390)
        at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157)
        at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:283)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28)
        at net.minecraft.network.NetworkManager.func_150718_a(NetworkManager.java:304)
        at net.minecraft.network.NetHandlerPlayServer$1.operationComplete(NetHandlerPlayServer.java:172)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:406)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
        at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:523)
        at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:247)
        at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:322)
        at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:212)
        at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364)
        at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707)
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248)
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)
```

This error may not be very relevant to the issue at hand here, but maybe somebody will find it useful.

**Comment by GirafiStudios** [comment]
I'm pretty sure that only Forge for Minecraft 1.10.2 is supported at this point :)

**Comment by inklit** [comment]
Just tested it with 1.10.2 Forge 12.18.1.2094.
It works on 1.10.2 as well!

The technique for duping still works too, but it behaves a little differently. It looks like you don't drop the items on your second client, however if you walk to the area that it was dropped you'll find that it really did drop even though the server never actually made it look like anything was thrown. You also don't see your duplicate player, but believe me it's still there.

**Comment by Actuarius** [comment]
@mezz added labels [Bug]
