### ISSUE TITLE
FML 12.18.1.2095 cpu full 

### ISSUE THREAD

**Issue by tymop** [MinecraftForge/MinecraftForge#3296]
Hello,
I have some problems with my server forge 12.18.1.2095.

1 - without any player, the cpu load is very high [screenshot](https://postimg.org/image/819o9l8ct/)
and then, when I connect, the loading and the game are very slow

2 - I have some error when the server is loading
`[21:19:44] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalArgumentException: timeout value is negative
[21:19:44] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at java.lang.Thread.sleep(Native Method)
[21:19:44] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]:     at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
`

some times, when i want to cennect, i am ejected and this is what there is in the log:
`[22:05:38] [Server thread/INFO]: tymop joined the game
[22:05:41] [VoiceServer Listen Thread/INFO] [Mekanism]: VoiceServer: Accepted new connection.
[22:05:41] [Thread-13/INFO] [Mekanism]: VoiceServer: Traced IP in 1 attempts.
[22:05:42] [Netty Epoll Server IO #0/ERROR] [FML]: NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
        at net.minecraft.network.play.server.SPacketCustomPayload.<init>(SPacketCustomPayload.java:27) ~[gl.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toS3FPackets(FMLProxyPacket.java:156) ~[FMLProxyPacket.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:531) ~[NetworkDispatcher.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:?]
        at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:247) [eo$4.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [EpollEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
[22:05:43] [Server thread/INFO]: tymop lost connection: Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
[22:05:43] [Server thread/INFO]: tymop left the game
`
I do not know if the two problems have a relation.

this is the entire server log:
http://s000.tinyupload.com/index.php?file_id=83221909036335455344

Thank you for your help.

**Comment by LexManos** [comment]
Use the forums for basic debugging, only come where when you KNOW its a Forge issue.
