### ISSUE TITLE
[1.11] Couldn't render entity EntityZombieVillager

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#3398]
`[20:19:40] [Client thread/ERROR]: Couldn't render entity
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at net.minecraft.entity.monster.EntityZombieVillager.func_82230_o(EntityZombieVillager.java:149) ~[aao.class:?]
	at net.minecraft.client.renderer.entity.RenderZombieVillager.func_77043_a(SourceFile:44) ~[bwv.class:?]
	at net.minecraft.client.renderer.entity.RenderZombieVillager.func_77043_a(SourceFile:9) ~[bwv.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:120) [bvi.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:41) [bvn.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.func_76986_a(SourceFile:16) [bvn.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:383) [buo.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:367) [buo.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:626) [bqk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1332) [bqc.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1246) [bqc.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053) [bqc.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1075) [beq.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370) [beq.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

It works fine on vanilla.
Forge : 13.19.0.2141 without any mod.

**Comment by ezterry** [comment]
There was some changes to villagers not echoed into the forge villager/zombie villager registry, you may want to see if PR #3401 fixes this

**Comment by LexManos** [comment]
Need a bit more information im able to run around spamming the Zombie Villager egg and its working just fine.
What setup are you having?
