### ISSUE TITLE
"API loaded from an incompatible classloader" for duplicate copies of API

### ISSUE THREAD

**Issue by Choonster** [MinecraftForge/MinecraftForge#3423]
I've added the JEI API as a `deobfCompile` dependency and JEI itself as a `runtime` dependency, but when I run Minecraft I receive this error in the log:

```
[14:42:53] [Client thread/WARN] [FML/]: ****************************************
[14:42:53] [Client thread/WARN] [FML/]: * The API JustEnoughItemsAPI from source C:\Users\USER\.gradle\caches\minecraft\deobfedDeps\deobf\mezz\jei\jei_1.10.2\3.13.3.373\jei_1.10.2-3.13.3.373.jar is loaded from an incompatible classloader. THIS WILL NOT WORK!
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.ModAPIManager$APIContainer.validate(ModAPIManager.java:113)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.ModAPIManager.registerDataTableAndParseAPI(ModAPIManager.java:173)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.ModAPIManager.manageAPI(ModAPIManager.java:231)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:522)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
[14:42:53] [Client thread/WARN] [FML/]: *  at net.minecraft.client.Minecraft.startGame(Minecraft.java:477)...
[14:42:53] [Client thread/WARN] [FML/]: ****************************************
```

[Full Logs](https://gist.github.com/Choonster/3779faa6c71d29a411b25e5cc60f1bea)
[build.gradle](https://github.com/Choonster/JEITestMod/blob/ffad309529961640afbeef456265e25e73e361d7/build.gradle)

Originally reported to JEI [here](https://github.com/mezz/JustEnoughItems/issues/627), but apparently this is just a side effect of the JEI API being loaded from two JARs.

Is this intended? Is there any way to stop the message from being logged for this particular case?

**Comment by LexManos** [comment]
At dev time this error isnt a issue as you SHOULD only have one API version.
This error was introduced because some modders were adding APIs to coremods which completely screws up any of our version management stuff.
We could tone it down in Dev time, but its not a big enough deal that we care.
You should only care at RUNTIME as this IS a big deal.

**Comment by AEnterprise** [comment]
at dev time you sometimes have to have the api from 2 different places, if you only rely on the api instead of the full mod as compile dependancy that is also loaded when you launch minecraft, if you then also add in the mod just at runtime to test with you have the same api loaded from 2 places

**Comment by mezz** [comment]
I fixed this by having the API `deobfProvided` (which means compile-time only, not runtime), and the full jar be `runtime`. That way runtime only has the API once.

old way (has this error):
```
dependencies {
  deobfCompile "mezz.jei:jei_${mc_version}:${jei_version}:api"
  deobfCompile "mezz.jei:jei_${mc_version}:${jei_version}"
}
```

new way (correct):
```
dependencies {
  // compile against the JEI API but do not include it at runtime
  deobfProvided "mezz.jei:jei_${mc_version}:${jei_version}:api"
  // at runtime, use the full JEI jar
  runtime "mezz.jei:jei_${mc_version}:${jei_version}"
}
```
