### ISSUE TITLE
NPE with version comparison (ComparableVersion.compareTo)

### ISSUE THREAD

**Issue by Elix-x** [MinecraftForge/MinecraftForge#3470]
I have met this bug very often for a few months now, with one of my mods, but succeeded in tracking it down and confirming that it is caused by forge only now, in #2906.

This is what was tracked down:
Running this part of code
```java
VersionParser.parseVersionReference("supermod3000@[1.2,)").equals(VersionParser.parseVersionReference("supermod3000@[1.2,)"));
```
Will cause following NPE:
```
java.lang.NullPointerException
	at net.minecraftforge.fml.common.versioning.ComparableVersion.compareTo(ComparableVersion.java:480)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.compareTo(DefaultArtifactVersion.java:55)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.compareTo(DefaultArtifactVersion.java:1)
	at net.minecraftforge.fml.common.versioning.Restriction.containsVersion(Restriction.java:84)
	at net.minecraftforge.fml.common.versioning.VersionRange.containsVersion(VersionRange.java:522)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.containsVersion(DefaultArtifactVersion.java:77)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.equals(DefaultArtifactVersion.java:49)
...
```

Changing version numbers does not help, removing them - does.

**Comment by mezz** [comment]
I went to fix this and... whew the version range code is madness.
Even the formatting is really unusual.

Digging deep into ancient history of FML, it looks like it started as an old version of maven artifacts.

Maybe worth looking at what changed and if it can be updated to a more recent version.
https://maven.apache.org/ref/3.2.1/maven-artifact/apidocs/org/apache/maven/artifact/versioning/ArtifactVersion.html

Probably not going to get changed any time soon because it works in almost every case except equality testing and comparison with version ranges. If you want to have a look go ahead but it's scary stuff. 

I started by making a test mod with junit that exposes your bug. A much better set of tests will definitely be necessary if anyone changes this code.

**Comment by LexManos** [comment]
There is no garentee that equals will work how you're intending it to.
The current setup is a bit of a rats nest yes, however i'd be interested in what use case you have for testing equals where both sides are ranges.
The standard usage for this, which the code supports fully, is to have a range and .equals being a static version. Or better to use compareTo a static version.
