### ISSUE TITLE
[1.10.2] NPE when showing GuiModsMissing

### ISSUE THREAD

**Issue by iChun** [MinecraftForge/MinecraftForge#3501]
Installed Forge version: 12.18.2.2099
iChunUtil required 12.18.2.2151 so Forge tries to show the Missing mods screen and promptly crashes so someone reported it to me. Just passing on the message.

Stacktrace:

```
java.lang.NullPointerException: Rendering screen
at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.containsVersion(DefaultArtifactVersion.java:74)
at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.equals(DefaultArtifactVersion.java:56)
at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:211)
at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498)
at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106)
at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full issue (+ full crash log) here: https://github.com/iChun/iChunUtil/issues/130

**Comment by bs2609** [comment]
Possibly related to #3470?

**Comment by LexManos** [comment]
Not related, #3470 is comparing two version ranges to eachother to see if they are equal. Which.. is not something that the system supports at all.
I'd be curious to see what his real world uses for this is. Instead of what the system is designed for, compareTo.
This one is a missing null check.
