### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by eirikh1996** [MinecraftForge/MinecraftForge#3530]
So I attempted to launch Forge with liteloader and had LunatrusCore, Schematica, VoxelMap and InventoryTweaks installed:
What should happen:
Minecraft Forge should launch as usual

What really happened:
It failed to launch. Log output:

[21:39:42] [Client thread/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/inventory/Container
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663) ~[?:1.8.0_25]
	at java.lang.Class.getConstructor0(Class.java:3067) ~[?:1.8.0_25]
	at java.lang.Class.getConstructor(Class.java:1817) ~[?:1.8.0_25]
	at net.minecraft.entity.EntityList.func_191303_a(EntityList.java:356) ~[so.class:?]
	at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:265) ~[so.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[kt.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:340) ~[beq.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.inventory.Container
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663) ~[?:1.8.0_25]
	at java.lang.Class.getConstructor0(Class.java:3067) ~[?:1.8.0_25]
	at java.lang.Class.getConstructor(Class.java:1817) ~[?:1.8.0_25]
	at net.minecraft.entity.EntityList.func_191303_a(EntityList.java:356) ~[so.class:?]
	at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:265) ~[so.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[kt.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:340) ~[beq.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file net/minecraft/inventory/Container
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_25]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663) ~[?:1.8.0_25]
	at java.lang.Class.getConstructor0(Class.java:3067) ~[?:1.8.0_25]
	at java.lang.Class.getConstructor(Class.java:1817) ~[?:1.8.0_25]
	at net.minecraft.entity.EntityList.func_191303_a(EntityList.java:356) ~[so.class:?]
	at net.minecraft.entity.EntityList.func_151514_a(EntityList.java:265) ~[so.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:498) ~[kt.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:340) ~[beq.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) ~[Main.class:?]
	... 6 more
[21:39:42] [Client thread/INFO]: [STDERR]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[21:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[21:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[21:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.Runtime.exit(Runtime.java:107)
[21:39:42] [Client thread/INFO]: [STDERR]: 	at java.lang.System.exit(System.java:968)
[21:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[21:39:42] [Client thread/INFO]: [STDERR]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Also, prior to launch, CPU usage exceeds 95% and get close to 100%

**Comment by diesieben07** [comment]
Please use the forums for tech support. This is a bugtracker for verified bugs in forge.

**Comment by mezz** [comment]
Tech support forum is here: http://www.minecraftforge.net/forum/index.php?board=15.0
