### ISSUE TITLE
Error launching Forge with mods

### ISSUE THREAD

**Issue by bt1crt** [MinecraftForge/MinecraftForge#3531]
Just tried booting the latest version of Forge with Optifine and got this error message in the console: 
2016-12-11 22:37:37,230 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2016-12-11 22:37:37,232 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[22:37:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:37:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[22:37:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[22:37:37] [main/INFO] [FML]: Forge Mod Loader version 13.19.1.2189 for Minecraft 1.11 loading
[22:37:37] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[22:37:37] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.7.10_HD_D1.jar
[22:37:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:37:37] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[22:37:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[22:37:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:37:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[22:37:37] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[22:37:37] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[22:37:37] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[22:37:37] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[22:37:37] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Brandon/AppData/Roaming/.minecraft/mods/OptiFine_1.7.10_HD_D1.jar
[22:37:37] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@eafc191
[22:37:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:37:38] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[22:37:38] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[22:37:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[22:37:38] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
Exception in thread "main" [22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/ICrashCallable
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName0(Native Method)
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.forName(Class.java:344)
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.launcher.FMLDeobfTweaker.injectIntoClassLoader(FMLDeobfTweaker.java:53)
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.common.ICrashCallable
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[22:37:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 5 more
[22:37:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.IncompatibleClassChangeError: Implementing class
[22:37:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[22:37:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[22:37:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[22:37:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[22:37:38] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:643]: 	... 7 more

**Comment by diesieben07** [comment]
You installed Optifine for 1.7.10...
Please use the forum for tech support issues like this in the future.

**Comment by mezz** [comment]
Tech support forum is here: http://www.minecraftforge.net/forum/index.php?board=15.0
