### ISSUE TITLE
Assertion Error when opening container

### ISSUE THREAD

**Issue by maxanier** [MinecraftForge/MinecraftForge#3595]
When opening an inventory container/GUI I get:
```
[13:01:36] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AssertionError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_111]
	at net.minecraft.util.Util.runTask(Util.java:26) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:742) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:687) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.AssertionError
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:203) ~[EmbeddedChannel.class:4.0.23.Final]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:97) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2723) ~[EntityPlayer.class:?]
	at de.teamlapen.vampirism.blocks.BlockHunterTable.onBlockActivated(BlockHunterTable.java:65) ~[BlockHunterTable.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:477) ~[PlayerInteractionManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processRightClickBlock(NetHandlerPlayServer.java:706) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:68) ~[CPacketPlayerTryUseItemOnBlock.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(CPacketPlayerTryUseItemOnBlock.java:13) ~[CPacketPlayerTryUseItemOnBlock.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_111]
	at net.minecraft.util.Util.runTask(Util.java:25) ~[Util.class:?]
	... 5 more
```
Somehow a ChannelFuture/ChannelPromise does not finish.
It does not seem to be a problem with my mod, I could recreate this issue with the latest version of BloodMagic.
I am using **MC 1.10**. I know this isn't really supported anymore and I'm also not sure, how relevant the effects of this exception is.
But I would like to know what is causing this. Maybe you have an idea.

I've tested Forge between 12.18.1.2073 and latest.

**Comment by AlexiyOrlov** [comment]
See this #3309

**Comment by maxanier** [comment]
Thx :) did not find that.

Also I forgot that I enabled assertions some time ago, which explains why this exception was not occurring before.
Since this seems to be a vanilla bug with no real effects, I will ignore it.
Now I'm only enabling assertions for my own packages (`-ea:de.teamlapen...`)
