### ISSUE TITLE
[1.11.2 - 13.20.0.2201] Java 6 no longer working

### ISSUE THREAD

**Issue by chylex** [MinecraftForge/MinecraftForge#3596]
Firstly, I'm in favour of not supporting outdated Java, but I'm not aware of Forge dropping support for Java 6 so I figured I'd report this:

Since https://github.com/MinecraftForge/MinecraftForge/commit/e9143859c0535b76b649ef40fbed0a7928d285eb which converted `.close()` to `IOUtils.closeQuietly()`, using Java 6 crashes in [JarDiscoverer.java](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/discovery/JarDiscoverer.java#L122) and possibly in other places, because it tries to pass `JarFile` as a `Closeable` parameter.

According to the docs, `JarFile`'s parent class `ZipFile` only implements `Closable` since Java 7:
[java 6](https://docs.oracle.com/javase/6/docs/api/java/util/zip/ZipFile.html), [java 7](https://docs.oracle.com/javase/7/docs/api/java/util/zip/ZipFile.html)

In a dev environment, this causes an error:

```
java.lang.IncompatibleClassChangeError: Class java.util.jar.JarFile does not implement the requested interface java.io.Closeable
	at org.apache.commons.io.IOUtils.closeQuietly(IOUtils.java:303)
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:122)
	(...)
```

In the actual game, using `OpenJDK 1.6.0-OpenCSG-Build-21`, it actually doesn't print anything and simply reports that "some exception happened" and crashes with no stack trace in the launcher, nor any of the log files.

```
[14:10:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:10:10] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:10:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:10:10] [main/INFO] [FML]: Forge Mod Loader version 13.20.0.2201 for Minecraft 1.11.2 loading
[14:10:10] [main/INFO] [FML]: Java is OpenJDK Client VM, version 1.6.0-OpenSCG-Build-21, running on Windows 7:x86:6.1, installed at J:\JavaPortable\6\jre
[14:10:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:10:10] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:10:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:10:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:10:10] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:10:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:10:12] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
Exception in thread "main" 
```

I'm not sure how this managed to compile against Java 6, but I did run into an issue with ForgeGradle where it freely compiled invalid code that was using methods only available in Java 8, despite setting `sourceCompatibility = targetCompatibility = 1.6` in `build.gradle`, so I suspect something similar happened with Forge.

**Comment by bs2609** [comment]
`FMLSanityChecker`, `JarDiscoverer`, and `FMLServerHandler` are the offending classes.

I don't think it's needed to call `close()` on these files, provided all input streams opened on them are closed, which appears to be the case here.

@mezz made the commit, so they should probably review this, though.

**Comment by bs2609** [comment]
Funnily enough, [it's happened before](http://www.minecraftforum.net/forums/support/modded-client-support/1952588-java-util-zip-zipfile-big-confusion), see https://github.com/MinecraftForge/FML/commit/a13598b17ea9637c054d867a76298d6c080c5e32

**Comment by gigaherz** [comment]
It is a known issue of compiling with a newer JDK, that even if you set source compatibility to an older version, that doesn't prevent the compiled code from referencing method overloads that did not exist yet in the older version (or in this case, passing a class as parameter that didn't implement an interface).

The only real solution for catching those issues is to use jdk6 (and force the buildbots to use it too) for compiling.

**Comment by mezz** [comment]
We really need a github build bot on PRs to catch this type of error.
Anyone have recommendations?

**Comment by diesieben07** [comment]
Travis can build PRs.

**Comment by simon816** [comment]
@mezz [Travis CI](https://travis-ci.org/)

**Comment by 0xilly** [comment]
There's a good [Jenkins PR builder](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin) that works. I remember Lex saying somthing about not want use Travis because we decompile mc or something along those lines.

**Comment by mezz** [comment]
Thanks.
I'm setting up TravisCI with JEI to test it out, seems to work well.
I may try out the Jenkins builder too, since Forge already has a Jenkins running.
Will have to talk to Lex and Flamegoat about it.

**Comment by 0xilly** [comment]
Oh that reminds me Lex wanted me to talk to you and flame about a PR bot.
