### ISSUE TITLE
Dispensing a minecart into air with rail below crashes the game

### ISSUE THREAD

**Issue by sargunv** [MinecraftForge/MinecraftForge#3671]
1. Place a dispenser and load it with a cart
2. Place a rail directly below the block directly in front of the dispenser
3. Power the dispenser. The game crashes before the cart is placed.

This bug was introduced in version 1.11.2-13.20.0.2210 and is still around in version 1.11.2-13.20.0.2226.

```
java.lang.ClassCastException: net.minecraft.block.BlockAir cannot be cast to net.minecraft.block.BlockRailBase
	at net.minecraft.item.ItemMinecart$1.func_82487_b(ItemMinecart.java:55)
	at net.minecraft.dispenser.BehaviorDefaultDispenseItem.func_82482_a(SourceFile:12)
	at net.minecraft.block.BlockDispenser.func_176439_d(SourceFile:119)
	at net.minecraft.block.BlockDispenser.func_180650_b(SourceFile:143)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:745)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by williewillus** [comment]
@liach any insight? the only minecart change in 2210 was this: https://github.com/MinecraftForge/MinecraftForge/commit/d672584b8dac8e46b626ac072d908edbb27fc589

**Comment by bs2609** [comment]
Found a typo in the patch, made a PR to fix.

**Comment by liach** [comment]
Yeah. When I code, I used copy paste to change
`(BlockRailBase.EnumRailDirection)iblockstate1.func_177229_b(((BlockRailBase)iblockstate1.func_177230_c()).func_176560_l()) : BlockRailBase.EnumRailDirection.NORTH_SOUTH;`
to
`((BlockRailBase)iblockstate.func_177230_c()).getRailDirection(world, blockpos, iblockstate, null) : BlockRailBase.EnumRailDirection.NORTH_SOUTH;`

Didn't consider that there would be more than 1 `IBlockState` local variables.
