### ISSUE TITLE
FMLMissingMappingsEvent.MissingMapping.remap(...) does not work

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3846]
Currently, [FMLMissingMappingsEvent.MissingMapping.remap(...)](https://github.com/MinecraftForge/MinecraftForge/blob/cec90d7/src/main/java/net/minecraftforge/fml/common/event/FMLMissingMappingsEvent.java#L122-L156) seems to be working incorrectly, for both items and blocks. This issue will only discuss blocks, but much of it relates to items as well.

After much discussion on  the MMD Discord server, it seems that the problem arises from [PersistentRegistryManager.java#L547](https://github.com/MinecraftForge/MinecraftForge/blob/cec90d7/src/main/java/net/minecraftforge/fml/common/registry/PersistentRegistryManager.java#L547). The `PersistentRegistryManager` tries to register the replacement block (`remap.getTarget()`, name ID = `newName`) with the old missing ID (`remap.id`), but as seen in [FMLControlledNamespacedRegistry.java#L459-L463](https://github.com/MinecraftForge/MinecraftForge/blob/cec90d7/src/main/java/net/minecraftforge/fml/common/registry/FMLControlledNamespacedRegistry.java#L459-L463), the registry will return the replacement block's already existing ID. As a result, an exception is thrown at [PersistentRegistryManager.java#L566-L569](https://github.com/MinecraftForge/MinecraftForge/blob/cec90d7/src/main/java/net/minecraftforge/fml/common/registry/PersistentRegistryManager.java#L566-L569).

## How to replicate

See MrIbby/MinecraftForge@6fcdc4f (in [MrIbby/MinecraftForge/remap](/MrIbby/MinecraftForge/tree/remap)).

After placing a debug block (`forgeremapdebug:debug_block`), exiting the game, disabling registration, and reloading the world, the debug block is not replaced by a dirt block as desired and is instead replaced by air.

The following exception is printed in the console when reloading the world:

````
[20:44:00] [Server thread/INFO] [FML]: Found a missing id from the world forgeremapdebug:debug_block
[20:44:00] [Server thread/WARN] [FML]: ****************************************
[20:44:00] [Server thread/WARN] [FML]: * The object Block{minecraft:dirt} has been registered twice for the same name minecraft:dirt.
[20:44:00] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:461)
[20:44:00] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.PersistentRegistryManager.processIdRematches(PersistentRegistryManager.java:547)
[20:44:00] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.Loader.fireMissingMappingEvent(Loader.java:1076)
[20:44:00] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:315)
[20:44:00] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:329)
[20:44:00] [Server thread/WARN] [FML]: *  at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:418)...
[20:44:00] [Server thread/WARN] [FML]: ****************************************
[20:44:00] [Server thread/ERROR]: Exception reading ./saves/World/level.dat
java.lang.IllegalStateException
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.processIdRematches(PersistentRegistryManager.java:568) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.Loader.fireMissingMappingEvent(Loader.java:1076) ~[Loader.class:?]
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:315) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:329) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:418) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [SaveFormatOld.class:?]
	at net.minecraft.world.storage.SaveHandler.loadWorldInfo(SaveHandler.java:122) [SaveHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:74) [IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:120) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
````

**Comment by ghost** [comment]
**NOTE:** Remapping was reported to work as intended in version 12.18.3.2185 for 1.10.2. At the time of writing, the current version is 13.20.0.2282 for 1.11.2.

**Comment by ghost** [comment]
**Update:** An alternative to using `FMLMissingMappingsEvent` for items is to register an implementation of `IFixableData`. For example:

````java
CompoundDataFixer dataFixer = FMLCommonHandler.instance().getDataFixer();
ModFixs modDataFixer = dataFixer.init(MOD_ID, MOD_DATA_VERSION);
modDataFixer.registerFix(FixTypes.ITEM_INSTANCE, new FixableDataImpl());
````

**Comment by LexManos** [comment]
Remapping has never been intended to combine two entries like this.
It's for fixing name changes during mod updates. Not for merging blocks or items.
So yes... working as intended.

**Comment by ghost** [comment]
What? Are you sure you didn't miss this line in the example mod?

````java
public static boolean shouldRegister = false; // Set to false after placing block in test world
````

(Yes, `shouldRegister` is supposed to be `true`, then `false`, but that's not the point.)
