### ISSUE TITLE
Forge 1.9 Error

### ISSUE THREAD

**Issue by siddarth2000** [MinecraftForge/MinecraftForge#3850]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/16/17 2:36 PM
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:236)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:227)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:195)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:144)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:332)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:236)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:227)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:195)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/font/ascii.png
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(TextureManager.java:144)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:130)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:111)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:756)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:332)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 19332296 bytes (18 MB) / 255066112 bytes (243 MB) up to 255066112 bytes (243 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1887 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1887.jar) 
	UCHIJA	Forge{12.16.1.1887} [Minecraft Forge] (forge-1.9-12.16.1.1887.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.65' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.9-forge1.9-12.16.1.1887
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: #A a ron (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz

**Comment by williewillus** [comment]
increase the ram allocation in your launcher, and go to the forums for further troubleshooting

**Comment by siddarth2000** [comment]
I have 8GB ram, increase to how much?

**Comment by williewillus** [comment]
> Memory: 19332296 bytes (18 MB) / 255066112 bytes (243 MB) up to 255066112 bytes (243 MB)

the JVM is only allowed to use 256M of your 8G, increase it to 1G or 2G at least.

**Comment by siddarth2000** [comment]
I set it to 2G and it still crashes

**Comment by siddarth2000** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/16/17 2:52 PM
Description: Registering texture

java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:236)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:227)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:195)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42)
	at net.minecraft.client.renderer.RenderGlobal.<init>(RenderGlobal.java:159)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:507)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:236)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:227)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:195)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:46)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/misc/forcefield.png
	Texture object class: net.minecraft.client.renderer.texture.SimpleTexture
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67)
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42)
	at net.minecraft.client.renderer.RenderGlobal.<init>(RenderGlobal.java:159)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:507)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 33310912 bytes (31 MB) / 241631232 bytes (230 MB) up to 241631232 bytes (230 MB)
	JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G -Xmx256M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.23 Powered by Forge 12.16.1.1887 3 mods loaded, 3 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9-12.16.1.1887.jar) 
	UCH	Forge{12.16.1.1887} [Minecraft Forge] (forge-1.9-12.16.1.1887.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 381.65' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Launched Version: 1.9-forge1.9-12.16.1.1887
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 960/PCIe/SSE2 GL version 4.5.0 NVIDIA 381.65, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: #A a ron (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz

**Comment by diesieben07** [comment]
> and go to the forums for further troubleshooting

**Comment by siddarth2000** [comment]
Minecraft Forums?

**Comment by diesieben07** [comment]
http://www.minecraftforge.net/

**Comment by siddarth2000** [comment]
It worked!! Thanks for the help guys!!
