### ISSUE TITLE
Mc - 1.11.2 TickNextTick list out of synch

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#3883]
This crash happens to me many times. I think it appears after calling world.tickUpdates(true) after a while ~1 million attempts.
It called in world generator event or from server tick event.
https://gist.github.com/Endmateria/442944648b49b3264c369b668ca78228#file-crash-2017-05-09_15-53-18-server-txt

java.lang.IllegalStateException: TickNextTick list out of synch
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:699)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:217)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

**Comment by ghost** [comment]
As I can see forge not support bug reporting.

**Comment by mezz** [comment]
http://www.minecraftforge.net/forum/forum/18-support-bug-reports/
