### ISSUE TITLE
[1.11.2] Tripwire block disappeared on server (tested only realms)

### ISSUE THREAD

**Issue by SteveKunG** [MinecraftForge/MinecraftForge#3924]
Step to reproduce
1. Start your game and join Realm.
2. Exit Realm and join any singleplayer world.
3. Exit Singleplayer world and join realm again.

Forge 2304 without any mod installed

Also got some error log.
> [22:28:26] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:540) ~[auo.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:335) ~[ajs.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_180503_b(WorldClient.java:293) ~[bnq.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147234_a(NetHandlerPlayClient.java:759) ~[bno.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:40) ~[gb.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:13) ~[gb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

![1](https://cloud.githubusercontent.com/assets/6128413/26500913/0ed9ff94-4262-11e7-94e1-730e90fc11b7.png)

**Comment by Pokechu22** [comment]
I've reproduced this _once_ on a non-realms spigot server using forge 2315 with schematica installed.  I can't consistently reproduce it, though, with or without mods.  Going to take a look at this myself.

**Comment by Pokechu22** [comment]
I remembered a second aspect: It also occurred on relogging (or rather, going to the server hub and back within the same bungee instance).  In fact, it happened after I relogged to check why my schematic didn't have string in it.  The missing string from the server persisted subsequent relogs, but I know for sure wasn't an issue on the first join.

```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:540) ~[auo.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:335) ~[ajs.class:?]
	at net.minecraft.client.multiplayer.WorldClient.func_180503_b(WorldClient.java:293) ~[bnq.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147234_a(NetHandlerPlayClient.java:759) ~[bno.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:40) ~[gb.class:?]
	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:13) ~[gb.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```

-----

Anyways, some analysis based off of the previous stacktrace:

OK... I'm not 100% familiar with forge's codebase or how things are lined up, but this is my analysis assuming line numbers are still the same between versions (which it looks like is the case):

```
Caused by: java.lang.NullPointerException
 at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:540) ~[auo.class:?]
 at net.minecraft.world.World.func_180501_a(World.java:335) ~[ajs.class:?]
 at net.minecraft.client.multiplayer.WorldClient.func_180503_b(WorldClient.java:293) ~[bnq.class:?]
 at net.minecraft.client.network.NetHandlerPlayClient.func_147234_a(NetHandlerPlayClient.java:759) ~[bno.class:?]
 at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:40) ~[gb.class:?]
 at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:13) ~[gb.class:?]
 at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
 at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
 at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
 ... 9 more
```

Line 540 of `Chunk.java` is `Block block = state.getBlock();` and that's the first place `state` is accessed.  So a null `state` was passed to <ruby><rb>`Chunk.setBlockState`</rb><rp> (</rp><rt>func_177436_a</rt><rp>)</rp></ruby>.  That null state would have previously been passed to <ruby><rb>`World.setBlockState`</rb><rp>( </rp><rt>func_180501_a</rt><rp>)</rp></ruby>, which doesn't access it so a null could slip through; that would happen in <ruby><rb>`WorldClient.invalidateRegionAndSetBlock`</rb><rp>( </rp><rt>func_180503_b</rt><rp>)</rp></ruby> which also doesn't do anything with the state.  That brings us to <ruby><rb>`NetHandlerPlayClient.handleBlockChange`</rb><rp>( </rp><rt>func_147234_a</rt><rp>)</rp></ruby>, which uses `getBlockState` from the `SPacketBlockChange` and doesn't do any other processing.  That value is received via `(IBlockState)Block.BLOCK_STATE_IDS.getByValue(buf.readVarInt());`.

String is one of those blocks that has more states than metadata would allow.  `GameData.onAdd` mentions these blocks:

> ```java
> //So, due to blocks having more in-world states then metadata allows, we have to turn the map into a semi-milti-bimap.
> //We can do this however because the implementation of the map is last set wins. So we can add all states, then fix the meta bimap.
> //Multiple states -> meta. But meta to CORRECT state.
> ```

Relatedly, the annonymous subclass of `ClearableObjectIntIdentityMap` has this warning (sic):

> ```java
> // There are some cases where this map is queried to serialize a state that is valid,
> //but somehow not in this list, so attempt to get real metadata. Doing this hear saves us 7 patches
> ```

Unfortunately it doesn't log when it's not on that list, and I can't seem to repro a case where it's not on the list.  But I'll keep looking.

**Comment by mezz** [comment]
Does this bug happen on 1.12 as well, or only 1.11.2?

**Comment by Pokechu22** [comment]
I haven't encountered it in 1.12 yet, but it seems to be a rare and random bug so it may still be present.

**Comment by Pokechu22** [comment]
OK, here's a more complete account from my ~6 hr log video for that session `2017-07-14-1219-08.mp4` (don't ask why I have those; I just do):

* At 12:19:50, I connect to the bungee hub.  Very soon after, I switch servers in bungee to skyblock.
* From that point on, I mine cobblestone until 16:21.  Nothing eventful happens here, just 4 hours of mining cobblestone while AFK.
* I visit a few people's islands within the same world (teleportation, but not far and not involving a reload)
* At 16:43 I start building from one of my schematics.  At 16:48 (4:29:00) I start building an area that uses vines, and string to keep the vines in place; I go to grab vines and when I return I realize the schematic doesn't have string. I quit the server to go into singleplayer to check.  The string is also missing in singleplayer.
* I return to the server.  Undaunted, I start building, and grab some string.  This takes an embarrassingly long time.
* At 16:54:58, I place my first string.  It visually places successfully from the client, but the following is printed in the log:
    ```
    [16:54:58] [Client thread/FATAL]: Error executing task
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
    	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
    	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
    	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
    	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    Caused by: java.lang.NullPointerException
    	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:540) ~[auo.class:?]
    	at net.minecraft.world.World.func_180501_a(World.java:335) ~[ajs.class:?]
    	at net.minecraft.client.multiplayer.WorldClient.func_180503_b(WorldClient.java:293) ~[bnq.class:?]
    	at net.minecraft.client.network.NetHandlerPlayClient.func_147234_a(NetHandlerPlayClient.java:759) ~[bno.class:?]
    	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:40) ~[gb.class:?]
    	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:13) ~[gb.class:?]
    	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
    	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
    	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
    	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
    	... 9 more
    [16:54:58] [Client thread/FATAL]: Error executing task
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
    	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
    	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
    	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
    	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    Caused by: java.lang.NullPointerException
    	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:540) ~[auo.class:?]
    	at net.minecraft.world.World.func_180501_a(World.java:335) ~[ajs.class:?]
    	at net.minecraft.client.multiplayer.WorldClient.func_180503_b(WorldClient.java:293) ~[bnq.class:?]
    	at net.minecraft.client.network.NetHandlerPlayClient.func_147234_a(NetHandlerPlayClient.java:759) ~[bno.class:?]
    	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:40) ~[gb.class:?]
    	at net.minecraft.network.play.server.SPacketBlockChange.func_148833_a(SourceFile:13) ~[gb.class:?]
    	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
    	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_91]
    	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_91]
    	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
    	... 9 more
    ```
    
    I continue placing string, and the same message appears (twice each time) at 16:55:06, 16:55:36, 16:55:52, and 16:55:54.  On the second one for 16:55:36 and all subsequent ones, the cause is no longer printed:
    ```
    [16:55:36] [Client thread/FATAL]: Error executing task
    java.util.concurrent.ExecutionException: java.lang.NullPointerException
    	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_91]
    	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_91]
    	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
    	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1046) [bes.class:?]
    	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372) [bes.class:?]
    	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    Caused by: java.lang.NullPointerException
    ```

    At 16:56:12, the message is printed 5 times, then back to 2 times at 16:57:02, 16:57:05, 16:57:06, 16:57:08/16:57:09 (split), 16:57:54, 16:57:54 again, 16:57:59, 16:58:03, 16:58:03 again, 16:58:04, 16:58:07, and 16:58:08.  The message starts appearing once each time: at 16:58:10, 16:58:13, 16:58:16, three times at 16:58:32, once at 16:58:33, twice at 17:00:15, once at 17:01:03, twice at 17:01:04, once at 17:01:05, twice at 17:01:07, thrice at 17:01:08, once at 17:01:09, twice at 17:01:40.

* At this point, I am more or less finished with the string and do more stuff for a while.  At 17:27, I head over to another part of my island, and notice the gravel in the ceiling of the cave (don't ask) is levitating due to particle effects from it (there's supposed to be string under it; I know that I can get real levitating gravel via MC-31038 but haven't had access to the materials for that).  I write into chat `???` at 17:27:09, and then the messages start appearing in chat again (I'm not sure whether I was right-clicking the ceiling or not; that's not in my log):

    4 times at 17:27:12, twice at 17:27:18, twice at 17:27:19, twice at 17:27:33, once at 17:27:34, thrice at 17:27:35.  **I get an independent observer to come to my island, and at 17:28:39 I ask them if they saw string under the gravel.  They did; I did not.**  The message continues to be printed, once at 17:28:39, once at 17:28:40, once at 17:29:01, once at 17:29:02.  The cause still isn't printed, so I don't know if this was from the same packet (I don't know why that happens), twice at 17:29:08, twice at 17:29:21.

* I relog within bungee later within 17:29:21.  The message is printed more times; I don't feel like listing them anymore.  I start placing some string (5:11:16), relog from bungee, and observe that it is gone.  Placing blocks into it causes those blocks to appear to be there (torches were tried), but breaking those blocks drops string.  (Speculation: it's because the server tries to resend the string, but since string is causing the problem, it's still left as a torch).  Right-clicking in the place for the string also doesn't work.  However, I can still place string myself and it will show up.
* At 17:32:10 I disconnect from the server and close the game.  Later attempts to reproduce the bug fail.

It's worth noting that re-opening the singleplayer world in question still shows a lack of string, and the schematic is also missing it (the schematic was saved a few days before the incident in question).  I never actually placed any string, nor did I run into it, until after loading and leaving single-player, nor did I relog except through bungee; as such I can't say whether this issue actually did persist through a "real" reload.

I just checked, and the singleplayer world in question also doesn't have string when loaded through forge... and... I just reproduced it!  More info soon.

**Comment by Pokechu22** [comment]
OK. Still on 1.11.2:

* It persists a full relog.
* Placing a string causes the message to appear, as do some other things (I'm not 100% sure since there is some weird anticheat stuff on the server that may be sending more block changes)
* It doesn't persist after a restart (duh)
* But it **does** return after opening that single-player world.
* It does _not_ affect singleplayer worlds.  (tested with a basic superflat, where I then placed a few strings and relogged)
* It happens on _any_ singleplayer world, not just my personal world.  Phew, that makes it a fair bit easier.

Now to test 1.12.

**Comment by Pokechu22** [comment]
**Confirmed for Forge 1.12-14.21.1.2413 with no mods**.  Steps to reproduce, should be 100% consistent(!):

1. Join a server.  (This might not actually be needed, but I've done it each time).
2. Place some string.
3. Leave the server
4. Enter a singleplayer world.  Any world will do.
5. Leave the singleplayer world.
6. Join a server.
7. Observe that the string is invisible, and the block where it should be behaves weirdly.

**Comment by Pokechu22** [comment]
Update: This happens after relogging in general; don't even need to go into singleplayer.

Also:

**Before relogging**:
```
2114 is minecraft:tripwire[attached=false,disarmed=false,east=false,north=false,powered=false,south=false,west=false]

2112: minecraft:tripwire[attached=false,disarmed=false,east=false,north=false,powered=false,south=false,west=false]
2113: minecraft:tripwire[attached=false,disarmed=false,east=false,north=false,powered=true,south=false,west=false]
2114: minecraft:tripwire[attached=false,disarmed=false,east=false,north=false,powered=false,south=false,west=false]
2115: minecraft:tripwire[attached=false,disarmed=false,east=false,north=false,powered=true,south=false,west=false]
2116: minecraft:tripwire[attached=true,disarmed=false,east=false,north=false,powered=false,south=false,west=false]
2117: minecraft:tripwire[attached=true,disarmed=false,east=false,north=false,powered=true,south=false,west=false]
2118: minecraft:tripwire[attached=true,disarmed=false,east=false,north=false,powered=false,south=false,west=false]
2119: minecraft:tripwire[attached=true,disarmed=false,east=false,north=false,powered=true,south=false,west=false]
2120: minecraft:tripwire[attached=false,disarmed=true,east=false,north=false,powered=false,south=false,west=false]
2121: minecraft:tripwire[attached=false,disarmed=true,east=false,north=false,powered=true,south=false,west=false]
2122: minecraft:tripwire[attached=false,disarmed=true,east=false,north=false,powered=false,south=false,west=false]
2123: minecraft:tripwire[attached=false,disarmed=true,east=false,north=false,powered=true,south=false,west=false]
2124: minecraft:tripwire[attached=true,disarmed=true,east=false,north=false,powered=false,south=false,west=false]
2125: minecraft:tripwire[attached=true,disarmed=true,east=false,north=false,powered=true,south=false,west=false]
2126: minecraft:tripwire[attached=true,disarmed=true,east=false,north=false,powered=false,south=false,west=false]
2127: null
```

**After relogging**:
```
2114 is null
2112: minecraft:tripwire[attached=false,disarmed=false,east=false,north=false,powered=false,south=false,west=false]
2113: minecraft:tripwire[attached=false,disarmed=false,east=false,north=false,powered=true,south=false,west=false]
2114: null
2115: null
2116: minecraft:tripwire[attached=true,disarmed=false,east=false,north=false,powered=false,south=false,west=false]
2117: minecraft:tripwire[attached=true,disarmed=false,east=false,north=false,powered=true,south=false,west=false]
2118: null
2119: null
2120: minecraft:tripwire[attached=false,disarmed=true,east=false,north=false,powered=false,south=false,west=false]
2121: minecraft:tripwire[attached=false,disarmed=true,east=false,north=false,powered=true,south=false,west=false]
2122: null
2123: null
2124: minecraft:tripwire[attached=true,disarmed=true,east=false,north=false,powered=false,south=false,west=false]
2125: minecraft:tripwire[attached=true,disarmed=true,east=false,north=false,powered=true,south=false,west=false]
2126: null
2127: null
```

**Comment by Pokechu22** [comment]
This seems to be caused by the slave maps not having everything in them after `GameData.revertToFrozen` is called.  Not sure why, and this is unfortunately out of my knowledge of forge.  Best guess is that when the registry resyncs, it only uses the states that it knows, and not the states that, er, redirect to others (I think?).  But I don't know why tripwire is missing some states like that that it isn't missing the other way around.

As far as I can tell, my original guess about the `ClearableObjectIntIdentityMap` subclass is **NOT** the actual cause.

**Comment by LexManos** [comment]
Ya, seems tripwire is crap and need to be special cased. Fixed, thanks for looking into it.

**Comment by Pokechu22** [comment]
Thanks, and glad to help!
