### ISSUE TITLE
No More Entity Indicies Left

### ISSUE THREAD

**Issue by TheModNoob** [MinecraftForge/MinecraftForge#3949]
I need help with a modpack i'm making. I am aware that using as many mods as I am using (93) will definitely mess up your game, however I seem to have run into a different problem. I am using the new launcher on version 1.7.10. My error is: java.lang.RuntimeException: No more entity indicies left

My Crash Report:
"[net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/1/17 7:47 PM
Description: Initializing game

java.lang.RuntimeException: No more entity indicies left 
at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322) 
at com.inventorypets.InventoryPets.load(InventoryPets.java:507) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:483) 
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) 
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:483) 
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) 
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) 
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) 
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) 
at com.google.common.eventbus.EventBus.post(EventBus.java:275) 
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) 
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:483) 
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) 
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) 
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) 
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) 
at com.google.common.eventbus.EventBus.post(EventBus.java:275) 
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) 
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) 
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) 
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) 
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) 
at net.minecraft.client.main.Main.main(SourceFile:148) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.lang.reflect.Method.invoke(Method.java:483) 
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) 

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at cpw.mods.fml.common.registry.EntityRegistry.findGlobalUniqueEntityId(EntityRegistry.java:322)
at com.inventorypets.InventoryPets.load(InventoryPets.java:507)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3939302120 bytes (3756 MB) / 5234491392 bytes (4992 MB) up to 5234491392 bytes (4992 MB)
JVM Flags: 26 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -Xms5G -Xmn1280m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D1 93 mods loaded, 93 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHI mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHI FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
UCHI Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
UCHI CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
UCHI Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
UCHI NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
UCHI <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
UCHI FastCraft{1.23} [FastCraft] (FastCraft.jar) 
UCHI Chimneys{1.7.2} [Chimneys] ([1.7.10]Chimneys.jar) 
UCHI DamageIndicatorsMod{3.2.0} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
UCHI fpsspoofmod{1.0} [FPS Spoofer Mod] ([1.7.10]FPSSpoofer-1.0.jar) 
UCHI adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8c.jar) 
UCHI ac2{1.1.3 Beta} [Alchemy Craft 2] (alchemycraft2 v1.1.3.jar) 
UCHI BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
UCHI BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
UCHI AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.2-1.jar) 
UCHI BuildCraft|Core{7.1.21} [BuildCraft] (buildcraft-7.1.21.jar) 
UCHI BuildCraft|Builders{7.1.21} [BC Builders] (buildcraft-7.1.21.jar) 
UCHI BuildCraft|Energy{7.1.21} [BC Energy] (buildcraft-7.1.21.jar) 
UCHI BuildCraft|Factory{7.1.21} [BC Factory] (buildcraft-7.1.21.jar) 
UCHI BuildCraft|Robotics{7.1.21} [BC Robotics] (buildcraft-7.1.21.jar) 
UCHI BuildCraft|Silicon{7.1.21} [BC Silicon] (buildcraft-7.1.21.jar) 
UCHI BuildCraft|Transport{7.1.21} [BC Transport] (buildcraft-7.1.21.jar) 
UCHI candycraftmod{Beta 1.3} [CandyCraft] (CandyCraft-1.3.jar) 
UCHI CarpentersBlocks{3.3.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.1 - MC 1.7.10.jar) 
UCHI cfm{3.4.8} [§9MrCrayfish's Furniture Mod] (cfm-3.4.8-mc1.7.10.jar) 
UCHI colourfulportalsmod{1.4.3} [Colourful Portals] (ColourfulPortals-1.4.3.jar) 
UCHI CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip) 
UCHI customnpcs{1.7.10b} [CustomNpcs] (CustomNPCs_1.7.10b.jar) 
UCHI PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.2_1.7.10.jar) 
UCHI props{2.3.2} [Decocraft] (Decocraft-2.3.2_1.7.10.jar) 
UCHI jawser{1.0.0} [Decorative Videogame Systems] (Decorative Systems Mod v1.4.1.jar) 
UCHI doggytalents{v1.9.0h} [Doggy Talents] (DoggyTalents-1.7.10-v1.9.0h-universal.jar) 
UCHI ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
UCHI MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
UCHI ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
UCHI DragonAPI{v17c} [DragonAPI] (DragonAPI 1.7.10 V17c.jar) 
UCHI DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
UCHI MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
UCHI RotaryCraft{v17c} [RotaryCraft] (RotaryCraft 1.7.10 V17c.jar) 
UCHI ElectriCraft{v17a} [ElectriCraft] (ElectriCraft 1.7.10 V17a.jar) 
UCHI etfuturum{1.5.5} [Et Futurum] (Et Futurum-1.5.5.jar) 
UCHI evilcraft{0.8.6} [EvilCraft] (EvilCraft-1.7.10-0.8.6.jar) 
UCHI exoticbirds{1.0} [Exotic Birds] (Exotic Birds 1.7.10 - 1.0.3b.jar) 
UCHI fairylights{1.4.0} [Fairy Lights] (fairylights-1.4.0-1.7.10.jar) 
UCHI flowercraftmod{1.9} [Flowercraft] (Flowercraftmod 1.8 - 1.7.10 Forge.jar) 
UCHI GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.462.jar) 
UCHI GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.462.jar) 
UCHI GollumCoreLib{2.0.0} [Gollum Core Lib] (GollumCoreLib-2.0.0-1.7.10.jar) 
UCHI hamsterrific{0.2.0} [Hamsterrific] (Hamsterrific-0.2.0.zip) 
UCHI headcrumbs{1.7.4} [Headcrumbs] (Headcrumbs-1.7.4.jar) 
UCHI howlingmoon{1.1.1} [Howling Moon] (howlingMoon-1.7.10-1.1.1.jar) 
UCHI iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
UCHE InventoryPets{1.1.2a} [Inventory Pets] (inventorypets-1.7.10-1.1.2a.jar) 
UCHI IronChest{6.0.41.729} [Iron Chest] (ironchest-1.7.10-6.0.41.729-universal.jar) 
UCHI lasercreepers{1.1b} [Laser Creeper Robot Dino Riders From Space] (Laser Creeper Robot Dino Riders From Space-1.1b.jar) 
UCHI SlimevoidLib{2.0.4.7} [Slimevoid Library] (SlimevoidLibrary-2.0.4.7.jar) 
UCHI LittleBlocks{2.2.4.4} [Little Blocks] (LittleBlocks-2.2.4.4.jar) 
UCHI LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10 v7.jar) 
UCHI malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3.jar) 
UCHI malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2.jar) 
UCHI mcheli{0.10.6} [MC Helicopter] (mcheli) 
UCHI mfs{2.1.0} [Minecraft Flight Simulator] (Minecraft Flight Simulator-1.7.10-2.1.0.jar) 
UCHI MorePistons{2.0.0} [More Pistons] (MorePistons-2.0.0-1.7.10.jar) 
UCHI moreplayermodels{1.7.10} [MorePlayerModels] (MorePlayerModels_1.7.10.jar) 
UCHI Morph{0.9.0} [Morph] (Morph-Beta-0.9.0.jar) 
UCHI musiccraft{2.9.9} [MusicCraft] (musiccraft-2.9.9.jar) 
UCHI notenoughIDs{1.4.3.4} [NotEnoughIDs] (NotEnoughIDs-1.4.3.4.jar) 
UCHI OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
UCHI ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
UCHI ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
UCHI ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
UCHI ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
UCHI ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
UCHI ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
UCHI ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
UCHI ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
UCHE rancraftpenguins{1.7.10q} [Rancraft Penguins] (rancraftpenguins-1.7.10q.jar) 
UCHI RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
UCHI Safe{1.3.0} [Safe] (safe-1.3.0b.jar) 
UCHI secretroomsmod{4.7.1} [The SecretRoomsMod] (secretroomsmod-1.7.10-4.7.1.413.jar) 
UCHE securitycraft{v1.6.1} [SecurityCraft] (SecurityCraft v1.6.1 for 1.7.10.jar) 
UCHI SGCraft{1.9.3} [Greg's SG Craft] (SGCraft-1.9.3-mc1.7.10.jar) 
UCHI StuffedAnimals{1.7.10v1} [Stuffed Animals] (Stuffed Animals-1.7.10v1.jar) 
UCHE dna948{1.35} [The Last Sword You Will Ever Need Mod] (The_Last_Sword_You_Will_Ever_Need_Mod-1.10.jar) 
UCHI torchLevers{1.4.2} [Torch Levers] (TorchLevers-V1.4.2-MC1.7.10.jar) 
UCHE ultimate_unicorn_mod{1.5.6} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.7.10-1.5.6.jar) 
UCHI witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
UCHI McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
UCHI ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
UCHI MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
UCHI RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
UCHI ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4624' Renderer: 'Intel(R) HD Graphics 4400'
Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
LWJGL: 2.9.1
OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4624, Intel
GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
OptiFine Version: OptiFine_1.7.10_HD_U_D1
Render Distance Chunks: 16
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
OpenGlVersion: 4.3.0 - Build 20.19.15.4624
OpenGlRenderer: Intel(R) HD Graphics 4400
OpenGlVendor: Intel
CpuCount: 4"

I know NEID (Not Enough ID's) adds more block and item IDs, and was wondering if there is anything similar for entity IDs. I know a little bit about minecraft and mods, and I can fix something in a config file, however I know very little of java code and if it requires that then at least tell me what to do. If your solution is to delete one (or more) of the mods tell me which mods would be the best, but consider other options first.

**Comment by liach** [comment]
1. Use forums
2. The version is too old, no longer supported

**Comment by Alpvax** [comment]
@liach While correct, there is no point directing 1.7.10 posts to the forum, as the thread will just get locked.

@TheModNoob try the Minecraft forums or update to a newer version, this does not belong on github.

**Comment by LexManos** [comment]
Also stop using global ids you havent needed to do this for years.

**Comment by TheModNoob** [comment]
Thanks
