### ISSUE TITLE
Crashing when launching minecraft 1.10.2 with mo (matter overdrive)

### ISSUE THREAD

**Issue by IlyaS64** [MinecraftForge/MinecraftForge#3950]
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo)
Caused by: net.minecraft.util.ReportedException: Generating mipmaps for frame
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147963_d(TextureAtlasSprite.java:335)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:60)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at matteroverdrive.client.render.RenderParticlesHandler.<init>(RenderParticlesHandler.java:68)
	at matteroverdrive.client.RenderHandler.init(RenderHandler.java:209)
	at matteroverdrive.proxy.ClientProxy.init(ClientProxy.java:130)
	at matteroverdrive.MatterOverdrive.init(MatterOverdrive.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by liach** [comment]
Go to forums. You also need the stacktrace for `java.lang.ArrayIndexOutOfBoundsException`

**Comment by shadowfacts** [comment]
Why are you reporting this here? This is a Matter Overdrive/Extra Utilities 2 bug and is not at all related to Forge. Additionally, if you'd looked at the [Matter Overdrive issue tracker](https://github.com/simeonradivoev/MatterOverdrive/issues), you'd see that this has already been reported.

**Comment by IlyaS64** [comment]
Where?! There is no report on such theme :(

**Comment by shadowfacts** [comment]
[Yes there is](https://github.com/simeonradivoev/MatterOverdrive/issues/525)

**Comment by IlyaS64** [comment]
Oh, thanks!
