### ISSUE TITLE
[1.12] Crash on launch

### ISSUE THREAD

**Issue by Aareon** [MinecraftForge/MinecraftForge#3969]
Hey Lex, sorry to keep bothering you, but here's the full error log after having installed your new installer (using the win version).
```---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 6/11/17 1:21 PM
Description: Initializing game

java.lang.VerifyError: Bad return type
Exception Details:
  Location:
    Config.getDefiningResourcePack(Lnet/minecraft/network/play/server/SPacketPlayerListHeaderFooter;)Lnet/minecraft/client/renderer/entity/RenderLlamaSpit; @101: areturn
  Reason:
    Type 'net/minecraft/client/renderer/entity/RenderBiped' (current frame, stack[0]) is not assignable to 'net/minecraft/client/renderer/entity/RenderLlamaSpit' (from method signature)
  Current Frame:
    bci: @101
    flags: { }
    locals: { 'net/minecraft/network/play/server/SPacketPlayerListHeaderFooter', 'net/minecraft/client/renderer/entity/RenderLiving', 'net/minecraft/client/renderer/entity/RenderLlamaSpit', 'java/util/List' }
    stack: { 'net/minecraft/client/renderer/entity/RenderBiped' }
  Bytecode:
    0x0000000: b202 d3b6 0366 4c2b b603 854d 2cc6 000f
    0x0000010: 2c2a b903 bd02 0099 0005 2cb0 2bb4 03c0
    0x0000020: 4e2d b903 8801 0004 6436 0415 049b 002b
    0x0000030: 2d15 04b9 03c4 0200 c000 073a 0519 05b6
    0x0000040: 037f 3a06 1906 2ab9 03bd 0200 9900 0619
    0x0000050: 06b0 8404 ffa7 ffd6 b803 9f2a b603 c599
    0x0000060: 0007 b803 9fb0 01b0                    
  Stackmap Table:
    append_frame(@28,Object[#9],Object[#860])
    append_frame(@43,Object[#878],Integer)
    same_frame(@82)
    chop_frame(@88,1)
    same_frame(@102)

	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getField0(Unknown Source)
	at java.lang.Class.getField(Unknown Source)
	at net.minecraftforge.fml.client.FMLClientHandler.detectOptifine(FMLClientHandler.java:310)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:217)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getField0(Unknown Source)
	at java.lang.Class.getField(Unknown Source)
	at net.minecraftforge.fml.client.FMLClientHandler.detectOptifine(FMLClientHandler.java:310)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:217)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 55798040 bytes (53 MB) / 251269120 bytes (239 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	Launched Version: 1.12-forge1.12-14.21.0.2322
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R5 Graphics GL version 4.5.13447 Compatibility Profile Context 16.300.2201.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-7410 APU with AMD Radeon R5 Graphics ```

**Comment by LexManos** [comment]
Use  the forums, $20 days you have a coremod somewhere

**Comment by Aareon** [comment]
Remind me later that I owe you $20

**Comment by diesieben07** [comment]
It's Optifine, btw. Which still puts it's classes in the default package. Like... wtf.
