### ISSUE TITLE
[1.12] "Exception reading ./world/level.dat" On every startup

### ISSUE THREAD

**Issue by BrainStone** [MinecraftForge/MinecraftForge#3989]
Whenever I start a server I get this error/warning:

```
[01:11:42] [Server thread/ERROR]: Exception reading ./world/level.dat
java.lang.NullPointerException: null
        at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:282) ~[PersistentRegistryManager.class:?]
        at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:332) ~[FMLContainer.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:419) ~[FMLCommonHandler.class:?]
        at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [bfa.class:?]
        at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$zpj000(SaveHandler.java:1064) [bez.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bez.class:?]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:686) [WorldManager.class:1.12-2321-7.0.0-BETA-2386]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3550) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:267) [nx.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[01:11:42] [Server thread/WARN] [FML]: Forge Mod Loader detected that the backup level.dat is being used.

This may happen due to a bug or corruption, continuing can damage
your world beyond repair or lose data / progress.

It's recommended to create a world backup before continuing.

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

Forge: forge-1.12-14.21.0.2324

This didn't happen in forge-1.12-14.21.0.2322! So either 2323 or 2324 introduced it. So according to the changelog @LexManos has introduced this bug.

**Comment by GirafiStudios** [comment]
Cannot reproduce with just Forge. Since you have Sponge installed, please report this issue to them instead.

**Comment by BrainStone** [comment]
Alright and thanks @GirafiStudios. I'm sorry. That bug looked so Forge related.

**Comment by Superloup10** [comment]
I have reproduced this bug with just Forge 14.21.0.2324 and I have recipes in my mod.
I use Json files for my recipes, I specify because without the recipes I can launch my game.

Sorry for my bad english, i'm french.

**Comment by BrainStone** [comment]
Well now I have no clue which on to blame. I'll happily close the wrong issue.

**Comment by crazysnailboy** [comment]
I can also reproduce this with a clean MDK install and just the example mod.

**Comment by BrainStone** [comment]
Just the server or the client too? Because for me it's just the server. @crazysnailboy

**Comment by crazysnailboy** [comment]
On the server. Happens every time I try to load or create a world using 1.12-14.21.0.2324 or 1.12-14.21.0.2325.

```
[01:24:43] [Server thread/ERROR]: Exception reading .\saves\New World\level.dat
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:284) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:332) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:419) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:126) [SaveFormatOld.class:?]
	at net.minecraft.world.storage.SaveHandler.loadWorldInfo(SaveHandler.java:141) [SaveHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:74) [IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:160) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:549) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by Hexeption** [comment]
This happens to me too 

Running Client Side 
```
[01:56:14] [Server thread/ERROR]: Exception reading .\saves\Sexy\level.dat
java.lang.NullPointerException: null
	at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:282) ~[PersistentRegistryManager.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:332) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:419) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:119) [SaveFormatOld.class:?]
	at net.minecraft.world.storage.SaveHandler.loadWorldInfo(SaveHandler.java:122) [SaveHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:73) [IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by Actuarius** [comment]
@tterrag1098 added labels [Bug]

**Comment by ThexXTURBOXx** [comment]
Happens to me, too.
I made a little mod, which adds recipes.
Maybe it's really because of them (Source code here: https://github.com/ThexXTURBOXx/MegaQuarry)

**Comment by crazysnailboy** [comment]
It's not a problem with recipes, it happens even with no mods installed at all.

Also confirmed to affect build 2327.

**Comment by raoulvdberge** [comment]
Got this crash after I added at least one JSON recipe.

**Comment by raoulvdberge** [comment]
This seems to only happen when the JSON recipe is malformed. For example, providing a pattern when you're using `minecraft:crafting_shapeless`.

THIS CRASHES:
```
{
  "type": "minecraft:crafting_shapeless",
  "pattern": [
    "II",
    "IQ"
  ],
  "key": {
    "I": {
      "item": "minecraft:iron_ingot"
    },
    "Q": {
      "item": "minecraft:quartz"
    }
  },
  "result": {
    "item": "refinedstorage:quartz_enriched_iron"
  }
}
```
THIS DOESN'T CRASH:
```
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "II",
    "IQ"
  ],
  "key": {
    "I": {
      "item": "minecraft:iron_ingot"
    },
    "Q": {
      "item": "minecraft:quartz"
    }
  },
  "result": {
    "item": "refinedstorage:quartz_enriched_iron"
  }
}
```

**Comment by ThexXTURBOXx** [comment]
Hmm, that it odd, because my mod doesn't use json-recipes and it causes this, too.

**Comment by BrainStone** [comment]
I also don't had mods installed that add recipies. Only thing related to recipies is JEI

**Comment by BrainStone** [comment]
Still not fixed in the latest forge!
