### ISSUE TITLE
[1.12] Crash with mod ids, factories and illegal characters

### ISSUE THREAD

**Issue by Elix-x** [MinecraftForge/MinecraftForge#4022]
When a mod id contains a character cannot be used in file name (`|` for instance), Forge crashes trying to load recipe factory for it.
```
java.nio.file.InvalidPathException: Illegal char <|> at index 26: assets/appliedenergistics3|debug/recipes/_factories.json
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
	at net.minecraftforge.common.crafting.CraftingHelper.loadFactories(CraftingHelper.java:617)
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$16(CraftingHelper.java:596)
	at net.minecraftforge.common.crafting.CraftingHelper$$Lambda$97/750245005.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:596)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:358)
	at net.minecraft.client.Minecraft.init(Minecraft.java:576)
	at net.minecraft.client.Minecraft.run(Minecraft.java:416)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)```

**Comment by williewillus** [comment]
....how does a mod id like that load anything else normally? textures, models, loot tables... they all live under /assets/modid/

**Comment by KnightMiner** [comment]
Wait, I though Minecraft disallowed characters other than underscore and lowercase letters

**Comment by LexManos** [comment]
I thought we did as well.. i'll look into that. Your mod ID needs to be file system safe as it is used for your assets folder.

**Comment by Elix-x** [comment]
@williewillus It does not require any of the assets from its' own folder. So there hasn't been any problems with that.

@LexManos Already did. I reported it here to inform that illegal characters are still usable in mod ids.
