### ISSUE TITLE
[1.12] Missing mapping event NPE

### ISSUE THREAD

**Issue by raoulvdberge** [MinecraftForge/MinecraftForge#4067]
```
[22:08:37] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$MissingMappings@5e23a945:
java.lang.NullPointerException: null
	at net.minecraftforge.event.RegistryEvent$MissingMappings.lambda$getMappings$0(RegistryEvent.java:114) ~[RegistryEvent$MissingMappings.class:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_102]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_102]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_102]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_102]
	at net.minecraftforge.event.RegistryEvent$MissingMappings.getMappings(RegistryEvent.java:114) ~[RegistryEvent$MissingMappings.class:?]
	at com.raoulvdberge.refinedstorage.proxy.ProxyCommon.fixItemMappings(ProxyCommon.java:322) ~[ProxyCommon.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_ProxyCommon_fixItemMappings_MissingMappings.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:145) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) ~[EventBus.class:?]
	at net.minecraftforge.registries.GameData.lambda$injectSnapshot$20(GameData.java:511) ~[GameData.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_102]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_102]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) [?:1.8.0_102]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) [?:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_102]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_102]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_102]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_102]
	at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:506) [GameData.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:250) [FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:425) [FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:126) [SaveFormatOld.class:?]
	at net.minecraft.world.storage.SaveHandler.loadWorldInfo(SaveHandler.java:141) [SaveHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:74) [IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:160) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:549) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
[22:08:38] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[22:08:38] [Server thread/ERROR] [FML]: 0: NORMAL
[22:08:38] [Server thread/ERROR] [FML]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@589de505
[22:08:38] [Server thread/ERROR] [FML]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@692afea4
[22:08:38] [Server thread/ERROR]: Exception reading .\saves\New World\level.dat
java.lang.NullPointerException: null
	at net.minecraftforge.event.RegistryEvent$MissingMappings.lambda$getMappings$0(RegistryEvent.java:114) ~[RegistryEvent$MissingMappings.class:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_102]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_102]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_102]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_102]
	at net.minecraftforge.event.RegistryEvent$MissingMappings.getMappings(RegistryEvent.java:114) ~[RegistryEvent$MissingMappings.class:?]
	at com.raoulvdberge.refinedstorage.proxy.ProxyCommon.fixItemMappings(ProxyCommon.java:322) ~[ProxyCommon.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_ProxyCommon_fixItemMappings_MissingMappings.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:145) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:186) ~[EventBus.class:?]
	at net.minecraftforge.registries.GameData.lambda$injectSnapshot$20(GameData.java:511) ~[GameData.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_102]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_102]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_102]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_102]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_102]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_102]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_102]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_102]
	at net.minecraftforge.registries.GameData.injectSnapshot(GameData.java:506) ~[GameData.class:?]
	at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:250) ~[FMLContainer.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:425) ~[FMLCommonHandler.class:?]
	at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:126) [SaveFormatOld.class:?]
	at net.minecraft.world.storage.SaveHandler.loadWorldInfo(SaveHandler.java:141) [SaveHandler.class:?]
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:74) [IntegratedServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:160) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:549) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```
This is `ProxyCommon#fixItemMappings`: https://github.com/raoulvdberge/refinedstorage/blob/mc1.12/src/main/java/com/raoulvdberge/refinedstorage/proxy/ProxyCommon.java#L320-L327

This happens when loading a world from MC 1.10 with a bunch of blocks and items from mods that aren't in MC 1.12.

**Comment by LexManos** [comment]
We only care if you load 1.11.2 worlds.
Support for older stuff has been removed.

**Comment by maruohon** [comment]
The NPE happens immediately when anyone calls `event.getMappings()`. In my case it happened on a test world started in 1.12, and I then removed a mod from it. When the missing mappings event fires and my mod calls `getMappings()`, the crash occurs.

**Comment by raoulvdberge** [comment]
Ah so 1.10 migration is unsupported? Good to know, then I can remove some compatibility hacks.


But like @maruohon says, this also happens on normal 1.12 worlds.

**Comment by LexManos** [comment]
Right, I missed a function, seriously have no idea how that happened. I blame git fuckups.
And yes,l If anyone wants to migrate anything <1.11.2 they need to load it in 1.11.2 first.
