### ISSUE TITLE
When creating new registry without ids range, game crashes

### ISSUE THREAD

**Issue by Elix-x** [MinecraftForge/MinecraftForge#4095]
When creating a new registry with `RegistryBuilder` without explicitly setting bounds, game crashes.
```---- Minecraft Crash Report ----
// You're mean.

Time: 6/27/17 8:43 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Applied Energistics 3 (appliedenergistics3)
// Removed internal reflective junk
Caused by: java.lang.NegativeArraySizeException: nbits < 0: -2147483648
	at java.util.BitSet.<init>(BitSet.java:159)
	at net.minecraftforge.registries.ForgeRegistry.<init>(ForgeRegistry.java:95)
	at net.minecraftforge.registries.RegistryManager.createRegistry(RegistryManager.java:90)
	at net.minecraftforge.registries.RegistryBuilder.create(RegistryBuilder.java:134)
	at appeng.core.core.AppEngCore.preInit(AppEngCore.java:116)
	... 54 more
```

Possible fix: Use `Integer.MAX_INT - 1` as default max id [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/registries/RegistryBuilder.java#L37).

**Comment by Alpvax** [comment]
Is it a problem? It's an easy fix, and you SHOULD explicitly state the id range.

**Comment by Elix-x** [comment]
I already fixed where it was a problem.
I reported it here so either Forge fixes it and you can not explicitly set one, or Forge states that you must explicitly set one.

**Comment by LexManos** [comment]
You must explicitly set one. We could add a warning, but not that high of a priority.
