### ISSUE TITLE
Feature-Request: Log to named-pipes

### ISSUE THREAD

**Issue by marvinside** [MinecraftForge/MinecraftForge#4272]
(consider this as low-priority)

I am currently running a bad combination of mods, that generate a lot of log output, and i think my disk might be slowing down the process. So i tried to make the file fml-server-latest.log a named pipe, which did not work.

`2017-08-01 19:51:28,438 ERROR Unable to invoke method createAppender in class org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender for element RollingRandomAccessFile java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.logging.log4j.core.config.BaseConfiguration.createPluginObject(BaseConfiguration.java:841)
        at org.apache.logging.log4j.core.config.BaseConfiguration.createConfiguration(BaseConfiguration.java:595)
        at org.apache.logging.log4j.core.appender.routing.RoutingAppender.createAppender(RoutingAppender.java:153)
        at org.apache.logging.log4j.core.appender.routing.RoutingAppender.getControl(RoutingAppender.java:137)
        at org.apache.logging.log4j.core.appender.routing.RoutingAppender.append(RoutingAppender.java:111)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
        at org.apache.logging.log4j.spi.AbstractLogger.log(AbstractLogger.java:1417)
        at cpw.mods.fml.relauncher.FMLRelaunchLog.log(FMLRelaunchLog.java:69)
        at cpw.mods.fml.relauncher.FMLRelaunchLog.fine(FMLRelaunchLog.java:103)
        at cpw.mods.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:303)
        at cpw.mods.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:221)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:74)
        at cpw.mods.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:39)
        at cpw.mods.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:23)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
Caused by: java.lang.IllegalStateException: Unable to create a manager
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:73)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:65)
        at org.apache.logging.log4j.core.appender.rolling.RollingRandomAccessFileManager.getRollingRandomAccessFileManager(RollingRandomAccessFileManager.java:62)
        at org.apache.logging.log4j.core.appender.RollingRandomAccessFileAppender.createAppender(RollingRandomAccessFileAppender.java:196)
        ... 30 more

2017-08-01 19:51:28,439 ERROR Unable to create Appender of type RollingRandomAccessFile
2017-08-01 19:51:28,444 ERROR Cannot access RandomAccessFile {}) java.io.IOException: Illegal seek
`

**Comment by Pokechu22** [comment]
This is a log4j thing.  You can specify custom log4j configurations, and use them with the game.  See [this wiki.vg article](http://wiki.vg/Debugging) (not designed for forge, but the same process _should_ apply); [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/resources/log4j2.xml) is forge's `log4j2.xml` file that you can start with.

As for named pipes, I checked [log4j's bug tracker](https://issues.apache.org/jira/browse/LOG4J2), and [a search](https://issues.apache.org/jira/browse/LOG4J2-1842?jql=project%20%3D%20LOG4J2%20AND%20text%20~%20%22pipe%22) doesn't reveal an existing ticket for that; you could create one.
