### ISSUE TITLE
Missing Models, File structure error

### ISSUE THREAD

**Issue by HossamMohsen7** [MinecraftForge/MinecraftForge#4378]
Hello,
I'm having this problem with forge 1.12.1 in my dev environment:

`Caused by: java.io.FileNotFoundException: minecraft:models/models/block/redstone_dot.json
	at net.minecraft.client.resources.FallbackResourceManager.getResource(FallbackResourceManager.java:69) ~[FallbackResourceManager.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.getResource(SimpleReloadableResourceManager.java:65) ~[SimpleReloadableResourceManager.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.loadModel(ModelBakery.java:365) ~[ModelBakery.class:?]
	at net.minecraftforge.client.model.ModelLoader.access$1600(ModelLoader.java:126) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:933) ~[ModelLoader$VanillaLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:733) ~[ModelLoader$WeightedRandomModel.class:?]
	at net.minecraftforge.client.model.ModelLoader$MultipartModel.<init>(ModelLoader.java:1275) ~[ModelLoader$MultipartModel.class:?]
	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1249) ~[ModelLoader$VariantLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 22 more`

From what I see it's trying to search in minecraft:models/models which doesn't exist.

I'm using build 14.22.0.2467

EDIT: It's not just with this model, many other have the same issue

**Comment by LexManos** [comment]
Quit telling it to load that model then..

**Comment by HossamMohsen7** [comment]
Well, if it was that easy why did I made and issue.
It's actually forge itself cause this error comes without any additional mods at all, It's just forge in a dev environment.
Thanks

**Comment by LexManos** [comment]
Unless you're screwing up the vanilla assets this won't happen on just vanilla. Do some debugging and figure out what model block it's trying to load the model for. And use the forums for basic debugging. This isn't a forge issue it's something on your end.
