### ISSUE TITLE
[1.12.1] TileEntity Crash

### ISSUE THREAD

**Issue by CluelessPhil** [MinecraftForge/MinecraftForge#4395]
My server crashes when someone did something with a hopper.

```
at net.minecraftforge.items.wrapper.InvWrapper.extractItem(InvWrapper.java:166)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.extractHook(VanillaInventoryCodeHooks.java:57)
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:301)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:142)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1812)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```
###  Forge: 14.22.0.2474

**Comment by LexManos** [comment]
Use the forums.
