### ISSUE TITLE
[1.12.2] Forge 14.23.0.2492 crashes on startup (no mods)

### ISSUE THREAD

**Issue by chylex** [MinecraftForge/MinecraftForge#4423]
- 2491 works fine
- 2492 crashes the game when ran via launcher without any mods

EDIT: Updated title; I realized I had 2491 in my MDK setup instead of 2492, so I haven't actually tested 2492 in a dev environment, just in the regular game.

```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 9/25/17 11:23 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access field net.minecraft.client.gui.GuiOverlayDebug.field_175242_a from class net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge
	at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.<init>(GuiIngameForge.java:917)
	at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.<init>(GuiIngameForge.java:911)
	at net.minecraftforge.client.GuiIngameForge.<init>(GuiIngameForge.java:101)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.<init>(GuiIngameForge.java:917)
	at net.minecraftforge.client.GuiIngameForge$GuiOverlayDebugForge.<init>(GuiIngameForge.java:911)
	at net.minecraftforge.client.GuiIngameForge.<init>(GuiIngameForge.java:101)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:536)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 76969736 bytes (73 MB) / 389283840 bytes (371 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.0.2492 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature                                |
	|:------ |:--------- |:------------ |:----------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None                                     |
	| UCHIJA | mcp       | 9.42         | minecraft.jar                 | None                                     |
	| UCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.0.2492.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge     | 14.23.0.2492 | forge-1.12.2-14.23.0.2492.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	Loaded coremods (and transformers): 
	Launched Version: 1.12.2-forge1.12.2-14.23.0.2492
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R9 200 Series GL version 4.5.13469 Compatibility Profile Context 21.19.519.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
```

**Comment by diesieben07** [comment]
This is the same issue:
http://www.minecraftforge.net/forum/topic/60904-112-gradlew-build-compiler-switches-around-variables/

Reobfuscation seems to not take into account the target class name anymore.

**Comment by LunNova** [comment]
https://github.com/md-5/SpecialSource/pull/49

**Comment by CDAGaming** [comment]
Same Issue here also sadly

**Comment by LexManos** [comment]
Yes, known issue in that build update.
