### ISSUE TITLE
IllegalReferenceCountException when spawning mod entities

### ISSUE THREAD

**Issue by SanAndreaP** [MinecraftForge/MinecraftForge#4523]
I maintain the Clay Soldiers mod for Minecraft 1.12.2. A user that runs the latest Forge version (```14.23.0.2542```) reported issues seeing the soldiers when spawned (see SanAndreasP/ClaySoldiersMod#211).
I've looked into this issue and noticed that it occurs since Forge ```14.23.0.2538```. The error is an IllegalReferenceCountException within the AbstractByteBuf class, thus I assume it has to do with the network fixes introduced in 2538.

Here's the full log:
https://gist.github.com/SanAndreasP/f670d9a7d6c80caee15e8cc75fc2e1cc

And here is the stacktrace of the error:
```
Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: A severe problem occurred during the spawning of an entity at (-254.32084839454646, 64.0, -164.8836508370485)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1086) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: A severe problem occurred during the spawning of an entity at (-254.32084839454646, 64.0, -164.8836508370485)
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:134) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.process(EntitySpawnHandler.java:63) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.lambda$channelRead0$0(EntitySpawnHandler.java:55) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler$$Lambda$224/282372305.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1394) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:696) ~[AbstractByteBuf.class:4.1.9.Final]
	at de.sanandrew.mods.claysoldiers.network.packet.PacketSyncUpgrades.fromBytes(PacketSyncUpgrades.java:79) ~[PacketSyncUpgrades.class:?]
	at de.sanandrew.mods.claysoldiers.entity.soldier.EntityClaySoldier.readSpawnData(EntityClaySoldier.java:934) ~[EntityClaySoldier.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:128) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.process(EntitySpawnHandler.java:63) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler.lambda$channelRead0$0(EntitySpawnHandler.java:55) ~[EntitySpawnHandler.class:?]
	at net.minecraftforge.fml.common.network.internal.EntitySpawnHandler$$Lambda$224/282372305.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more
```

**Comment by williewillus** [comment]
probably related to @bs2609's fixes

**Comment by bs2609** [comment]
Yeah I see what the problem is here. PR incoming.

**Comment by LexManos** [comment]
Ya, pretty obvious issue that'll happen on any packet that uses the buffer without retaining it.
As a lot of the time things are pushed to the main thread. 
@bs2609 Be sure to check any other packets that are hanging out. Tho i think this is the only one that has a raw buffer.

**Comment by SanAndreaP** [comment]
I can confirm, Forge 2543 with this fix works, thanks! :)
