### ISSUE TITLE
1.12.2 strange issue

### ISSUE THREAD

**Issue by MadRatSRP** [MinecraftForge/MinecraftForge#4558]
[00:43:54] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)

Caused by: java.lang.NullPointerException
	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48) ~[cgw.class:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48) ~[cgw.class:?]
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44) ~[cgw.class:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:603) ~[bib.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.reloadSearchTrees(FMLClientHandler.java:1119) ~[forge-1.12.2-14.23.1.2554.jar:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.reloadSearchTrees(FMLCommonHandler.java:771) ~[forge-1.12.2-14.23.1.2554.jar:?]
	at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:554) ~[forge-1.12.2-14.23.1.2554.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:900) ~[Loader.class:?]
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:233) ~[GameData.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:728) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352) ~[FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[1.12.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) ~[launchwrapper-1.12.jar:?]

**Comment by Cloudhunter** [comment]
These kind of things should be discussed on the forums first as they are a support issue. Please open a thread there at https://minecraftforge.net
