### ISSUE TITLE
Can not open chests

### ISSUE THREAD

**Issue by 2001zhaozhao** [MinecraftForge/MinecraftForge#4669]
I can not open any chests in the game. Using forge 14.23.1.2586 with a lot of other mods. Haven't tried this without forge yet, but the console error does not seem to have any modded things in it. Here's the log:

`
[00:08:49] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.AbstractMethodError: net.minecraft.block.state.BlockStateContainer$StateImplementation.doesSideBlockChestOpening(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;)Z
	at net.minecraft.block.BlockChest.func_176456_n(BlockChest.java:541) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_176457_m(BlockChest.java:536) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_189418_a(BlockChest.java:460) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180676_d(BlockChest.java:444) ~[api.class:?]
	at net.minecraft.block.BlockChest.func_180639_a(BlockChest.java:421) ~[api.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:446) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more`

I originally thought it was a problem with FoamFix, as it showed the coremod replacement blockstate at first, but upon disabling the feature in FoamFix config this appears instead.
All the modded chests seem to work fine, it's just the two vanilla ones that don't open. Pipes still work nd breaking the chest still gives you the items.

**Comment by mezz** [comment]
Update Optifine and please use the forums for this type of issue.
