### ISSUE TITLE
NetworkDispatcher exception

### ISSUE THREAD

**Issue by ziceptor** [MinecraftForge/MinecraftForge#4683]
More info https://github.com/SpongePowered/SpongeForge/issues/1968

https://gist.github.com/ziceptor/40825cd7bf99f3457786eddb72f245ef
https://gist.github.com/ziceptor/1d48d6f67609dc6a3e435dc1723144b7
https://gist.github.com/ziceptor/88e8988036f81b205ef269f6b04d074e

video https://youtu.be/7HZVv4CoAbA

**Comment by bs2609** [comment]
Remapped stacktrace:
```
[06:17:55] [Server thread/WARN]: Failed to handle packet for /192.168.10.105:52769
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240) ~[DefaultChannelPipeline.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.insertIntoChannel(NetworkDispatcher.java:174) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:160) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:72) ~[FMLNetworkHandler.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:135) ~[pc.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:63) ~[pc.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:179) [oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by ziceptor** [comment]
spam https://gist.github.com/ziceptor/40825cd7bf99f3457786eddb72f245ef#file-fml-junk-earlystartup-log-L998

**Comment by NewMilenium** [comment]
It is still an ongoing problem.

Reproduced : one friend connects to my local (pc) minecraft 1.12.2 modded server using forge 1.12.2-forge1.12.2-14.23.4.2708 , or using 1.12.2-forge1.12.2-14.23.4.2729 (the crash happens in both cases, both versions being the same on the server & his client). His client starts loading the world, then on the server this is spammed : 
                [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception
                java.io.IOException: Une connexion existante a dû être fermée par l'hôte distant

                at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_144]
                at sun.nio.ch.SocketDispatcher.writev(Unknown Source) ~[?:1.8.0_144]
                at sun.nio.ch.IOUtil.write(Unknown Source) ~[?:1.8.0_144]
                at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[?:1.8.0_144]
                at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel
        .java:432) ~[NioSocketChannel.class:?]
                at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChanne
        l.java:856) [AbstractChannel$AbstractUnsafe.class:?]
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(
        AbstractNioChannel.java:368) [AbstractNioChannel$AbstractNioUnsafe.class:?]
                at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.jav
        a:618) [NioEventLoop.class:?]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEve
        ntLoop.java:559) [NioEventLoop.class:?]
                at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.ja
        va:476) [NioEventLoop.class:?]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEven
        tLoop.class:?]
                at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThread
        EventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
                at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]


and his client crashes.

**Comment by LexManos** [comment]
It doesn't appear to be a Forge issue. You should try reproducing it without any other modifications to Forge/Minecraft. Currently you have a ton of coremods and the like.
Also, it could just be a network issue, as its thinking your channel is closed.

**Comment by Niko-sk2x** [comment]
I was able to get this issue with just 2 mods (but very very rarely, haven't seen it in months), none of which touched much of networking code, in mod dev environment. And I have some fuzzy memory of actually getting that one in forge dev environment (the one where you edit forge) back when trying to figure out and maybe fix some of the netty issues. But I was never able to reliably reproduce it. It just sometimes happened.

**Comment by LexManos** [comment]
Thanks for the completly useless comment. Logs and exact details or dont comment
