### ISSUE TITLE
Crash biomesoplenty.common.block.BlockBOPGrass$BOPGrassType

### ISSUE THREAD

**Issue by neocrypto** [MinecraftForge/MinecraftForge#4716]
Actually getting folling crash on some biomes.
Forge Version .2606

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPGrass$BOPGrassType, values=[spectral_moss, overgrown_stone, loamy, sandy, silty, origin, overgrown_netherrack, daisy, mycelial_netherrack]} as it does not exist in BlockStateContainer{block=camping:hemp, properties=[age]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
at biomesoplenty.common.block.BlockBOPGrass.func_149688_o(BlockBOPGrass.java:140)
at com.rikmuld.camping.objs.block.Hemp.getGrowthRate(Hemp.scala:77)
at com.rikmuld.camping.objs.block.Hemp.func_180650_b(Hemp.scala:56)
at net.minecraft.block.Block.func_180645_a(Block.java:508)
at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:475)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
at java.lang.Thread.run(Thread.java:748)

Error comes on all forge Versions on 14.23.1.255 up to actually .2607
(Also on new World, and privat client)

Some fix i can use?

Full report:

https://pastebin.com/LVfcThqK

**Comment by raoulvdberge** [comment]
Forums
