### ISSUE TITLE
Item class constructor returning "null"

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/MinecraftForge#4785]
I looked everywhere and it seems noone has the same problem as me.

What's happening is I get this crash when my game hits initialization phase:
```
2018-03-02 16:35:57,990 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-03-02 16:35:58,007 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:35:59] [main/INFO] [GradleStart]: username: mattwilkason@gmail.com
[16:35:59] [main/INFO] [GradleStart]: Extra: []
[16:35:59] [main/INFO] [GradleStart]: Password found, attempting login
[16:35:59] [main/INFO]: Logging in with username & password
[16:36:01] [main/INFO] [GradleStart]: Login Succesful!
[16:36:01] [main/INFO] [GradleStart]: Running with arguments: [--userProperties, [], --assetsDir, C:/Users/WolfHybrid23/.gradle/caches/minecraft/assets, --assetIndex, 1.12, --userType, mojang, --accessToken{REDACTED}, --version, 1.12.2, --uuid, 927844d084bf4880aa660256d00d370d, --username, WolfHybrid23, --tweakClass, net.minecraftforge.fml.common.launcher.FMLTweaker, --tweakClass, net.minecraftforge.gradle.tweakers.CoremodTweaker]
[16:36:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:36:02] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:36:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.CoremodTweaker
[16:36:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:36:02] [main/INFO] [FML]: Forge Mod Loader version 14.23.2.2623 for Minecraft 1.12.2 loading
[16:36:02] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_161, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_161
[16:36:02] [main/INFO] [FML]: Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
[16:36:02] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin), we are in deobf and it's a forge core plugin
[16:36:02] [main/INFO] [FML]: Ignoring missing certificate for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin), we are in deobf and it's a forge core plugin
[16:36:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.CoremodTweaker
[16:36:02] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.fml.relauncher.FMLCorePlugin
[16:36:02] [main/INFO] [GradleStart]: Injecting location in coremod net.minecraftforge.classloading.FMLForgePlugin
[16:36:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:36:02] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[16:36:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:02] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
2018-03-02 16:36:04,104 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-03-02 16:36:05,760 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-03-02 16:36:05,766 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:36:11] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[16:36:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:36:11] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:36:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.gradle.tweakers.AccessTransformerTweaker
[16:36:14] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:36:14] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:36:14] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:36:18] [main/INFO]: Setting user: WolfHybrid23
[16:36:46] [main/INFO]: LWJGL Version: 2.9.4
[16:36:54] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 187323312 bytes (178 MB) / 364904448 bytes (348 MB) up to 880279552 bytes (839 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13469 Compatibility Profile Context 21.19.526.1026' Renderer: 'AMD Radeon(TM) R2 Graphics'
[16:36:55] [main/INFO] [FML]: MinecraftForge v14.23.2.2623 Initialized
[16:36:55] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[16:36:55] [main/INFO] [FML]: Replaced 1036 ore ingredients
[16:36:57] [main/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[16:36:57] [main/INFO] [FML]: Searching C:\Users\WolfHybrid23\Desktop\WolfPack\WolfPack\mods for mods
[16:37:03] [Thread-3/INFO] [FML]: Using alternative sync timing : 200 frames of Display.update took 5522616364 nanos
[16:40:20] [main/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[16:40:21] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, wolfpack] at CLIENT
[16:40:21] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, wolfpack] at SERVER
[16:40:25] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Wolf Pack
[16:40:25] [main/WARN]: ResourcePack: ignored non-lowercase namespace: WolfPack/ in C:\Users\WolfHybrid23\Desktop\WolfPack\WolfPack\Output
[16:40:26] [main/INFO] [FML]: Processing ObjectHolder annotations
[16:40:26] [main/INFO] [FML]: Found 1178 ObjectHolder annotations
[16:40:26] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[16:40:26] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[16:40:27] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[16:40:27] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[16:40:27] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@30f19549:
java.lang.NullPointerException: Can't use a null-name for the registry, object null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864) ~[guava-21.0.jar:?]
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:287) ~[ForgeRegistry.class:?]
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281) ~[ForgeRegistry.class:?]
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:114) ~[ForgeRegistry.class:?]
	at com.wolfhybrid23.wolfpack.proxy.CommonProxy.registerBlocks(CommonProxy.java:53) ~[CommonProxy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_CommonProxy_registerBlocks_Register.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143) ~[EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:736) [GameData.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:513) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:421) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
[16:40:27] [main/ERROR] [FML]: Index: 3 Listeners:
[16:40:27] [main/ERROR] [FML]: 0: NORMAL
[16:40:27] [main/ERROR] [FML]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@57bbdcf1
[16:40:27] [main/ERROR] [FML]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@73d0dbbf
[16:40:27] [main/ERROR] [FML]: 3: net.minecraftforge.fml.common.eventhandler.EventBus$1@273ea660
[16:40:27] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Found status: OUTDATED Target: 14.23.2.2624
[16:40:27] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: ---- Minecraft Crash Report ----
// You're mean.

Time: 3/2/18 4:40 PM
Description: Initializing game

java.lang.NullPointerException: Can't use a null-name for the registry, object null.
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:287)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:114)
	at com.wolfhybrid23.wolfpack.proxy.CommonProxy.registerBlocks(CommonProxy.java:53)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_CommonProxy_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:736)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.init(Minecraft.java:513)
	at net.minecraft.client.Minecraft.run(Minecraft.java:421)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:287)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:114)
	at com.wolfhybrid23.wolfpack.proxy.CommonProxy.registerBlocks(CommonProxy.java:53)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_6_CommonProxy_registerBlocks_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:736)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.init(Minecraft.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:421)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 292391168 bytes (278 MB) / 466092032 bytes (444 MB) up to 880279552 bytes (839 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2623 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID        | Version      | Source                           | Signature |
	|:----- |:--------- |:------------ |:-------------------------------- |:--------- |
	| UCH   | minecraft | 1.12.2       | minecraft.jar                    | None      |
	| UCH   | mcp       | 9.42         | minecraft.jar                    | None      |
	| UCH   | FML       | 8.0.99.99    | forgeSrc-1.12.2-14.23.2.2623.jar | None      |
	| UCH   | forge     | 14.23.2.2623 | forgeSrc-1.12.2-14.23.2.2623.jar | None      |
	| UCH   | wolfpack  | 1.0.0        | Output                           | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13469 Compatibility Profile Context 21.19.526.1026' Renderer: 'AMD Radeon(TM) R2 Graphics'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R2 Graphics GL version 4.5.13469 Compatibility Profile Context 21.19.526.1026, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD E2-7110 APU with AMD Radeon R2 Graphics 
[16:40:27] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\WolfHybrid23\Desktop\WolfPack\WolfPack\.\crash-reports\crash-2018-03-02_16.40.27-client.txt
```
From it I was able to determine that the variable from my ModItems class was set to "null", Which is odd because I used the proper constructor for it. Here's my code:
```java
///Testite.java
package com.wolfhybrid23.wolfpack.items;

import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

public class Testite extends Item {
	public Testite() {
		this.setUnlocalizedName("testite");
		this.setRegistryName("testite");
		this.setCreativeTab(CreativeTabs.MATERIALS);
	}
	
	@SideOnly(Side.CLIENT)
	public void initModel()
	{
		ModelLoader.setCustomModelResourceLocation(this, 0, new ModelResourceLocation(getRegistryName(), "inventory"));
	}
}
```
```java
///ModItems.java
package com.wolfhybrid23.wolfpack.items;

import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

public class ModItems {
	
	@ObjectHolder("WolfPack:testite")
	public static Testite ItemTestite;
	
	@ObjectHolder("WolfPack:test_item")
	public static TestItem ItemTestItem;
	
	@SideOnly(Side.CLIENT)
	public static void initModels()
	{
		ItemTestite.initModel();
		ItemTestItem.initModel();
	}
}
```
```java
///CommonProxy.java (The file that's errored)
package com.wolfhybrid23.wolfpack.proxy;

import org.apache.logging.log4j.Level;

import com.wolfhybrid23.wolfpack.WolfPack;
import com.wolfhybrid23.wolfpack.blocks.ModBlocks;
import com.wolfhybrid23.wolfpack.items.ModItems;
import com.wolfhybrid23.wolfpack.tools.ModTools;

import net.minecraft.block.Block;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;

@Mod.EventBusSubscriber
public class CommonProxy {
	public void preInit(FMLPreInitializationEvent e)
	{
		
	}
	public void init(FMLInitializationEvent e)
	{
		WolfPack.logger.log(Level.INFO, "Loading Recipes...");
		GameRegistry.addSmelting(ModBlocks.BlockTestOre, new ItemStack(ModItems.ItemTestite, 1), 10f);
		GameRegistry.addShapedRecipe(new ResourceLocation("testite_pickaxe"), new ResourceLocation("recipes"), new ItemStack(ModTools.ToolTestitePickaxe, 1), new Object[]{"aaa"," b "," b ","a", ModItems.ItemTestite, "b", Items.STICK}); //Error occuring here, It seems that the variable that I constructed the Testite item with has a value of "null".
		GameRegistry.addShapedRecipe(new ResourceLocation("testite_axe_r"), new ResourceLocation("recipes"), new ItemStack(ModTools.ToolTestiteAxe, 1), new Object[]{"aa","ab"," b","a", ModItems.ItemTestite, "b", Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("testite_axe_l"), new ResourceLocation("recipes"), new ItemStack(ModTools.ToolTestiteAxe, 1), new Object[]{"aa","ba","b ","a", ModItems.ItemTestite, "b", Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("testite_shovel"), new ResourceLocation("recipes"), new ItemStack(ModTools.ToolTestiteShovel, 1), new Object[]{"a","b","b","a", ModItems.ItemTestite, "b", Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("testite_hoe_r"), new ResourceLocation("recipes"), new ItemStack(ModTools.ToolTestiteHoe, 1), new Object[]{"aa"," b"," b","a", ModItems.ItemTestite, "b", Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("testite_hoe_l"), new ResourceLocation("recipes"), new ItemStack(ModTools.ToolTestiteHoe, 1), new Object[]{"aa","b ","b ","a", ModItems.ItemTestite, "b", Items.STICK});
		GameRegistry.addShapedRecipe(new ResourceLocation("testite_sword"), new ResourceLocation("recipes"), new ItemStack(ModTools.ToolTestiteSword, 1), new Object[]{"a","a","b","a",ModItems.ItemTestite,"b",Items.STICK});
		WolfPack.logger.log(Level.INFO, "Loading & Initializing Models");
		ModItems.initModels();
		ModTools.initModels();
		ModBlocks.initModels();
	}
	public void postInit(FMLPostInitializationEvent e)
	{
		
	}
	
	@SubscribeEvent
	public static void registerBlocks(RegistryEvent.Register<Block> event)
	{
		event.getRegistry().register(ModBlocks.BlockTestBlock);
		event.getRegistry().register(ModBlocks.BlockTestOre);
	}
	
	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event)
	{
		event.getRegistry().register(ModItems.ItemTestItem);
		event.getRegistry().register(ModItems.ItemTestite);
		event.getRegistry().register(ModTools.ToolTestiteAxe);
		event.getRegistry().register(ModTools.ToolTestiteHoe);
		event.getRegistry().register(ModTools.ToolTestitePickaxe);
		event.getRegistry().register(ModTools.ToolTestiteShovel);
		event.getRegistry().register(ModTools.ToolTestiteSword);
	}
}
```

**Comment by ghost** [comment]
I figured it out, I am so stupid. I changed the modid to be all lowercase but I didn't change the object holders as well. The issue is fixed.
