### ISSUE TITLE
[1.12] EnteringChunk Fired in client proxy when chunk is loaded server side

### ISSUE THREAD

**Issue by cam72cam** [MinecraftForge/MinecraftForge#4793]
I have had a number of users report the following crash for immersive railroading:

```
java.lang.NullPointerException: Exception ticking world
	at paulscode.sound.SoundSystem.setPitch(SoundSystem.java:1009)
	at cam72cam.immersiverailroading.sound.ClientSound.setPitch(ClientSound.java:90)
	at cam72cam.immersiverailroading.proxy.ClientProxy.onEnterChunk(ClientProxy.java:536)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_121_ClientProxy_onEnterChunk_EnteringChunk.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:739)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:534)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:483)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:97)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:309)
	at net.minecraft.world.World.func_175726_f(World.java:304)
	at net.minecraft.world.World.func_175625_s(World.java:2383)
	at cam72cam.immersiverailroading.tile.TileRail.get(TileRail.java:28)
	at cam72cam.immersiverailroading.tile.TileRailBase.getParentTile(TileRailBase.java:290)
	at cam72cam.immersiverailroading.tile.TileRailBase.getRenderRailBed(TileRailBase.java:144)
	at cam72cam.immersiverailroading.tile.TileRailBase.writeUpdateNBT(TileRailBase.java:153)
	at cam72cam.immersiverailroading.tile.SyncdTileEntity.func_189517_E_(SyncdTileEntity.java:54)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:157)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
```

To me, that appears to do:

load some tile on server thread -> world load chunk -> chunk add entity -> fire entity in chunk event

**Comment by diesieben07** [comment]
You are reaching across logical sides, because you do not understand how `@SidedProxy` works.
`@SidedProxy` checks the physical side, the integrated server still uses your client proxy.

**Comment by cam72cam** [comment]
So when the EnteringChunk event is fired in the integrated server on the server thread, it calls ClientProxy code?

**Comment by josephcsible** [comment]
Right. ServerProxy is used only for dedicated servers. ClientProxy is used for all clients and integrated servers. To distinguish the client thread from the server thread, use world.isRemote.
