### ISSUE TITLE
1.12 Invisible Servertimeout

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#4837]
If a client has a too slow connection the server will cut it after about 30 to 60 seconds. But the client get only a IO exception
```
[00:20:55] [Netty Client IO #1/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: connection terminated by host
at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_151]
at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_151]
at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_151]
at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_151]
at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_151]
at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[PooledUnsafeDirectByteBuf.class:4.1.9.Final]
at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[AbstractByteBuf.class:4.1.9.Final]
at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[NioSocketChannel.class:4.1.9.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [AbstractNioByteChannel$NioByteUnsafe.class:4.1.9.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [NioEventLoop.class:4.1.9.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [NioEventLoop.class:4.1.9.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [NioEventLoop.class:4.1.9.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [NioEventLoop.class:4.1.9.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```
Even when using -Dfml.readTimeout=1200 the timeout gets not longer. I noticed in `net.minecraft.network.Networkanager#createNetworkManagerAndConnect` L:380, `p_initChannel_1_.pipeline().addLast("timeout", new ReadTimeoutHandler(30)).addLast("splitter", new NettyVarint21FrameDecoder()).addLast("decoder", new NettyPacketDecoder(EnumPacketDirection.CLIENTBOUND)).addLast("prepender", new NettyVarint21FrameEncoder()).addLast("encoder", new NettyPacketEncoder(EnumPacketDirection.SERVERBOUND)).addLast("packet_handler", networkmanager);`, is it a hard timeut to 30 seconds ? Maybe changing this to READ_TIMEOUT will help ?

**Comment by LexManos** [comment]
Use the forum to determine the cause of the slowness before coming back. Most likely there is another cause.
