### ISSUE TITLE
Add a more descriptive error message for pack.mcmeta errors.

### ISSUE THREAD

**Issue by trentv4** [MinecraftForge/MinecraftForge#4847]
When editing a mod `pack.mcmeta` , I made an error and left a trailing comma (which is usually invalid syntax in all json files)

```json
{
    "pack": {
        "description": "examplemod resources",
        "pack_format": 3,
    }
}
```
This errors out as it should. However, the error report is less than sufficient for identifying what is wrong. All you get is `Caught exception from null (modid)`. I suggest that there should be a more descriptive error message to tell you where the error is, or failing that, the fact that it is a problem in `pack.mcmeta`.
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 4/3/18 2:31 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from null (musicalenergy)
Caused by: java.lang.RuntimeException
	at net.minecraftforge.fml.common.LoadController.buildModObjectList(LoadController.java:314)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:250)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.init(Minecraft.java:513)
	at net.minecraft.client.Minecraft.run(Minecraft.java:421)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)
```

**Comment by Exidex** [comment]
It doesn't really error out. I've made same mistake with comma but I got this in log 
```
[main/ERROR] [FML]: Could not dispatch event: public void net.minecraftforge.fml.common.LoadController.buildModList(net.minecraftforge.fml.common.event.FMLLoadEvent) to java.lang.RuntimeException: An unexpected exception occurred constructing the custom resource pack for GregTech Community Edition
```
and crashed with unsatisfied dependency exception because I have hard dependency on another mod which didn't load because of parse exception

Here's code that handles exception and logs error
https://github.com/MinecraftForge/MinecraftForge/blob/bad83a303e6770d484aad0b0d891549dc273cf05/src/main/java/net/minecraftforge/fml/common/LoadController.java#L81-L84

**Comment by mezz** [comment]
I'll take a look at this, there is a larger general issue with catching errors during startup that I want to get more into.
