### ISSUE TITLE
Exception reading DIM1/level.dat

### ISSUE THREAD

**Issue by Aersaud** [MinecraftForge/MinecraftForge#4876]
```
[02:19:23] [Server thread/ERROR]: Exception reading ./TKM-MadCraft/DIM1/level.dat
java.io.EOFException: null
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_162]
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_162]
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_162]
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_162]
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_162]
        at net.minecraft.nbt.CompressedStreamTools.func_74796_a(CompressedStreamTools.java:26) ~[gi.class:?]
        at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:117) [bfc.class:?]
        at net.minecraft.world.storage.SaveHandler.redirect$onLoadWorldInfo$bbi000(SaveHandler.java:1068) [bfb.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:122) [bfb.class:?]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:706) [WorldManager.class:1.12.2-2611-7.1.0-BETA-3019]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3530) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

Started getting this recently on my latest.log. Just wanted to report and possibly find a fix.

Using 
```
forge-1.12.2-14.23.2.2611-universal.jar  
```

Mods installed:

```
BetterFps-1.4.8.jar                            jei_1.12.2-4.8.5.159.jar     Nucleus-1.3.6-S7.0-MC1.12.2-plugin.jar
CodeChickenLib-1.12.2-3.1.6.339-universal.jar  journeymap-1.12.2-5.5.2.jar  spongeforge-1.12.2-2611-7.1.0-BETA-3019.jar
foamfix-0.9.7-1.12.2-law.jar                   LuckPerms-Sponge-4.1.63.jar  Wearable-Backpacks-Mod-1.12.2.jar
griefprevention-1.12.2-4.3.0.574.jar           Not-Enough-Items-1.12.2.jar  worldedit-forge-mc1.12-6.1.8-dist.jar
```

**Comment by loordgek** [comment]
report to https://github.com/SpongePowered/SpongeForge

**Comment by Aersaud** [comment]
@loordgek Just did thanks. --> https://github.com/SpongePowered/SpongeForge/issues/2102
