### ISSUE TITLE
rename book and quill

### ISSUE THREAD

**Issue by seema84** [MinecraftForge/MinecraftForge#4980]
Forge Version: 1.12.2 - 14.23.2.2654

if i rename a book and quill and give a other player this book i get (on a spigot server)

Couldn't handle book info
java.io.IOException: Invalid book tag!
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2229) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-2086bb0-d0a3620]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

without forge i can't rename a book and quill

**Comment by LexManos** [comment]
There should be a error directly proceeding that one.
However, we do not support coremods/server mods such as Spigot. As they have to be compatible with Forge. 
Let me know if you have issues with a Forge server.
