### ISSUE TITLE
Unable to determine registrant mod

### ISSUE THREAD

**Issue by lsiem** [MinecraftForge/MinecraftForge#4992]
Stacktrace
`java.lang.Throwable: null
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:75) ~[EventBus.class:?]
	at de.lasse.notence.feature.Feature.onEnable(Feature.java:85) ~[Feature.class:?]
	at de.lasse.notence.feature.Feature.toggle(Feature.java:102) ~[Feature.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_172]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_172]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_172]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_172]
	at de.lasse.notence.NoTence.onIngameUpdate(NoTence.java:61) [NoTence.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1_NoTence_onIngameUpdate_PlayerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.updateSize(EntityPlayer.java:416) [EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:326) [EntityPlayer.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230) [EntityPlayerSP.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2168) [World.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2127) [World.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1928) [World.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1972) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:441) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
[13:49:58] [main/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@65a6c44e:
java.lang.NullPointerException: null
	at de.lasse.notence.feature.Feature.onEnable(Feature.java:86) ~[Feature.class:?]
	at de.lasse.notence.feature.Feature.toggle(Feature.java:102) ~[Feature.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_172]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_172]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_172]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_172]
	at de.lasse.notence.NoTence.onIngameUpdate(NoTence.java:61) ~[NoTence.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1_NoTence_onIngameUpdate_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.updateSize(EntityPlayer.java:416) [EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:326) [EntityPlayer.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230) [EntityPlayerSP.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2168) [World.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2127) [World.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1928) [World.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1972) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:441) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
[13:49:58] [main/ERROR] [FML]: Index: 1 Listeners:
[13:49:58] [main/ERROR] [FML]: 0: NORMAL
[13:49:58] [main/ERROR] [FML]: 1: ASM: de.lasse.notence.NoTence@61c0fb12 onIngameUpdate(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[13:49:58] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[13:49:58] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[13:49:58] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[13:49:58] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'Test'/overworld
[13:49:58] [Server thread/INFO] [FML]: Unloading dimension 0
[13:49:58] [Server thread/INFO] [FML]: Applying holder lookups
[13:49:58] [Server thread/INFO] [FML]: Holder lookups applied
[13:49:59] [main/FATAL] [net.minecraft.client.Minecraft]: Reported exception thrown!
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.world.World.updateEntities(World.java:1942) ~[World.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1972) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:441) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
Caused by: java.lang.NullPointerException
	at de.lasse.notence.feature.Feature.onEnable(Feature.java:86) ~[Feature.class:?]
	at de.lasse.notence.feature.Feature.toggle(Feature.java:102) ~[Feature.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_172]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_172]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_172]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_172]
	at de.lasse.notence.NoTence.onIngameUpdate(NoTence.java:61) ~[NoTence.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1_NoTence_onIngameUpdate_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.updateSize(EntityPlayer.java:416) ~[EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:326) ~[EntityPlayer.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230) ~[EntityPlayerSP.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2168) ~[World.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2127) ~[World.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1928) ~[World.class:?]
	... 16 more
`
[13:49:59] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: ---- Minecraft Crash Report ----
// Sorry :(

Time: 6/23/18 1:49 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at de.lasse.notence.feature.Feature.onEnable(Feature.java:86)
	at de.lasse.notence.feature.Feature.toggle(Feature.java:102)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at de.lasse.notence.NoTence.onIngameUpdate(NoTence.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1_NoTence_onIngameUpdate_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369)
	at net.minecraft.entity.player.EntityPlayer.updateSize(EntityPlayer.java:416)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:326)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2168)
	at net.minecraft.world.World.updateEntity(World.java:2127)
	at net.minecraft.world.World.updateEntities(World.java:1928)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1972)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186)
	at net.minecraft.client.Minecraft.run(Minecraft.java:441)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.lasse.notence.feature.Feature.onEnable(Feature.java:86)
	at de.lasse.notence.feature.Feature.toggle(Feature.java:102)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at de.lasse.notence.NoTence.onIngameUpdate(NoTence.java:61)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1_NoTence_onIngameUpdate_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369)
	at net.minecraft.entity.player.EntityPlayer.updateSize(EntityPlayer.java:416)
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:326)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2168)
	at net.minecraft.world.World.updateEntity(World.java:2127)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 0
	Entity Name: Player483
	Entity's Exact location: -2477.76, 4.00, 837.99
	Entity's Block location: World: (-2478,4,837), Chunk: (at 2,0,5 in -155,52; contains blocks -2480,0,832 to -2465,255,847), Region: (-5,1; contains chunks -160,32 to -129,63, blocks -2560,0,512 to -2049,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1928)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Player483'/0, l='MpServer', x=-2477.76, y=4.00, z=837.99]]
	Chunk stats: MultiplayerChunkCache: 575, 575
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-2567,4,813), Chunk: (at 9,0,13 in -161,50; contains blocks -2576,0,800 to -2561,255,815), Region: (-6,1; contains chunks -192,32 to -161,63, blocks -3072,0,512 to -2561,255,1023)
	Level time: 5343 game time, 5343 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Player483'/0, l='MpServer', x=-2477.76, y=4.00, z=837.99]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:461)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2886)
	at net.minecraft.client.Minecraft.run(Minecraft.java:462)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.17.2-1-ARCH
	Java Version: 1.8.0_172, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 367433688 bytes (350 MB) / 853016576 bytes (813 MB) up to 1834483712 bytes (1749 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2708 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                           | Signature |
	|:--------- |:--------- |:------------ |:-------------------------------- |:--------- |
	| UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                    | None      |
	| UCHIJAAAA | mcp       | 9.42         | minecraft.jar                    | None      |
	| UCHIJAAAA | FML       | 8.0.99.99    | forgeSrc-1.12.2-14.23.4.2708.jar | None      |
	| UCHIJAAAA | forge     | 14.23.4.2708 | forgeSrc-1.12.2-14.23.4.2708.jar | None      |

	Loaded coremods (and transformers): 
NoTenceLoader (unknown)
  
	GL info: ' Vendor: 'Intel Open Source Technology Center' Version: '3.0 Mesa 18.1.2' Renderer: 'Mesa DRI Intel(R) Haswell Desktop '
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: Mesa DRI Intel(R) Haswell Desktop  GL version 3.0 Mesa 18.1.2, Intel Open Source Technology Center
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
[13:49:59] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:629]: #@!@# Game crashed! Crash report saved to: #@!@# /home/lasse/Documents/Projects/NoTence/run/./crash-reports/crash-2018-06-23_13.49.59-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 255

### I can provide code if needed.
Overall I'm registering an object in it's parent class to the forge eventbus.

**Comment by HenryLoenwind** [comment]
Really?

YOUR code is throwing a NullPointerException...

```
java.lang.NullPointerException:
at de.lasse.notence.feature.Feature.onEnable(Feature.java:86)
at de.lasse.notence.feature.Feature.toggle(Feature.java:102)
```

**Comment by Niko-sk2x** [comment]
And there is no mod loaded. Which makes it look like what he did is use events from within a coremod (because there clearly is one)

**Comment by lsiem** [comment]
I'am using a coremod.
I'm wondering why the devs decided to descripe an exception as 'impossible' if it's possible.
That's why i decided to make an issue because I thought "Wait... an exception was thrown which says it is impossible..."

**Comment by lsiem** [comment]
And sorry about my NPE mistake.
I was confused about the exception.

**Comment by lsiem** [comment]
I have to add another important thing.
`[14:56:49] [main/ERROR] [FML]: Unable to determine registrant mod for de.lasse.notence.feature.impl.Sprint@20e87aa3. This is a critical error and should be impossible
java.lang.Throwable: null
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:75) ~[EventBus.class:?]
	at de.lasse.notence.feature.Feature.onEnable(Feature.java:85) ~[Feature.class:?]
	at de.lasse.notence.feature.Feature.toggle(Feature.java:102) ~[Feature.class:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_172]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) [?:1.8.0_172]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) [?:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) [?:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_172]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) [?:1.8.0_172]
	at de.lasse.notence.NoTence.onIngameUpdate(NoTence.java:66) [NoTence.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_0_NoTence_onIngameUpdate_PlayerTickEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:369) [FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.updateSize(EntityPlayer.java:416) [EntityPlayer.class:?]
	at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:326) [EntityPlayer.class:?]
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230) [EntityPlayerSP.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2168) [World.class:?]
	at net.minecraft.world.World.updateEntity(World.java:2127) [World.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1928) [World.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1972) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1186) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:441) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:25) [start/:?]
[14:56:49] [main/INFO] [STDOUT]: [de.lasse.notence.feature.Feature:onEnable:87]: Sprint was enabled!`
I still get this exception after fixing the NPE.
Everything seems to work fine but every time onEnable method is called this exception appears.

**Comment by Niko-sk2x** [comment]
First, this is likely not the right place for this discussion and this issue will be closed soon.

You should not be using a coremod. And ESPECIALLY do things like register event listeners from a coremod. Make a normal mod instead. A lot of forge internals rely on there being an actual mod. Looking at the first log, you don't even have a class transformer. Remove that coremod.

**Comment by lsiem** [comment]
I have my reasons to have this coremod.
The whole point is that (in my opinion) `This is a critical error and should be impossible` as an exception message is a bit weird since it is possible to trigger the exception.
Consider removing this sentence because it might just confuse others.

**Comment by srs-bsns** [comment]
@IntenceYT
You are failing to understand the situation and the context of the exception message.
Usage of the Forge event bus requires that you have a registered Forge mod, which you do not. The error is saying that it `should be impossible` because it is expecting a mod container to be present, in which case it should be `impossible` for it to be `null`. The exception is thrown because you are doing something improperly (trying to register a listener from a coremod), not because there is some obscure bug in Forge.

This issue is invalid.

**Comment by LexManos** [comment]
Do Not make coremods. "I'm complaining that your error says it should be impossible, but I am hacking your shit to pieces to make it possible, stop yelling at me that i'm ding it wrong!"
