### ISSUE TITLE
Stalls from race in AnvilChunkLoader.writeNextIO (vanilla?)

### ISSUE THREAD

**Issue by Player3324** [MinecraftForge/MinecraftForge#5052]
Despite its apparent concurrency-safe design, AnvilChunkLoader.writeNextIO can not be safely executed from more than one thread at once safely. chunksToSave may become empty between the emptiness check in the first line and the chunksToSave.keySet().iterator().next() invocation below in this case.

Iterator.next() will throw NoSuchElementException, File IO Thread dies from it, the server thread will be unable to save anything and stalls at ThreadedFileIOBase.waitForFinish(),

The problem has been observed sporadically, it happens if MC's own save happens to collide with e.g. "/save-all flush", but presumably in a more pronounced fashion by backup mods doing flushes.

There are two obvious ways to fix this:
1. Make AnvilChunkLoader.writeNextIO() synchronized.
2. In addition to checking chunksToSave.isEmpty, fetch the first element catching NoSuchElementException and check that chunksBeingSaved.add yields true. Only then assume that the obtained position is to be saved, otherwise retry until chunksToSave.isEmpty holds.

Using method 1 has no real downsides and is better. Doing something else would be only warranted if there was more than one I/O thread. With writeNextIO only covering a single chunk, a concurrent save-all flush from the server thread can still achieve reasonable throughput while the I/O thread sleeps.

Stall:
```
"Server thread" #22 prio=5
TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.world.storage.ThreadedFileIOBase.waitForFinish(SourceFile:69)
	at net.minecraft.world.chunk.storage.AnvilSaveHandler.flush(AnvilSaveHandler.java:47)
	at net.minecraft.world.WorldServer.flush(WorldServer.java:1230)
	at net.minecraft.world.WorldServerMulti.flush(WorldServerMulti.java:87)
	at net.minecraftforge.common.DimensionManager.unloadWorlds(DimensionManager.java:404)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:788)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)
```

File IO Thread crash:
```
java.util.NoSuchElementException
     at java.util.concurrent.ConcurrentHashMap$KeyIterator.next(ConcurrentHashMap.java:3416)
     at net.minecraft.world.chunk.storage.AnvilChunkLoader.writeNextIO(AnvilChunkLoader.java:207)
     at net.minecraft.world.storage.ThreadedFileIOBase.processQueue(SourceFile:37)
     at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
     at java.lang.Thread.run(Thread.java:748)
```

**Comment by bs2609** [comment]
https://bugs.mojang.com/browse/MC-106551 ?

**Comment by Player3324** [comment]
Looks like the same issue, two years old at least...
