### ISSUE TITLE
Forge build 2758 doesn't work due to classloader exclusion change

### ISSUE THREAD

**Issue by bs2609** [MinecraftForge/MinecraftForge#5114]
The change in c6abcf5b84cbce6ad425475b5cdc0b9e4f886578 breaks Forge - without a classloader exception for `org.apache.commons.`, the game fails to load with the following fatal errors ([gist](https://gist.github.com/bs2609/0f47286d8947292dc524a43a961ec7e3)).

**Comment by LexManos** [comment]
Fixed

**Comment by Tsoccerguy3** [comment]
This fix causes Liteloader to now crash

[12:05:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:05:57] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[12:05:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[12:05:57] [main/INFO] [FML]: Forge Mod Loader version 14.23.4.2760 for Minecraft 1.12.2 loading
[12:05:57] [main/INFO] [FML]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_181, running on Linux:amd64:4.15.0-33-generic, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[12:05:57] [main/INFO] [FML]: Searching /home/wds/.minecraft/mods for mods
[12:05:57] [main/INFO] [FML]: Searching /home/wds/.minecraft/mods/1.12.2 for mods
[12:05:57] [main/INFO] [FML]: Loading tweaker com.mumfrey.liteloader.launch.LiteLoaderTweaker from liteloader-1.12.2-SNAPSHOT-release.jar
[12:05:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:05:57] [main/INFO] [LaunchWrapper]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker
[12:05:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:05:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:05:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[12:05:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:05:58] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[12:05:58] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[12:05:58] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[12:05:58] [main/INFO] [LaunchWrapper]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker
[12:05:58] [main/INFO] [LiteLoader]: Bootstrapping LiteLoader 1.12.2
[12:05:58] [main/INFO] [LiteLoader]: Registering API provider class com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient
[12:05:58] [main/INFO] [LiteLoader]: Spawning API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' ...
[12:05:58] [main/INFO] [LiteLoader]: API provider class 'com.mumfrey.liteloader.client.api.LiteLoaderCoreAPIClient' provides API 'liteloader'
[12:05:58] [main/INFO] [LiteLoader]: Initialising API 'liteloader' ...
[12:05:58] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/home/wds/.minecraft/mods/1.12.2/liteloader-1.12.2-SNAPSHOT-release.jar Service=LaunchWrapper Env=CLIENT
[12:05:58] [main/INFO] [LiteLoader]: LiteLoader begin PREINIT...
[12:05:58] [main/INFO] [LiteLoader]: Initialising Loader properties...
[12:05:58] [main/INFO] [LiteLoader]: Setting up logger...
[12:05:58] [main/INFO] [LiteLoader]: LiteLoader 1.12.2 starting up...
[12:05:58] [main/INFO] [LiteLoader]: Active Pack: 1.12.2-SNAPSHOT-r4CC2BB0-b4-4
[12:05:58] [main/INFO] [LiteLoader]: Java reports OS="linux"
[12:05:58] [main/INFO] [LiteLoader]: Adding supported mod class prefix 'LiteMod'
[12:05:58] [main/INFO] [LiteLoader]: Enumerating class path...
[12:05:58] [main/INFO] [LiteLoader]: Class path separator=":"
[12:05:58] [main/INFO] [LiteLoader]: Class path entries=(
   classpathEntry=/home/wds/.minecraft/libraries/net/minecraftforge/forge/1.12.2-14.23.4.2760/forge-1.12.2-14.23.4.2760.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
   classpathEntry=/home/wds/.minecraft/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
   classpathEntry=/home/wds/.minecraft/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
   classpathEntry=/home/wds/.minecraft/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/google/guava/guava/21.0/guava-21.0.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
   classpathEntry=/home/wds/.minecraft/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
   classpathEntry=/home/wds/.minecraft/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
   classpathEntry=/home/wds/.minecraft/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
   classpathEntry=/home/wds/.minecraft/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
   classpathEntry=/home/wds/.minecraft/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
   classpathEntry=/home/wds/.minecraft/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
   classpathEntry=/home/wds/.minecraft/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
   classpathEntry=/home/wds/.minecraft/versions/1.12.2/1.12.2.jar
)
[12:05:59] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleClassPath: [<Java Class Path>]
[12:05:59] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleFolder: [/home/wds/.minecraft/mods]
[12:05:59] [main/INFO] [LiteLoader]: Registering discovery module EnumeratorModuleFolder: [/home/wds/.minecraft/mods/1.12.2]
[12:05:59] [main/INFO] [LiteLoader]: Registering enumerator plugin DefaultEnumeratorPlugin: [com.mumfrey.liteloader.core.api.DefaultEnumeratorPlugin@1eb6e1c]
[12:05:59] [main/INFO] [LiteLoader]: Discovering valid mod files in folder /home/wds/.minecraft/mods
[12:05:59] [main/INFO] [LiteLoader]: Discovering valid mod files in folder /home/wds/.minecraft/mods/1.12.2
[12:05:59] [main/INFO] [LiteLoader]: Inspecting jar metadata in 'liteloader-1.12.2-SNAPSHOT-release.jar'
[12:05:59] [main/INFO] [LiteLoader]: Baking listener list for EnumerationObserver with 1 listeners
[12:05:59] [main/INFO] [LiteLoader]: Discovering tweaks on class path...
[12:05:59] [main/INFO] [LiteLoader]: Registering discovered mod files in folder /home/wds/.minecraft/mods
[12:05:59] [main/INFO] [LiteLoader]: Registering discovered mod files in folder /home/wds/.minecraft/mods/1.12.2
[12:05:59] [main/INFO] [LiteLoader]: Mod file 'liteloader-1.12.2-SNAPSHOT-release.jar' provides tweakClass 'com.mumfrey.liteloader.launch.LiteLoaderTweaker', adding to Launch queue with priority 1000
[12:05:59] [main/INFO] [LiteLoader]: Initialising LiteLoader Mixins
[12:05:59] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[12:05:59] [main/INFO] [LiteLoader]: LiteLoader PREINIT complete
[12:05:59] [main/INFO] [LiteLoader]: Injecting required class transformer 'com.mumfrey.liteloader.transformers.event.EventProxyTransformer'
[12:05:59] [main/ERROR] [mixin]: Critical problem: mixins.liteloader.client.preinit.json:MixinClientBrandRetriever target net.minecraft.client.ClientBrandRetriever was already transformed.
[12:05:59] [main/INFO] [LiteLoader]: Injecting required class transformer 'com.mumfrey.liteloader.launch.LiteLoaderTransformer'
[12:05:59] [main/INFO] [LiteLoader]: Injecting required class transformer 'com.mumfrey.liteloader.client.transformers.CrashReportTransformer'
[12:05:59] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.EventTransformer'
[12:05:59] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[12:05:59] [main/INFO] [LiteLoader]: Queuing required class transformer 'com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer'
[12:05:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[12:05:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:05:59] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[12:05:59] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[12:05:59] [main/INFO] [LaunchWrapper]: Loading tweak class name com.mumfrey.liteloader.launch.LiteLoaderTweaker$PreInitTweaker
[12:05:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[12:05:59] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[12:05:59] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@743c6ce4
[12:05:59] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[12:05:59] [main/INFO] [LaunchWrapper]: Calling tweak class com.mumfrey.liteloader.launch.LiteLoaderTweaker$PreInitTweaker
[12:05:59] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker has already been visited -- skipping
[12:05:59] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[12:05:59] [main/INFO] [LiteLoader]: Injecting downstream transformers
[12:05:59] [main/INFO] [LiteLoader]: Injecting additional class transformer class 'com.mumfrey.liteloader.transformers.event.EventTransformer'
[12:05:59] [main/INFO] [LiteLoader]: Injecting additional class transformer class 'com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer'
[12:05:59] [main/INFO] [LiteLoader]: Injecting additional class transformer class 'com.mumfrey.liteloader.transformers.event.json.ModEventInjectionTransformer'
[12:05:59] [main/INFO] [LiteLoader]: FML detected, switching to searge mappings
[12:06:00] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: joptsimple.MultipleArgumentsForOptionException: Found multiple arguments for option version, but you asked for only one
	at joptsimple.OptionSet.valueOf(OptionSet.java:179) ~[OptionSet.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:86) ~[Main.class:?]
	... 6 more
[12:06:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[12:06:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[12:06:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[12:06:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[12:06:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[12:06:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[12:06:00] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
