### ISSUE TITLE
IllegalArgumentException in VillagerRegistry.VillagerProfession.getRandomCareer

### ISSUE THREAD

**Issue by NightKosh** [MinecraftForge/MinecraftForge#5118]
Hello. 
I encountered with a crash of my mod, which happened inside forge "VillagerRegistry.VillagerProfession" class in "getRandomCareer" method. As I find out such problem occurs in case of no careers for villager profession. 
I'm working with villagers from other mods, so I have no ways to know correct amount of its careers. Furthermore there aren't any way to know it from "VillagerProfession" class so I can't fix it on my side.

Here is a crash log:

```
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.minecraftforge.fml.common.registry.VillagerRegistry$VillagerProfession.getRandomCareer(VillagerRegistry.java:234)
    at nightkosh.gravestone_extended.item.corpse.VillagerCorpseHelper.getDefaultCorpses(VillagerCorpseHelper.java:62)
    at nightkosh.gravestone_extended.item.corpse.CorpseHelper.getDefaultCorpse(CorpseHelper.java:127)
    at nightkosh.gravestone_extended.block.BlockCorpse.getSubBlocks(BlockCorpse.java:75)
    at net.minecraft.item.ItemBlock.getSubItems(ItemBlock.java:149)
    at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:586)
    at net.minecraft.client.Minecraft.init(Minecraft.java:528)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3929)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by LexManos** [comment]
You'd have to report it to whomever is creating a incorrect profession, professions must have atleast one career to be of any use.
Also, you *probably* don't want a RANDOM career when creating your corpses, you probably want ALL careers, may be worth adding a getCareerCount to profession...
Anyways use the forums for basic things like this until you get a game plan sorted.
