### ISSUE TITLE
Wayland issue on linux

### ISSUE THREAD

**Issue by codedcosmos** [MinecraftForge/MinecraftForge#5204]
This is a relatively minor issue, that will effect very few users. So no rush, but just wanted to let you guys know.

The problem is the java installer for linux won't work on wayland. Simple workaround for now is running xorg.

```

java.net.preferIPv4Stack=true
No protocol specified
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.installer.Java6Gate.main(Java6Gate.java:48)
Caused by: java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:126)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:161)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:54)
	... 5 more
```

**Comment by LexManos** [comment]
This seems to, from first glance be a java/driver issues. As getSystemLookAndFeelClassName is a fairly bog standard api. However, this isn't a majorly inportant thing, a work around pr may be considered.

**Comment by simon816** [comment]
Don't see how this issue would be unique to forge. Have you tried launching any other java swing applications?

**Comment by williewillus** [comment]
this could be a variety of issues, since the dependency chain is swing -> gtk 2/3 -> DE/wm/wayland -> graphics drivers

**Comment by codedcosmos** [comment]
@simon816 I haven't tried any other swing applications with this setup from memory.

**Comment by liketechnik** [comment]
The problem here is missing wayland support in the java ui libraries. One solution would be to use XWayland on top of you wayland compositor, but I don't think it's something forge is able to handle correctly, because you would need an extra library to support wayland.

**Comment by Alpvax** [comment]
Seems to me that this is a Java issue, not a forge issue. We could maybe document that Java UI libs are required, but it's not on us to fix this.

**Comment by codedcosmos** [comment]
Lack of support for wayland from java.awt.*

Not a forge issue. 

To workaround, just run xorg for the installation or install XWayland for your distro.
