### ISSUE TITLE
Remapping issue

### ISSUE THREAD

**Issue by Raycoms** [MinecraftForge/MinecraftForge#5268]
I've been trying to get support on the discord for a few days already now.
I have two mods, minecolonies and structurize.

https://github.com/ldtteam/minecolonies
https://github.com/ldtteam/Structurize

I recently moved all decorative blocks to structurize to declutter minecolonies.
Now, I added an event in minecolonies (I tried to add this in structurize as well)
To remap the old block ids from minecolonies to make sure that the blocks don't vanish from the world.

```    private static <T extends IForgeRegistryEntry<T>> int onRegistryMissingMappings(final RegistryEvent.MissingMappings<T> event)
    {
        return event.getMappings().stream().mapToInt(missingMapping -> {
            if (missingMapping.key.getNamespace().equals(Constants.MOD_ID))
            {
                final String path = missingMapping.key.getPath();
                final ResourceLocation remappedTargetId = new ResourceLocation("structurize".toLowerCase(), path);
                @Nullable final T target = missingMapping.registry.getValue(remappedTargetId);
                if (target != null && target != Blocks.AIR && target != Items.AIR)
                {
                    missingMapping.remap(target);
                    return 1;
                }
            }  
            return 0;
        }).sum();
    }
```

Now, this gets called correctly for all blocks and missingMapping receives the right structurize blocks.

But, all blocks vanish from the world nonetheless, because this here is thrown:

> [10:24:06] [Server thread/WARN] [FML]: ****************************************
[10:24:06] [Server thread/WARN] [FML]: Registered object did not get ID it asked for. Name: structurize:blocktimberframe_birch_gateframed Type: class net.minecraft.item.Item Expected: 4194 Got: 4273
[10:24:06] [Server thread/WARN] [FML]: ****************************************
[10:24:06] [Server thread/WARN] [FML]: * Registry Item: The object net.minecraft.item.ItemBlock@6d677422 has been registered twice for the same name structurize:blockshingle_birch.
[10:24:06] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:308)
[10:24:06] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:289)
[10:24:06] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.ForgeRegistry.processMissingEvent(ForgeRegistry.java:935)
[10:24:06] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.GameData.processMissing(GameData.java:743)
[10:24:06] [Server thread/WARN] [FML]: *  at net.minecraftforge.registries.GameData.lambda$injectSnapshot$20(GameData.java:627)
[10:24:06] [Server thread/WARN] [FML]: *  at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)...

**Comment by Raycoms** [comment]
Debugging this it seems like the Ids for the structurize blocks get added to the world before the remap event is executed which leads to this issue. Shouldn't this be fired only afterwards?

**Comment by Raycoms** [comment]
Some additional info.
Remapping from the minecraft domain to the mod domain works fine, remapping from the mod domain to another mod domain is not working fine.
