### ISSUE TITLE
[forge-1.13-24.0.81-1.13-pre] MissingRequiredOptionsException

### ISSUE THREAD

**Issue by HatTrkPatrk** [MinecraftForge/MinecraftForge#5360]
Attempting to launch this beta version as a server:

> java -Xmx2048M -jar forge-1.13-24.0.81-1.13-pre.jar

However, it fails to run

```
2019-01-15 16:20:25,360 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2019-01-15 16:20:25,420 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[16:20:25] [main/INFO]: ModLauncher starting: java version 1.8.0_191
[16:20:25] [main/INFO]: Found launch services [fmlclient,fmlserver,fmldevclient,fmldevserver,minecraft,testharness]
[16:20:25] [main/INFO]: Found transformer services : [fml]
[16:20:25] [main/INFO]: Found naming services []
[16:20:25] [main/INFO]: Found launch plugins: [eventbus,object_holder_definalize,runtime_enum_extender,accesstransformer,capability_inject_definalize,runtimedistcleaner]
[16:20:25] [main/INFO]: ModLauncher running: args [--launchTarget, fmlserver, --gameDir, .]
Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [fml.forgeVersion, fml.mcVersion, fml.mcpVersion]
        at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
        at joptsimple.OptionParser.parse(OptionParser.java:400)
        at cpw.mods.modlauncher.ArgumentHandler.processArguments(ArgumentHandler.java:37)
        at cpw.mods.modlauncher.TransformationServicesHandler.processArguments(TransformationServicesHandler.java:51)
        at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:38)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:53)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:28)
```

I see the exception (MissingRequiredOptionsException) however this was an attempt to run it without any mods present anyway (just attempting to run it on its own).

**Comment by LexManos** [comment]
Has been fixed a few days ago.

**Comment by AleehOnline** [comment]
2019-02-12 23:11:17,133 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2019-02-12 23:11:17,368 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[23:11:17] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:11:17] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:11:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:11:17] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2811 for Minecraft 1.12.2 loading
[23:11:17] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 8.1:amd64:6.3, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_51
[23:11:18] [main/INFO] [FML]: Searching C:\Users\Aleh\AppData\Roaming\.minecraft\mods for mods
[23:11:18] [main/INFO] [FML]: Searching C:\Users\Aleh\AppData\Roaming\.minecraft\mods\1.12.2 for mods
[23:11:18] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in astralsorcery-1.12.2-1.10.10.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
2019-02-12 23:11:18,436 main ERROR Error processing element Queue ([Appenders: null]): CLASS_NOT_FOUND
2019-02-12 23:11:18,452 main ERROR Unable to locate appender "ServerGuiConsole" for logger config "root"
[23:11:18] [main/WARN] [FML]: The coremod hellfirepvp.astralsorcery.core.AstralCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:11:18] [main/INFO] [Astral Core]: [AstralCore] Initialized.
[23:11:18] [main/INFO] [FML]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[23:11:18] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.2.18.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:11:18] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:11:18] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[23:11:18] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in EnderCore-1.12.2-0.5.43.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:11:18] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.7.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:11:18] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:11:18] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[23:11:18] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_D2.jar
[23:11:18] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E3.jar
[23:11:18] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.5-145.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:11:18] [main/WARN] [FML]: The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:11:18] [main/WARN] [FML]: The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[23:11:18] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:11:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:11:18] [main/INFO] [LaunchWrapper]: Loading tweak class name codechicken.asm.internal.Tweaker
[23:11:18] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[23:11:18] [main/WARN] [LaunchWrapper]: Tweak class name optifine.OptiFineForgeTweaker has already been visited -- skipping
[23:11:18] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:11:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:11:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:11:18] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[23:11:18] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[23:11:18] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[23:11:18] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[23:11:18] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\Aleh\AppData\Roaming\.minecraft\mods\OptiFine_1.12.2_HD_U_D2.jar
[23:11:18] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:11:22] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:11:22] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[23:11:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:11:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:11:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:11:22] [main/INFO] [LaunchWrapper]: Calling tweak class codechicken.asm.internal.Tweaker
[23:11:22] [main/INFO] [STDOUT]: [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
[23:11:22] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[23:11:22] [main/INFO] [Astral Core]: [AstralTransformer] Loading patches...
[23:11:23] [main/INFO] [Astral Core]: [AstralTransformer] Initialized! Loaded 15 class patches!
[23:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[23:11:23] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:11:23] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[23:11:23] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[23:11:23] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[23:11:24] [main/INFO] [Astral Core]: [AstralTransformer] Transforming amu : net.minecraft.world.World with 2 patches!
[23:11:24] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHSUNBRIGHTNESSWORLDCLIENT
[23:11:24] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHSUNBRIGHTNESSWORLDCOMMON
[23:11:24] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.entity.player.EntityPlayer finished, added func_184613_cA() overriding EntityLivingBase
[23:11:24] [main/INFO] [Astral Core]: [AstralTransformer] Transforming vp : net.minecraft.entity.EntityLivingBase with 4 patches!
[23:11:24] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHAPPLYPOTIONEFFECTEVENT
[23:11:24] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHENTITYLIVINGBASEWATERSLOWDOWN
[23:11:24] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHSETPLAYERATTRIBUTE
[23:11:24] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHUPDATEELYTRA
[23:11:25] [main/INFO] [FML]: [Quark ASM] Transforming WorldServer
[23:11:25] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [areAllPlayersAsleep, func_73056_e, g] Descriptor ()Z / ()Z)
[23:11:25] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:25] [main/INFO] [FML]: [Quark ASM] Located patch target node L0
[23:11:25] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:26] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:229]: Transforming Class [net.minecraftforge.client.ForgeHooksClient], Method [getDamageModel]
[23:11:26] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:241]: Transforming net.minecraftforge.client.ForgeHooksClient Finished.
[23:11:26] [main/INFO] [Config]: [OptiFine] *** Reflector Forge ***
[23:11:26] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[23:11:26] [main/INFO] [Config]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
[23:11:26] [main/INFO] [Astral Core]: [AstralTransformer] Transforming axw : net.minecraft.world.chunk.Chunk with 1 patches!
[23:11:26] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHBLOCKMODIFY
[23:11:26] [main/INFO] [Astral Core]: [AstralTransformer] Transforming buq : net.minecraft.client.renderer.EntityRenderer with 1 patches!
[23:11:26] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHENTITYRENDEREREXTENDEDENTITYREACH
[23:11:27] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:229]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[23:11:27] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:241]: Transforming net.minecraft.block.Block Finished.
[23:11:27] [main/INFO] [Astral Core]: [AstralTransformer] Transforming aip : net.minecraft.item.ItemStack with 2 patches!
[23:11:27] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHMODIFYENCHANTMENTLEVELSTOOLTIP
[23:11:27] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHMODIFYENCHANTMENTLEVELSTOOLTIPEVENT
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: java.lang.ExceptionInInitializerError
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraftforge.common.ForgeHooks.<clinit>(ForgeHooks.java:333)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at java.lang.Class.forName0(Native Method)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at java.lang.Class.forName(Class.java:264)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at ReflectorClass.getTargetClass(ReflectorClass.java:45)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at ReflectorClass.<init>(ReflectorClass.java:24)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at ReflectorClass.<init>(ReflectorClass.java:15)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at Reflector.<clinit>(Reflector.java:258)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.client.renderer.vertex.DefaultVertexFormats.<clinit>(DefaultVertexFormats.java:16)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraftforge.client.ForgeHooksClient$LightGatheringTransformer.<clinit>(ForgeHooksClient.java:599)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraftforge.client.ForgeHooksClient.<clinit>(ForgeHooksClient.java:642)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:335)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[23:11:28] [main/INFO] [STDERR]: [ReflectorClass:getTargetClass:53]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:11:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.RuntimeException: Accessed Items before Bootstrap!
[23:11:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraft.init.Items.<clinit>(SourceFile:9)
[23:11:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:634]: 	... 18 more
[23:11:28] [main/INFO] [FML]: [Quark ASM] Transforming ModelBiped
[23:11:28] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [setRotationAngles, func_78087_a, a] Descriptor (FFFFFFLnet/minecraft/entity/Entity;)V / (FFFFFFLvg;)V)
[23:11:28] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:28] [main/INFO] [FML]: [Quark ASM] Located patch target node RETURN
[23:11:28] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:29] [main/INFO] [FML]: [Quark ASM] Transforming RenderItem
[23:11:29] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [renderItem, func_180454_a, a] Descriptor (Lnet/minecraft/item/ItemStack;Lnet/minecraft/client/renderer/block/model/IBakedModel;)V / (Laip;Lcfy;)V)
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located patch target node L0
[23:11:29] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:29] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [renderEffect, func_191966_a, a] Descriptor (Lnet/minecraft/client/renderer/block/model/IBakedModel;)V / (Lcfy;)V)
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located patch target node LDC -8372020
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located patch target node LDC -8372020
[23:11:29] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:29] [main/INFO] [EnderCore ASM]: Transforming Class [net.minecraft.client.renderer.RenderItem], Method [func_180453_a, func_184391_a]
[23:11:29] [main/INFO] [EnderCore ASM]: Transforming failed. Applying ersatz patch...
[23:11:29] [main/WARN] [EnderCore ASM]: Ersatz patch applied, things may break!
[23:11:29] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.client.renderer.RenderItem Finished.
[23:11:29] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:229]: Transforming Class [net.minecraft.client.renderer.texture.TextureMap], Method [registerSprite]
[23:11:29] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:241]: Transforming net.minecraft.client.renderer.texture.TextureMap Finished.
[23:11:29] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:229]: Transforming Class [net.minecraft.client.renderer.texture.TextureAtlasSprite], Method [updateAnimationInterpolated]
[23:11:29] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:241]: Transforming net.minecraft.client.renderer.texture.TextureAtlasSprite Finished.
[23:11:29] [main/INFO] [FML]: [Quark ASM] Transforming BlockPistonBase
[23:11:29] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [doMove, func_176319_a, a] Descriptor (Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;Z)Z / (Lamu;Let;Lfa;Z)Z)
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located patch target node ALOAD 5
[23:11:29] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:29] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [canPush, func_185646_a, a] Descriptor (Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/util/EnumFacing;ZLnet/minecraft/util/EnumFacing;)Z / (Lawt;Lamu;Let;Lfa;ZLfa;)Z)
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:29] [main/INFO] [FML]: [Quark ASM] Located patch target node INVOKEVIRTUAL aow.hasTileEntity (Lawt;)Z
[23:11:29] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:29] [main/INFO] [Astral Core]: [AstralTransformer] Transforming wg : net.minecraft.entity.ai.attributes.AbstractAttributeMap with 1 patches!
[23:11:29] [main/INFO] [Astral Core]: [AstralTransformer] Applied patch PATCHADDPLAYERATTRIBUTE
[23:11:29] [main/WARN] [Config]: [OptiFine] (Reflector) More than one method found: net.minecraft.potion.Potion.renderHUDEffect
[23:11:29] [main/WARN] [Config]: [OptiFine] (Reflector)  - public void net.minecraft.potion.Potion.renderHUDEffect(net.minecraft.potion.PotionEffect,net.minecraft.client.gui.Gui,int,int,float,float)
[23:11:29] [main/WARN] [Config]: [OptiFine] (Reflector)  - public void net.minecraft.potion.Potion.renderHUDEffect(int,int,net.minecraft.potion.PotionEffect,net.minecraft.client.Minecraft,float)
[23:11:30] [main/INFO] [FML]: [Quark ASM] Transforming Render
[23:11:30] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [renderEntityOnFire, func_76977_a, a] Descriptor (Lnet/minecraft/entity/Entity;DDDF)V / (Lvg;DDDF)V)
[23:11:30] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:30] [main/INFO] [FML]: [Quark ASM] Located patch target node L0
[23:11:30] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:30] [main/INFO] [Config]: [OptiFine] *** Reflector Vanilla ***
[23:11:30] [main/INFO] [EnderCore ASM]: Transforming Class [net.minecraft.inventory.ContainerFurnace], Method [func_82846_b]
[23:11:30] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.inventory.ContainerFurnace Finished.
[23:11:31] [main/INFO] [FML]: [Quark ASM] Transforming RenderBoat
[23:11:31] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [doRender, func_188300_b, b] Descriptor (Lnet/minecraft/entity/item/EntityBoat;DDDFF)V / (Lafd;DDDFF)V)
[23:11:31] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:31] [main/INFO] [FML]: [Quark ASM] Located patch target node INVOKEINTERFACE brc.b (Lvg;FFFFFF)V
[23:11:31] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:31] [main/INFO] [FML]: [Quark ASM] Transforming EntityBoat
[23:11:31] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [attackEntityFrom, func_70097_a, a] Descriptor (Lnet/minecraft/util/DamageSource;F)Z / (Lur;F)Z)
[23:11:31] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:31] [main/INFO] [FML]: [Quark ASM] Located patch target node POP
[23:11:31] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:31] [main/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [onUpdate, func_70071_h_, B_] Descriptor ()V / ()V)
[23:11:31] [main/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:31] [main/INFO] [FML]: [Quark ASM] Located patch target node L0
[23:11:31] [main/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:31] [Client thread/INFO] [minecraft/Minecraft]: Setting user: Aleh
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Transforming TileEntityPiston
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [update, func_73660_a, e] Descriptor ()V / ()V)
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Located patch target node L0
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [clearPistonTileEntity, func_145866_f, j] Descriptor ()V / ()V)
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Located patch target node INVOKEVIRTUAL amu.a (Let;Lawt;I)Z
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [update, func_73660_a, e] Descriptor ()V / ()V)
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Located patch target node INVOKEVIRTUAL amu.a (Let;Lawt;I)Z
[23:11:32] [Client thread/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:34] [Client thread/INFO] [FML]: [Quark ASM] Transforming ItemBanner
[23:11:34] [Client thread/INFO] [FML]: [Quark ASM] Applying Transformation to method (Names [appendHoverTextFromTileEntityTag, func_185054_a, a] Descriptor (Lnet/minecraft/item/ItemStack;Ljava/util/List;)V / (Laip;Ljava/util/List;)V)
[23:11:34] [Client thread/INFO] [FML]: [Quark ASM] Located Method, patching...
[23:11:34] [Client thread/INFO] [FML]: [Quark ASM] Located patch target node BIPUSH 6
[23:11:34] [Client thread/INFO] [FML]: [Quark ASM] Patch result: true
[23:11:35] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.init.Items
	at net.minecraft.potion.PotionHelper.func_185207_a(PotionHelper.java:154) ~[akh.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:504) ~[ni.class:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:365) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
Exception in thread "Client thread" [23:11:35] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:11:35] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[23:11:35] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:11:35] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:11:35] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[23:11:35] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[23:11:35] [Client thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by Zemogiter** [comment]
I'm having the same error but I'm attempting to launch as a client. Please reopen this issue.
```
[23:26:29.331] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Jendrus, --version, 1.13.2-forge-25.0.70, --gameDir, C:\Users\Jonasz\AppData\Roaming\.minecraft, --assetsDir, C:\Users\Jonasz\AppData\Roaming\.minecraft\assets, --assetIndex, 1.13.1, --uuid, b9088929582f4aa49d2ff72c2563790f, --accessToken, ????????, --userType, legacy, --versionType, release, --proxyHost, 127.0.0.1, --proxyPort, 58930]
[23:26:29.333] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher starting: java version 1.8.0_201
[23:26:30.096] [main/INFO] [loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [fml.forgeVersion, fml.mcVersion, fml.mcpVersion]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at cpw.mods.modlauncher.ArgumentHandler.processArguments(ArgumentHandler.java:37)
	at cpw.mods.modlauncher.TransformationServicesHandler.processArguments(TransformationServicesHandler.java:44)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:32)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:51)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:42)
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
```
No mods are being loaded.
