### ISSUE TITLE
[1.13] Connecting to server crashes if a custom channel is registered

### ISSUE THREAD

**Issue by ichttt** [MinecraftForge/MinecraftForge#5366]
When trying to connect in userdev to my localhost server, I get the following exception:
```
java.lang.NullPointerException: null
	at net.minecraftforge.fml.network.NetworkHooks.registerClientLoginChannel(NetworkHooks.java:71) ~[?:?]
	at net.minecraft.client.gui.GuiConnecting$1.run(GuiConnecting.java:65) [?:?]
```
This is only happens if I call
```
NETWORKING = NetworkRegistry.newSimpleChannel(
                new ResourceLocation(MODID, "channel"),
                () -> NETWORKING_VERSION,
                s -> s.startsWith(NETWORKING_MAJOR),
                s -> s.equals(NETWORKING_VERSION));
```
It doesn't matter if this is called in a static initializer or in the FMLCommonSetupEvent.

**Comment by ichttt** [comment]
Not reproducable anymore
