### ISSUE TITLE
[1.13] Playing modded sounds occasionally deadlocks

### ISSUE THREAD

**Issue by williewillus** [MinecraftForge/MinecraftForge#5408]
Playing a modded sound using the usual methods (world.playSound) has a chance to deadlock the client completely.
Posting this since both @GirafiStudios and I were able to get it to happen.

~~We're not sure what's causing it yet, but~~ it doesn't occur 100% of the time.

Here's my analysis so far:
* The main client thread is blocked trying to acquire a lock (SoundSystem.THREAD_SYNC) to enqueue a "SET LISTENER POSITION" command.
* That lock was taken by one of the paulscode soundsystem threads processing a "NEW SOURCE" command, which calls into Minecraft's `LibraryLWJGL3.newSource` which then calls `LibraryLWJGL3.loadSound`.
* `loadSound` calls `icodec.initialize`, which somehow fails, printing "CodecJOrbis error reading the header" on the console
* the vanilla code doesn't check that initialize failed and directly starts reading the file, causing an infinite loop in `CodecJOrbis.readAll` waiting for data that never comes.

So there's two problems:
* Why is the header failing sometimes?
* Vanilla doesn't check for header reading failing and just launches itself into an infinite loop holding the central soundsystem lock.

Stacktrace for relevant threads:
```
"Client thread@1" prio=5 tid=0x1 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for Thread-4@7772 to release lock on <0x2fde> (a java.lang.Object)
	  at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2359)
	  at paulscode.sound.SoundSystem.setListenerPosition(SoundSystem.java:1280)
	  at net.minecraft.client.audio.SoundManager.setListener(SoundManager.java:458)
	  at net.minecraft.client.audio.SoundHandler.setListener(SoundHandler.java:226)
	  at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:780)
	  at net.minecraft.client.Minecraft.run(Minecraft.java:354)
	  at net.minecraft.client.main.Main.main(SourceFile:144)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52)
	  at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider$$Lambda$265.2115640742.call(Unknown Source:-1)
	  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:35)
	  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	  at cpw.mods.modlauncher.Launcher.run(Launcher.java:58)
	  at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
	  at net.minecraftforge.userdev.UserdevLauncher.main(UserdevLauncher.java:77)

"Thread-4@7772" prio=5 tid=0x1c nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks Client thread@1
	  at paulscode.sound.codecs.CodecJOrbis.readAll(CodecJOrbis.java:379)
	  at net.minecraft.client.audio.LibraryLWJGL3.loadSound(SourceFile:201)
	  at net.minecraft.client.audio.LibraryLWJGL3.newSource(SourceFile:360)
	  at paulscode.sound.SoundSystem.CommandNewSource(SoundSystem.java:1800)
	  at paulscode.sound.SoundSystem.CommandQueue(SoundSystem.java:2415)
	  - locked <0x2fde> (a java.lang.Object)
	  at paulscode.sound.CommandThread.run(CommandThread.java:121)
```

**Comment by williewillus** [comment]
Progress: So the reason the header fails is because in `CodecJOrbis.readHeader` trying to read from the inputStream throws a `ClosedByInterruptException`. Not sure what that means yet

**Comment by williewillus** [comment]
More progress: looks like this only affects mod sounds, and I have an inkling of an idea why. So `ModFileResourcePack` uses nio to return paths to sounds on the local filesystem, and it returns InputStreams backed by `FileChannel`, which explicitly say they throw this exception if the thread gets interrupted while IO operations are happening.

Well, does this thread ("Thread-4") get interrupted? Of course it does, the sound system explicitly interrupts the command processing thread to tell it to process items on the queue.

Vanilla sounds are unaffected by this since they use normal `FileInputStream`s to point into the gradle cache.

not sure what a good solution is currently, converting the `Path` in `ModFileResourcePack` back to a `File` and using normal `FileInputStream` might not work with jars

**Comment by cpw** [comment]
Well, this is a curious one and no mistake.

**Comment by williewillus** [comment]
fixed in 138
