### ISSUE TITLE
[1.13] Crash when looking at mod in modlist. 

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5418]
I got the following crash when looking at a mod in the modlist. Said mod is the base example mod for 1.13. I am not able to reproduce this error 100% of the time, but I have reproduced it multiple times. 

```
java.lang.ClassCastException: net.minecraft.resources.ResourcePackInfo cannot be cast to net.minecraft.client.resources.ResourcePackInfoClient
	at net.minecraftforge.fml.client.gui.GuiModList.lambda$updateCache$6(GuiModList.java:436)
	at java.util.Optional.map(Unknown Source)
	at net.minecraftforge.fml.client.gui.GuiModList.updateCache(GuiModList.java:433)
	at net.minecraftforge.fml.client.gui.GuiModList.selectModIndex(GuiModList.java:414)
	at net.minecraftforge.fml.client.gui.GuiSlotModList$ModEntry.mouseClicked(GuiSlotModList.java:117)
	at net.minecraft.client.gui.GuiListExtended.mouseClicked(SourceFile:21)
	at net.minecraft.client.gui.GuiSlot.mouseClicked(GuiSlot.java:225)
	at net.minecraft.client.gui.GuiEventHandler.mouseClicked(SourceFile:46)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:80)
	at net.minecraft.client.gui.GuiScreen.runOrMakeCrashReport(GuiScreen.java:418)
	at net.minecraft.client.MouseHelper.mouseButtonCallback(MouseHelper.java:78)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at net.minecraft.client.MainWindow.update(SourceFile:308)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:816)
	at net.minecraft.client.Minecraft.run(Minecraft.java:354)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:35)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:58)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
	at net.minecraftforge.userdev.UserdevLauncher.main(UserdevLauncher.java:77)
```

Forge: 24.0.147
MC: 1.13

**Comment by liach** [comment]
can you try both in the main menu and in a singleplayer game?

**Comment by Darkhax** [comment]
@liach There is no option to open this GUI while in game anymore. (This may be a separate issue, not sure if it's removal was intended)

**Comment by liach** [comment]
ah. the pack containers have client and server variants which the coder did not consider.

**Comment by LexManos** [comment]
Key note here is to enter a local world before looking at the mod list.
That'll re-create the map with server resource infos.
