### ISSUE TITLE
[1.13] NullPointerException in mouseClicked event when joining world.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5419]
I got this exception on joining the world. I haven't been able to reproduce this more than once, so there may be some form of race condition going on here. Unfortunately I don't have any more information at this time. 

```
java.lang.NullPointerException: mouseClicked event handler
	at net.minecraftforge.fml.network.NetworkHooks.registerClientLoginChannel(NetworkHooks.java:75)
	at net.minecraft.client.Minecraft.launchIntegratedServer(Minecraft.java:1418)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.loadWorld(SourceFile:294)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.joinWorld(SourceFile:223)
	at net.minecraft.client.gui.GuiWorldSelection$1.onClick(SourceFile:59)
	at net.minecraft.client.gui.GuiButton.mouseClicked(GuiButton.java:104)
	at net.minecraft.client.gui.GuiEventHandler.mouseClicked(SourceFile:46)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:80)
	at net.minecraft.client.gui.GuiScreen.runOrMakeCrashReport(GuiScreen.java:418)
	at net.minecraft.client.MouseHelper.mouseButtonCallback(MouseHelper.java:78)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at net.minecraft.client.MainWindow.update(SourceFile:308)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:816)
	at net.minecraft.client.Minecraft.run(Minecraft.java:354)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:52)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:35)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:58)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
	at net.minecraftforge.userdev.UserdevLauncher.main(UserdevLauncher.java:77)
```

Forge: 24.0.147
MC: 1.13

**Comment by GirafiStudios** [comment]
I've had this happen as well. Pretty sure I had it happen when going into Options though.

**Comment by Sana36** [comment]
I have had it happen in a few places, below are the logs I have loaded up on these issues.

https://gist.github.com/Sana36/0a17d85dbf4029bc081ebffbe5bbf599
https://gist.github.com/Sana36/55f6ef2fed25ab1e029bf04a8467d486

**Comment by LexManos** [comment]
Spent a good 20 mins trying to reproduce this in any case where I could think of. And failed.
Going to leave this open in case anyone else gets a reproduction.
Note, this "java.lang.NullPointerException: mouseClicked event handler" is actually a GENERIC error. And needs the full stracktrace/context to be useful.
So keep that in mind when saying "I had this happen as well"

**Comment by DreamThorn** [comment]
One thing that all the error logs have in common is that the user was re-entering the world after saving and exiting.

So, I'd guess that something is getting nulled when exiting the world, but not getting a value when entering it.  Probably something that was set up before entering the world for the first time.

**Comment by hugeblank** [comment]
I haven't had this issue, but in order to properly click on any GUI buttons in the main menu/pause screen they need to be double clicked. I don't know if this behavior is relevant to this particular issue, but it's close enough I think.

**Comment by Sana36** [comment]
I have had it happen twice on starting a new world as well as returning to a saved world, it is an intermittent error. I am happy to try to recreate the error if someone can help me set it up so I get useful information ie "full stracktrace" Searching for stracktrace in docs comes back with a this page doesn't exist yet.

PS I have no interest in creating mods or any other coding at this time. I just want simple, preferably written instructions on the bare minimum I need to do and for later what version of Java is being used, incase I change my mind after this version is released.

**Comment by tterrag1098** [comment]
The stacktrace will be in the logs (/logs/latest.log), just copy it from there.

**Comment by Sana36** [comment]
I had attached latest.log, the crash-reports (which contain stacktraces) and what was happening when they occurred but they apparently weren't enough. I thought I had attached them the recommended way. Have I missed something?

I will try to recreate tomorrow, I had no luck (unluck?) tonight.

**Comment by tterrag1098** [comment]
No yours is fine. But as we do not yet have a reliable repro case, more stacktraces from others would be helpful. The most helpful thing however would be a reliable step-by-step way to reproduce the crash.

**Comment by Sana36** [comment]
I am starting to think it is biome related, specifically I have had it happen in the swamp biomes but not in mountains or plains. Can anyone else test to see if the biomes are involved or if it is just a coincidence?

In the new version I have had very repeatable errors, these were error after error, no gameplay at all.

Beta 1.13.2 25.0.21 - too easy - https://github.com/MinecraftForge/MinecraftForge/issues/5499

- Creating a swamp only world 2:44 pm
- Opening saved swamp world 2:48 pm
- Creating a swamp only world 2:50 pm
- Opening saved swamp world 1 2:51pm
- Opening saved swamp world 2 2:53pm
- Creating a swamp only world 2:55pm

Crash Reports https://gist.github.com/Sana36/007e80b2a8dd498da48201509c7f5f9e


V192 - I still can't get a reproducible crash. Between each crash is normal(ish) survival behaviour - gathering resources, building, limited farming.
- Saving and exiting from spruce on edge of swamp - 11:19 am 
  - Not repeatable from same location
- Saving and exiting in swamp 12:09 pm (early night, raining)
  -   Not repeatable from same location
- Opening world into swamp 12:41 pm (day, sunny)
  -   Very close to 12:09 pm location - within 10 blocks
  -   Not repeatable from same location
- Opening world into swamp 1:54 pm (night, raining)
  -   Very close to 12:09 pm &12:41 pm location - modified witches hut
  -   Not repeatable from same location
- Tried to create a swamp only world 1:59 pm
  -   Was able to enter game as a saved game
  -   Got a repeat 2:04 pm - first replication but not sure if fluke
  -   Next two times not repeated

v192 Crash reports https://gist.github.com/Sana36/552c8bb0e703dcf50371641683103606

**Comment by Darkhax** [comment]
I haven't had this issue happen at all in 1.14 and apparently neither has anyone else. Going to close this one prematurely.
