### ISSUE TITLE
[1.13] Server startup failures. Jopt options and missing libraries. 

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5424]
When attempting to launch a server for 1.13 in a non-dev environment, there are several expected options that are missing. `fml.forgeVersion`, `fml.mcVersion`, `fml.mcpVersion`. If these options are specified via the command line, it will look for the libraries in locations that do not exist. 

My command
`java -jar .\forge-1.13-24.0.150-1.13-pre.jar -"fml.forgeVersion=1.13-24.0.150" -"fml.mcVersion=1.13" -"fml.mcpVersion=1.13-2018.09.12.04.11.00"`

Exception
```
[22:48:35.309] [main/FATAL] [loading.FMLCommonLaunchHandler/CORE]: Failed to find forge version 1.13-24.0.150 for MC 1.13 at C:\Users\Tyler\Desktop\Forge\server\libraries\net\minecraftforge\forge\1.13-1.13-24.0.150\forge-1.13-1.13-24.0.150-universal.jar
Exception in thread "main" java.lang.RuntimeException: Missing forge!
        at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:113)
        at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:146)
        at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:82)
        at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:43)
        at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$5(TransformationServicesHandler.java:75)
        at java.util.HashMap$Values.forEach(Unknown Source)
        at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:75)
        at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:40)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:53)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:28)
```

The forge libraries it is looking for do not exist at that location. Since this is the test branch, libraries are in `C:\Users\Tyler\Desktop\Forge\server\libraries\net\minecraftforge\test\forge\1.13-24.0.150-1.13-pre` instead.

Edit: The versions I provided in my command are also incorrect (no 1.13- prefix required) however it is still looking in the wrong location. Moving the jars by hand will allow the user to proceed past this step.

**Comment by LexManos** [comment]
Well yes.. if you specify the wrong version it'll look in the wrong place...
I've updated the server main to include default arguments. 
https://github.com/MinecraftForge/MinecraftForge/commit/aa91af865d837c54acf6be10e599ff1ee3565c57

**Comment by Darkhax** [comment]
@LexManos The versions are not the issue here. Look at the location it's searching carefully. 

C:\Users\Tyler\Desktop\Forge\server\libraries\net\minecraftforge\ **test\forge** \1.13-24.0.150-1.13-pre

The actual jar location is in /forge/ and not /test/forge/.

**Comment by LexManos** [comment]
No.. No it's not. test is correct.
