### ISSUE TITLE
[1.13] Library finder can't find realms. 

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5425]
When I launch the 1.13 server, it crashes when trying to find the realms jar. The vanilla server does not need or use the realms client, and Forge's server shouldn't need it either. 

```
[22:54:00.361] [main/FATAL] [loading.LibraryFinder/CORE]: Failed to find JAR for class com/mojang/realmsclient/RealmsVersion.class - realms
Exception in thread "main" java.lang.RuntimeException: Unable to locate com/mojang/realmsclient/RealmsVersion.class - realms
        at net.minecraftforge.fml.loading.LibraryFinder.findJarPathFor(LibraryFinder.java:68)
        at net.minecraftforge.fml.loading.LibraryFinder.findJarPathFor(LibraryFinder.java:52)
        at net.minecraftforge.fml.loading.LibraryFinder.commonLibPaths(LibraryFinder.java:73)
        at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.configureTransformationClassLoader(FMLCommonLaunchHandler.java:71)
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.configureTransformationClassLoaderBuilder(LaunchServiceHandlerDecorator.java:26)
        at cpw.mods.modlauncher.LaunchServiceHandler.identifyTransformationTargets(LaunchServiceHandler.java:60)
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:55)
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:28)
Caused by: java.lang.NullPointerException
        at net.minecraftforge.fml.loading.LibraryFinder.findJarPathFor(LibraryFinder.java:58)
        ... 8 more
```

Forge: 24.0.150

**Comment by cpw** [comment]
Hmm. Looks like I accidentally merged that code too much.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/aa91af865d837c54acf6be10e599ff1ee3565c57
Dedicated server still doesn't work due to a classloading issue im looking into. But I fixed this one.
