### ISSUE TITLE
[1.13] Listening for the same registry event in two different mods fails

### ISSUE THREAD

**Issue by LordMonoxide** [MinecraftForge/MinecraftForge#5446]
I have two different mods in my project, and both listen for the item registration event.  The mod that loads last fails with the following message:
```
[13:50:17.705] [Client thread/ERROR] [ne.mi.fm.ja.FMLModContainer/]: Exception caught during firing event: Attempted to set event phase to NORMAL when already NORMAL
	Index: 0
	Listeners:
		0: NORMAL
		1: ASM: class lordmonoxide.gradient.core.GradientCore registerItems(Lnet/minecraftforge/event/RegistryEvent$Register;)V
java.lang.IllegalArgumentException: Attempted to set event phase to NORMAL when already NORMAL
	at net.minecraftforge.eventbus.api.Event.setPhase(Event.java:163)
	at net.minecraftforge.eventbus.api.EventPriority.invoke(EventPriority.java:48)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:249)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:105)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at java.base/java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:98)
	at net.minecraftforge.fml.ModList.lambda$dispatchSynchronousEvent$4(ModList.java:99)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at net.minecraftforge.fml.ModList.dispatchSynchronousEvent(ModList.java:99)
	at net.minecraftforge.fml.ModList.lambda$static$0(ModList.java:78)
	at net.minecraftforge.fml.LifecycleEventProvider.dispatch(LifecycleEventProvider.java:72)
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:143)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:818)
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:132)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:52)
	at net.minecraft.client.Minecraft.init(Minecraft.java:407)
	at net.minecraft.client.Minecraft.run(Minecraft.java:340)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:35)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:58)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
	at net.minecraftforge.userdev.UserdevLauncher.main(UserdevLauncher.java:77)
```

Here's a simple repro:
```
@Mod("moda")
@Mod.EventBusSubscriber(modid = "moda", bus = Mod.EventBusSubscriber.Bus.MOD)
public class ModA {
  @SubscribeEvent
  public static void registerItems(final RegistryEvent.Register<Item> event) {
  }
}
```

```
@Mod("modb")
@Mod.EventBusSubscriber(modid = "modb", bus = Mod.EventBusSubscriber.Bus.MOD)
public class ModB {
  @SubscribeEvent
  public static void registerItems(final RegistryEvent.Register<Item> event) {
  }
}
```

**Comment by LordMonoxide** [comment]
Note: it works if both even handlers are in the same mode, and a temporary workaround is to adjust the priorities of the event handlers accordingly.

**Comment by cpw** [comment]
Should be fixed. Closing.

**Comment by StephanieNight** [comment]
im sad to inform this has been reintoduced to 1.14.4 im having that error rigth now.

**Comment by cpw** [comment]
Wrong bus

**Comment by StephanieNight** [comment]
hey  CPW, thanks for your super quick response, in that case what bus should i use ? is there some documentation i can look at, dont wanna to much of a bother.
