### ISSUE TITLE
[1.13] The game crash when trying to start it with some languages

### ISSUE THREAD

**Issue by Just-random-user** [MinecraftForge/MinecraftForge#5455]
How to reproduce: 
Enter the game and change language to russian or german;
Close the game;
Try to enter it again.
Crash report example: 

**---- Minecraft Crash Report ----**
// Don't be sad. I'll do better next time, I promise!
Time: 09.02.19 23:54
Description: Rendering screen

java.lang.IllegalArgumentException: unknown format type: auswahl
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1526)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.applyPattern
(ExtendedMessageFormat.java:191)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:125)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:110)
	at net.minecraftforge.fml.ForgeI18n.parseFormat(ForgeI18n.java:95)
	at net.minecraftforge.fml.ForgeI18n.parseMessage(ForgeI18n.java:91)
	at net.minecraftforge.fml.BrandingControl.computeBranding(BrandingControl.java:45)
	at net.minecraftforge.fml.BrandingControl.getBrandings(BrandingControl.java:53)
	at net.minecraftforge.fml.BrandingControl.forEachLine(BrandingControl.java:62)
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:296)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:347)
	at net.minecraft.client.renderer.EntityRenderer.func_195458_a(EntityRenderer.java:654)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:792)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:354)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0
(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$246/116734858.call
(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch
(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:35)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:58)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1526)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.applyPattern
(ExtendedMessageFormat.java:191)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:125)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:110)
	at net.minecraftforge.fml.ForgeI18n.parseFormat(ForgeI18n.java:95)
	at net.minecraftforge.fml.ForgeI18n.parseMessage(ForgeI18n.java:91)
	at net.minecraftforge.fml.BrandingControl.computeBranding(BrandingControl.java:45)
	at net.minecraftforge.fml.BrandingControl.getBrandings(BrandingControl.java:53)
	at net.minecraftforge.fml.BrandingControl.forEachLine(BrandingControl.java:62)
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:296)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:347)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
	Mouse location: Scaled: (0, 0). Absolute: (0.000000, 0.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_195458_a(EntityRenderer.java:654)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:792)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:354)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0
(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$246/116734858.call
(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch
(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:35)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:58)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)

-- System Details --
Details:
	Minecraft Version: 1.13
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1458773216 bytes (1391 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Launched Version: 1.13-forge-24.0.172-1.13-pre
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

**Comment by ichttt** [comment]
Seems like the german translaters made a mistake and translate the control code as well.
I submited a fix to crowdin

**Comment by Just-random-user** [comment]
Same with russian?
There is a problem with choise of text about amount of mods (singular/plural)

**Comment by Just-random-user** [comment]
Here it is:

---- Minecraft Crash Report ----
// But it works on my machine.
Time: 09.02.19 23:15
Description: Rendering screen
java.lang.IllegalArgumentException: Choice Pattern incorrect: 0#Без модов|1#1 мод|5>{0} мода|4<{0} модов
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1519)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.applyPattern
(ExtendedMessageFormat.java:191)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:125)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:110)
	at net.minecraftforge.fml.ForgeI18n.parseFormat(ForgeI18n.java:95)
	at net.minecraftforge.fml.ForgeI18n.parseMessage(ForgeI18n.java:91)
	at net.minecraftforge.fml.BrandingControl.computeBranding(BrandingControl.java:45)
	at net.minecraftforge.fml.BrandingControl.getBrandings(BrandingControl.java:53)
	at net.minecraftforge.fml.BrandingControl.forEachLine(BrandingControl.java:62)
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:296)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:347)
	at net.minecraft.client.renderer.EntityRenderer.func_195458_a(EntityRenderer.java:654)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:792)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:354)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0
(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$247/1605851606.call
(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch
(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:35)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:58)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)
Caused by: java.lang.IllegalArgumentException
	at java.text.ChoiceFormat.applyPattern(ChoiceFormat.java:214)
	at java.text.ChoiceFormat.<init>(ChoiceFormat.java:315)
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1516)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.text.MessageFormat.makeFormat(MessageFormat.java:1519)
	at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.applyPattern
(ExtendedMessageFormat.java:191)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:125)
	at org.apache.commons.lang3.text.ExtendedMessageFormat.<init>(ExtendedMessageFormat.java:110)
	at net.minecraftforge.fml.ForgeI18n.parseFormat(ForgeI18n.java:95)
	at net.minecraftforge.fml.ForgeI18n.parseMessage(ForgeI18n.java:91)
	at net.minecraftforge.fml.BrandingControl.computeBranding(BrandingControl.java:45)
	at net.minecraftforge.fml.BrandingControl.getBrandings(BrandingControl.java:53)
	at net.minecraftforge.fml.BrandingControl.forEachLine(BrandingControl.java:62)
	at net.minecraft.client.gui.GuiMainMenu.func_73863_a(GuiMainMenu.java:296)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:347)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
	Mouse location: Scaled: (0, 0). Absolute: (0.000000, 0.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_195458_a(EntityRenderer.java:654)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:792)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:354)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0
(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$247/1605851606.call
(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch
(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:35)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:58)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44)

-- System Details --
Details:
	Minecraft Version: 1.13
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2960122776 bytes (2822 MB) / 4831838208 bytes (4608 MB) up to 4831838208 bytes (4608 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4608M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Launched Version: 1.13-forge-24.0.172-1.13-pre
	LWJGL: 3.1.6

**Comment by kierajreed** [comment]
Please use [hastebin](https://hastebin.com/) for error logs and stack traces, it makes the issues a lot less cluttered.

**Comment by LexManos** [comment]
We should look into having something that doesn't crash with this. As the translations are crowdsourced, we need a proper 'this string is invalid in this language' that is SOLEY in english/hardcoded. But ya, wouldn't consider this a Forge bug, more of a issue with the crowdsourced translations. You can help by providing better/fixed entries here: https://crowdin.com/project/minecraft-forge

**Comment by Just-random-user** [comment]
I submitted working translations on russian and ukraine so issue can be closed once working translation be accepted. Thank you all for all your comments.

**Comment by Just-random-user** [comment]
The game doesn't crushes anymore, even when translation is not right. There's only Crowdin-related stuff left, therefore the issue technically resolved.

**Comment by Just-random-user** [comment]
The game doesn't crushes anymore, even when translation is not right. There's only Crowdin-related stuff left, therefore the issue technically resolved.
