### ISSUE TITLE
Installer crashes on headless server instead of showing help

### ISSUE THREAD

**Issue by LemADEC** [MinecraftForge/MinecraftForge#5478]
As of 1.12.2-14.23.5.2815, using the installer on an headless server will crash instead of reporting an help message.
I recommend to just default to server installation in such case.

```
java -jar forge-1.12.2-14.23.5.2815-installer.jar
Setting up logger: /home/pozone/forge-1.12.2-14.23.5.2815-installer.jar.log
java.net.preferIPv4Stack=true
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.installer.Java6Gate.main(Java6Gate.java:48)
Caused by: java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at net.minecraftforge.installer.InstallerPanel.run(InstallerPanel.java:377)
        at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:168)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:54)
        ... 5 more
```

**Comment by tilda** [comment]
I believe you *should* be able to run it with --installServer and it will work. Just defaulting to --installServer wouldn't work that well since the GUI exists mostly for Windows/Mac users who just want to install a mod.

**Comment by LexManos** [comment]
Defaulting to server install is not an option no, and if someone wants to PR [to the correct repository ](https://github.com/MinecraftForge/Installer). Something that detects a headless environment. Then it can be addressed. Until then i'm filing this as a non-issue/wrong repo.

**Comment by XakepSDK** [comment]
@LemADEC https://github.com/MinecraftForge/Installer/pull/45 test please, i don't have headless atm
