### ISSUE TITLE
[1.13.2] FMLPlayMessages.SpawnEntity attempt to load WorldClient on DEDICATED_SERVER

### ISSUE THREAD

**Issue by yuxuanchiadm** [MinecraftForge/MinecraftForge#5573]
Stacktrace:
```
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/WorldClient for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:67) ~[forge-1.13.2-25.0.52_mapped_snapshot_20180921-1.13-launcher.jar:25.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$offerClassNodeToPlugins$7(LaunchPluginHandler.java:38) ~[modlauncher-0.10.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373) ~[?:1.8.0_162]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_162]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_162]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_162]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474) ~[?:1.8.0_162]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:39) ~[modlauncher-0.10.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:83) ~[modlauncher-0.10.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:214) ~[modlauncher-0.10.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:76) ~[modlauncher-0.10.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.loadClass(TransformingClassLoader.java:169) ~[modlauncher-0.10.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_162]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_162]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_162]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_162]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_162]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_162]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_162]
	at net.minecraftforge.fml.network.FMLPlayHandler.<clinit>(FMLPlayHandler.java:35) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:177) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:122) ~[?:?]
```
At:
https://github.com/MinecraftForge/MinecraftForge/blob/0bcc60fbe3842861092508589fef89a3b3d9014b/src/main/java/net/minecraftforge/fml/network/FMLPlayMessages.java#L131

**Comment by HyCraftHD** [comment]
This happens to all forge messages for play, because the clinit of FMLPlayHandler wont succeed.
(OpenGui and EntitySpawn)

**Comment by henkelmax** [comment]
I have the same issue

```
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/WorldClient for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:67) ~[forge-1.13.2-25.0.59_mapped_snapshot_20180921-1.13-launcher.jar:25.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$offerClassNodeToPlugins$8(LaunchPluginHandler.java:39) ~[modlauncher-0.11.0.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373) ~[?:1.8.0_144]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_144]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_144]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_144]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474) ~[?:1.8.0_144]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:40) ~[modlauncher-0.11.0.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:83) ~[modlauncher-0.11.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:214) ~[modlauncher-0.11.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:76) ~[modlauncher-0.11.0.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.loadClass(TransformingClassLoader.java:169) ~[modlauncher-0.11.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_144]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_144]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_144]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_144]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_144]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_144]
	at net.minecraftforge.fml.network.FMLPlayHandler.<clinit>(FMLPlayHandler.java:35) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.getEntitySpawningPacket(NetworkHooks.java:69) ~[?:?]
	at net.minecraft.entity.EntityTrackerEntry.createSpawnPacket(EntityTrackerEntry.java:413) ~[?:?]
	at net.minecraft.entity.EntityTrackerEntry.updatePlayerEntity(EntityTrackerEntry.java:318) ~[?:?]
	at net.minecraft.entity.EntityTrackerEntry.updatePlayers(EntityTrackerEntry.java:403) ~[?:?]
	at net.minecraft.entity.EntityTracker.track(EntityTracker.java:162) ~[?:?]
	... 23 more
```

**Comment by williewillus** [comment]
@henkelmax @yuxuanchiadm try the latest build?
