### ISSUE TITLE
[1.13] Issue tracker URL not handled safely.

### ISSUE THREAD

**Issue by Darkhax** [MinecraftForge/MinecraftForge#5619]
If the `issueTrackerURL` in mods.toml is not a valid URL the game will crash with a malformed URL exception. This exception should probably be caught and replaced with a warning in the console instead. 

While it makes sense to ensure the issueTrackerURL is a valid URL, there are some situations in the dev environment where this may be invalid. For example I am setting the value at build time using a gradle property. In the dev environment the url is `${issue_tracker}` which causes the issue. I am also using this approach for `displayURL` however that property does not seem to be affected by this issue. 

Here is a stack trace pointing to the code in Forge. This is with Forge `25.0.85`.
```
Exception in thread "main" java.lang.RuntimeException: java.net.MalformedURLException: no protocol: ${issue_tracker}
	at net.minecraftforge.fml.loading.StringUtils.toURL(StringUtils.java:51)
	at java.util.Optional.map(Unknown Source)
	at net.minecraftforge.fml.loading.moddiscovery.ModFileInfo.<init>(ModFileInfo.java:61)
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.loadModFile(ModFileParser.java:59)
	at net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:51)
	at net.minecraftforge.fml.loading.moddiscovery.ModFile.identifyMods(ModFile.java:126)
	at net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:76)
	at net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:187)
	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:86)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:43)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$6(TransformationServicesHandler.java:68)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:68)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:33)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:51)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:42)
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:84)
Caused by: java.net.MalformedURLException: no protocol: ${issue_tracker}
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at java.net.URL.<init>(Unknown Source)
	at net.minecraftforge.fml.loading.StringUtils.toURL(StringUtils.java:47)
	... 16 more
```

**Comment by Unnoen** [comment]
~~@tterrag1098 It appears you didn't push the fix to this repo https://github.com/tterrag1098/MinecraftForge/commit/f2de4fb6376721893a3ddd3bbf5646ad7567c825 😛~~

EDIT: It appears it wasn't verified with cpw if that was the correct fix. This is still an issue however.
