### ISSUE TITLE
[1.12.2] [Compatability] MW Item rendering issue

### ISSUE THREAD

**Issue by Carvercarver1** [MinecraftForge/MinecraftForge#5631]
Forge Version: 14.23.5.2822

Maybe someone remembers Vic's Modern Warfare mod. One particular issue I have - item rendering for the mod. 
When I open my inventory (did this in creative mode) and scroll to the MW's tab, where weapon "Catalogue" is located, game instantly crashes. And when looking at certain mobs, which wield said weapons (Bandits) - weird visual glitches occur, which won't crash the game, but make it seem like a hard drug trip.

Here's the relevant part of the crash (thanks to vanillafix): 
___________________________________________________________________________________________
_java.lang.IllegalStateException: Not building!
    at net.minecraft.client.renderer.BufferBuilder.finishDrawing(BufferBuilder.java:537)
    at net.minecraft.client.renderer.Tessellator.draw(SourceFile:21)
    at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.getQuads(CompatibleWeaponRenderer.java:137)
    at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:650)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:118)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:106)
    at net.minecraft.client.renderer.RenderItem.renderItem(RenderItem.java:149)
    at net.minecraft.client.renderer.RenderItem.renderItemModelIntoGUI(RenderItem.java:308)
    at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:347)
    at net.minecraft.client.renderer.RenderItem.renderItemAndEffectIntoGUI(RenderItem.java:336)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawTab(GuiContainerCreative.java:922)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawGuiContainerBackgroundLayer(GuiContainerCreative.java:758)
    at net.minecraft.client.gui.inventory.GuiContainer.drawScreen(GuiContainer.java:75)
    at net.minecraft.client.renderer.InventoryEffectRenderer.drawScreen(InventoryEffectRenderer.java:51)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:643)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)_

_-- Item being rendered --
  Item Type: com.vicmatskiv.weaponlib.Weapon@1ecd80fe
  Registry Name: mw:m16a4 //that's just example, it does the same with other weapons//
  Item Aux: 0
  Item NBT: null
  Item Foil: false

-- Screen render details --
  Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative_
_____________________________________________________________________________________________

From what I know, Forge changed something about rendering after recommended forge version 2768 , if I'm not mistaken (*and even both _Vic_ and _Forge dev's_ had some serious quarrels (?) between each other about that?*). 

Could this be fixed, or at least tweaked in the next 1.12 forge release, , so it would work again, please? 

P.S: And __please__, put aside your accusations and different opinions, and make this __work__. Or at least try. It is just sad to see.
P.P.S: A new thread in "Pull requests" may be made, referring to this issue.

**Comment by Carvercarver1** [comment]
... or at least give me a brief explanation  why this render change was needed in the first place.

**Comment by LexManos** [comment]
I have no idea who Vic is, nore do I care. But it sounds like he's trying to render things using a buffer that is already finalized. Use the forum to do basic debugging and track down exact versions and mods that are in use.
