### ISSUE TITLE
[1.14.2] Worlds looks total loss due to a config bug

### ISSUE THREAD

**Issue by FoxSamu** [MinecraftForge/MinecraftForge#5816]
Started minecraft forge with 1.14.2, but once I entered a world, only some entities and some floating blocks appeared. The game is laggy, entities, fluids and blocks appear all over the place, the player constantly falls through the world into the void, entities render upside down, a mysterious black square appears above the player: the world looks literally total loss.

It seems to be a client-only problem, the server just behaves like normal. It happens to every world, either from an integrated or a dedicated server. Newest forge version (1.14.2-26.0.25) still has the bug.

When I enter a world in vanilla, everything seems to be fine:
![2019-06-14_23 30 12](https://user-images.githubusercontent.com/11669132/59539429-832ac880-8efd-11e9-81c6-05940c8f2a72.png)

When I enter the same world in forge, it looks total loss:
![2019-06-14_23 34 21](https://user-images.githubusercontent.com/11669132/59539491-bff6bf80-8efd-11e9-9332-f5046e1900bb.png)

When I enter the same world again in vanilla, everything is just fine again...

I checked the game log and saw loads of these messages/exceptions:
```
[14jun2019 23:13:27.342] [Client thread/ERROR] [net.minecraft.client.renderer.entity.LivingRenderer/]: Couldn't render entity
java.lang.NullPointerException: Cannot get config value without assigned Config object present
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787) ~[guava-21.0.jar:?]
	at net.minecraftforge.common.ForgeConfigSpec$ConfigValue.get(ForgeConfigSpec.java:632) ~[?:?]
	at net.minecraft.client.renderer.ItemRenderer.func_191967_a(ItemRenderer.java:79) ~[?:?]
	at net.minecraft.client.renderer.ItemRenderer.func_191961_a(ItemRenderer.java:71) ~[?:?]
	at net.minecraft.client.renderer.ItemRenderer.func_180454_a(ItemRenderer.java:108) ~[?:?]
	at net.minecraft.client.renderer.ItemRenderer.func_184394_a(ItemRenderer.java:236) ~[?:?]
	at net.minecraft.client.renderer.ItemRenderer.func_184392_a(ItemRenderer.java:219) ~[?:?]
	at net.minecraft.client.renderer.FirstPersonRenderer.func_187462_a(FirstPersonRenderer.java:73) ~[?:?]
	at net.minecraft.client.renderer.entity.layers.HeldItemLayer.func_188358_a(HeldItemLayer.java:52) ~[?:?]
	at net.minecraft.client.renderer.entity.layers.HeldItemLayer.func_212842_a_(HeldItemLayer.java:33) ~[?:?]
	at net.minecraft.client.renderer.entity.layers.HeldItemLayer.func_212842_a_(HeldItemLayer.java:15) ~[?:?]
	at net.minecraft.client.renderer.entity.LivingRenderer.func_177093_a(LivingRenderer.java:394) ~[?:?]
	at net.minecraft.client.renderer.entity.LivingRenderer.func_76986_a(LivingRenderer.java:143) ~[?:?]
	at net.minecraft.client.renderer.entity.MobRenderer.func_76986_a(SourceFile:40) ~[?:?]
	at net.minecraft.client.renderer.entity.MobRenderer.func_76986_a(SourceFile:15) ~[?:?]
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:371) ~[?:?]
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188388_a(EntityRendererManager.java:360) ~[?:?]
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:540) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:712) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640) ~[?:?]
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:898) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:154) ~[1.14.2-forge-26.0.8.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.14.2-26.0.8.jar:26.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:59) [modlauncher-2.1.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:44) [modlauncher-2.1.1.jar:?]
```

I have concluded that the problem is caused by a bug in the forge config system.

**Environment Info**
- OSX 10.14
- Java 1.8
- Forge 26.0.25
- Minecraft 1.14.2

**Comment by LexManos** [comment]
This is a known symptom of something in your code breaking.
cpw is working on properly showing the error screens. He should have it this weekend.
However the real cause of this issue is your code/event handlers somewhere. Read your log for more details.

**Comment by FoxSamu** [comment]
Ah, found the cause of the problem. It was just a sneaky 1.13 mod that was still in my mods folder. My fault, LOL...

**Comment by ProsperCraft** [comment]
I had the same problem with a 1.14.2 mod - 
https://github.com/MinecraftForge/MinecraftForge/issues/5816

Remove the mod and the world generates normally.
