### ISSUE TITLE
1.14.3 Killing Ender Dragon crashes the game

### ISSUE THREAD

**Issue by FullMetalMaster** [MinecraftForge/MinecraftForge#5897]
**Minecraft Version:** {Minecraft version}

**1.14.3:** {1.14.3. *- 27.0.23*}

**Full Log:** {Link to GitHub Gist with full latest.log}

**Steps to Reproduce:**
 1. go to the end
 2. Kill the ender dragon
 3. game crashes

**Description of bug:**

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 7/4/19 4:12 AM
Description: Colliding entity with block

java.lang.NullPointerException: Colliding entity with block
	at net.minecraft.entity.Entity.func_212321_a(Entity.java:2125) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.item.ItemEntity.func_212321_a(ItemEntity.java:320) ~[?:?] {}
	at net.minecraft.block.EndPortalBlock.func_196262_a(SourceFile:41) ~[?:?] {}
	at net.minecraft.block.BlockState.func_196950_a(BlockState.java:262) ~[?:?] {}
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:838) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:572) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.item.ItemEntity.func_70071_h_(ItemEntity.java:102) ~[?:?] {}
	at net.minecraft.world.ServerWorld.func_217479_a(ServerWorld.java:574) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.ServerWorld$$Lambda$4346/88379626.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.ServerWorld.func_72835_b(ServerWorld.java:381) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:813) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:748) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:609) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.Entity.func_212321_a(Entity.java:2125)
	at net.minecraft.entity.item.ItemEntity.func_212321_a(ItemEntity.java:320)
	at net.minecraft.block.EndPortalBlock.func_196262_a(SourceFile:41)
	at net.minecraft.block.BlockState.func_196950_a(BlockState.java:262)

-- Block being collided with --
Details:
	Block: Block{minecraft:end_portal}
	Block location: World: (2,64,1), Chunk: (at 2,4,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:838)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.item.ItemEntity)
	Entity ID: 949
	Entity Name: Torch
	Entity's Exact location: 2.38, 64.54, 1.01
	Entity's Block location: World: (2,64,1), Chunk: (at 2,4,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.06, -0.37, 0.04
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.func_213315_a(Entity.java:572)
	at net.minecraft.entity.item.ItemEntity.func_70071_h_(ItemEntity.java:102)
	at net.minecraft.world.ServerWorld.func_217479_a(ServerWorld.java:574)
	at net.minecraft.world.ServerWorld$$Lambda$4346/88379626.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.entity.item.ItemEntity)
	Entity ID: 949
	Entity Name: Torch
	Entity's Exact location: 2.38, 64.54, 1.01
	Entity's Block location: World: (2,64,1), Chunk: (at 2,4,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.06, -0.37, 0.04
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.ServerWorld.func_72835_b(ServerWorld.java:381)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['FullMetalMaster1'/239, l='17 forge test', x=15.97, y=94.24, z=-10.40]]
	Chunk stats: ServerChunkCache: 1789
	Level dimension: DimensionType{minecraft:the_end}
	Derived: true
	Level name: 17 forge test
	Level seed: 5933002064126558257
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (16,69,-176), Chunk: (at 0,4,0 in 1,-11; contains blocks 16,0,-176 to 31,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1702 game time, 1702 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 144194 (now: false), thunder time: 71208 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:813)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:748)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:609)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2867275992 bytes (2734 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	FML: New FML!
	Loaded coremods (and transformers): Nothing
	Player Count: 1 / 8; [ServerPlayerEntity['FullMetalMaster1'/239, l='17 forge test', x=15.97, y=94.24, z=-10.40]]
	Data Packs: vanilla, mod:xaerominimap, mod:worldedit, mod:waila, mod:waddles, mod:uteamcore, mod:usefulbackpacks, mod:tolaserblade, mod:reap, mod:practicaltools, mod:philosopher, mod:mobcatcher, mod:metalbarrels, mod:lightoverlay-forge, mod:jei, mod:inventorysorter, mod:gobber2, mod:forge, mod:forbidden_arcanus, mod:fastleafdecay, mod:essentials, mod:doggytalents, mod:corpse, mod:cfm
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by Unnoen** [comment]
There is a section specifically for the log/crash and please list *exactly* what you're doing in the steps to reproduce.

**Comment by FullMetalMaster** [comment]
updated the steps sorry havent done much of this before.. all new to me ;;

**Comment by m00nl1ght-dev** [comment]
This is fixed in #5833

**Comment by FullMetalMaster** [comment]
okay for 1.14.3? bc the lastest out rn still crashes

**Comment by FullMetalMaster** [comment]
lastest for 1.14.3 is forge 1.14.3 - 27.0.23

**Comment by m00nl1ght-dev** [comment]
Yes, that pull request has not been merged yet.

**Comment by FullMetalMaster** [comment]
then its not FiXeD iS iT?

**Comment by williewillus** [comment]
When this ticket is closed and the PR is merged, then it's fixed. Until then, try not to spam the issue.

**Comment by FullMetalMaster** [comment]
> When this ticket is closed and the PR is merged, then it's fixed. Until then, try not to spam the issue.

sorry for the spam but i havent seen an update to forge. ill wait ig.

**Comment by williewillus** [comment]
fixed in 27.0.24
