### ISSUE TITLE
crashing when switching tab

### ISSUE THREAD

**Issue by voidegg** [MinecraftForge/MinecraftForge#5898]
forge ver14.23.2838 
every time when i switch page in creative inventory the game crashes

crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/4/19 6:06 PM
Description: Rendering ingredient

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleStaticModelSourceRenderer.func_188616_a(CompatibleStaticModelSourceRenderer.java:101)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:63)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_101_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:615)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleStaticModelSourceRenderer.func_188616_a(CompatibleStaticModelSourceRenderer.java:101)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)

-- Ingredient being rendered --
Details:
	Ingredient Mod: Modern Warfare
	Ingredient Info: 1xitem.mw_Murasaki@0 mw:murasaki
Stacktrace:
	at mezz.jei.util.ErrorUtil.createRenderIngredientException(ErrorUtil.java:256)
	at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:34)
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157)
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
	at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:62)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_101_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:575)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:615)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (514, 340). Absolute: (1029, 25)
	Screen size: Scaled: (683, 353). Absolute: (1366, 706). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Eye_Of_The_Sky'/202, l='MpServer', x=-130.70, y=78.49, z=-274.27]]
	Chunk stats: MultiplayerChunkCache: 553, 553
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-119,64,-277), Chunk: (at 9,4,11 in -8,-18; contains blocks -128,0,-288 to -113,255,-273), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1153 game time, 1153 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 98 total; [EntityRabbit['Rabbit'/29, l='MpServer', x=-210.50, y=64.00, z=-225.50], EntityRabbit['Rabbit'/30, l='MpServer', x=-209.50, y=64.00, z=-223.50], EntityCreeper['Creeper'/33, l='MpServer', x=-202.50, y=16.00, z=-324.50], EntityZombie['Zombie'/34, l='MpServer', x=-196.50, y=41.00, z=-303.81], EntitySkeleton['Skeleton'/35, l='MpServer', x=-197.50, y=43.00, z=-307.50], EntitySkeleton['Skeleton'/36, l='MpServer', x=-198.50, y=43.00, z=-307.50], EntitySkeleton['Skeleton'/37, l='MpServer', x=-204.27, y=28.00, z=-291.50], EntityEnderman['Enderman'/38, l='MpServer', x=-199.48, y=27.00, z=-293.27], EntityEnderman['Enderman'/39, l='MpServer', x=-204.50, y=27.00, z=-286.50], EntityEnderman['Enderman'/40, l='MpServer', x=-192.50, y=17.00, z=-219.50], EntitySkeleton['Skeleton'/46, l='MpServer', x=-183.50, y=28.00, z=-353.50], EntityZombie['Zombie'/47, l='MpServer', x=-170.50, y=24.00, z=-339.80], EntitySkeleton['Skeleton'/48, l='MpServer', x=-188.50, y=37.00, z=-336.50], EntitySkeleton['Skeleton'/49, l='MpServer', x=-181.50, y=23.00, z=-330.50], EntitySkeleton['Skeleton'/50, l='MpServer', x=-198.47, y=41.00, z=-314.73], EntityRabbit['Rabbit'/51, l='MpServer', x=-177.11, y=70.00, z=-276.66], EntitySkeleton['Skeleton'/52, l='MpServer', x=-191.50, y=25.00, z=-260.50], EntityCreeper['Creeper'/53, l='MpServer', x=-186.50, y=25.00, z=-243.50], EntityCreeper['Creeper'/54, l='MpServer', x=-187.50, y=34.00, z=-245.50], EntitySquid['Squid'/55, l='MpServer', x=-187.92, y=55.93, z=-237.48], EntitySquid['Squid'/56, l='MpServer', x=-182.03, y=57.04, z=-240.83], EntitySquid['Squid'/57, l='MpServer', x=-188.24, y=52.39, z=-228.87], EntitySquid['Squid'/58, l='MpServer', x=-179.62, y=54.71, z=-233.53], EntitySkeleton['Skeleton'/65, l='MpServer', x=-171.31, y=25.00, z=-330.50], EntitySquid['Squid'/66, l='MpServer', x=-159.08, y=60.64, z=-322.16], EntitySpider['Spider'/67, l='MpServer', x=-163.50, y=21.00, z=-285.50], EntityRabbit['Rabbit'/68, l='MpServer', x=-175.50, y=71.00, z=-284.25], EntityRabbit['Rabbit'/69, l='MpServer', x=-171.50, y=65.00, z=-277.50], EntitySquid['Squid'/70, l='MpServer', x=-161.02, y=61.08, z=-255.94], EntitySquid['Squid'/71, l='MpServer', x=-164.24, y=59.32, z=-261.04], EntitySquid['Squid'/72, l='MpServer', x=-158.37, y=57.91, z=-245.48], EntitySquid['Squid'/80, l='MpServer', x=-157.64, y=59.16, z=-324.56], EntitySquid['Squid'/81, l='MpServer', x=-160.49, y=59.28, z=-331.89], EntityRabbit['Rabbit'/82, l='MpServer', x=-151.22, y=70.00, z=-297.02], EntitySquid['Squid'/83, l='MpServer', x=-156.16, y=57.63, z=-252.57], EntitySquid['Squid'/84, l='MpServer', x=-149.81, y=59.35, z=-254.57], EntitySquid['Squid'/85, l='MpServer', x=-154.73, y=55.15, z=-261.84], EntitySquid['Squid'/86, l='MpServer', x=-163.45, y=56.82, z=-259.49], EntityZombie['Zombie'/88, l='MpServer', x=-129.50, y=46.00, z=-309.50], EntityRabbit['Rabbit'/89, l='MpServer', x=-147.54, y=71.00, z=-285.36], EntityZombie['Zombie'/90, l='MpServer', x=-138.50, y=23.00, z=-266.50], EntitySkeleton['Skeleton'/91, l='MpServer', x=-134.50, y=26.00, z=-267.50], EntitySquid['Squid'/105, l='MpServer', x=-115.33, y=61.14, z=-315.76], EntitySquid['Squid'/106, l='MpServer', x=-112.97, y=59.22, z=-317.85], EntitySkeleton['Skeleton'/107, l='MpServer', x=-125.50, y=44.00, z=-299.50], EntityItem['item.tile.mushroom'/108, l='MpServer', x=-127.88, y=18.00, z=-281.25], EntitySquid['Squid'/113, l='MpServer', x=-103.75, y=57.13, z=-321.39], EntitySquid['Squid'/114, l='MpServer', x=-100.67, y=54.90, z=-325.72], EntitySquid['Squid'/115, l='MpServer', x=-94.82, y=55.03, z=-324.94], EntitySquid['Squid'/116, l='MpServer', x=-104.44, y=49.33, z=-321.64], EntityBat['Bat'/372, l='MpServer', x=-79.99, y=24.10, z=-339.58], EntityZombie['Zombie'/117, l='MpServer', x=-99.50, y=15.00, z=-305.50], EntitySkeleton['Skeleton'/118, l='MpServer', x=-103.50, y=15.00, z=-297.79], EntitySquid['Squid'/119, l='MpServer', x=-90.93, y=53.62, z=-313.39], EntitySquid['Squid'/120, l='MpServer', x=-106.90, y=56.22, z=-323.55], EntityItem['item.tile.gravel'/121, l='MpServer', x=-107.88, y=58.00, z=-303.88], EntitySkeleton['Skeleton'/122, l='MpServer', x=-99.70, y=18.00, z=-198.30], EntitySkeleton['Skeleton'/123, l='MpServer', x=-96.50, y=17.00, z=-198.50], EntityCreeper['Creeper'/124, l='MpServer', x=-99.50, y=22.00, z=-194.50], EntityCreeper['Creeper'/125, l='MpServer', x=-101.50, y=22.00, z=-194.50], EntityBat['Bat'/386, l='MpServer', x=-176.34, y=33.24, z=-306.75], EntityZombieVillager['Zombie Villager'/132, l='MpServer', x=-81.25, y=24.00, z=-350.48], EntityItem['item.tile.torch'/133, l='MpServer', x=-90.88, y=22.00, z=-325.93], EntitySkeleton['Skeleton'/134, l='MpServer', x=-95.50, y=23.00, z=-326.50], EntitySkeleton['Skeleton'/135, l='MpServer', x=-95.50, y=19.00, z=-314.75], EntityZombie['Zombie'/136, l='MpServer', x=-90.28, y=22.00, z=-314.54], EntitySquid['Squid'/137, l='MpServer', x=-83.75, y=58.30, z=-289.36], EntityCreeper['Creeper'/138, l='MpServer', x=-85.50, y=29.00, z=-240.50], EntitySquid['Squid'/139, l='MpServer', x=-82.98, y=58.63, z=-233.86], EntitySquid['Squid'/140, l='MpServer', x=-86.67, y=57.48, z=-232.36], EntitySquid['Squid'/141, l='MpServer', x=-90.67, y=61.62, z=-231.48], EntitySquid['Squid'/142, l='MpServer', x=-86.62, y=59.30, z=-228.64], EntityZombie['Zombie'/143, l='MpServer', x=-93.73, y=17.00, z=-203.45], EntityBat['Bat'/146, l='MpServer', x=-83.91, y=22.08, z=-199.61], EntityZombieVillager['Zombie Villager'/148, l='MpServer', x=-89.50, y=21.00, z=-203.50], EntityZombieVillager['Zombie Villager'/149, l='MpServer', x=-93.08, y=21.00, z=-201.25], EntityCreeper['Creeper'/150, l='MpServer', x=-94.22, y=21.00, z=-202.47], EntityCreeper['Creeper'/151, l='MpServer', x=-92.50, y=21.00, z=-198.50], EntitySkeleton['Skeleton'/157, l='MpServer', x=-65.50, y=23.00, z=-324.50], EntitySquid['Squid'/159, l='MpServer', x=-67.60, y=61.51, z=-306.62], EntitySquid['Squid'/160, l='MpServer', x=-71.73, y=61.69, z=-303.21], EntitySquid['Squid'/161, l='MpServer', x=-83.38, y=62.47, z=-283.47], EntitySquid['Squid'/162, l='MpServer', x=-75.14, y=61.85, z=-286.11], EntitySquid['Squid'/163, l='MpServer', x=-82.92, y=57.10, z=-280.97], EntityCreeper['Creeper'/164, l='MpServer', x=-74.50, y=23.00, z=-247.50], EntityCreeper['Creeper'/165, l='MpServer', x=-78.50, y=15.00, z=-214.50], EntityBat['Bat'/166, l='MpServer', x=-67.75, y=19.10, z=-218.46], EntityCreeper['Creeper'/167, l='MpServer', x=-71.50, y=28.00, z=-219.50], EntityBat['Bat'/168, l='MpServer', x=-66.75, y=21.63, z=-211.25], EntityBat['Bat'/169, l='MpServer', x=-65.35, y=23.02, z=-201.50], EntityBat['Bat'/170, l='MpServer', x=-66.56, y=25.10, z=-205.81], EntityCreeper['Creeper'/175, l='MpServer', x=-62.50, y=28.00, z=-323.50], EntityBat['Bat'/178, l='MpServer', x=-55.75, y=22.09, z=-258.54], EntitySpider['Spider'/180, l='MpServer', x=-53.03, y=27.00, z=-226.55], EntityZombie['Zombie'/181, l='MpServer', x=-53.50, y=27.00, z=-227.70], EntityZombie['Zombie'/182, l='MpServer', x=-54.50, y=27.00, z=-227.50], EntityBat['Bat'/183, l='MpServer', x=-58.56, y=14.68, z=-204.75], EntityPlayerSP['Eye_Of_The_Sky'/202, l='MpServer', x=-130.70, y=78.49, z=-274.27]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 653437472 bytes (623 MB) / 1539309568 bytes (1468 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID          | Version      | Source                        | Signature                                |
	|:------ |:----------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft   | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp         | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge       | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | applecore   | 3.2.0        | AppleCore-mc1.12.2-3.2.0.jar  | None                                     |
	| LCHIJA | jei         | 4.15.0.268   | jei_1.12.2-4.15.0.268.jar     | None                                     |
	| LCHIJA | appleskin   | 1.0.9        | AppleSkin-mc1.12-1.0.9.jar    | None                                     |
	| LCHIJA | baubles     | 1.5.2        | Baubles-1.12-1.5.2.jar        | None                                     |
	| LCHIJA | journeymap  | 1.12.2-5.5.4 | journeymap-1.12.2-5.5.4.jar   | None                                     |
	| LCHIJA | mousetweaks | 2.10         | MouseTweaks-2.10-mc1.12.2.jar | None                                     |
	| LCHIJA | mw          | 1.11.7.7     | mw-1.11.7.7_mc1.12.2.jar      | None                                     |
	| LCHIJA | theoneprobe | 1.4.28       | theoneprobe-1.12-1.4.28.jar   | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'Intel' Version: '3.0.0 - Build 8.15.10.2253' Renderer: 'Intel(R) HD Graphics Family'
	Launched Version: forge-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics Family GL version 3.0.0 - Build 8.15.10.2253, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-2310M CPU @ 2.10GHz

**Comment by Tfarcenim** [comment]
How is this related to Forge?

**Comment by FinnT730** [comment]
Read the 6th line, what does it say? please, don't report this, this is not a Forge issue.
Also, remove Modern Warfare, because that is you're issue, go to them, and let them fix this mess up, not blame Forge Devs for this, since they don't do something wrong.....

**Comment by DaemonUmbra** [comment]
Next time go to the forums first
