### ISSUE TITLE
[1.14.3] cant respawn after dying in the nether and the game crashes when killing the ender dragon

### ISSUE THREAD

**Issue by BruhPotato420** [MinecraftForge/MinecraftForge#5912]
**Minecraft Version:** {Minecraft version}

**Forge Version:** {Forge version. *Version number, not latest/rb*}

**Full Log:** {Link to GitHub Gist with full latest.log}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of bug:**

**Comment by FinnT730** [comment]
Why does this bloody issue exist? There is no way to recreate what you did, and we don't even know if it was a mod or not.

**Comment by Zode** [comment]
I'm actually getting similar behaviour in nether/end when a player dies. 


```[13:22:44.674] [Client thread/INFO] [minecraft/NewChatGui]: [CHAT] devaccount fell from a high place
[13:22:45.890] [Server thread/DEBUG] [ne.mi.co.DimensionManager/DIMS]: Queueing dimension 1 to unload
[13:22:46.954] [Server thread/DEBUG] [ne.mi.co.DimensionManager/DIMS]: Queueing dimension 1 to unload
[13:22:46.954] [Server thread/INFO] [minecraft/ChunkManager]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[13:22:46.962] [Server thread/ERROR] [minecraft/ChunkManager]: Couldn't load chunk [-293, 111]
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:1.8.0_212] {}
	at java.io.RandomAccessFile.seek(Unknown Source) ~[?:1.8.0_212] {}
	at net.minecraft.world.chunk.storage.RegionFile.func_222666_a(RegionFile.java:100) ~[?:?] {}
	at net.minecraft.world.chunk.storage.RegionFileCache.readChunk(RegionFileCache.java:47) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkManager.loadChunkData(ChunkManager.java:733) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:463) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_212] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:131) [?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:106) [?:?] {pl:accesstransformer:B}
	at net.minecraft.world.chunk.ServerChunkProvider$ChunkExecutor.driveOne(ServerChunkProvider.java:460) [?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:119) [?:?] {pl:accesstransformer:B}
	at net.minecraft.world.chunk.ServerChunkProvider.getChunk(ServerChunkProvider.java:109) [?:?] {pl:accesstransformer:B}
	at net.minecraft.world.World.getChunk(World.java:175) [?:?] {pl:accesstransformer:B}
	at net.minecraft.world.IWorldReader.getChunk(IWorldReader.java:98) [?:?] {}
	at net.minecraft.world.World.getChunk(World.java:171) [?:?] {pl:accesstransformer:B}
	at net.minecraft.world.World.getBlockState(World.java:423) [?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.travel(LivingEntity.java:1963) [?:?] {}
	at net.minecraft.entity.player.PlayerEntity.travel(PlayerEntity.java:1536) [?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.livingTick(LivingEntity.java:2365) [?:?] {}
	at net.minecraft.entity.player.PlayerEntity.livingTick(PlayerEntity.java:506) [?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2179) [?:?] {}
	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:221) [?:?] {pl:accesstransformer:B}
	at net.minecraft.entity.player.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:381) [?:?] {pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.tick(ServerPlayNetHandler.java:183) [?:?] {}
	at net.minecraft.network.NetworkManager.tick(NetworkManager.java:257) [?:?] {}
	at net.minecraft.network.NetworkSystem.tick(NetworkSystem.java:148) [?:?] {}
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:863) [?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:781) [?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118) [?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_212] {}
[13:23:57.871] [Client thread/INFO] [minecraft/Minecraft]: Stopping!

**Comment by LexManos** [comment]
Unable to reproduce, Able to kill dragon.  And respawn from the nether in overworld just fine.

**Comment by aelfwyne** [comment]
Having the exact same issues. No mods loaded, plain Forge. Crashes when players die in the nether. 

EDIT: I did have a datpack loaded, not a mod when testing. Turns out this happens with both a Mod AND a Datapack, the player gravestone mod OR player graves datapack from XisumaVoid. It looks like they're hitting some kind of Forge bug but I'm not expert enough to figure out how to show which it is.

**Comment by LexManos** [comment]
Provide more details, your setup, logs, etc..
As stated I can not reproduce when taking the steps provided {Killing the dragon, or respawning from the nether}

**Comment by aelfwyne** [comment]
Minecraft 1.14.3.. I haven't figured out exactly what causes it...

What I CAN tell you it is it Forge server 1.14.3-27.0.57, started with 0.50 and the problem was present there. I THOUGHT I had narrowed it down to gravestone mod, but I deleted that mod completely and it's still doing it. I also considered that Biomes O Plenty may have been causing the issue - so I tried it without BOP and the issue remained. Also tried running the game with zero datapacks (I have datapacks from Xisumavoid installed) and it STILL caused the issue. The only thing that seemed to help keep it from happening constantly was deleting gravestone. It also crashed with the player-graves datapack, as I tried to replace it with that. NEITHER ONE is loaded, and while in my testing I was able to die several times without crashing it, it has started doing it again just a few hours later.

Problem is the player dies in lava in the nether, tries to respawn, game crashes. It's REALLY that simple to reproduce. It didn't do it for a few tries while I was testing, but it started doing it again. I have tried telling the particular player to STOP dying in the Nether, but you can imagine that doesn't go over well. 

log:
https://pastebin.com/c4NG5sRX

**Comment by LexManos** [comment]
Just tried dieing in the nether 30 times with https://www.curseforge.com/minecraft/mc-mods/gravestone-mod/files/2738569
Still unable to reproduce.
Steps:
Install the linked mod
Go to Nether
Die in lava
Respawn
Repeat 30x
No issues.

The issue is that the region file is closed without being unloaded.
Forge does not touch any part of that. So what it SOUNDS like is that there is a mod in your setup that is closing the region file. Which is a incredibly stupid thing to do. Only real way to track it down would be to get a reproduce able case. And then read the stack for when its closed.

For now, go to the forums, Provide FULL logs. Full links to exact versions of every mod installed. Once you or someone tracks down a way to reproduce this I can help. Until then, it's not a issue in Forge, so locking.
