### ISSUE TITLE
Minecraft 1.8 Clients crashes

### ISSUE THREAD

**Issue by ApplyStudio** [MinecraftForge/MinecraftForge#5939]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 15.07.19 19:29
Description: Updating screen events

java.lang.NoClassDefFoundError: gnu/trove/map/TIntObjectMap
	at net.minecraft.client.Minecraft.launchIntegratedServer(Minecraft.java:2323)
	at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:193)
	at net.minecraft.client.gui.GuiSelectWorld$List.elementClicked(GuiSelectWorld.java:269)
	at net.minecraft.client.gui.GuiSlot.func_178039_p(GuiSlot.java:348)
	at net.minecraft.client.gui.GuiSelectWorld.handleMouseInput(GuiSelectWorld.java:81)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:554)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1768)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1101)
	at net.minecraft.client.Minecraft.run(Minecraft.java:410)
	at net.minecraft.client.main.Main.main(Main.java:114)
Caused by: java.lang.ClassNotFoundException: gnu.trove.map.TIntObjectMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.Minecraft.launchIntegratedServer(Minecraft.java:2323)
	at net.minecraft.client.gui.GuiSelectWorld.func_146615_e(GuiSelectWorld.java:193)
	at net.minecraft.client.gui.GuiSelectWorld$List.elementClicked(GuiSelectWorld.java:269)
	at net.minecraft.client.gui.GuiSlot.func_178039_p(GuiSlot.java:348)
	at net.minecraft.client.gui.GuiSelectWorld.handleMouseInput(GuiSelectWorld.java:81)
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:554)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiMainMenu
Stacktrace:
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1768)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1101)
	at net.minecraft.client.Minecraft.run(Minecraft.java:410)
	at net.minecraft.client.main.Main.main(Main.java:114)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 258968520 bytes (246 MB) / 469762048 bytes (448 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: ApplyMod
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.31, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Alpvax** [comment]
Issue for the forums. But you won't get support there for 1.8. You need to update.
