### ISSUE TITLE
Can't find a direct cause for forge crashing on the loading screen. Does anyone mind helping me? (Forge 28.1.26 "Mod fluids must override createAttributes.")

### ISSUE THREAD

**Issue by ComicalTNM** [MinecraftForge/MinecraftForge#6201]
Crash Report:

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 10/1/19 9:22 PM
Description: Rendering overlay

java.lang.RuntimeException: Mod fluids must override createAttributes.
at net.minecraftforge.common.ForgeHooks.createVanillaFluidAttributes(ForgeHooks.java:858) ~[?:?] {re:classloading}
at net.minecraft.fluid.Fluid.createAttributes(Fluid.java:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraft.fluid.Fluid.getAttributes(Fluid.java:124) ~[?:?] {re:classloading,pl:accesstransformer:B}
at net.minecraftforge.client.ForgeHooksClient.lambda$gatherFluidTextures$0(ForgeHooksClient.java:563) ~[?:?] {re:classloading}
at net.minecraftforge.client.ForgeHooksClient$$Lambda$4078/1925134193.apply(Unknown Source) ~[?:?] {}
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_51] {}
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_51] {}
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_51] {}
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
at net.minecraftforge.client.ForgeHooksClient.gatherFluidTextures(ForgeHooksClient.java:565) ~[?:?] {re:classloading}
at net.minecraft.client.renderer.model.ModelBakery.(ModelBakery.java:157) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
at net.minecraftforge.client.model.ModelLoader.(ModelLoader.java:139) ~[?:?] {re:classloading}
at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:46) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:17) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading}
at net.minecraft.client.resources.ReloadListener$$Lambda$3445/1163065503.get(Unknown Source) ~[?:?] {}
at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51] {}
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at net.minecraftforge.common.ForgeHooks.createVanillaFluidAttributes(ForgeHooks.java:858)
at net.minecraft.fluid.Fluid.createAttributes(Fluid.java:118)
at net.minecraft.fluid.Fluid.getAttributes(Fluid.java:124)
at net.minecraftforge.client.ForgeHooksClient.lambda$gatherFluidTextures$0(ForgeHooksClient.java:563)
at net.minecraftforge.client.ForgeHooksClient$$Lambda$4078/1925134193.apply(Unknown Source)
at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
at java.util.Iterator.forEachRemaining(Iterator.java:116)
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)

-- Overlay render details --
Details:
Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:544)
at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:887)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384)
at net.minecraft.client.main.Main.main(SourceFile:155)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$354/1098737173.call(Unknown Source)
at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
Minecraft Version: 1.14.4
Minecraft Version ID: 1.14.4
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 3434450256 bytes (3275 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
CPUs: 4
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
ModLauncher: 4.0.0+61+ca3b447
ModLauncher launch target: fmlclient
ModLauncher naming: srg
ModLauncher services:
/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE
/forge-1.14.4-28.1.26.jar object_holder_definalize PLUGINSERVICE
/forge-1.14.4-28.1.26.jar runtime_enum_extender PLUGINSERVICE
/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE
/forge-1.14.4-28.1.26.jar capability_inject_definalize PLUGINSERVICE
/forge-1.14.4-28.1.26.jar runtimedistcleaner PLUGINSERVICE
/forge-1.14.4-28.1.26.jar fml TRANSFORMATIONSERVICE
FML: 28.1
Forge: net.minecraftforge:28.1.26
FML Language Providers:
javafml@28.1
minecraft@1
Mod List:
[1.14.4]+SecurityCraft+v1.8.12.2.jar SecurityCraft {securitycraft@v1.8.12.2 ENQUEUE_IMC}
Apotheosis-1.14.4-2.4.0.jar Apotheosis {apotheosis@2.4.0 ENQUEUE_IMC}
AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 ENQUEUE_IMC}
BadMobs-1.14.4-3.0.1.jar BadMobs {badmobs@3.0.1 ENQUEUE_IMC}
BetterAdvancements-1.14.4-0.1.0.87.jar Better Advancements {betteradvancements@0.1.0.87 ENQUEUE_IMC}
betteranimalsplus-1.14.4-7.1.0.jar Better Animals Plus {betteranimalsplus@7.1.0 ENQUEUE_IMC}
BetterAnimationsCollection2-v1.1b4-1.14.4.jar Better Animations Collection 2 {betteranimationscollection2@1.1b4 ENQUEUE_IMC}
BetterThanMending-1.3.1.jar BetterThanMending {betterthanmending@1.3.1 ENQUEUE_IMC}
bettertridentreturn-1.14.4-1.0.0.jar Better Trident Return {bettertridentreturn@1.0.0 ENQUEUE_IMC}
BiomesOPlenty-1.14.4-9.0.0.251-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.251 ENQUEUE_IMC}
caelus-FORGE-1.14.4-0.11.jar Caelus API {caelus@FORGE-1.14.4-0.11 ENQUEUE_IMC}
camera-1.4.5.jar Camera Mod {camera@1.4.5 ENQUEUE_IMC}
Clumps-4.0.0.jar Clumps {clumps@4.0.0 ENQUEUE_IMC}
colytra-FORGE-1.14.4-2.0-beta4.jar Colytra {colytra@FORGE-1.14.4-2.0-beta4 ENQUEUE_IMC}
CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a ENQUEUE_IMC}
Cucumber-1.14.4-2.0.3.jar Cucumber Library {cucumber@2.0.3 ENQUEUE_IMC}
Cyclic-1.14.4-0.0.9.jar Cyclic {cyclic@1.14.4-0.0.9 ENQUEUE_IMC}
DoggyTalents-1.14.4-1.15.1.4-universal.jar Doggy Talents {doggytalents@1.15.1.4 ENQUEUE_IMC}
elevatorid-1.14.4-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 ENQUEUE_IMC}
EnchantmentDescriptions-1.14.4-1.3.3.jar EnchantmentDescriptions {enchdesc@1.3.3 ENQUEUE_IMC}
extragolems-9.0.1.jar Extra Golems {golems@TODO-golems_version ENQUEUE_IMC}
FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 ENQUEUE_IMC}
FriendlyFire-1.14.4-3.0.1.jar FriendlyFire {friendlyfire@3.0.1 ENQUEUE_IMC}
furniture-7.0.0-pre5-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre5 ENQUEUE_IMC}
goodnightsleep-1.14.4-0.3.0.jar Good Night's Sleep {goodnightsleep@0.3.0 ENQUEUE_IMC}
gravestone-1.15.0.jar Gravestone Mod {gravestone@1.15.0 ENQUEUE_IMC}
guardillagers-1.14.4-1.0.1.jar GuardIllagers {guardillagers@1.0.1 ENQUEUE_IMC}
ironchest-1.14.4-9.0.4.jar Iron Chests {ironchest@1.14.3-9.0.3 ENQUEUE_IMC}
IronJetpacks-1.14.4-2.0.2.jar Iron Jetpacks {ironjetpacks@2.0.2 ENQUEUE_IMC}
jei-1.14.4-6.0.0.13.jar Just Enough Items {jei@6.0.0.13 ENQUEUE_IMC}
lumberjack-2.0.0.jar LumberJack {lumberjack@2.0.0 ENQUEUE_IMC}
lycanitesmobs-1.14.4-2.1.0.2.jar Lycanites Mobs {lycanitesmobs@1.0 ENQUEUE_IMC}
mcjtylib-1.14-3.5.6-alpha.jar McJtyLib {mcjtylib@NONE ENQUEUE_IMC}
MobBattleMod-1.14.4-2.3.2.jar Mob Battle Mod {mobbattle@2.3.2 ENQUEUE_IMC}
modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 ENQUEUE_IMC}
Neat+1.5-19.jar Neat {neat@1.5-19 ENQUEUE_IMC}
Placebo-1.14.4-2.2.0.jar Placebo {placebo@2.2.0 ENQUEUE_IMC}
rftoolsbase-1.14-0.0.3-alpha.jar RFToolsBase {rftoolsbase@NONE ENQUEUE_IMC}
rftoolspower-1.14-1.2.3-alpha.jar RFToolsPower {rftoolspower@NONE ENQUEUE_IMC}
SilentGear-1.14.4-1.3.11+64.jar Silent Gear {silentgear@1.3.11+64 ENQUEUE_IMC}
SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 ENQUEUE_IMC}
supertools-1.14.4-2.3.jar Vanilla+ Tools {supertools@version ENQUEUE_IMC}
TrashSlot_1.14.4-10.4.5.jar TrashSlot {trashslot@10.4.5 ENQUEUE_IMC}
u_team_core-1.14.4-2.7.0.129.jar U Team Core {uteamcore@2.7.0.129 ENQUEUE_IMC}
useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 ENQUEUE_IMC}
Xaeros_Minimap_1.18.1.1_Forge_1.14.4.jar Xaero's Minimap {xaerominimap@1.18.1.1 ENQUEUE_IMC}
forge-1.14.4-28.1.26-universal.jar Forge {forge@28.1.26 ENQUEUE_IMC}
forge-1.14.4-28.1.26-client.jar Minecraft {minecraft@1.14.4 ENQUEUE_IMC}
Launched Version: 1.14.4-forge-28.1.26
LWJGL: 3.2.2 build 10
OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.64, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz

**Comment by tterrag1098** [comment]
The error tells you the exact problem.
