### ISSUE TITLE
BiomeDictionary.getTypes infinite recursion

### ISSUE THREAD

**Issue by Player3324** [MinecraftForge/MinecraftForge#6283]
There is an old bug where the lack of type registrations in combination with failure to guess any types results in infinite recursion from trying to log the guessed types.

```
java.lang.StackOverflowError
        at net.minecraftforge.common.BiomeDictionary.getBiomeInfo(BiomeDictionary.java:330)
        at net.minecraftforge.common.BiomeDictionary.hasAnyType(BiomeDictionary.java:262)
        at net.minecraftforge.common.BiomeDictionary.ensureHasTypes(BiomeDictionary.java:338)
        at net.minecraftforge.common.BiomeDictionary.getTypes(BiomeDictionary.java:225)
        at net.minecraftforge.common.BiomeDictionary.ensureHasTypes(BiomeDictionary.java:341)
        at net.minecraftforge.common.BiomeDictionary.getTypes(BiomeDictionary.java:225)
        at net.minecraftforge.common.BiomeDictionary.ensureHasTypes(BiomeDictionary.java:341)
        at net.minecraftforge.common.BiomeDictionary.getTypes(BiomeDictionary.java:225)
        at net.minecraftforge.common.BiomeDictionary.ensureHasTypes(BiomeDictionary.java:341)
[...]
```

**Comment by DaemonUmbra** [comment]
Can you please identify your Minecraft and Forge versions? The templates are there for a reason.

**Comment by Player3324** [comment]
As indicated this most certainly happens with any version from the last several years, i checked the code for relevant changes..
