### ISSUE TITLE
Can anyone tell me what this crash is, why its happening....

### ISSUE THREAD

**Issue by CarlucciMods** [MinecraftForge/MinecraftForge#6522]
**Minecraft Version: 1 14 4

**Forge Version:** 28.2.0

**Logs:** 
[crash-2020-02-18_17.34.17-client.txt](https://github.com/MinecraftForge/MinecraftForge/files/4222001/crash-2020-02-18_17.34.17-client.txt)

**Steps to Reproduce:**
 1. go into sea
 2. come to a underwater temple like structure, white bricks with chest, not the blue temple.
 3. ...crash, but not only that the map will never load agian. Corrupted

**Description of issue:**
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/18/20 5:34 PM
Description: Unexpected error

java.lang.UnsupportedOperationException: No bounds for empty shape.
	at net.minecraft.util.math.shapes.VoxelShape.func_197752_a(SourceFile:47) ~[?:?] {re:classloading}
	at com.buuz135.industrial.proxy.client.event.IFClientEvents.lambda$blockOverlayEvent$0(IFClientEvents.java:78) ~[?:2.1.2] {re:classloading}
	at com.buuz135.industrial.proxy.client.event.IFClientEvents$$Lambda$8339/1715403642.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at com.buuz135.industrial.proxy.client.event.IFClientEvents.blockOverlayEvent(IFClientEvents.java:76) ~[?:2.1.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_639_IFClientEvents_blockOverlayEvent_DrawBlockHighlightEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:157) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:786) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:1217) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:1030) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:790) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.0.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/379963364.call(Unknown Source) [forge-1.14.4-28.2.0.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.util.math.shapes.VoxelShape.func_197752_a(SourceFile:47)
	at com.buuz135.industrial.proxy.client.event.IFClientEvents.lambda$blockOverlayEvent$0(IFClientEvents.java:78)
	at com.buuz135.industrial.proxy.client.event.IFClientEvents$$Lambda$8339/1715403642.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.buuz135.industrial.proxy.client.event.IFClientEvents.blockOverlayEvent(IFClientEvents.java:76)
	at net.minecraftforge.eventbus.ASMEventHandler_639_IFClientEvents_blockOverlayEvent_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:157)
	at sun.reflect.GeneratedMethodAccessor83.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:786)
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:1217)
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:1030)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Carlucci_Ace'/73811, l='MpServer', x=342.42, y=55.26, z=-2742.58]]
	Chunk stats: Client Chunk Cache: 529, 322
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (16,63,161), Chunk: (at 0,3,1 in 1,10; contains blocks 16,0,160 to 31,255,175), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 321674 game time, 325938 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$419/379963364.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5102236816 bytes (4865 MB) / 10703863808 bytes (10208 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.0
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotori_scala@2.13.1-build-6
	Mod List: 
		enchantedbookredesign-1.1.jar Enchanted Book Redesign {enchantedbookredesign@1.1 DONE}
		nether+-1.4.1-1.14.4.jar nether+ {netherplus@1.0.0 DONE}
		CyclopsCore-1.14.4-1.6.1.jar Cyclops Core {cyclopscore@1.6.1 DONE}
		BetterSigns-1.0_v1.14.4.jar Better Signs {bettersigns@1.0 DONE}
		Uppers-0.1.11.jar Uppers {uppers@0.1.11 DONE}
		extrabows-v1.14.4 b9.jar Extra Bows {extrabows@v1.14.4 b9 DONE}
		SilentMechanisms-1.14.4-0.6.13+49.jar Silent's Mechanisms {silents_mechanisms@0.6.13+49 DONE}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 DONE}
		ForgeEndertech-1.14.4-5.2.0.1-build.0073.jar Forge Endertech {forgeendertech@5.2.0.1 DONE}
		xnet-1.14-1.8.7-alpha.jar XNet {xnet@1.14-1.8.7-alpha DONE}
		JRFTL+[1.14.4]-1.1.jar JRFTL {jrftl@1.1 DONE}
		CookingForBlockheads_1.14.4-7.4.4.jar Cooking for Blockheads {cookingforblockheads@7.4.4 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		Powah-1.14.4-0.2.7.jar Powah {powah@0.2.7 DONE}
		rangedpumps-0.6.1.jar Ranged Pumps {rangedpumps@0.6.1 DONE}
		Fence+Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version DONE}
		u_team_core-1.14.4-2.8.2.150.jar U Team Core {uteamcore@2.8.2.150 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		JustEnoughResources-1.14.4-0.10.1.74.jar Just Enough Resources {jeresources@0.10.1.74 DONE}
		ExpOre-1.14.4-1.4.jar Exp Ore Block Mod {exp_ore@1.4 DONE}
		BetterThanMending-1.3.2.jar BetterThanMending {betterthanmending@1.3.2 DONE}
		TOOLKIT-1.4.2.jar Tool Kit {toolkit@1.4.2 DONE}
		shetiphiancore-1.14-3.6.0.jar ShetiPhian-Core {shetiphiancore@3.6.0 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		simpleores-1.14.4-2.0.6.0.jar Simple Ores {simpleores@1.14.4-2.0.6.0 DONE}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 DONE}
		useful_backpacks-1.14.4-1.7.6.60.jar Useful Backpacks {usefulbackpacks@1.7.6.60 DONE}
		torchmaster-2.0.0-rc2.jar Torchmaster {torchmaster@2.0.0-rc2 DONE}
		endertanks-1.14-1.7.0b.jar EnderTanks {endertanks@1.7.0 DONE}
		AmbientSounds_v3.0.16_mc1.14.4.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		Lollipop-1.14.4-0.0.23.jar Lollipop {lollipop@0.0.23 DONE}
		practicaltools-1.14.4-1.4.jar Practical Tools {practicaltools@1.14.4-1.4 DONE}
		simplefarming-1.14.4-1.2.7.jar Simple Farming {simplefarming@1.14.4-1.2.7 DONE}
		CatchEverythingInBook-1.14.4-1.0.1-forge.jar Catch Everything In Book {catcheverythinginbook@1.14.4-1.0.1-forge DONE}
		SolarFluxReborn-1.14.4-14.1.5.jar Solar Flux Reborn {solarflux@14.1.5 DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		elevatorid-1.14.4-1.5.2.jar Elevator Mod {elevatorid@1.14.4-1.5.2 DONE}
		ChunkNoGoByeBye-1.14.4-1.0.3.jar ChunkNoGoByeBye {chunknogobyebye@1.14.4-1.0.3 DONE}
		globalxp-1.14.4-v1.4.10.jar Global XP {globalxp@v1.4.10 DONE}
		YAMDA-4.0.1.jar YAMDA {yamda@4.0.1 DONE}
		instantunify-1.14.4-1.0.3.jar InstantUnify {instantunify@1.0.3 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		sfm_1.14-1.0.jar Snowballs Freeze Mobs {sfm@1.0 DONE}
		Cyclic-1.14.4-0.1.3.jar Cyclic {cyclic@1.14.4-0.1.3 DONE}
		Sauuuuucey's Ores-1.14.4-1.3-release.jar Sauuuuucey's Ores {sauuuuuceysores@1.3-release DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		TrashSlot_1.14.4-10.4.8.jar TrashSlot {trashslot@10.4.8 DONE}
		EquipmentTooltips-1.14.4-1.3.2+10.jar Equipment Tooltips {equipmenttooltips@1.3.2+10 DONE}
		bountifulbaubles-1.14.4-0.0.2.jar Bountiful Baubles {bountifulbaubles@NONE DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		AttributeFix-1.14.4-3.0.3.jar AttributeFix {attributefix@3.0.3 DONE}
		caelus-FORGE-1.14.4-1.0.1.2.jar Caelus API {caelus@FORGE-1.14.4-1.0.1.2 DONE}
		Waystones_1.14.4-5.1.1.jar Waystones {waystones@5.1.1 DONE}
		MoreOresInONE-1.5.jar More Ores in ONE {moreoresinone@1.5 DONE}
		OresAboveDiamonds-1.14.4 v3.0.jar Ores Above Diamonds {oresabovediamonds@1.4 DONE}
		DimStorage-1.14.4-2.3.1.jar DimStorage {dimstorage@2.3.1 DONE}
		BasicNetherOres-1.14.4-3.2.2.jar Basic Nether Ores {bno@3.2.2 DONE}
		AdHooks-1.14.4-4.0.0.2-build.0072.jar Advanced Hook Launchers {adhooks@4.0.0.2 DONE}
		FarmingForBlockheads_1.14.4-5.3.2.jar Farming for Blockheads {farmingforblockheads@5.3.2 DONE}
		mcjtylib-1.14-3.5.17-alpha.jar McJtyLib {mcjtylib@1.14-3.5.17-alpha DONE}
		rftoolsbase-1.14-0.0.12-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.12-alpha DONE}
		ClickMachine-1.14.4-2.1.2.jar Click Machine {clickmachine@2.1.2 DONE}
		travellersboots-1.14.4-1.2.2.jar Traveller's Boots {travellersboots@1.2.2 DONE}
		CraftingSpawn-1.14.4-0.1.1.jar Crafting Spawn {craftingspawn@0.1.1 DONE}
		rftoolspower-1.14-1.2.12-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.12-alpha DONE}
		forge-1.14.4-28.2.0-universal.jar Forge {forge@28.2.0 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		Trashed-1.14.4-1.1.1.jar Trashed {trashed@1.1.1 DONE}
		forge-1.14.4-28.2.0-client.jar Minecraft {minecraft@1.14.4 DONE}
		Flopper-1.14.4-1.0.6.jar Flopper {flopper@1.0.6 DONE}
		EnchantmentDescriptions-1.14.4-1.3.9.jar EnchantmentDescriptions {enchdesc@1.3.9 DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		simplefluidtanks-1.14.4-1.8.0.1.jar Simple Fluid Tanks {simplefluidtanks@1.14.4-1.8.0.1 DONE}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.14.4-2.2.10.jar Titanium {titanium@2.2.10 DONE}
		compactores-1.14.4-1.2.2.jar Compact Ores {compactores@1.2.2 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		Durability101-1.14-0.0.3.jar Durability101 {durability101@0.0.3 DONE}
		LargeFluidTank-14.9.6.jar FluidTank {fluidtank@14.9.6 DONE}
		extragolems-9.0.5.jar Extra Golems {golems@9.0.5 DONE}
		Exotic Ores 1.14-0.8.jar Exotic Ores {exotic_ores@0.8.0 DONE}
		Quark-r2.0-210.jar Quark {quark@r2.0-210 DONE}
		gravestone-1.15.2.jar Gravestone Mod {gravestone@1.15.2 DONE}
		corail_recycler-4.0.2-1.14.4.jar Corail Recycler {corail_recycler@4.0.2 DONE}
		polyores-1.2.jar Poly's Ores {polyores@1.2 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		InventoryHud_1.14.4.forge.2.0.jar Inventory HUD+(Forge edition) {inventoryhud@2.0 DONE}
		InstantLava_1.13.2-1.1.1.jar InstantLava {instantlava@1.1.1 DONE}
		FastFurnace-1.14.4-2.2.4.jar FastFurnace {fastfurnace@2.2.4 DONE}
		AppleSkin-mc1.14.4-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 DONE}
		ElementaryOres-1.14.4-0.0.1.jar Elementary Ores {elementaryores@1.14.4-0.0.1 DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		healingcf_1.14-1.7.jar Healing Campfire {healingcf@1.7 DONE}
		SuperTools-1.6b.jar Super Tools {supertools@1.6b DONE}
		luckyores-1.14.4-1.3.1.jar Lucky Ores Mod {luckyores@1.3 DONE}
		pn_1.14-1.0.jar Pet Names {pn@1.0 DONE}
		bigbuckets-1.0.0.jar BigBuckets {bigbuckets@1.0.0 DONE}
	Launched Version: 1.14.4-forge-28.2.0
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.19, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/Soartex_Fanver - 64x .zip, file/Nelliks-GUIs-2.6.0-1.14.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F5
	OptiFine Build: 20191204-141250
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.1.04.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 442.19
	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by CarlucciMods** [comment]
seems like when i brake a few blocks and i move through the area where they once were, thats when i get a freeze then crash.
