### ISSUE TITLE
i am being disconnected when i join my minecraft server 

### ISSUE THREAD

**Issue by TRR-Slimer** [MinecraftForge/MinecraftForge#6524]
this is all outputs from when i join untill when i am disconnected

[09:12:08] [User Authenticator #2/INFO]: UUID of player TRR_Slimer is 76e0af3d-286d-432a-a071-add12c4c3f9a
[09:12:08] [Netty IO #3/INFO] [FML]: Client protocol version 2
[09:12:08] [Netty IO #3/INFO] [FML]: Client attempting to join with 65 mods : NotEnoughItems@1.0.5.111,asielib@0.2.7,NEIAddons@1.12.10.33,weepingangels@3.3.2,battlegear2@1.7.10,iChunUtil@4.2.2,BiblioCraft@1.10.5,armourersWorkshop@1.7.10-0.33.0.84,EE3@0.3.507,PortalGun@4.0.0-beta-4,Morph@0.9.1,mcp@9.05,controlling@1.0.0,InventoryPets@1.1.2a,transformers@${version},MutantCreatures@1.4.8,MobiusCore@1.2.5,jewelrycraft2@1.1.4,pandorasbox@2.0.1,MobProperties@0.4.0,secretroomsmod@4.7.1,pacman@1.0.7,props@2.0.2,morehealth@6.3,Railcraft@9.6.1.0,NEIAddons|AppEng@1.12.10.33,TardisMod@0.99,GraviGun@4.0.0-beta,malisisdoors@1.7.10-1.4.3,CarpentersBlocks@3.3.6,lucky@5.1.0,malisiscore@1.7.10-0.10.5+unknown-b0.git-unknown,MapWriter@2.1.2,origin@3.3.0,FastCraft@1.25,Forge@10.13.4.1614,RDMenuServer@2.0.0.2,IronChest@6.0.60.741,NEIAddons|Botany@1.12.10.33,Opis@1.2.5,FoodPlus@3.2rS,HatStand@4.0.0,sus@4.1.2,CodeChickenCore@1.0.7.46,AnimationAPI@1.2.4,darkcore@0.3,securitycraft@v1.7.4.1,surpriseeggs@1.0.6,statues@2.1.3,FML@7.10.99.99,SSTOW@1.7.10-0.1-RC9-7,NEIAddons|Forestry@1.12.10.33,customnpcs@1.7.10d,adventurebackpack@1.7.10-0.8b,cfm@3.4.7,chisel@2.3.10.37,Baubles@1.0.1.10,NEIAddons|CraftingTables@1.12.10.33,NEIAddons|ExNihilo@1.12.10.33,mcheli@0.10.6,witchery@0.24.1,Hats@4.0.1,OreSpawn@1.7.10.20.3,SaintsCore@0.8,TrailMix@4.0.0
[09:12:08] [Netty IO #3/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[09:12:08] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[09:12:08] [Server thread/INFO]: TRR_Slimer[/127.0.0.1:50578] logged in with entity id 141 at (-13.610358113719975, 67.0, 190.50425166848126)
[09:12:08] [Server thread/INFO]: TRR_Slimer joined the game
[09:12:08] [Server thread/INFO] [STDOUT]: [io.darkcraft.darkcore.mod.DarkcoreMod:repostWarning:146]: RW
[09:12:08] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@7c84d37e:
java.lang.NoClassDefFoundError: org/lwjgl/input/Keyboard
        at com.nohero.morehealth.mod_moreHealthEnhanced.updateKeyBindings(mod_moreHealthEnhanced.java:333) ~[mod_moreHealthEnhanced.class:?]
        at com.nohero.morehealth.EventHandlers.PlayerHandler.onPlayerLogin(PlayerHandler.java:59) ~[PlayerHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_501_PlayerHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) ~[FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[09:12:08] [Server thread/ERROR] [FML]: Index: 24 Listeners:
[09:12:08] [Server thread/ERROR] [FML]: 0: NORMAL
[09:12:08] [Server thread/ERROR] [FML]: 1: ASM: Forge playerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 2: ASM: fastcraft.e@1cc4ef4d a(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 3: ASM: baubles.common.event.EventHandlerNetwork@5b3c6051 playerLoggedInEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 4: ASM: com.darkona.adventurebackpack.handlers.PlayerEventHandler@58633a33 playerLogsIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 5: ASM: noppes.npcs.ServerTickHandler@6af7f320 playerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 6: ASM: com.foodplus.core.updater.FoodPlusConnectionHandler@67064ef4 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 7: ASM: ichun.common.iChunUtil@574a8f86 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 8: ASM: com.inventorypets.LoginEventHandler@3c55531e onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 9: ASM: mods.battlegear2.BgPlayerTracker@1f67ccc9 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 10: ASM: morph.common.core.EventHandler@1348fc8e onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 11: ASM: INSTANCE onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 12: ASM: com.temportalist.origin.library.common.Origin$@4ff59ca3 onPlayerJoin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 13: ASM: org.freeforums.geforce.securitycraft.handlers.ForgeEventHandler@7e8c9dd7 onPlayerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 14: ASM: com.emoniph.witchery.common.ServerTickEvents@5792115d onPlayerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 15: ASM: codechicken.nei.ServerHandler@55383ce1 loginEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 16: ASM: pl.asie.lib.chat.NicknameNetworkHandler@28bc172f playerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 17: ASM: io.darkcraft.darkcore.mod.DarkcoreMod@590e4be5 repostWarning(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 18: ASM: com.pahimar.ee3.handler.PlayerEventHandler@1c4fd055 onPlayerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 19: ASM: gravigun.common.core.EventHandler@4cfa9194 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 20: ASM: hats.common.core.EventHandler@11dc0aca onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 21: ASM: com.mrcrayfish.furniture.handler.PlayerEvents@687af956 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 22: ASM: com.mrcrayfish.furniture.handler.SyncEvent@b07d623 onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 23: ASM: net.bdew.neiaddons.network.ServerHandler@644096e4 handlePlayerLoggedIn(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 24: ASM: com.nohero.morehealth.EventHandlers.PlayerHandler@1cae695a onPlayerLogin(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: 25: ASM: tardis.common.core.TardisDimensionRegistry@37e28ed sendPacket(Lcpw/mods/fml/common/gameevent/PlayerEvent$PlayerLoggedInEvent;)V
[09:12:08] [Server thread/ERROR] [FML]: HandshakeCompletionHandler exception
java.lang.NoClassDefFoundError: org/lwjgl/input/Keyboard
        at com.nohero.morehealth.mod_moreHealthEnhanced.updateKeyBindings(mod_moreHealthEnhanced.java:333) ~[mod_moreHealthEnhanced.class:?]
        at com.nohero.morehealth.EventHandlers.PlayerHandler.onPlayerLogin(PlayerHandler.java:59) ~[PlayerHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_501_PlayerHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) ~[FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[09:12:08] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel FML
java.lang.NoClassDefFoundError: org/lwjgl/input/Keyboard
        at com.nohero.morehealth.mod_moreHealthEnhanced.updateKeyBindings(mod_moreHealthEnhanced.java:333) ~[mod_moreHealthEnhanced.class:?]
        at com.nohero.morehealth.EventHandlers.PlayerHandler.onPlayerLogin(PlayerHandler.java:59) ~[PlayerHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_501_PlayerHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:550) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:180) ~[oi.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:463) ~[NetworkDispatcher.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:17) ~[HandshakeCompletionHandler.class:?]
        at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) ~[HandshakeCompletionHandler.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) ~[FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[09:12:08] [Server thread/WARN]: Failed to handle packet for /127.0.0.1:50578
java.lang.NullPointerException
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101) ~[FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at fastcraft.u.a(F:289) [fastcraft.jar:?]
        at fastcraft.H.aq(F:36) [fastcraft.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[09:12:08] [Server thread/INFO]: TRR_Slimer lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[09:12:08] [Server thread/INFO]: TRR_Slimer left the game

**Comment by TRR-Slimer** [comment]
sorry for the long string of info

**Comment by Unnoen** [comment]
We do not provide support for outdated versions of Minecraft, update to 1.14.4 or 1.15.2.
