### ISSUE TITLE
Running Forge crashes 1.12.2

### ISSUE THREAD

**Issue by Articuno1234** [MinecraftForge/MinecraftForge#6598]
**Minecraft Version:** {Minecraft version}
1.12.2
**Forge Version:** {Forge version. *Version number, not latest/rb*}
1.12.2 - 14.23.5.2768
&
1.12.2 - 14.23.5.2847

**Steps to Reproduce:**
 1. Running Forge

**Description of issue:**
When starting up a new install of forge and running it. It Instantly reads:
```
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more
```
Any ideas?

**Comment by FinnT730** [comment]
Update to a more modern version, so 1.14.4 and 1.15.2
And use Java 8 next time....

**Comment by camielverdult** [comment]
> Update to a more modern version, so 1.14.4 and 1.15.2
> And use Java 8 next time....

I am getting the same error. Can you propose an actual solution instead of a garbage workaround?
