### ISSUE TITLE
Crashes when a dimension has no players

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/MinecraftForge#6607]
**Minecraft Version:** 1.14.4, I have not tested 1.15.2 yet

**Forge Version:** 28.2.1

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
```
[07Apr2020 21:23:04.990] [Server thread/ERROR] [net.minecraft.world.server.ChunkManager/]: Couldn't load chunk [6, 12]
java.io.IOException: Stream Closed
	at java.io.RandomAccessFile.seek0(Native Method) ~[?:1.8.0_221]
	at java.io.RandomAccessFile.seek(Unknown Source) ~[?:1.8.0_221]
	at net.minecraft.world.chunk.storage.RegionFile.func_222666_a(RegionFile.java:100) ~[?:?]
	at net.minecraft.world.chunk.storage.RegionFileCache.func_219099_e(SourceFile:48) ~[?:?]
	at net.minecraft.world.server.ChunkManager.func_219178_f(ChunkManager.java:775) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:474) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_221]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:550) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:135) [?:?]
	at net.minecraft.world.World.func_217353_a(World.java:164) [?:?]
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:94) [?:?]
	at net.minecraft.world.World.func_212866_a_(World.java:160) [?:?]
	at net.minecraft.world.World.func_175726_f(World.java:156) [?:?]
	at net.minecraft.world.World.func_175625_s(World.java:840) [?:?]
	at futurepack.depend.api.helper.HelperEnergyTransfer$EnergyUser.isValidBlock(HelperEnergyTransfer.java:241) [?:1.14.4-28.0.51]
	at futurepack.common.FPBlockSelector.getValidBlocks(FPBlockSelector.java:248) [?:1.14.4-28.0.51]
	at futurepack.depend.api.helper.HelperEnergyTransfer.spreadPower(HelperEnergyTransfer.java:291) [?:1.14.4-28.0.51]
	at futurepack.common.block.inventory.TileEntityFlashServer.func_73660_a(TileEntityFlashServer.java:148) [?:1.14.4-28.0.51]
	at net.minecraft.world.World.func_217391_K(World.java:621) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```
After this the watchdog kills the server as the tick is waiting on a crashed Completeable Feature.

**Steps to Reproduce:**
 1. Acces getChunk from the server thread somehow, getBlockState works. It doenst matter if called from tileEntity or completeable feature running on the main thread
2. leave the dimension so all chunks get unloaded
3. crash
I can repdroduce this without problems on my server, ~~I have not tested single player yet.~~ I was not able to reproduce this in singleplayer.

**Description of issue:**
It crashes when you try to access a chunk stored in a file already closed. Note that the server ticked the tileentity so the chunk was still loaded.

**Comment by Shadows-of-Fire** [comment]
Please update this issue if this problem is still present in 1.16 or higher.
