### ISSUE TITLE
Forge error custom pack manager.. please help

### ISSUE THREAD

**Issue by cmspeedau** [MinecraftForge/MinecraftForge#6625]
when i go to build the pack this is the error i get. im not sure if its a forge error or a problem with the packmaker code.. if someone could help it would be greatful
packmaker location https://github.com/cmspeedau/Launcher

Installing forge-1.14.4-28.2.4-installer.jar...
[warning] Task failed
java.lang.NullPointerException
at com.skcraft.launcher.builder.PackageBuilder.processLoader(PackageBuilder.java:162)
at com.skcraft.launcher.builder.PackageBuilder.addLoaders(PackageBuilder.java:128)
at com.skcraft.launcher.builder.PackageBuilder.main(PackageBuilder.java:392)
at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:66)
at com.skcraft.launcher.creator.controller.task.PackBuilder.call(PackBuilder.java:21)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

**Comment by diesieben07** [comment]
Not a forge issue.
