### ISSUE TITLE
Private server with my friends via Radmin VPN extremely delayed after an attempted fix to stop "An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by Gyzr13** [MinecraftForge/MinecraftForge#6694]
So my friends and I have recently moved from a modded 1.14.4 server to a 1.12.2 server. We had no problems whatsoever with connection back on our old server, but now, on this 1.12.2 server, my friends have been constantly lagged out randomly, with the console following up with:

`[09:40:40] [Netty Server IO #12/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_241]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_241]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_241]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_241]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_241]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) ~[minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

This would be repeated over and over in the console, so I researched the issue to try and fix my friends being lagged out. I came across a forum saying to update Netty and place it in the server and 
/libraries/io/netty/netty-all
I also changed the run.bat file in my server from
java -Xmx5000M -Xms5000M -jar forge-1.12.2-14.23.5.2854.jar nogui
to
java -Xmx5000M -Xms5000M -cp netty-all-4.1.50.Final.jar -jar forge-1.12.2-14.23.5.2854.jar nogui
Now I've been introduced to an even bigger problem: massive delay. The delay is around 2 seconds and all entities seem to lag. Also, when anyone is in the server, the console is updated, saying:

`Exception in thread "Thread-72" [13:33:54] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[13:33:54] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
[13:33:54] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186)
[13:33:54] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
[13:33:54] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at net.minecraft.tileentity.TileEntitySkull.func_174884_b(SourceFile:151)
[13:33:54] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at ganymedes01.headcrumbs.utils.ThreadedProfileFiller$1.run(ThreadedProfileFiller.java:25)
[13:33:54] [Thread-72/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-73" [13:34:03] [Thread-73/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[13:34:03] [Thread-73/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
[13:34:03] [Thread-73/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186)
[13:34:03] [Thread-73/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
[13:34:03] [Thread-73/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at net.minecraft.tileentity.TileEntitySkull.func_174884_b(SourceFile:151)
[13:34:03] [Thread-73/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at ganymedes01.headcrumbs.utils.ThreadedProfileFiller$1.run(ThreadedProfileFiller.java:25)
[13:34:03] [Thread-73/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at java.lang.Thread.run(Unknown Source)
Exception in thread "Thread-74" [13:34:12] [Thread-74/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.IllegalArgumentException: Name and ID cannot both be blank
[13:34:12] [Thread-74/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26)
[13:34:12] [Thread-74/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:186)
[13:34:12] [Thread-74/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173)
[13:34:12] [Thread-74/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at net.minecraft.tileentity.TileEntitySkull.func_174884_b(SourceFile:151)
[13:34:12] [Thread-74/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at ganymedes01.headcrumbs.utils.ThreadedProfileFiller$1.run(ThreadedProfileFiller.java:25)
[13:34:12] [Thread-74/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]:     at java.lang.Thread.run(Unknown Source)`

As you can probably see, each individual "Thread" is showing their own "info", then it produces? another thread? Anyone got anything on this?

**Comment by FinnT730** [comment]
Anything under 1.14.4 is not supported anymore. Please update to get support.

**Comment by Gyzr13** [comment]
> Anything under 1.14.4 is not supported anymore. Please update to get support.

I'd rather not update back to 1.14.4. Could you possibly lead me somewhere else that I could be provided with support?

**Comment by FinnT730** [comment]
You can also go to 1.15.2.....
https://discord.mcmoddev.com/ or http://discord.gg/moddedmc they might help you....
