### ISSUE TITLE
[1.15.2] NullPointerException in mouseClicked event when updating world from 1.12.2 to 1.15.2.

### ISSUE THREAD

**Issue by LaChimere** [MinecraftForge/MinecraftForge#6730]
**Minecraft Version:** {1.15.2}

**Forge Version:** {1.15.2-forge-31.2.0}

**Description of issue:**
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 20-5-29 2:34am
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at net.minecraft.world.storage.WorldInfo.func_76064_a(WorldInfo.java:366) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.WorldInfo.func_76082_a(WorldInfo.java:302) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveHandler.func_75755_a(SaveHandler.java:49) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:133) ~[?:?] {re:classloading}
	at net.minecraft.util.WorldOptimizer.<init>(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.OptimizeWorldScreen.<init>(SourceFile:30) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.EditWorldScreen.func_214305_a(SourceFile:74) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.EditWorldScreen$$Lambda$3235/2022055326.proceed(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.ConfirmBackupScreen.func_212992_b(SourceFile:47) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.screen.ConfirmBackupScreen$$Lambda$3237/1644631132.onPress(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.widget.button.Button.onPress(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.button.AbstractButton.onClick(SourceFile:15) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.widget.Widget.mouseClicked(Widget.java:136) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3148/306321254.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3147/1941482284.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$2709/647580778.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:949) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$412/1515116175.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.storage.WorldInfo.func_76064_a(WorldInfo.java:366)
	at net.minecraft.world.storage.WorldInfo.func_76082_a(WorldInfo.java:302)
	at net.minecraft.world.storage.SaveHandler.func_75755_a(SaveHandler.java:49)
	at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:133)
	at net.minecraft.util.WorldOptimizer.<init>(SourceFile:63)
	at net.minecraft.client.gui.screen.OptimizeWorldScreen.<init>(SourceFile:30)
	at net.minecraft.client.gui.screen.EditWorldScreen.func_214305_a(SourceFile:74)
	at net.minecraft.client.gui.screen.EditWorldScreen$$Lambda$3235/2022055326.proceed(Unknown Source)
	at net.minecraft.client.gui.screen.ConfirmBackupScreen.func_212992_b(SourceFile:47)
	at net.minecraft.client.gui.screen.ConfirmBackupScreen$$Lambda$3237/1644631132.onPress(Unknown Source)
	at net.minecraft.client.gui.widget.button.Button.onPress(SourceFile:18)
	at net.minecraft.client.gui.widget.button.AbstractButton.onClick(SourceFile:15)
	at net.minecraft.client.gui.widget.Widget.mouseClicked(Widget.java:136)
	at net.minecraft.client.gui.INestedGuiEventHandler.mouseClicked(SourceFile:27)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)
	at net.minecraft.client.MouseHelper$$Lambda$3148/306321254.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.ConfirmBackupScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$3147/1941482284.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$2709/647580778.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:123)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:949)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$412/1515116175.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1035275360 bytes (987 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre17.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.0
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.0-universal.jar Forge {forge@31.2.0 DONE}
		inventoryprofiles-forge-1.15.2-0.2.1.jar Inventory Profiles {inventoryprofiles@0.2.1 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		DurabilityViewer-1.15.2-forge31.1.30-1.7.1.jar Giselbaers Durability Viewer {durabilityviewer@1.15.2-forge31.1.30-1.7.1 DONE}
	Launched Version: 1.15.2-forge-31.2.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 950M/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.54, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: 简体中文 (中国)
	CPU: 4x Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre17
	OptiFine Build: 20200515-184428
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.54
	OpenGlRenderer: GeForce GTX 950M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by LexManos** [comment]
1) Use the forum to verify that this is a Forge issue, step 1 would be to remove optifine. And other mods
2) Provide the old world so we can test/reproduce.

**Comment by LaChimere** [comment]
> 1. Use the forum to verify that this is a Forge issue, step 1 would be to remove optifine. And other mods
> 2. Provide the old world so we can test/reproduce.

I have tried to remove all the mods including optifine but the same exception still exists.
The old world have been sent to your email, please help me fix this issue...

**Comment by LexManos** [comment]
Then post a log with no mods installed.
And Don't email me... Especially with unknown attachments I'll just instantly delete it.
Upload it to a hosting site so others can test.

**Comment by LaChimere** [comment]
> Then post a log with no mods installed.
> And Don't email me... Especially with unknown attachments I'll just instantly delete it.
> Upload it to a hosting site so others can test.

The crash log becomes like this:
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 20-5-29 上午3:14
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at crm.a(SourceFile:362)
	at crm.a(SourceFile:299)
	at crn.a(SourceFile:56)
	at crn.a(SourceFile:136)
	at aiz.<init>(SourceFile:63)
	at djj.<init>(SourceFile:30)
	at dji.a(SourceFile:74)
	at dji$$Lambda$2205/2075566580.proceed(Unknown Source)
	at dey.b(SourceFile:47)
	at dey$$Lambda$2207/1808415527.onPress(Unknown Source)
	at dcv.onPress(SourceFile:18)
	at dcq.onClick(SourceFile:15)
	at dct.mouseClicked(SourceFile:150)
	at ddr.mouseClicked(SourceFile:27)
	at dbo.b(SourceFile:86)
	at dbo$$Lambda$2132/1698990386.run(Unknown Source)
	at dgb.wrapScreenError(SourceFile:447)
	at dbo.a(SourceFile:86)
	at dbo.c(SourceFile:150)
	at dbo$$Lambda$2131/495886114.run(Unknown Source)
	at ais.execute(SourceFile:94)
	at dbo.b(SourceFile:150)
	at dbo$$Lambda$1531/1267290459.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)
	at cxx.e(SourceFile:301)
	at dbn.d(SourceFile:1012)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at crm.a(SourceFile:362)
	at crm.a(SourceFile:299)
	at crn.a(SourceFile:56)
	at crn.a(SourceFile:136)
	at aiz.<init>(SourceFile:63)
	at djj.<init>(SourceFile:30)
	at dji.a(SourceFile:74)
	at dji$$Lambda$2205/2075566580.proceed(Unknown Source)
	at dey.b(SourceFile:47)
	at dey$$Lambda$2207/1808415527.onPress(Unknown Source)
	at dcv.onPress(SourceFile:18)
	at dcq.onClick(SourceFile:15)
	at dct.mouseClicked(SourceFile:150)
	at ddr.mouseClicked(SourceFile:27)
	at dbo.b(SourceFile:86)
	at dbo$$Lambda$2132/1698990386.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: dey
Stacktrace:
	at dgb.wrapScreenError(SourceFile:447)
	at dbo.a(SourceFile:86)
	at dbo.c(SourceFile:150)
	at dbo$$Lambda$2131/495886114.run(Unknown Source)
	at ais.execute(SourceFile:94)
	at dbo.b(SourceFile:150)
	at dbo$$Lambda$1531/1267290459.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)
	at cxx.e(SourceFile:301)
	at dbn.d(SourceFile:1012)
	at dbn.d(SourceFile:619)
	at net.minecraft.client.main.Main.main(SourceFile:204)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1516295056 bytes (1446 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.15.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 950M/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.54, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: 简体中文 (中国)
	CPU: 4x Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
```

I uploaded my old world on github, and the site is [The-Old-World](https://github.com/LaChimere/The-Old-World)

**Comment by LexManos** [comment]
So, this isn't a Forge issue, it is a vanilla issue. Report it to them.

**Comment by LaChimere** [comment]
> So, this isn't a Forge issue, it is a vanilla issue. Report it to them.

Okay, thanks. I'll report it to them.
