### ISSUE TITLE
Send help 

### ISSUE THREAD

**Issue by bloodyfishhammock** [MinecraftForge/MinecraftForge#6771]
Minecraft Version: 1.12.2

Forge Version: 14.23.5.2847

Logs:
[19:30:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:30:55] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:30:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:30:55] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading
[19:30:55] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_251, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_251
[19:30:55] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[19:30:55] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[19:30:55] [main/INFO] [FML]: Searching E:\forge modded server\.\mods for mods
[19:30:55] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Bloodmoon-MC1.12.2-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:30:55] [main/WARN] [FML]: The coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:30:55] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-1.0.2.31.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:30:55] [main/WARN] [FML]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[19:30:55] [main/WARN] [FML]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[19:30:55] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in iceandfire-1.9.1-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[19:30:55] [main/WARN] [FML]: The coremod iceandfire (com.github.alexthe666.iceandfire.asm.IceAndFirePlugin) is not signed!
[19:30:55] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5.jar
[19:30:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:30:55] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[19:30:55] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:30:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:30:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:30:55] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[19:30:55] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[19:30:55] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: Forge server detected, skipping class transformer
[19:30:55] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:57] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[19:30:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:30:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:30:57] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:30:57] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[19:30:57] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments
[19:30:58] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[19:30:58] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:preTransform:230]: Transforming Class [net.minecraft.block.Block], Method [getExtendedState]
[19:30:58] [main/INFO] [STDOUT]: [team.chisel.ctm.client.asm.CTMTransformer:finishTransform:242]: Transforming net.minecraft.block.Block Finished.
[19:31:01] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.12.2
[19:31:01] [Server thread/INFO] [FML]: MinecraftForge v14.23.5.2847 Initialized
[19:31:01] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[19:31:01] [Server thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[19:31:01] [Server thread/INFO] [FML]: Replaced 1227 ore ingredients
[19:31:01] [Server thread/INFO] [FML]: Searching E:\forge modded server\.\mods for mods
[19:31:02] [Server thread/INFO] [FML]: Disabling mod antiqueatlasoverlay it is client side only.
[19:31:02] [Server thread/ERROR] [FML]: Unable to read a class file correctly
java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) [ASMModParser.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[19:31:02] [Server thread/ERROR] [FML]: There was a problem reading the entry module-info.class in the jar .\mods\avatarmod-1.5.17-alpha.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) ~[ASMModParser.class:?]
	... 12 more
[19:31:02] [Server thread/WARN] [FML]: Zip file avatarmod-1.5.17-alpha.jar failed to read properly, it will be ignored
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:102) ~[JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-5.2.jar:5.2]
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:57) ~[ASMModParser.class:?]
	... 12 more
[19:31:02] [Server thread/INFO] [FML]: Disabling mod ctm it is client side only.
[19:31:02] [Server thread/WARN] [FML]: Mod hiddenarmor is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.12.2-1.0
[19:31:02] [Server thread/INFO] [FML]: Disabling mod neat it is client side only.
[19:31:02] [Server thread/INFO] [FML]: Disabling mod norecipebook it is client side only.
[19:31:02] [Server thread/WARN] [FML]: Mod patchouli is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0-20
[19:31:03] [Server thread/INFO] [FML]: Forge Mod Loader has identified 25 mods to load
[19:31:03] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[19:31:03] [Server thread/WARN] [FML]: Missing English translation for libraryex: assets/libraryex/lang/en_us.lang
[19:31:03] [Server thread/WARN] [FML]: Missing English translation for morpheus: assets/morpheus/lang/en_us.lang
[19:31:03] [Server thread/WARN] [FML]: Missing English translation for roguelike: assets/roguelike/lang/en_us.lang
[19:31:03] [Server thread/INFO] [FML]: FML has found a non-mod file CTM-MC1.12.2-1.0.2.31.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[19:31:03] [Server thread/INFO] [FML]: FML has found a non-mod file Neat+1.4-17.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[19:31:03] [Server thread/INFO] [FML]: FML has found a non-mod file noRecipeBook_v1.2.2formc1.12.2.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[19:31:03] [Server thread/INFO] [FML]: FML has found a non-mod file core-3.6.0.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[19:31:03] [Server thread/INFO] [FML]: FML has found a non-mod file json-3.6.0.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.
[19:31:04] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, antiqueatlas, avatarmod, gorecore, bloodmoon, explorercraft, ftbbackups, hiddenarmor, hardcorequesting, iceandfire, jei, libraryex, morpheus, mowziesmobs, netherex, netherportalfix, patchouli, roguelike, travellersbackpack, twilightforest, llibrary, thebetweenlands] at CLIENT
[19:31:04] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, antiqueatlas, avatarmod, gorecore, bloodmoon, explorercraft, ftbbackups, hiddenarmor, hardcorequesting, iceandfire, jei, libraryex, morpheus, mowziesmobs, netherex, netherportalfix, patchouli, roguelike, travellersbackpack, twilightforest, llibrary, thebetweenlands] at SERVER
[19:31:05] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[19:31:06] [Server thread/INFO] [FML]: Found 2363 ObjectHolder annotations
[19:31:06] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[19:31:06] [Server thread/INFO] [FML]: Found 1 ItemStackHolder annotations
[19:31:06] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[19:31:06] [Forge Version Check/INFO] [forge.VersionCheck]: [avatarmod] Starting version check at http://av2.io/updates.json
[19:31:06] [Server thread/INFO] [avatarmod]: [Info] Fetching latest AvatarMod2 announcements...
[19:31:07] [Server thread/INFO] [avatarmod]: [Info] Finished loading announcements
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `lectern`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `podium`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `egginice`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `pixie_house`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `jar`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `dread_portal`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `dread_spawner`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `dummygorgonheadidle`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `dummygorgonheadactive`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `myrmexcocoon`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `dragonforge`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `dragonforgeinput`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `dragonforgebrick`, expected `iceandfire`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:07] [Server thread/INFO] [Ice And Fire]: A raven flies from the north to the sea
[19:31:07] [Server thread/INFO] [Ice And Fire]: A dragon whispers her name in the east
[19:31:08] [Server thread/INFO] [morpheus]: Loading configuration
[19:31:08] [Server thread/INFO] [travellersbackpack]: Registered the class com.tiviacz.travellersbackpack.fluids.effects.EffectWater as a FluidEffect for water with the ID 0
[19:31:08] [Server thread/INFO] [travellersbackpack]: Registered the class com.tiviacz.travellersbackpack.fluids.effects.EffectLava as a FluidEffect for lava with the ID 1
[19:31:08] [Server thread/INFO] [travellersbackpack]: Registered the class com.tiviacz.travellersbackpack.fluids.effects.EffectMilk as a FluidEffect for milk with the ID 2
[19:31:08] [Server thread/INFO] [travellersbackpack]: Registered the class com.tiviacz.travellersbackpack.fluids.effects.EffectPotion as a FluidEffect for potion with the ID 3
[19:31:08] [Server thread/INFO] [twilightforest]: Skipped compatibility for mod Baubles.
[19:31:08] [Server thread/INFO] [twilightforest]: Skipped compatibility for mod Chisel.
[19:31:08] [Server thread/INFO] [twilightforest]: Skipped compatibility for mod Forestry.
[19:31:08] [Server thread/INFO] [twilightforest]: Skipped compatibility for mod Immersive Engineering.
[19:31:08] [Server thread/INFO] [twilightforest]: Loaded compatibility for mod Just Enough Items.
[19:31:08] [Server thread/INFO] [twilightforest]: Skipped compatibility for mod Tinkers' Construct.
[19:31:08] [Server thread/INFO] [twilightforest]: Skipped compatibility for mod Thaumcraft.
[19:31:14] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[19:31:14] [Forge Version Check/INFO] [forge.VersionCheck]: [forge] Found status: OUTDATED Target: 14.23.5.2854
[19:31:14] [Forge Version Check/INFO] [forge.VersionCheck]: [twilightforest] Starting version check at https://raw.githubusercontent.com/TeamTwilight/twilightforest/1.12.x/update.json
[19:31:14] [Forge Version Check/INFO] [forge.VersionCheck]: [twilightforest] Found status: AHEAD Target: null
[19:31:14] [Forge Version Check/INFO] [forge.VersionCheck]: [llibrary] Starting version check at https://gist.githubusercontent.com/gegy1000/a6639456aeb8edd92cbf7cbfcf9d65d9/raw/llibrary_updates.json
[19:31:14] [Forge Version Check/INFO] [forge.VersionCheck]: [llibrary] Found status: AHEAD Target: null
[19:31:14] [Forge Version Check/INFO] [forge.VersionCheck]: [travellersbackpack] Starting version check at https://gist.githubusercontent.com/Tiviacz1337/906937677aa472285dff9d6c2a189d5e/raw/2d0fbb4c09b8e5da711c3b03914882e6a551a658/TravellersBackpackUpdateJSON.json
[19:31:14] [Forge Version Check/INFO] [forge.VersionCheck]: [travellersbackpack] Found status: AHEAD Target: null
[19:31:15] [Server thread/INFO] [FML]: Applying holder lookups
[19:31:15] [Server thread/INFO] [FML]: Holder lookups applied
[19:31:15] [Server thread/INFO] [FML]: Applying holder lookups
[19:31:15] [Server thread/INFO] [FML]: Holder lookups applied
[19:31:16] [Server thread/INFO] [FML]: Applying holder lookups
[19:31:16] [Server thread/INFO] [FML]: Holder lookups applied
[19:31:16] [Server thread/INFO] [FML]: Applying holder lookups
[19:31:16] [Server thread/INFO] [FML]: Holder lookups applied
[19:31:16] [Server thread/INFO] [FML]: Injecting itemstacks
[19:31:16] [Server thread/INFO] [FML]: Itemstack injection complete
[19:31:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Loading properties
[19:31:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Default game type: SURVIVAL
[19:31:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Generating keypair
[19:31:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting Minecraft server on *:25565
[19:31:16] [Server thread/INFO] [net.minecraft.network.NetworkSystem]: Using default channel type
[19:31:17] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `painted acacia slab`, expected `mowziesmobs`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:17] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `minecraft` for name `nether_brick_fence`, expected `netherex`. This could be a intended override, but in most cases indicates a broken mod.
[19:31:18] [Server thread/INFO] [FML]: Applying holder lookups
[19:31:18] [Server thread/INFO] [FML]: Holder lookups applied
[19:31:18] [Server thread/WARN] [net.minecraft.entity.passive.EntityVillager]: PriceRange(2, 1) invalid, 1 smaller than 2
[19:31:18] [Server thread/WARN] [net.minecraft.entity.passive.EntityVillager]: PriceRange(4, 1) invalid, 1 smaller than 4
[19:31:18] [Server thread/WARN] [net.minecraft.entity.passive.EntityVillager]: PriceRange(10, 1) invalid, 1 smaller than 10
[19:31:18] [Server thread/WARN] [net.minecraft.entity.passive.EntityVillager]: PriceRange(9, 1) invalid, 1 smaller than 9
[19:31:18] [Server thread/WARN] [net.minecraft.entity.passive.EntityVillager]: PriceRange(3, 2) invalid, 2 smaller than 3
[19:31:18] [Server thread/INFO] [Ice And Fire]: The watcher waits on the northern wall
[19:31:18] [Server thread/INFO] [Ice And Fire]: A daughter picks up a warrior's sword
[19:31:18] [Server thread/INFO] [FML]: Injecting itemstacks
[19:31:18] [Server thread/INFO] [FML]: Itemstack injection complete
[19:31:18] [Server thread/INFO] [Ice And Fire]: A brother bound to a love he must hide
[19:31:18] [Server thread/INFO] [Ice And Fire]: The younger's armor is worn in the mind
[19:31:18] [Server thread/INFO] [Ice And Fire]: A cold iron throne holds a boy barely grown
[19:31:18] [Server thread/INFO] [Ice And Fire]: And now it is known
[19:31:18] [Server thread/INFO] [Ice And Fire]: A claim to the prize, a crown laced in lies
[19:31:18] [Server thread/INFO] [Ice And Fire]: You win or you die
[19:31:18] [Server thread/INFO] [Ice And Fire]: Damn season 8 really sucked didn't it
[19:31:19] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 25 mods
[19:31:19] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Preparing level "world"
[19:31:19] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[19:31:19] [Server thread/INFO] [FML]: Applying holder lookups
[19:31:19] [Server thread/INFO] [FML]: Holder lookups applied
[19:31:19] [Server thread/INFO] [FML]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@4be98ac3)
[19:31:20] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 838 advancements
[19:31:20] [Server thread/INFO] [Hardcore Questing Mode]: Couldn't copy default files
[19:31:20] [Server thread/INFO] [NetherEx]: Creating Nether biome data configs.
[19:31:20] [Server thread/INFO] [NetherEx]: Reading Nether biome data configs.
[19:31:21] [Server thread/INFO] [NetherEx]: Creating Pigtificate trade configs.
[19:31:21] [Server thread/INFO] [NetherEx]: Reading Pigtificate trade configs.
[19:31:21] [Server thread/INFO] [FML]: Loading dimension -1 (world) (net.minecraft.server.dedicated.DedicatedServer@4be98ac3)
[19:31:21] [Server thread/INFO] [FML]: Loading dimension 1 (world) (net.minecraft.server.dedicated.DedicatedServer@4be98ac3)
[19:31:21] [Server thread/INFO] [FML]: Loading dimension 20 (world) (net.minecraft.server.dedicated.DedicatedServer@4be98ac3)
[19:31:21] [Server thread/INFO] [FML]: Loading dimension 7 (world) (net.minecraft.server.dedicated.DedicatedServer@4be98ac3)
[19:31:21] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing start region for level 0
[19:31:22] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 90%
[19:31:22] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Done (3.249s)! For help, type "help" or "?"
[19:31:22] [Server thread/INFO] [NetherEx]: The Nether has been overridden.
[19:31:22] [Server thread/INFO] [FTB Backups]: Backups folder - E:\forge modded server\.\backups
[19:31:22] [Server thread/INFO] [FML]: Unloading dimension -1
[19:31:22] [Server thread/INFO] [FML]: Unloading dimension 1
[19:31:22] [Server thread/INFO] [FML]: Unloading dimension 20
[19:31:22] [Server thread/INFO] [FML]: Unloading dimension 7
[19:32:07] [Server thread/INFO] [antiqueatlas]: Saving local markers data to NBT

 1. I put my mods in
 2. ran the server
 3. played on the server till the server kicked everyone

I feel like this can be fixed really easily but I am just stupid

Thank you

**Comment by DaemonUmbra** [comment]
https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/

**Comment by bloodyfishhammock** [comment]
so basically i am fucked
