### ISSUE TITLE
Forge 1.16.1 crashes when selecting beacon power

### ISSUE THREAD

**Issue by AnarchoLemons** [MinecraftForge/MinecraftForge#6871]
Placing an ingot in the beacon power selection menu results in a crash when using Forge version 1.16.1 - 32.0.24

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 6/28/20, 11:38 AM
Description: Container click

java.lang.IllegalStateException: Tag forge:beacon_payment used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:77) ~[?:?] {re:classloading}
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:88) ~[?:?] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeItem.isBeaconPayment(IForgeItem.java:622) ~[?:?] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeItemStack.isBeaconPayment(IForgeItemStack.java:313) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.BeaconContainer$BeaconSlot.func_75214_a(BeaconContainer.java:157) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:272) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:380) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231048_c_(ContainerScreen.java:509) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:93) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:421) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:91) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:304) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:970) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:581) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.1-forge-32.0.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.1-32.0.23.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:77)
	at net.minecraft.tags.TagRegistry$NamedTag.func_230235_a_(TagRegistry.java:88)
	at net.minecraftforge.common.extensions.IForgeItem.isBeaconPayment(IForgeItem.java:622)
	at net.minecraftforge.common.extensions.IForgeItemStack.isBeaconPayment(IForgeItemStack.java:313)
	at net.minecraft.inventory.container.BeaconContainer$BeaconSlot.func_75214_a(BeaconContainer.java:157)
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:272)

-- Click info --
Details:
	Menu Type: minecraft:beacon
	Menu Class: net.minecraft.inventory.container.BeaconContainer
	Slot Count: 37
	Slot: 0
	Button: 1
	Type: PICKUP
Stacktrace:
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160)
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:380)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231048_c_(ContainerScreen.java:509)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:93)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.BeaconScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:421)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:91)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['AnarchoLemons'/7707, l='ClientLevel', x=-318.05, y=113.00, z=1530.30]]
	Chunk stats: Client Chunk Cache: 625, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (19,63,133), Chunk: (at 3,3,5 in 1,8; contains blocks 16,0,128 to 31,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 34619756 game time, 18374988 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:445)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:597)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.7, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 3665722824 bytes (3495 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseG1GC -Xmx4G -Xms4G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.23.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.1-32.0.23.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.23.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.23.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.23
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.23-client.jar Minecraft {minecraft@1.16.1 DONE}
		forge-1.16.1-32.0.23-universal.jar Forge {forge@32.0.23 DONE}
		light-overlay-5.4.0.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		jei-1.16.1-7.0.0.2.jar Just Enough Items {jei@7.0.0.2 DONE}
		cloth-config-forge-4.0.1.jar Cloth Config v4 API {cloth-config@4.0 DONE}
	Launched Version: 1.16.1-forge-32.0.23
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.48, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/PureBDcraft 128x MC116.zip, file/PureBDcraft Customisation MC115.zip, file/PureBDcraft More 3D Blocks MC115.zip, file/Removed Pumpkin Blur.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

**Comment by Cyborgmas** [comment]
Ah okay you are on a server missed that. Yeah tags are problematic on the server currently. I have a potential fix, will test if it works for this as well.

**Comment by Cyborgmas** [comment]
was not able to reproduce this crash. could you retry without any mods? also you arent on .24 but .23 :P

**Comment by AnarchoLemons** [comment]
Removed my mods and there was no crash. Updating to .24 also solved the problem. Thanks for the help
