### ISSUE TITLE
[1.16.1] Tag minecraft:beehives used before it was bound

### ISSUE THREAD

**Issue by JaisDK** [MinecraftForge/MinecraftForge#6908]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.46

**Logs:**
```
[16:21:17] [modloading-worker-1/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid productivebees
java.lang.IllegalStateException: Tag minecraft:beehives used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:77) ~[forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {re:classloading}
	at net.minecraft.tags.TagRegistry$NamedTag.func_230236_b_(TagRegistry.java:92) ~[forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {re:classloading}
	at cy.jdkdigital.productivebees.ProductiveBees.fixPOI(ProductiveBees.java:240) ~[main/:?] {re:classloading}
	at cy.jdkdigital.productivebees.ProductiveBees.preInit(ProductiveBees.java:120) ~[main/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:32.0] {re:classloading}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_241] {}
	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_241] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) ~[?:1.8.0_241] {}
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401) ~[?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160) ~[?:1.8.0_241] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174) ~[?:1.8.0_241] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_241] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.ModList.lambda$dispatchParallelEvent$11(ModList.java:135) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_241] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_241] {}

```

**Steps to Reproduce:**
 1. Access a tag during the FMLCommonSetupEvent 

**Description of issue:**

**Comment by sciwhiz12** [comment]
You accessed a tag during FMLCommonSetupEvent, in which the game is only initializing, and no tags are loaded yet during that phase of game loading, if I recall correctly.

**Comment by JaisDK** [comment]
This works in 1.15.2. I need to access the tag to fix POI for beehives.

https://github.com/JDKDigital/productive-bees/blob/master/src/main/java/cy/jdkdigital/productivebees/ProductiveBees.java#L240

**Comment by KnightMiner** [comment]
You missed the point. Tags have no content before the world loads because data packs are tied to the world. 1.15 simply gave you empty content, while 1.16 errors now.

You should check your code in 1.15 again, likely you will find that tag has no entries at the time you called it. In any case, whether it "worked" or not in 1.15, it's still wrong and should never have worked. Do not access tags before they are loaded.

**Comment by JaisDK** [comment]
Interesting, I'll rewrite this to not use the tag then.

**Comment by Cyborgmas** [comment]
Last comment, vanilla does only use blockstates directly. In PointOfInterestType the bed heads are created from all the blockstates, even though there exists a tag for them.
