### ISSUE TITLE
[1.16.1] Tag minecraft:logs used before it was bound

### ISSUE THREAD

**Issue by JaisDK** [MinecraftForge/MinecraftForge#6909]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.46

**Logs:**

Description: Initializing game
```

java.lang.IllegalStateException: Tag minecraft:logs used before it was bound
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:77) ~[forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {re:classloading}
	at net.minecraft.tags.TagRegistry$NamedTag.func_230236_b_(TagRegistry.java:92) ~[forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {re:classloading}
	at cy.jdkdigital.productivebees.item.WoodChip.fillItemGroup(WoodChip.java:72) ~[main/:?] {re:classloading}
	at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:630) ~[forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:463) ~[forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_241] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241] {}
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55) ~[forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105) [forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.tags.TagRegistry$NamedTag.func_232944_c_(TagRegistry.java:77)
	at net.minecraft.tags.TagRegistry$NamedTag.func_230236_b_(TagRegistry.java:92)
	at cy.jdkdigital.productivebees.item.WoodChip.fillItemGroup(WoodChip.java:72)
	at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:630)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:463)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.userdev.FMLUserdevClientLaunchProvider.lambda$launchService$0(FMLUserdevClientLaunchProvider.java:55)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
	at net.minecraftforge.userdev.LaunchTesting.main(LaunchTesting.java:105)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1082224048 bytes (1032 MB) / 1777336320 bytes (1695 MB) up to 3786407936 bytes (3611 MB)
	CPUs: 8
	JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmluserdevclient
	ModLauncher naming: mcp
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16-launcher.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16-launcher.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16-launcher.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16-launcher.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16-launcher.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.46
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		client-extra.jar Minecraft {minecraft@1.16.1 COMMON_SETUP}
		forge-1.16.1-32.0.46_mapped_snapshot_20200514-1.16.jar Forge {forge@32.0.46 COMMON_SETUP}
		main Productive Bees {productivebees@NONE COMMON_SETUP}
		jei-1.16.1-7.0.0.3_mapped_snapshot_20200514-1.16.jar Just Enough Items {jei@7.0.0.3 COMMON_SETUP}
	Launched Version: MOD_DEV
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 25.20.100.6374, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
[17:06:03] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:printToSYSOUT:120]: #@!@# Game crashed! 

```

**Steps to Reproduce:**
 1. Access a tag in an items "fillItemGroup" method

**Description of issue:**

**Comment by sciwhiz12** [comment]
First, please use a paste site (GitHub Gists) in posting your logs.
Second, why are you accessing tags during the FMLCommonSetupEvent? Tags are not loaded until a server instance (integrated or dedicated) is loaded.

**Comment by JaisDK** [comment]
I am accessing a tag because I want to populate the itemgroup based on a tag

https://github.com/JDKDigital/productive-bees/blob/master/src/main/java/cy/jdkdigital/productivebees/item/WoodChip.java#L70

**Comment by sciwhiz12** [comment]
As said in https://github.com/MinecraftForge/MinecraftForge/issues/6908, tags are not loaded until a server instance is started and a world is loaded, because they are used by datapacks. 
Your code is flawed because you rely on tags to create your items. Instead of using tags and making distinct items by using an NBT tag, you should follow the strategy that guided the Flattening:
> If it has a different name, it should be a separate block/item/etc.

**Comment by JaisDK** [comment]
Prompted by your comment in the other issue, I had a look at the contents of the tag when used in the method. It seems that this method is called multiple times and the first time it is called the tag is indeed empty.
During subsequent calls, the tag is populated.

I am well aware that this approach is not approved by today's flat standards, but it is simple too inconvenient for me to create a separate item for each modded wood log out there.

**Comment by sciwhiz12** [comment]
If you're thinking what I thinking, then you might've thought that my suggestion was to make a separate class for each item. 

What I actually meant was creating multiple instances of one class, and passing parameters to its constructor to make it distinct. See how `SignItem`s are registered in vanilla. (`Items.class, MC 1.16.1, mappings 20200514-1.16, L669-676`)

They reuse the same `SignItem` class, but pass different `Block`s and use different registry names to make them distinct.
You can do something akin to that. You don't need to support *every* modded wood log, only the ones which matter to your mod and use case.

**Comment by JaisDK** [comment]
There was no misunderstanding, I know you meant multiple instances of the same class with different registry names. I make great use of that already.
I don't need to support all wood, but I want to. In essence I am making a wood processor and it does not make sense to support only some wood and not others.
