### ISSUE TITLE
[1.16.1] NullPointerException when spawning mod-registered entity

### ISSUE THREAD

**Issue by JaisDK** [MinecraftForge/MinecraftForge#6911]
**Minecraft Version:** 1.16.1

**Forge Version:** 32.0.47

**Logs:** https://gist.github.com/JaisDK/3e3563d55950cfd3ecf6b0105bb2a568

**Steps to Reproduce:**
 1. Setup fresh Forge MDK
 2. Create and register entity
 3. Launch and summon entity

**Description of issue:**

```
[22:11:56] [Server thread/WARN] [minecraft/EntityType]: Exception loading entity: 
java.lang.NullPointerException: null
	at net.minecraft.entity.ai.attributes.AttributeModifierManager.func_233795_c_(AttributeModifierManager.java:67) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_233637_b_(LivingEntity.java:1848) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.getMaxHealth(LivingEntity.java:1609) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity.java:208) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.MobEntity.<init>(MobEntity.java:107) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.CreatureEntity.<init>(CreatureEntity.java:13) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.monster.MonsterEntity.<init>(MonsterEntity.java:28) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.monster.ZombieEntity.<init>(ZombieEntity.java:80) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.EntityType.create(EntityType.java:442) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.EntityType.lambda$loadEntityUnchecked$1(EntityType.java:453) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_241] {}
	at net.minecraft.entity.EntityType.loadEntityUnchecked(EntityType.java:452) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.EntityType.loadEntity(EntityType.java:510) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.entity.EntityType.func_220335_a(EntityType.java:492) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.command.impl.SummonCommand.summonEntity(SummonCommand.java:49) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at net.minecraft.command.impl.SummonCommand.lambda$register$1(SummonCommand.java:33) ~[forge-1.16.1-32.0.47_mapped_snapshot_20200514-1.16-recomp.jar:?] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[brigadier-1.0.17.jar:?] {}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[brigadier-1.0.17.jar:?] {}
	at net.minecraft.command.Commands.handleCommand(Commands.java:218) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.handleSlashCommand(ServerPlayNetHandler.java:1085) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.processChatMessage(ServerPlayNetHandler.java:1065) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CChatMessagePacket.processPacket(CChatMessagePacket.java:40) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CChatMessagePacket.processPacket(CChatMessagePacket.java:8) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:19) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(TickDelayedTask.java:20) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.run(ThreadTaskExecutor.java:139) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.run(RecursiveEventLoop.java:22) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:763) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:157) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveOne(ThreadTaskExecutor.java:109) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.driveOneInternal(MinecraftServer.java:746) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.driveOne(MinecraftServer.java:740) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.driveUntil(ThreadTaskExecutor.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.runScheduledTasks(MinecraftServer.java:726) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:669) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:231) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241] {}
```

**Comment by JaisDK** [comment]
Example project showing error

[3e3563d55950cfd3ecf6b0105bb2a568.zip](https://github.com/MinecraftForge/MinecraftForge/files/4871208/3e3563d55950cfd3ecf6b0105bb2a568.zip)

**Comment by itsmeow** [comment]
This log shows a zombie being summoned, but you say it's a custom entity?

**Comment by itsmeow** [comment]
The problem here is you haven't registered any attributes for your custom entity.
```
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
[22:09:38] [Worker-Main-13/ERROR] [minecraft/GlobalEntityTypeAttributes]: Entity examplemod:test has no attributes
```
You need to, at absolute minimum, call
`MonsterEntity.func_234295_eP_().func_233813_a_()` (if you're doing a zombie) or `MobEntity.func_233666_p_().func_233813_a_()` as the next highest in the tree.

Above that is 
`LivingEntity.func_233639_cI_().func_233813_a_()`

**Comment by itsmeow** [comment]
Accidentally sent somehow.. to complete my statement.
`.func_233813_a_()` is `.build()` and completes any attribute builder statement. The base methods are themselves the equivalent of `super.registerAttributes()` in 1.15.

To set your own base values or register to the attribute map for an entity, look at how other entities do it. I've made a tool to auto-port these [here](https://itsmeow.dev/replacetool/) by selecting 1.16 Attribute Updater and then pasting the body of `registerAttributes()` from 1.15. You can then insert the output between the super call and the build call.

Once you get all that, during EntityType registration, or during common setup under a DeferredWorkQueue, call

```java
GlobalEntityTypeAttributes.put(YOUR_ENTITY_TYPE, MobEntity.func_233666_p_().func_233813_a_()/*(or your own)*/);
```

**Comment by JaisDK** [comment]
Thank you!, got it working now.
