### ISSUE TITLE
Failed to run Minecraft Forge server for 1.12.2

### ISSUE THREAD

**Issue by Unc1eCat** [MinecraftForge/MinecraftForge#7596]
I installed Forge server and tried to perform initial run of the _Forge server jar_ but it fails with this exception:
```
C:\Users\AntonBespoiasov\AppData\Roaming\.minecraft J\localserver\1.12.2_forge>java -server -Xms512M -Xmx1024M -jar forge-1.12.2-14.23.1.2597-universal.jar
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
```

I tried using 2 other versions of the Forge server, all couldn't launch.

**OS:** Windows 64-bit

**Java:** 1.8 64-bit

**Minecraft Version:** 1.12.2

**Forge Version:** 14.23.1.2597

**Comment by covers1624** [comment]
You must use Java 8 for Forge 1.12.2 and below.
