### ISSUE TITLE
Forge server not starting

### ISSUE THREAD

**Issue by Devansh-Singhal** [MinecraftForge/MinecraftForge#7729]
hello,
i am making a forge server to play modded mc with my friends but whenever i try to start it this comes,A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
i followed breakdown's video on how to make it but it isnt working please help me. comment if u need any more information

**Comment by sciwhiz12** [comment]
You must use Java 8 for Forge 1.12.2 and below. **Versions lower than 1.15 are unsupported by Forge.**

**Comment by Devansh-Singhal** [comment]
> You must use Java 8 for Forge 1.12.2 and below. **Versions lower than 1.15 are unsupported by Forge.**

i am using java 8

**Comment by jotoho** [comment]
> > You must use Java 8 for Forge 1.12.2 and below. **Versions lower than 1.15 are unsupported by Forge.**
> 
> i am using java 8

It's possible that you have multiple java versions installed and the server is using the wrong installed version due to misconfiguration of the launch command or an environment variable pointing to the wrong version.

All this seems like general minecraft modding support and unless you can prove that this is a bug in a **supported** version of Forge and not user error or a problem with an older version of Forge, I do not think this issue tracker for developers is the right place for this discussion.

Even if this were a valid bugreport you would probably need to provide more information than just a part of the log.

**Comment by Devansh-Singhal** [comment]
> > > You must use Java 8 for Forge 1.12.2 and below. **Versions lower than 1.15 are unsupported by Forge.**
> > 
> > 
> > i am using java 8
> 
> It's possible that you have multiple java versions installed and the server is using the wrong installed version due to misconfiguration of the launch command or an environment variable pointing to the wrong version.
> 
> All this seems like general minecraft modding support and unless you can prove that this is a bug in a **supported** version of Forge and not user error or a problem with an older version of Forge, I do not think this issue tracker for developers is the right place for this discussion.
> 
> Even if this were a valid bugreport you would probably need to provide more information than just a part of the log.

i did lots of research on the issue and one of the websites made me do some tinkering with the envioment variables, after that it broke completely. now i dont know how to fix it
