### ISSUE TITLE
EyeMod Crashes Minecraft

### ISSUE THREAD

**Issue by Onur259** [MinecraftForge/MinecraftForge#7768]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2021-05-15 08:47:30 CEST
Description: Ticking player

java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at net.minecraft.nbt.NBTTagCompound.copy(NBTTagCompound.java:450)
    at net.minecraft.item.ItemStack.copy(ItemStack.java:401)
    at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:85)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdate(EntityPlayerMP.java:324)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.WorldServer.tickPlayers(WorldServer.java:642)
    at net.minecraft.world.World.updateEntities(World.java:1737)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Player being ticked --
  Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
  Entity ID: 13
  Entity Name: Onur06
  Entity's Exact location: -498.51, 65.00, 1400.69
  Entity's Block location: World: (-499,65,1400), Chunk: (at 13,4,8 in -32,87; contains blocks -512,0,1392 to -497,255,1407), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,Spawns:[],ForgeData:{campInv:{},isInTrap:-1,PlayerPersisted:{"XU|SwordDim":0,XU2:{Frequency:-1332777060},gotDTStartingItems:1b},camping_lantern_time:0},SleepTimer:0s,Attributes:[{Base:20.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.10000000149011612d,Modifiers:[{UUIDMost:6667135215660042175L,UUIDLeast:-1371013230074716891L,Amount:0.0d,Operation:0,Name:"camping.speedBoost"}],Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:1.0d,Name:"generic.attackDamage"},{Base:4.0d,Name:"generic.attackSpeed"},{Base:0.0d,Name:"generic.luck"},{Base:5.0d,Name:"generic.reachDistance"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,abilities:{invulnerable:1b,mayfly:1b,instabuild:1b,walkSpeed:0.1f,mayBuild:1b,flying:0b,flySpeed:0.05f},FallDistance:0.0f,recipeBook:{recipes:["minecraft:wooden_pressure_plate","minecraft:wooden_door","minecraft:wooden_button","minecraft:trapdoor","minecraft:tnt","minecraft:stick","minecraft:sign","minecraft:oak_wooden_slab","minecraft:oak_stairs","minecraft:oak_planks","minecraft:fence_gate","minecraft:fence","minecraft:dispenser","minecraft:crafting_table","minecraft:chest"],isFilteringCraftable:0b,toBeDisplayed:["minecraft:wooden_pressure_plate","minecraft:wooden_door","minecraft:wooden_button","minecraft:trapdoor","minecraft:tnt","minecraft:stick","minecraft:sign","minecraft:oak_wooden_slab","minecraft:oak_stairs","minecraft:oak_planks","minecraft:fence_gate","minecraft:fence","minecraft:dispenser","minecraft:crafting_table","minecraft:chest"],isGuiOpen:0b},DeathTime:0s,XpSeed:772021467,ForgeCaps:{"ironbackpacks:equipped_backpack":{id:"minecraft:air",Count:1b,Damage:0s},"obfuscate:synced_player_data":[],"vehicle:held_vehicle":{}},XpTotal:0,playerGameType:1,seenCredits:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],UUIDLeast:0L,Health:20.0f,foodSaturationLevel:5.0f,HasSpawnDimensionSet:0b,Air:300s,OnGround:1b,Dimension:0,ForgeDataVersion:{minecraft:1343,securitycraft:1,props:1},Rotation:[354.8892f,43.65f],XpLevel:0,UpdateBlocked:0b,Score:0,UUIDMost:0L,Sleeping:0b,Pos:[-498.51394231325827d,65.0d,1400.6923414709304d],Fire:-20s,XpP:0.0f,EnderItems:[],DataVersion:1343,foodLevel:20,foodExhaustionLevel:0.0f,HurtTime:0s,SelectedItemSlot:5,Inventory:[{Slot:0b,id:"vehicle:boost_pad",Count:1b,Damage:0s},{Slot:1b,id:"props:props",Count:1b,Damage:508s},{Slot:2b,id:"props:props",Count:1b,Damage:143s},{Slot:3b,id:"props:props",Count:1b,Damage:1073s},{Slot:4b,id:"cfm:modern_coffee_table",Count:1b,Damage:0s},{Slot:5b,id:"eyemod:eyephone_op",Count:1b,tag:{owner:"Onur06",help:1b,money:0,mail:"Eye±Welcome!±Hello Onur06,¶¶Enjoy your brand new¶Eyephone!¶¶Eye.",background:"nether.png",location_example:[I;0,64,0],close_key:18,locations:"example",opened:1,battery:200,apps:"0-1-2-3-4-19-20"},Damage:0s}],foodTickTimer:0}

-- Affected level --
  Level name: G Modpack mo
  All players: 1 total; [EntityPlayerMP['Onur06'/13, l='G Modpack mo', x=-498.51, y=65.00, z=1400.69]]
  Chunk stats: ServerChunkCache: 289 Drop: 0
  Level seed: 7751520828042035140
  Level generator: ID 01 - flat, ver 0. Features enabled: true
  Level generator options: 3;minecraft:bedrock,59*minecraft:stone,3*minecraft:dirt,minecraft:grass;1;village,biome_1,decoration,stronghold,mineshaft,lake,lava_lake,dungeon
  Level spawn location: World: (-495,65,1399), Chunk: (at 1,4,7 in -31,87; contains blocks -496,0,1392 to -481,255,1407), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
  Level time: 88012 game time, 1000 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 52248 (now: false), thunder time: 173902 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_291, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3900884736 bytes (3720 MB) / 5335154688 bytes (5088 MB) up to 9663676416 bytes (9216 MB)
  JVM Flags: 8 total; -Xmn128M -Xmx9187M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 26 mods loaded, 26 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                         | Version         | Source                                        | Signature                                |
       |:------ |:-------------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                  | 1.12.2          | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp                        | 9.42            | minecraft.jar                                 | None                                     |
       | LCHIJA | FML                        | 8.0.99.99       | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                      | 14.23.5.2855    | forge-1.12.2-14.23.5.2855.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | obfuscate                  | 0.4.2           | minecraft.jar                                 | None                                     |
       | LCHIJA | securitycraft              | v1.8.11         | [1.12.2] SecurityCraft v1.8.11.jar            | None                                     |
       | LCHIJA | camera                     | 1.0.3           | camera-1.0.3.jar                              | None                                     |
       | LCHIJA | cjcm                       | 1.0             | cjcm-1.0.jar                                  | None                                     |
       | LCHIJA | ptrmodellib                | 1.0.4           | PTRLib-1.0.4.jar                              | None                                     |
       | LCHIJA | props                      | 2.6.3           | Decocraft-2.6.3_1.12.2.jar                    | None                                     |
       | LCHIJA | cdm                        | 0.2.0           | device-mod-0.2.0-1.12.2.jar                   | None                                     |
       | LCHIJA | doggytalents               | 1.14.2.380      | Doggy Talents-1.12.2-1.14.2.380-universal.jar | None                                     |
       | LCHIJA | extrautils2                | 1.0             | extrautils2-1.12-1.9.9.jar                    | None                                     |
       | LCHIJA | eyemod                     | 1.1.0           | EyeMod-Mod-1.12.2.jar                         | None                                     |
       | LCHIJA | cfm                        | 5.17.0          | furniture-5.17.0-1.12.2.jar                   | None                                     |
       | LCHIJA | ichunutil                  | 7.2.2           | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | gravitygun                 | 7.1.0           | GravityGun-1.12.2-7.1.0.jar                   | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | cgm                        | 0.9.2           | guns-0.9.2-1.12.2.jar                         | None                                     |
       | LCHIJA | ironbackpacks              | 1.12.2-3.0.8-12 | IronBackpacks-1.12.2-3.0.8-12.jar             | None                                     |
       | LCHIJA | jei                        | 4.13.1.224      | jei_1.12.2-4.13.1.224.jar                     | None                                     |
       | LCHIJA | neat                       | 1.4-17          | Neat 1.4-17.jar                               | None                                     |
       | LCHIJA | corerm                     | 1.3.3           | RikMuldsCore_1.3.3.jar                        | None                                     |
       | LCHIJA | camping                    | 2.4.3           | TheCampingMod_2.4.3.jar                       | None                                     |
       | LCHIJA | tlauncher_custom_cape_skin | 1.4             | tlskincape1.12.2-1.4.jar                      | None                                     |
       | LCHIJA | vanillafix                 | 1.0.10-150      | VanillaFix-1.0.10-150.jar                     | None                                     |
       | LCHIJA | vehicle                    | 0.37.0          | vehicle-mod-0.37.0-1.12.2.jar                 | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
                                        gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Unknown
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Onur06'/13, l='G Modpack mo', x=-498.51, y=65.00, z=1400.69]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 1

**Comment by Onur259** [comment]
Was using VanillaFix

**Comment by Onur259** [comment]
It's a modpack that i created

**Comment by Onur259** [comment]
Is now fixed but it's still open
