### ISSUE TITLE
World saving crashes when getFeatureName returns null for custom StructureFeature

### ISSUE THREAD

**Issue by rehwinkel** [MinecraftForge/MinecraftForge#8051]
**Minecraft Version:** 1.17.1

**Forge Version:** 37.0.50

**Logs:** 

```
[12:30:21] [IO-Worker-22/ERROR]: Failed to store chunk [-5, -5]
java.lang.NullPointerException: Cannot invoke "String.length()" because "str" is null
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:358) ~[?:?]
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:332) ~[?:?]
        at net.minecraft.nbt.CompoundTag.writeNamedTag(CompoundTag.java:385) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:74) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.CompoundTag.writeNamedTag(CompoundTag.java:386) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:74) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.CompoundTag.writeNamedTag(CompoundTag.java:386) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:74) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.CompoundTag.writeNamedTag(CompoundTag.java:386) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:74) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.NbtIo.writeUnnamedTag(NbtIo.java:191) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.nbt.NbtIo.write(NbtIo.java:184) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.world.level.chunk.storage.RegionFileStorage.write(RegionFileStorage.java:95) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.world.level.chunk.storage.IOWorker.runStore(IOWorker.java:132) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.world.level.chunk.storage.IOWorker.storePendingChunk(IOWorker.java:121) ~[forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:73) [forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:86) [forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:138) [forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:94) [forge-1.17.1-37.0.43_mapped_official_1.17.1-recomp.jar%2374!:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Steps to Reproduce:**
 1. Create a custom Structure 
 2. Generate and save a World
 3. Chunk writing crashes because of NPE.

**Description of issue:**
When writing Chunks in `net.minecraft.world.level.chunk.storage.ChunkSerializer`, in line 400, each Structure features serializes it's "references". Here, the structure name is used, which is retrieved using `StructureFeature#getFeatureName`, which currently uses `STRUCTURES_REGISTRY.inverse().get(this)` to get the Feature name. This solution doesn't work for modded structures, cause the `STRUCTURES_REGISTRY` is only used by vanilla. 

I think patching this function to return something from a forge registry would be a good fix for this. Overriding the method also fixes this Issue.  Considering that the error log really doesn't point to the `getFeatureName` being the issue, I'd at least add a null check in there and throw a meaningful error in that case.

**Comment by rehwinkel** [comment]
Here is a MVE that causes this crash.
[NastyCrashMod.zip](https://github.com/MinecraftForge/MinecraftForge/files/7090631/NastyCrashMod.zip)

**Comment by diesieben07** [comment]
And you cannot put your own Structure into `STRUCTURES_REGISTRY`, because...?

**Comment by rehwinkel** [comment]
> And you cannot put your own Structure into `STRUCTURES_REGISTRY`, because...?

Yes, that works, forgot to think of that. However, due to the error still being pretty confusing (in my opinion), adding a null check in the `getFeatureName` method would be practical.

**Comment by diesieben07** [comment]
We could add a validator to run after startup to check that the map is correctly filled, yes. However I don't think adding a patch for this is worth it.

**Comment by rehwinkel** [comment]
Depending on how many people encounter this issue, making a patch may or may not be appropriate. For the time being, I agree, making a patch isn't necessarily worth it.

**Comment by sciwhiz12** [comment]
Looking at `StructureFeature`, it seems to have a Forge registry (`ForgeRegistries#STRUCTURE_FEATURES`), so what could be done is changing that `STRUCTURES_REGISTRY` map (and possibly even the `STEP` map alongside it?) into a slave map to that Forge registry.

**Comment by diesieben07** [comment]
That is not as straightforward, because the names for the features are separate from the registry names, so we can't easily derive them.
The lowercasing that vanilla does is not reversible.

**Comment by TelepathicGrunt** [comment]
@rehwinkel If you are still having structure issues, please check out my structure tutorial mod
https://github.com/TelepathicGrunt/StructureTutorialMod

What you found this you forgot was this line:
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/e51cca9698110559f8f586b9c71ae9a4e655d786/src/main/java/com/telepathicgrunt/structuretutorial/STStructures.java#L82

That specific map is used for autocomplete in locate command, the structure for explorer maps to find in loot tables, and for saving/reading structures from chunks. Vanilla just has the structure's names such as "village" or "bastion_remnant". However, for modded structures, I **STRONGLY** recommend people put their structure's registry name so that it is easier for users to know what to put for /locate and prevent name overlaps with other mods (imagine if two mods added a castle and tried to put "castle" as their structure name in that map)

Forge could indeed loop over the structure registry after it is locked and then automatically dump all modded structures into that map with their registry names. But for now, you gotta do this step yourself. 

Edit: don't forget to also add to `FlatGenerationSettings.STRUCTURE_FEATURES` (prevents a crash although recent forge version patched away the crash), DimensionStructuresSettings.DEFAULTS (so the default spacing of your structure is exposed for anyone else to use), and to WorldGenRegistries.NOISE_GENERATOR_SETTINGS (some mods refuse to get structure spacing from the defaults map or resist WorldEvent.Load attempts for adding structure spacings so add to that noise setting map too. You'll still need the WorldEvent.Load hack to add spacing to datapacked dimensions with custom noise settings json)

**Comment by rehwinkel** [comment]
Thanks, @TelepathicGrunt! Considering how "rare" this error is and how much using a tutorial can help, I'll close this issue.
