### ISSUE TITLE
Custom Minecraft.jar with forge makes the game crashing

### ISSUE THREAD

**Issue by 8Ascoth8** [MinecraftForge/MinecraftForge#8066]
**Minecraft Version:** {1.10.2}

**Forge Version:** {12.18.3.2511}

**Logs:** {
---- Minecraft Crash Report ----
// You're mean.

Time: 8/29/21 6:31 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraftforge.fml.client.FMLClientHandler.getSavesDir(FMLClientHandler.java:702)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:706)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:245)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:168)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:118)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:50)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2138)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1184)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:458)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.client.FMLClientHandler.getSavesDir(FMLClientHandler.java:702)
	at net.minecraftforge.fml.client.FMLClientHandler.tryLoadExistingWorld(FMLClientHandler.java:706)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186777_e(GuiListWorldSelectionEntry.java:245)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_186774_a(GuiListWorldSelectionEntry.java:199)
	at net.minecraft.client.gui.GuiListWorldSelectionEntry.func_148278_a(GuiListWorldSelectionEntry.java:168)
	at net.minecraft.client.gui.GuiListExtended.func_148179_a(SourceFile:41)
	at net.minecraft.client.gui.GuiWorldSelection.func_73864_a(SourceFile:118)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiWorldSelection.func_146274_d(SourceFile:50)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiWorldSelection
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2138)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1184)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:458)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1314096288 bytes (1253 MB) / 1664090112 bytes (1587 MB) up to 11207180288 bytes (10688 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx12024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 466.47, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Current Language: English
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
}

**Steps to Reproduce:**
 1. Edit 1.10.2.jar (with a JBE or by editing a texture, .json...)
 2. Then install forge
 3. Congratulation! Your game can't launch!

**Description of issue:**
It's pretty easy to understand, let's take an example. For example, let's say you want to change the bow's charge time. To do this you use a JBE then you edit abq.class and change the 20.0F with 0.0F at line 117 (with Recaf JBE). Then you test it without forge, you're happy because it worked. Then you tell yourself "this could be even funnier if I add some mods with this!" so you install forge and... your game crashes. Then you cry ;-;
I'm at the crying step

Please help me.

**Comment by diesieben07** [comment]
Jarmodding is not supported.

**Comment by 8Ascoth8** [comment]
okay, but why optifine works?

**Comment by diesieben07** [comment]
Optifine is not a jarmod.

**Comment by 8Ascoth8** [comment]
oh.. okay thx
