### ISSUE TITLE
[1.18] Server: Failed to store chunk error

### ISSUE THREAD

**Issue by ricksouth** [MinecraftForge/MinecraftForge#8232]
**Minecraft Version:** 1.18

**Forge Version:** 38.0.4

**Logs:** https://gist.github.com/ricksouth/e08326da2f94d65922a74d114f367a61

**Steps to Reproduce:**
 1. Install a 38.0.4 server
 2. Launch it without mods
 3. See the error in the console

**Description of issue:**
Showing up in the console, no specific steps needed.
No crash.

`[11:08:26 ERROR]: Failed to store chunk [4, -7]
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at net.minecraft.nbt.CompoundTag.m_6434_(CompoundTag.java:132) ~[server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.nbt.NbtIo.m_128950_(NbtIo.java:215) ~[server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.nbt.NbtIo.m_128941_(NbtIo.java:184) ~[server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.world.level.chunk.storage.RegionFileStorage.m_63708_(RegionFileStorage.java:79) ~[server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.world.level.chunk.storage.IOWorker.m_63535_(IOWorker.java:174) ~[server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.world.level.chunk.storage.IOWorker.m_63553_(IOWorker.java:164) ~[server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.util.thread.StrictQueue$IntRunnable.run(StrictQueue.java:59) [server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) [server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) [server-1.18-20211130.085255-srg.jar%2337!:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) [server-1.18-20211130.085255-srg.jar%2337!:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Comment by UndefinedBHVR** [comment]
I can't seem to reproduce this issue. Going off the gist log you attached, it seems you're loading a world either from a previous version of Minecraft or one that contained mods that are no longer installed.

Can you please supply a copy of the world you used?

**Comment by ricksouth** [comment]
[world.zip](https://github.com/MinecraftForge/MinecraftForge/files/7636800/world.zip)

I did generate the world with two of my mods as a test, when the error occurred. I removed them after to see if it was still in the server console, which it was. The world was newly created in 38.0.4. But here's the world :)

I'll generate another one from scratch without any mods to see if it happens again.

**Comment by ricksouth** [comment]
[world.zip](https://github.com/MinecraftForge/MinecraftForge/files/7636811/world.zip)

This is the world used. It was newly generated in 38.0.4. Indeed with two mods installed when the error showed in the console. I removed the mods to see if it was still happening after, which it was.

I'll try to generate another world fresh without any mods to see if it's still there.

**Comment by ricksouth** [comment]
A newly generated world without anything does not print the error. I re-downloaded the zip file I just uploaded and extracted the world again to the server folder.

Now it again shows the "Failed to store chunk"

https://gist.github.com/ricksouth/9b7b6db32400735ebae48c601a997a71

Hopefully the world is of use to find the issue.

Mod files used:
https://www.curseforge.com/minecraft/mc-mods/collective/files/3542465
https://www.curseforge.com/minecraft/mc-mods/surface-mushrooms/files/3542861

Surface Mushrooms contains mixins, which I wanted to test in production.. that might be the issue? But I'd expected the mixins to just not have any effect after they were removed. Also now without them installed the server console still shows the error.

**Comment by ricksouth** [comment]
I think this will be fixed in 1.18.1 and can be closed:

Fix "Random non fatal exceptions in console: Failed to store chunk ConcurrentModificationException"

https://www.minecraft.net/en-us/article/minecraft-1-18-1-release-candidate-1

**Comment by TheCurle** [comment]
1.18.1 has been released, and it seems to have fixed this issue.

**Comment by grothedev** [comment]
it seems this is not actually fixed. i have had this happen twice on my server in the past few months, and when it happens it completely deletes a chunk, forcing it to regenerate from seed. 
![image](https://user-images.githubusercontent.com/5280051/164763975-c24a11a5-4ba1-4b3e-b766-48ae7bc0e967.png)
i can provide more info and server log, mods, etc. later tonight after work.

**Comment by TheCurle** [comment]
The original issue has been fixed by mojang, and given the EOFException thrown, this seems to be an entirely separate problem.

Please create a new issue so that we can properly investigate and track this new problem.
