### ISSUE TITLE
Extreme console spam related to vanilla GlDebug

### ISSUE THREAD

**Issue by LatvianModder** [MinecraftForge/MinecraftForge#8379]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.14

**Logs:** [Gist](https://gist.github.com/LatvianModder/2db8bdd565dc1d66083ecc21f9825a29)

**Steps to Reproduce:**
 1. Install plain Forge on Minecraft 1.18.1, no mods
 2. Open console
 3. Ponder

**Description of issue:**
Right after its done loading, when Main menu shows up, it first prints this error block:

```
[10Jan2022 00:29:32.951] [Thread-6/ERROR] [net.minecraftforge.eventbus.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.loadClass(String)" because the return value of "java.lang.Thread.getContextClassLoader()" is null
	at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:62) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:44) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:21) ~[eventbus-5.0.3.jar:?]
	at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:20) ~[eventbus-5.0.3.jar:5.0.3+70+master.d7d405b]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.0.7.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.0.7.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.0.7.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-0.9.54.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-0.9.54.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-0.9.54.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:130) ~[securejarhandler-0.9.54.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at com.mojang.blaze3d.platform.GlDebug.m_84038_(GlDebug.java:95) ~[?:?]
	at org.lwjgl.opengl.GLDebugMessageCallbackI.callback(GLDebugMessageCallbackI.java:39) [lwjgl-opengl-3.2.2.jar%2347!:build 10]
```

And then, it spams these lines in extreme volumes, so much that vanilla log can't keep up, seems to be follow this exact pattern always starting with `[Thread-6/INFO]: OpenGL debug message: `:

```
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPushAttrib is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPushMatrix is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glOrtho is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPopMatrix is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPopAttrib is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPushAttrib is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPushMatrix is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glOrtho is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glMatrixMode is deprecated and not available in preview contexts.'
id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glLoadIdentity is deprecated and not available in preview contexts.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Cannot enable <cap> in the current profile.'
```

I'm not sure if this is caused by Forge or even harmful for GL at all, as it warns about deprecated methods, this seems something that could just be removed entirely.

**Comment by XFactHD** [comment]
I had this issue a few months ago. It was caused by the Overwolf overlay using old GL stuff. Disabling the overlay for Minecraft in the Overwolf settings fixed it.

**Comment by LatvianModder** [comment]
Indeed, this fixed the issue, thank you! I still wonder if its something that Forge could have a client config option for, to disable GlDebug, because for most users that won't know how to fix this, the logs get spammed to megabytes in few minutes.

**Comment by XFactHD** [comment]
I don't think Forge should normally have a need for such an option because it always implies a serious bug in some part of the game or other software interfacing with the game.
Can you check if you are running the latest version of Overwolf?

**Comment by LatvianModder** [comment]
Yes, currently on latest that it gives me, Overwolf 0.187.1.13, CurseForge 0.190.1.5 and as soon as I enable overlay, log gets spammed. I've also posted in CurseForge support channel about this issue, hopefully they look into it. I guess I can close this now, as its not Forge issue.

**Comment by HeaserOW** [comment]
Thanks for reporting, this is on the Overwolf's overlay side.
As mentioned above, a temporary fix would be to disable the overlay in the Overwolf settings.
We're looking into a fix, I'll update here once we have something.

**Comment by HeaserOW** [comment]
We've currently in the process of deploying a fix.
On Overwolf version 0.188.0.21 this should no longer happen.
Thanks for the reports, everyone.
