### ISSUE TITLE
Cannot prevent player teleporting with ITeleporter

### ISSUE THREAD

**Issue by IzzelAliz** [MinecraftForge/MinecraftForge#8459]
**Minecraft Version:** 1.18.1

**Forge Version:** 39.0.66

**Logs:** 
<details><pre>
[13:42:32] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectSet.remove(Object)" because "objectset" is null
	at net.minecraft.server.level.DistanceManager.removePlayer(DistanceManager.java:258) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.level.ChunkMap.move(ChunkMap.java:958) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.level.ServerChunkCache.move(ServerChunkCache.java:448) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:850) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:28) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:84) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:21) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:17) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:139) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:22) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:765) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:161) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:112) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:748) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:742) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:122) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:728) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:672) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:258) ~[forge-1.18.1-39.0.66_mapped_official_1.18.1-recomp.jar%2377!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

</pre></details>

**Steps to Reproduce:**
 1. Teleport player with the following code
```java
player.changeDimension(server.getLevel(Level.NETHER), new ITeleporter() {
  public PortalInfo getPortalInfo(Entity entity, ServerLevel destWorld, Function<ServerLevel, PortalInfo> defaultPortalInfo) {
    return null;
  }
});
```

**Description of issue:**

As per ITeleporter doc said, return null in getPortalInfo can prevent teleporting, but player tp as such will remove the player from world and put player into an "inter-teleporting" state and throw exception.

This should be reproducible on 1.16.

**Comment by diesieben07** [comment]
This is not easy to fix for players without making the patch larger (and potentially even changing behavior).
I would propose the following:

1. Fix the documentation for `getPortalInfo` about disallowing `null`. Keep the behavior until 1.19 as it is a breaking change (this feature works for non-players).
2. Potentially add a new method to `ITeleporter` that allows prevention of the teleport. This is optional, as `EntityTravelToDimensionEvent` can be used for this functionality already. However for optimal use `EntityTravelToDimensionEvent` should be enhanced to include the (optional) `ITeleporter` that is being used (and also actually fire for entities other than players).

Opinions?

**Comment by IzzelAliz** [comment]
I made a fix that altered the getPortalInfo call(and the following if) before sending respawn packet, and it seems working. The only changed behaviour is that when getPortalinfo is called the player is not removed from world, and I assume this is acceptable.

I can do this PR if necessary.

**Comment by Jonathing** [comment]
> This is not easy to fix for players without making the patch larger (and potentially even changing behavior). I would propose the following:
> 
> 1. Fix the documentation for `getPortalInfo` about disallowing `null`. Keep the behavior until 1.19 as it is a breaking change (this feature works for non-players).
> 2. Potentially add a new method to `ITeleporter` that allows prevention of the teleport. This is optional, as `EntityTravelToDimensionEvent` can be used for this functionality already. However for optimal use `EntityTravelToDimensionEvent` should be enhanced to include the (optional) `ITeleporter` that is being used (and also actually fire for entities other than players).
> 
> Opinions?

I am still personally interested in this since it can be a huge roadblock for mods that use ITeleporter in a non-traditional way (i.e. portal forcers with traditional portals). What I'm thinking is creating two PRs: one that changes the documentation that states the result of `getPortalInfo` should not be null (since it is marked as `@Nullable` right now), and the other that either adds a method to the interface as you mentioned and/or having `EntityTravelToDimensionEvent` include the (optional) ITeleporter that was used.
