### ISSUE TITLE
Game crashing upon joining server, doesn't happen when I join a singleplayer world

### ISSUE THREAD

**Issue by CzechHech** [MinecraftForge/MinecraftForge#8510]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 13/03/2022, 00:34
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at com.mojang.blaze3d.vertex.BufferBuilder.m_166779_(BufferBuilder.java:112) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.emc.json:render.MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleRenderType$2.m_6505_(ParticleRenderType.java:42) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.client.particle.ParticleEngine.render(ParticleEngine.java:409) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:render.MixinParticleManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1379) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1056) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:render.MixinEntityRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:831) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:render.MixinEntityRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1041) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:game.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:661) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:game.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.vertex.BufferBuilder.m_166779_(BufferBuilder.java:112) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.emc.json:render.MixinBufferBuilder,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.particle.ParticleRenderType$2.m_6505_(ParticleRenderType.java:42) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading}
	at net.minecraft.client.particle.ParticleEngine.render(ParticleEngine.java:409) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:render.MixinParticleManager,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1379) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1056) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:render.MixinEntityRenderer,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['SechsGaming_YT'/134014, l='ClientLevel', x=24.81, y=35.00, z=189.05]]
	Chunk stats: 529, 313
	Level dimension: minecraft:the_nether
	Level spawn location: World: (0,86,0), Section: (at 0,6,0 in 0,5,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 746319 game time, 114170 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.emc.json:world.MixinWorldClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2249) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:game.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:683) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.emc.json:game.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2372!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Mac OS X (x86_64) version 11.6
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 775188688 bytes (739 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 17408.00
	Virtual memory used (MB): 9817.80
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 23.75
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.1-forge-39.1.0
	Backend library: LWJGL version 3.2.1 SNAPSHOT
	Backend API: Apple M1 GL version 4.1 Metal - 71.7.1, Apple
	Window size: 1440x900
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Apple M1
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		ToLaserBlade-1.18-5.1.1.1.jar                     |ToLaserBlade                  |tolaserblade                  |1.18-5.1.1.1        |DONE      |Manifest: NOSIGNATURE
		lootbeams-1.18.1-release-jan1522.jar              |LootBeams                     |lootbeams                     |1.18.1              |DONE      |Manifest: NOSIGNATURE
		upgradedcore-1.18.1-3.1.0.0-release.jar           |Upgraded Core                 |upgradedcore                  |1.18.1-3.1.0.0-relea|DONE      |Manifest: NOSIGNATURE
		BetterFurnacesReforged-1.18.1-1.2.4.jar           |BetterFurnaces Reforged       |betterfurnacesreforged        |1.18.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		upgradednetherite_ultimate-1.18.1-3.1.0.0-release.|Upgraded Netherite : Ultimerit|upgradednetherite_ultimate    |1.18.1-3.1.0.0-relea|DONE      |Manifest: NOSIGNATURE
		ElementalSwords-1.18.1-2.5.6.jar                  |Elemental Swords              |elementalswords               |2.5.6               |DONE      |Manifest: NOSIGNATURE
		walljump-forge-1.18.1-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.18.1-1.3.7        |DONE      |Manifest: NOSIGNATURE
		moredragoneggs-3.1.jar                            |More Dragon Eggs              |moredragoneggs                |3.1                 |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.4.1.112.jar                          |Just Enough Items             |jei                           |9.4.1.112           |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.2.1-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.2.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterShieldsMC1.18.1-1.0.jar                     |Better Shields                |bettershields                 |1.0                 |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.1.0-universal.jar                 |Forge                         |forge                         |39.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		torohealth-1.18-forge-2.jar                       |ToroHealth                    |torohealth                    |1.18-forge-2        |DONE      |Manifest: NOSIGNATURE
		sniffsinfinityweapons-1.18.1-2.6.3.jar            |Sniff's Infinity Weapons Mod  |sniffsinfinityweapons         |2.6.3               |DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v3.1.1-1.18.1-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |3.1.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		EMC.jar                                           |EMC Framework                 |emc                           |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		upgradednetherite-1.18.1-4.1.0.0-release.jar      |Upgraded Netherite            |upgradednetherite             |1.18.1-4.1.0.0-relea|DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.18.1-2.1.49d-beta.jar             |When Dungeons Arise           |dungeons_arise                |2.1.49d-1.18.1      |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.18.1-1.6.15.jar                          |Cyclic                        |cyclic                        |1.18.1-1.6.15       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: 5be1ee84-8a93-490a-a7ab-f19cd75d595e
	FML: 39.1
	Forge: net.minecraftforge:39.1.0

**Comment by sciwhiz12** [comment]
:wave: We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [Forge Support Forums](https://forums.minecraftforge.net/). 

Additionally, please note that under our version support policy, we only support **1.18.2** as the latest minor version of 1.18.x. Please update your Forge version and mods to 1.18.2 before recreating a thread on the forums, as your issue may be resolved on those updated versions.
