### ISSUE TITLE
[1.19.3] Config values defined by ForgeConfigSpec$Builder::defineInList throws NullPointerException when collection passed as acceptableValues does not allow null values

### ISSUE THREAD

**Issue by Fuzss** [MinecraftForge/MinecraftForge#9300]
**Minecraft Version:** 1.19.3

**Forge Version:** 1.19.3 - 44.1.4

**Steps to Reproduce:**
1. Setup a new config builder like this:
```java
ForgeConfigSpec.Builder builder = new ForgeConfigSpec.Builder();
        List<String> selection = List.of("1", "2", "3");
        builder.comment("Test selection", "Valid value: ", String.join(", ", selection)).defineInList("choice", "2", selection);
```

2. The game will crash when trying to create the config file with the following stacktrace:
```
Caused by: java.lang.NullPointerException
	at java.base/java.util.ImmutableCollections$ListN.indexOf(ImmutableCollections.java:716)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.contains(ImmutableCollections.java:329)
	at net.minecraftforge.common.ForgeConfigSpec$Builder.lambda$defineInList$4(ForgeConfigSpec.java:339)
	at net.minecraftforge.common.ForgeConfigSpec$ValueSpec.test(ForgeConfigSpec.java:788)
	at net.minecraftforge.common.ForgeConfigSpec.correct(ForgeConfigSpec.java:208)
	at net.minecraftforge.common.ForgeConfigSpec.isCorrect(ForgeConfigSpec.java:132)
	at net.minecraftforge.common.ForgeConfigSpec.setConfig(ForgeConfigSpec.java:66)
	at net.minecraftforge.common.ForgeConfigSpec.acceptConfig(ForgeConfigSpec.java:87)
	at net.minecraftforge.fml.config.ModConfig.setConfigData(ModConfig.java:81)
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:74)
	at net.minecraftforge.fml.config.ConfigTracker.loadTrackedConfig(ConfigTracker.java:56)
	at net.minecraftforge.fml.config.ConfigTracker.trackConfig(ConfigTracker.java:47)
	at net.minecraftforge.fml.config.ModConfig.<init>(ModConfig.java:39)
	at net.minecraftforge.fml.config.ModConfig.<init>(ModConfig.java:45)
```
**Description of issue:**
When ForgeConfigSpec$Builder::defineInList is passed a collection that does not allow `null` values (like instances of `java.util.ImmutableCollections$AbstractImmutableList`, other immutable collections like from Guava work fine though, as they allow `null` values) as the `acceptableValues` parameter, the game crashes with a NullPointerException when trying to create the config entry for the value.

The issue is located in this line:
https://github.com/MinecraftForge/MinecraftForge/blob/5946356f8e3aa0df5fc1cbea0fb9bfec0ce2b734/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L353

Simply adding a null check will prevent this issue from occurring, like this:
```java
return define(path, defaultSupplier, o -> o != null && acceptableValues.contains(o));
```

**Comment by SrRapero720** [comment]
This issue still persist 
https://github.com/MinecraftForge/MinecraftForge/blob/203fbbb742e03c8e3f59d2f894a7e5d7f33bd79f/src/main/java/net/minecraftforge/common/ForgeConfigSpec.java#L349
