### ISSUE TITLE
1.19.2 rendering issue with worldedit and other modded blocks

### ISSUE THREAD

**Issue by ink717** [MinecraftForge/MinecraftForge#9356]
forge version 43.2.0 and above, 
the issue happens regardless of optifine, rubidium, flywheel, distant horizons is active eg.

when using worldedit to fill an area, or paste a section, or manually placing some modded blocks (e.g. desk, bricks) by hand, the other players in the server can't see it. Even breaking the block, other players can't see. it's still there, but invisible. need to teleport out of the chunk render distance and back to make the blocks show.

tried individually with every mod in the server's mod pack, and can't find the cause. Perhaps its a forge or minecraft issue.

Whenever it happens, the console get spammed with this message:

[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_6933_(Level.java:198)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientLevel.m_6933_(ClientLevel.java:165)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.Level.m_7731_(Level.java:188)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientLevel.m_233647_(ClientLevel.java:142)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.prediction.BlockStatePredictionHandler.m_233856_(BlockStatePredictionHandler.java:44)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientLevel.m_233651_(ClientLevel.java:129)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.multiplayer.ClientPacketListener.m_214108_(ClientPacketListener.java:2109)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundBlockChangedAckPacket.m_5797_(ClientboundBlockChangedAckPacket.java:19)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ClientboundBlockChangedAckPacket.m_5797_(ClientboundBlockChangedAckPacket.java:6)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
[24/02/2023 22:36:41 PM] 	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
[24/02/2023 22:36:41 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[24/02/2023 22:36:41 PM] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[24/02/2023 22:36:41 PM] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[24/02/2023 22:36:41 PM] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[24/02/2023 22:36:41 PM] 	at MC-BOOTSTRAP/fmlloader@1.19.2-43.2.4/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
[24/02/2023 22:36:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
[24/02/2023 22:36:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
[24/02/2023 22:36:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
[24/02/2023 22:36:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
[24/02/2023 22:36:41 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
[24/02/2023 22:36:42 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[24/02/2023 22:36:42 PM] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[24/02/2023 22:36:42 PM] 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
[24/02/2023 22:36:42 PM] [Render thread/FATAL] Error executing task on Client

**Comment by TheCurle** [comment]
This is an issue with WorldEdit, not Forge. Complain to them, we can't fix a broken mod.

**Comment by ink717** [comment]
> This is an issue with WorldEdit, not Forge. Complain to them, we can't fix a broken mod.

it doesn't just happen with worldedit - it happens simply by hand-place or break as well. I did report this issue to worldedit's side as well, if i got more info will update.
