### ISSUE TITLE
java.lang.NullPointerException: Exception while updating neighbours

### ISSUE THREAD

**Issue by ben21121** [MinecraftForge/MinecraftForge#9396]
java.lang.NullPointerException: Exception while updating neighbours
	at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:252)
	at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:145)
	at net.minecraft.world.ServerWorldEventHandler.func_72703_a(ServerWorldEventHandler.java:37)
	at net.minecraft.world.World.func_72923_a(World.java:1222)
	at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1112)
	at net.minecraft.world.World.func_72838_d(World.java:1213)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.block.Block.func_180635_a(Block.java:599)
	at net.minecraft.block.Block.func_180653_a(Block.java:578)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:171)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockStaticLiquid.func_176370_f(BlockStaticLiquid.java:35)
	at net.minecraft.block.BlockStaticLiquid.func_189540_a(BlockStaticLiquid.java:28)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:493)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:107)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:106)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:106)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockStaticLiquid.func_176370_f(BlockStaticLiquid.java:35)
	at net.minecraft.block.BlockStaticLiquid.func_189540_a(BlockStaticLiquid.java:28)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:481)
	at net.minecraft.world.World.func_190524_a(World.java:551)
	at net.minecraft.world.World.func_175685_c(World.java:497)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:133)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:133)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.WorldServer.func_175654_a(WorldServer.java:551)
	at net.minecraft.world.WorldServer.func_175684_a(WorldServer.java:531)
	at net.minecraft.block.BlockDynamicLiquid.func_176213_c(BlockDynamicLiquid.java:306)
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:614)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.block.BlockDynamicLiquid.func_176375_a(BlockDynamicLiquid.java:175)
	at net.minecraft.block.BlockDynamicLiquid.func_180650_b(BlockDynamicLiquid.java:153)
	at net.minecraft.world.World.func_189507_a(World.java:2682)
	at net.minecraft.world.gen.feature.WorldGenLiquids.func_180709_b(WorldGenLiquids.java:88)
	at net.minecraft.world.biome.BiomeDecorator.func_150513_a(BiomeDecorator.java:352)
	at net.minecraft.world.biome.BiomeDecorator.func_180292_a(BiomeDecorator.java:88)
	at net.minecraft.world.biome.Biome.func_180624_a(Biome.java:225)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185931_b(ChunkGeneratorOverworld.java:464)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

**Comment by TheCurle** [comment]
Sorry, we don't support ancient versions of the game.

Secondarily, this is an issue tracker, not tech support.
