### ISSUE TITLE
1.19.x installer appears broken

### ISSUE THREAD

**Issue by enderger** [MinecraftForge/MinecraftForge#9437]
**Minecraft Version:** 1.19.x (tried with all)

**Forge Version:** Any, as far as I can tell

**OS:** Artix Linux (kernel 6.2.2-zen1-1-zen)

**Logs:** https://paste.sr.ht/~hutzdog/59a0dc33f49230dee5e9e833f569ed5563641b52

**Steps to Reproduce:**
 1. Attempt to install Forge 1.19.x on a fresh instance (without libraries already downloaded)
 2. Try to launch the game

**Description of issue:** The game crashes at the installer due to a faulty hash. This may be launcher specific, ~~I haven't tested the vanilla launcher yet~~ This also happens with the main installer. Regardless, it seems to happen after the game starts, making it most likely a problem with Forge.

**Comment by enderger** [comment]
Tested with temurin17, openjdk17, zulu19, zulu8, and temurin20. JDK is not the issue here. (temurin always uses hotspot, and zulu uses hotspot with a prebuilt binary)

**Comment by enderger** [comment]
Turns out, my ancient zulu8 install (when manually run against the Forge installer) somehow makes it work (when run manually with the installer). Seems like something might have screwed with the hashing, since only that install is able to get past them.

**Comment by warjort** [comment]
Just a guess, but maybe you hitting a variant of this zlib bug?
https://github.com/madler/zlib/issues/613

**Comment by enderger** [comment]
Unfortunately, that doesn’t explain why it worked under zulu8 (and only zulu8).

**Comment by enderger** [comment]
> Just a guess, but maybe you hitting a variant of this zlib bug?
> [madler/zlib#613](https://github.com/madler/zlib/issues/613)

Unfortunately, the fact that it works under the zulu8 install complicates things. Perhaps the checksum doesn’t work properly under it, leading it to be skipped?

**Comment by sciwhiz12** [comment]
Could you please provide an installer log of the latest 1.19.4 version, run manually (not through a launcher) with JDK 17?

**Comment by enderger** [comment]
> Could you please provide an installer log of the latest 1.19.4 version, run manually (not through a launcher) with JDK 17?

Error log, as requested: https://paste.sr.ht/~hutzdog/70f4d36e39fb3f53861b3b5a3ff90d0a3d03f048

**Comment by enderger** [comment]
> Just a guess, but maybe you hitting a variant of this zlib bug? [madler/zlib#613](https://github.com/madler/zlib/issues/613)

Looking at it more, this cannot be the case as the client is LZMA compressed, not Zlib compressed (as far as I can tell by looking in `/tmp`)

**Comment by LexManos** [comment]
First off the installer can't have issues after the game starts as the installer needs to finish for the game to exist and even attempt to start.
Secondly, the client.lzma file is the binary patches that Forge applies not the actual client itself. So you very much could be running into that zlib issue.

Step one to debug would be to get rid of any non-forge things in the process. Download the installer yourself and run it like Sci said. It seems you did that and are still getting issues.

It might be on our end, or it is something in your JRE that is not following specs properly. To know better I need to actually dissect the jars that the process is creating and figure out what is different.

So download https://maven.minecraftforge.net/net/minecraftforge/jarsplitter/1.1.4/jarsplitter-1.1.4-fatjar.jar
Save it into a new empty folder, then in a terminal in that folder run the command 
`java -jar jarsplitter-1.1.4-fatjar.jar --input /home/danielle/.minecraft/versions/1.19.2/1.19.2.jar --slim slim.jar --extra extra.jar --srg /home/danielle/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.2-20220805.130853/mcp_config-1.19.2-20220805.130853-mappings-merged.txt`
You're running linux so i'm gunna assume you know how to run that in the correct directory.
Once that has run you will have a slim.jar and an extra.jar.
Email them to LexManos@gmail.com

Now legal notice here: These files contain Minecraft. So *technically* you don't have the legal authority to send them to me. However I certify that I own a copy of Minecraft and am purely gunna use them to track down what the differences between your output and the normal one is. So lets hope Mojang's lawyers are fine with that.

**Comment by enderger** [comment]
> First off the installer can't have issues after the game starts as the installer needs to finish for the game to exist and even attempt to start. Secondly, the client.lzma file is the binary patches that Forge applies not the actual client itself. So you very much could be running into that zlib issue.
> 
> Step one to debug would be to get rid of any non-forge things in the process. Download the installer yourself and run it like Sci said. It seems you did that and are still getting issues.
> 
> It might be on our end, or it is something in your JRE that is not following specs properly. To know better I need to actually dissect the jars that the process is creating and figure out what is different.
> 
> So download https://maven.minecraftforge.net/net/minecraftforge/jarsplitter/1.1.4/jarsplitter-1.1.4-fatjar.jar Save it into a new empty folder, then in a terminal in that folder run the command `java -jar jarsplitter-1.1.4-fatjar.jar --input /home/danielle/.minecraft/versions/1.19.2/1.19.2.jar --slim slim.jar --extra extra.jar --srg /home/danielle/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.2-20220805.130853/mcp_config-1.19.2-20220805.130853-mappings-merged.txt` You're running linux so i'm gunna assume you know how to run that in the correct directory. Once that has run you will have a slim.jar and an extra.jar. Email them to [LexManos@gmail.com](mailto:LexManos@gmail.com)
> 
> Now legal notice here: These files contain Minecraft. So _technically_ you don't have the legal authority to send them to me. However I certify that I own a copy of Minecraft and am purely gunna use them to track down what the differences between your output and the normal one is. So lets hope Mojang's lawyers are fine with that.

Unfortunately, the JAR splitter itself fails with the following log (short enough to include inline) without producing either JAR:
```
Splitter: 
  Input:    /home/danielle/.minecraft/versions/1.19.2/1.19.2.jar
  Slim:     slim.jar
  Data:     null
  Extra:    extra.jar
  Including data in extra
  SRG:   /home/danielle/.minecraft/libraries/de/oceanlabs/mcp/mcp_config/1.19.2-20220805.130853/mcp_config-1.19.2-20220805.130853-mappings-merged.txt
  InputSha: 55b30d860ead928cba3849ba920c88b6950b654
  SrgSha:   eafb2fb0b2c99822165e44411685831410fe9f97
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "parent" is null
	at net.minecraftforge.jarsplitter.ConsoleTool.checkOutput(ConsoleTool.java:188)
	at net.minecraftforge.jarsplitter.ConsoleTool.checkOutput(ConsoleTool.java:164)
	at net.minecraftforge.jarsplitter.ConsoleTool.main(ConsoleTool.java:95)
```

**Comment by LexManos** [comment]
Try with https://maven.minecraftforge.net/net/minecraftforge/jarsplitter/1.1.5/jarsplitter-1.1.5-fatjar.jar

**Comment by enderger** [comment]
> Try with https://maven.minecraftforge.net/net/minecraftforge/jarsplitter/1.1.5/jarsplitter-1.1.5-fatjar.jar

That worked, but the JARs won't send due to GMail protections

**Comment by LexManos** [comment]
Then find a way to send a file over the internet. I'll leave the specifics to you.

**Comment by enderger** [comment]
> Then find a way to send a file over the internet. I'll leave the specifics to you.

Alright, I sent it using an unilsted Git repository (URL sent via email)

**Comment by SizableShrimp** [comment]
Please join our Discord at https://discord.minecraftforge.net and go to the #tech-support channel for faster communication so we can try to resolve this. Feel free to ping me when you get there. Thanks.

**Comment by Jonathing** [comment]
Please continue discussion of issues with Installer and zlib-ng-compat in MinecraftForge/Installer#80.
