### ISSUE TITLE
Ender Dragon causes errors

### ISSUE THREAD

**Issue by Lolothepro** [MinecraftForge/MinecraftForge#9653]
```
java.lang.NullPointerException: Cannot read field "f_20378_" because "p_19977_" is null
	at net.minecraft.world.entity.Entity.m_6380_(Entity.java:2787) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.entity.Entity.getEyeHeightAccess(Entity.java:3465) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraftforge.common.extensions.IForgeEntity.getEyeHeightForge(IForgeEntity.java:443) ~[forge-1.20.1-47.1.22-universal.jar%23155!/:?] {re:computing_frames,re:classloading}
	at net.minecraft.world.entity.Entity.<init>(Entity.java:262) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraftforge.entity.PartEntity.<init>(PartEntity.java:16) ~[forge-1.20.1-47.1.22-universal.jar%23155!/:?] {re:classloading}
	at net.minecraft.world.entity.boss.EnderDragonPart.<init>(EnderDragonPart.java:20) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.entity.boss.enderdragon.EnderDragon.<init>(EnderDragon.java:92) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.entity.EntityType.m_20615_(EntityType.java:525) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
	at net.minecraft.world.entity.EntityType.m_185996_(EntityType.java:530) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin}
	at net.minecraft.world.entity.EntityType.m_20642_(EntityType.java:529) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
	at net.minecraft.world.entity.EntityType.m_20669_(EntityType.java:607) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
	at net.minecraft.world.entity.EntityType.m_20645_(EntityType.java:563) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
	at net.minecraft.server.commands.SummonCommand.m_269066_(SummonCommand.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
	at net.minecraft.server.commands.SummonCommand.m_245828_(SummonCommand.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
	at net.minecraft.server.commands.SummonCommand.m_244862_(SummonCommand.java:50) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,xf:fml:forge:forge_method_redirector}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[brigadier-1.1.8.jar%2395!/:?] {}
	at net.minecraft.commands.Commands.m_242674_(Commands.java:257) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.commands.Commands.m_230957_(Commands.java:237) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.level.BaseCommandBlock.m_45414_(BaseCommandBlock.java:124) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.level.block.CommandBlock.m_51831_(CommandBlock.java:113) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.level.block.CommandBlock.m_213897_(CommandBlock.java:101) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222963_(BlockBehaviour.java:758) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,re:mixin}
	at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:680) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}
```

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/16863c8d3bf955b7d54a6db0f6dac631e2b527ed

**Comment by ProdNation** [comment]
> [16863c8](https://github.com/MinecraftForge/MinecraftForge/commit/16863c8d3bf955b7d54a6db0f6dac631e2b527ed)

what should i do with it? miss understand

**Comment by Lolothepro** [comment]
> > [16863c8](https://github.com/MinecraftForge/MinecraftForge/commit/16863c8d3bf955b7d54a6db0f6dac631e2b527ed)
> 
> what should i do with it? miss understand

it just means it's fixed in Forge.
