### ISSUE TITLE
Payload error when connecting to the Velocity server

### ISSUE THREAD

**Issue by levitskyyy** [MinecraftForge/MinecraftForge#9789]
## Client
**Minecraft Version:** 1.20.2

**Forge Version:** latest

## Server
**Proxy:** Velocity

**Servers:** Paper

### Velocity
```
[connected player] _Klayn1_ (/xxx.xxx.xxx.xxx:xxxxx) has connected
[07:08:09 INFO]: [server connection] _Klayn1_ -> auth has connected
[07:08:10 INFO]: [connected player] _Klayn1_ (/xxx.xxx.xxx.xxx:xxxxx): kicked from server auth: Invalid payload REGISTER!
[07:08:10 INFO]: [server connection] _Klayn1_ -> auth has disconnected
[07:08:10 INFO]: [connected player] _Klayn1_ (/xxx.xxx.xxx.xxx:xxxxx) has disconnected: You were kicked from auth: Invalid payload REGISTER!
```

### Paper lobby
```
[07:08:10 INFO]: _Klayn1_[/xxx.xxx.xxx.xxx:xxxxx] logged in with entity id 52 at ([world]0.0, 0.0, 0.0)
[07:08:10 ERROR]: Couldn't register custom payload
java.lang.IllegalArgumentException: Channel must contain : separator (attempted to use )
        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:503) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.addChannel(CraftPlayer.java:2354) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.handleCustomPayload(ServerCommonPacketListenerImpl.java:146) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:46) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.a(ServerboundCustomPayloadPacket.java:12) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2088]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[07:08:10 INFO]: _Klayn1_ lost connection: Invalid payload REGISTER!
```

### Paper plugins

- AuthMe
- AuthMe-Velocity
- Chatty

### Velocity plugins

- LuckPerms Velocity
- AuthMe-Velocity
- Geyser-Velocity
- ViaVersion
- ViaBackwards

## Steps to Reproduce
**Steps to Reproduce:**
 1. Install latest Forge
 2. Connect to Velocity proxy
 3. We get an error

**Description of issue:**
The error only occurs when using forge, logging in with fabric or the vanilla version succeeds. I [contacted](https://github.com/PaperMC/Velocity/issues/1141) the creators of velocity, they informed me that the problem was not on their part

**Comment by SrRapero720** [comment]
Related PR https://github.com/MinecraftForge/MinecraftForge/pull/9772

**Comment by LexManos** [comment]
Ya, its a mix of 
1) I am assuming Velocity sending the same set of channels multiple times, one when you connect, and once when you switch server. On our end we've already sent the channel list to the server so we don't have any new channels to send.

2) Bukkit putting a arbitrary limitation on it that there needs to be a namespace separator, which DEFINITLY isnt the case. The decoder reads a resource location, but resource locations don't actually REQUIRE a separator. 
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/messaging/StandardMessenger.java#502 
Vanilla:
```java
   protected static String[] decompose(String p_135833_, char p_135834_) {
      String[] astring = new String[]{"minecraft", p_135833_};
      int i = p_135833_.indexOf(p_135834_);
      if (i >= 0) {
         astring[1] = p_135833_.substring(i + 1);
         if (i >= 1) {
            astring[0] = p_135833_.substring(0, i);
         }
      }

      return astring;
   }
```

3) The spec not specifying wither empty lists or channel names are allowed.

Either way, I've prevented us from sending the channel list if its empty. I've also added a bit more sanitization to our handler, to ignore empty channels and check the end of the buffer after the last null if there is any trailing data. 

There are some other potential issues, but honestly not something I will care to fix on our end.
First being that we still append the null at the end. This is done for 1) backwards compatibility with the last 5 years of Forge/Other Servers and 2) Because the spec is a bit ambiguous and i've seen multiple implementations in the wild.

Secondly, we don't send all known channels every time we get told about the server channels. From Forge's point of view the server already knows what channels we have sent. We have no way to tell if this is a proxied connection or a normal server. So its up to the proxy server to forward those to the backend.

**Comment by SrRapero720** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/0d820eddd455c8dab6cc4a222b9c7c1290ec0dfa#diff-8c7d1124e5606fe2d34927e353fc367151bd980eb09a5dd25844b39dda3bc815R122

you repeat `of channels` 2 times, and this part should have a WARN logger about a bad channel, just in case any other "exceptional" issues comes.
