### ISSUE TITLE
Can't download forge on MultiMC/Prism Launcher/PolyMC [MC 1.20.4/Forge 49.0.3] 

### ISSUE THREAD

**Issue by juliocoliveira** [MinecraftForge/MinecraftForge#9815]
I can't use Forge on MultiMC or Prism Launcher or PolyMC.

MultiMC gives the error:
```
Game update failed: it was impossible to fetch the required libraries.
Reason:
Job 'Libraries for instance Forge [1.20.4]' failed to process:
https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.4-49.0.3/forge-1.20.4-49.0.3-launcher.jar
```
When accessing the URL it gives an error 404 (Page not found).

Prism Launcher gives error:
```
Exception caught from launcher
java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:144)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:123)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:157)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:38)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR
Process exited with code 2.
```

PolyMC gives error:
```
PolyMC version: 5.1


Launched instance in online mode

authserver.mojang.com resolves to:
    [108.158.147.40, 108.158.147.35, 108.158.147.12, 108.158.147.59]

session.minecraft.net resolves to:
    [2620:1ec:bdf::33, 2620:1ec:46::33, 13.107.246.33, 13.107.213.33]

textures.minecraft.net resolves to:
    [2620:1ec:46::33, 2620:1ec:bdf::33, 13.107.213.33, 13.107.246.33]

api.mojang.com resolves to:
    [2620:1ec:bdf::33, 2620:1ec:46::33, 13.107.213.33, 13.107.246.33]


Minecraft folder is:
V:/PolyMC/instances/Forge [1.20.4]/.minecraft


Java path is:
C:/Program Files/Eclipse Adoptium/jdk-17.0.9.9-hotspot/bin/javaw.exe


Checking Java version...
Java is version 17.0.9, using 64 (amd64) architecture, from Eclipse Adoptium.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  V:/PolyMC/instances/Forge [1.20.4]/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  V:/PolyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-arm64/3.3.2/lwjgl-glfw-natives-windows-arm64-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.2/lwjgl-glfw-natives-windows-x86-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.2/lwjgl-glfw-natives-windows-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-arm64/3.3.2/lwjgl-jemalloc-natives-windows-arm64-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.2/lwjgl-jemalloc-natives-windows-x86-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.2/lwjgl-jemalloc-natives-windows-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-natives-windows-arm64/3.3.2/lwjgl-natives-windows-arm64-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.2/lwjgl-natives-windows-x86-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-natives-windows/3.3.2/lwjgl-natives-windows-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-arm64/3.3.2/lwjgl-openal-natives-windows-arm64-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.2/lwjgl-openal-natives-windows-x86-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.2/lwjgl-openal-natives-windows-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-arm64/3.3.2/lwjgl-opengl-natives-windows-arm64-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.2/lwjgl-opengl-natives-windows-x86-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.2/lwjgl-opengl-natives-windows-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-arm64/3.3.2/lwjgl-stb-natives-windows-arm64-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.2/lwjgl-stb-natives-windows-x86-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.2/lwjgl-stb-natives-windows-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-arm64/3.3.2/lwjgl-tinyfd-natives-windows-arm64-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.2/lwjgl-tinyfd-natives-windows-x86-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.2/lwjgl-tinyfd-natives-windows-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  V:/PolyMC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  V:/PolyMC/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  V:/PolyMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  V:/PolyMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  V:/PolyMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  V:/PolyMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  V:/PolyMC/libraries/com/mojang/authlib/6.0.52/authlib-6.0.52.jar
  V:/PolyMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  V:/PolyMC/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  V:/PolyMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  V:/PolyMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  V:/PolyMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  V:/PolyMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  V:/PolyMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  V:/PolyMC/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  V:/PolyMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  V:/PolyMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  V:/PolyMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  V:/PolyMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  V:/PolyMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  V:/PolyMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  V:/PolyMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  V:/PolyMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  V:/PolyMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  V:/PolyMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  V:/PolyMC/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  V:/PolyMC/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  V:/PolyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  V:/PolyMC/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  V:/PolyMC/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  V:/PolyMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  V:/PolyMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  V:/PolyMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  V:/PolyMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  V:/PolyMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  V:/PolyMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  V:/PolyMC/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  V:/PolyMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc2/ForgeWrapper-mmc2.jar
  V:/PolyMC/libraries/net/minecraftforge/forge/1.20.4-49.0.3/forge-1.20.4-49.0.3-launcher.jar (missing)
  V:/PolyMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  V:/PolyMC/libraries/net/minecraftforge/securemodules/2.2.7/securemodules-2.2.7.jar
  V:/PolyMC/libraries/net/minecraftforge/unsafe/0.9.2/unsafe-0.9.2.jar
  V:/PolyMC/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  V:/PolyMC/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  V:/PolyMC/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  V:/PolyMC/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  V:/PolyMC/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  V:/PolyMC/libraries/net/minecraftforge/bootstrap/2.0.0/bootstrap-2.0.0.jar
  V:/PolyMC/libraries/net/minecraftforge/bootstrap-api/2.0.0/bootstrap-api-2.0.0.jar
  V:/PolyMC/libraries/net/minecraftforge/accesstransformers/8.1.1/accesstransformers-8.1.1.jar
  V:/PolyMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  V:/PolyMC/libraries/net/minecraftforge/eventbus/6.2.0/eventbus-6.2.0.jar
  V:/PolyMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  V:/PolyMC/libraries/net/minecraftforge/forgespi/7.1.1/forgespi-7.1.1.jar
  V:/PolyMC/libraries/net/minecraftforge/coremods/5.1.0/coremods-5.1.0.jar
  V:/PolyMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  V:/PolyMC/libraries/net/minecraftforge/modlauncher/10.1.2/modlauncher-10.1.2.jar
  V:/PolyMC/libraries/net/minecraftforge/mergetool-api/1.0/mergetool-api-1.0.jar
  V:/PolyMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  V:/PolyMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  V:/PolyMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  V:/PolyMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  V:/PolyMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  V:/PolyMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  V:/PolyMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  V:/PolyMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  V:/PolyMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  V:/PolyMC/libraries/net/minecraftforge/fmlcore/1.20.4-49.0.3/fmlcore-1.20.4-49.0.3.jar
  V:/PolyMC/libraries/net/minecraftforge/fmlloader/1.20.4-49.0.3/fmlloader-1.20.4-49.0.3.jar
  V:/PolyMC/libraries/net/minecraftforge/fmlearlydisplay/1.20.4-49.0.3/fmlearlydisplay-1.20.4-49.0.3.jar
  V:/PolyMC/libraries/net/minecraftforge/javafmllanguage/1.20.4-49.0.3/javafmllanguage-1.20.4-49.0.3.jar
  V:/PolyMC/libraries/net/minecraftforge/lowcodelanguage/1.20.4-49.0.3/lowcodelanguage-1.20.4-49.0.3.jar
  V:/PolyMC/libraries/net/minecraftforge/mclanguage/1.20.4-49.0.3/mclanguage-1.20.4-49.0.3.jar
  V:/PolyMC/libraries/com/mojang/minecraft/1.20.4/minecraft-1.20.4-client.jar

Native libraries:

Params:
  --username  --version 1.20.4 --gameDir V:/PolyMC/instances/Forge [1.20.4]/.minecraft --assetsDir V:/PolyMC/assets --assetIndex 12 --uuid  --accessToken  --userType  --versionType release --launchTarget forge_client

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]


Minecraft process ID: 23688


Dec 10, 2023 8:14:03 PM org.polymc.EntryPoint listen
SEVERE: Exception caught from launcher.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.RuntimeException: Unable to detect the forge installer!
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getDataFromInstaller(IFileDetector.java:136)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.getInstallProfileExtraData(IFileDetector.java:115)
	at io.github.zekerzhayard.forgewrapper.installer.detector.IFileDetector.checkExtraFiles(IFileDetector.java:147)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:29)
	... 9 more
Dec 10, 2023 8:14:03 PM org.polymc.EntryPoint main
INFO: Exiting with 1
Process exited with code 1.
Clipboard copy at: 10 Dec 2023 20:17:01 -0300
```

Each launcher gives an error that can't use forge.
Only MultiMC says that it can't download the files from forge.

Here is a issue from Prism Launcher: https://github.com/PrismLauncher/PrismLauncher/issues/1934

Maybe somebody forgot to upload the required file, Or is a bug in the build/upload process.
Could somebody take a look at it?

**Comment by LexManos** [comment]
This doesn't have anything to do with Forge. The launcher is the one responsible for installing Forge and the methods they use to do it are not working. They will need to fix things on their end.

No idea where they are getting this 'launcher' artifact from...
