### ISSUE TITLE
Forge 1.20.3 does not launch via PrismLauncher

### ISSUE THREAD

**Issue by JustRed23** [MinecraftForge/MinecraftForge#9831]
**Minecraft Version:** 1.20.3

**Forge Version:** 49.0.2

**Logs:** https://mclo.gs/L9GW09m

**Steps to Reproduce:**
 1. Install PrismLauncher
 2. Create a new instance with the provided version of forge
 3. Launch

**Description of issue:**
When launching, the window appears and then immediately disappears, leaving a crash log (provided above)

**Comment by PaintNinja** [comment]
https://forums.minecraftforge.net/topic/140300-forge-490-minecraft-1204/#comment-559496

> the difference between 1.20.3 and 1.20.4 was a single line change by Mojang that fixed [a data loss bug](https://bugs.mojang.com/browse/MC-267185). All 1.20.3 mods should work in 1.20.4 and there is no reason to use 1.20.3 which came out a day or two earlier.

**Comment by JustRed23** [comment]
> [forums.minecraftforge.net/topic/140300-forge-490-minecraft-1204/#comment-559496](https://forums.minecraftforge.net/topic/140300-forge-490-minecraft-1204/#comment-559496)
> 
> > the difference between 1.20.3 and 1.20.4 was a single line change by Mojang that fixed [a data loss bug](https://bugs.mojang.com/browse/MC-267185). All 1.20.3 mods should work in 1.20.4 and there is no reason to use 1.20.3 which came out a day or two earlier.

Yea was just testing an old server of mine but couldnt seem to launch the client, but looking at the bootstrap code, my guess is that the same thing will happen on 1.20.4

**Comment by JustRed23** [comment]
Can confirm, same thing happening on 1.20.4-49.0.11

MC: 1.20.4
Forge: 49.0.11
Log: https://mclo.gs/xMgJYl6
Same steps

**Comment by JustRed23** [comment]
> Can confirm, same thing happening on 1.20.4-49.0.11
> 
> MC: 1.20.4 Forge: 49.0.11 Log: [mclo.gs/xMgJYl6](https://mclo.gs/xMgJYl6) Same steps

The log seems to have been cut off, here is a better one: https://mclo.gs/CsvRn0U

**Comment by ItsReddi** [comment]
Getting the same issue with minecraft launcher:
```
11:48:25.493
launcher
main

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:48)
	at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:18)
Caused by: java.lang.IllegalStateException: Library directory: `libraries` does not exist. Set it via the `libraryDirectory` system property.
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.3/net.minecraftforge.fml.loading.LibraryFinder.findLibsPath(LibraryFinder.java:17)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.3/net.minecraftforge.fml.loading.LibraryFinder.findPathForMaven(LibraryFinder.java:23)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.3/net.minecraftforge.fml.loading.targets.ForgeProdLaunchHandler.getMinecraftPaths(ForgeProdLaunchHandler.java:27)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.3/net.minecraftforge.fml.loading.targets.ForgeProdLaunchHandler$Client.getMinecraftPaths(ForgeProdLaunchHandler.java:31)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.3/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:24)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.3/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:78)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.3/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:154)
	at SECURE-BOOTSTRAP/net.minecraftforge.fmlloader@1.20.4-49.0.3/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:58)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:98)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$7(TransformationServicesHandler.java:96)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:98)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:49)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:73)
	at SECURE-BOOTSTRAP/cpw.mods.modlauncher@10.1.2/cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17)
	at net.minecraftforge.bootstrap@2.0.0/net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:97)
	... 6 more
```

**Comment by PaintNinja** [comment]
Unable to reproduce with the latest 8.0 build of PrismLauncher and Forge 1.20.4 49.0.13, please [join our Discord](https://discord.minecraftforge.net) so we can figure out what the issue is for you

**Comment by ItsReddi** [comment]
Well found this for Curseforge:
There is a known issue where launching 1.20.4 MinecraftForge crashes on launch even with no mods. This is due to a change in Forge, and the tech team have a solution and are implementing it.

For now a temporary fix is to use a custom launch argument: 
> Click the <:CFmenu:798402764425527356> button in the top right corner of the app. Click the <:CFfolder:798388587099324446> Open Modding Folder button.
> Open the `libraries` folder in there (you must of created a Forge 1.17+ profile for the folder to exist)
> Click on the address bar at the top of file explorer, then press `Ctrl` + `C` to copy the path.
> Now go back to the CurseForge app and click on <:CFsettings:798388925072408577> in the bottom left, then go to the <:grass:795906775852515338> `Minecraft` category.
> Scroll down to the bottom to the `Additional Arguments` box and click on it.
> In the box type in `-DlibraryDirectory="` then press`Ctrl` + `V` to paste in the path you copied earlier. Then type a single `"` to end it. 
> It should look something like this: `-DlibraryDirectory="C:\Users\Arug\Curseforge\Install\libraries\"`
> You should now be able to launch 1.20.4 forge without issues! The argument will not affect any other versions and should be safe to leave there when playing other packs.

**Comment by Jonathing** [comment]
For the record, I've been able to launch Forge 1.20.4 on both the vanilla launcher and Prism without any issues.

This is a problem that is better discussed in our Discord server, so please continue there as this doesn't point towards something specific or reproducible in Forge.
